### ISSUE TITLE
AnalyticalTable: Add row action property

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents-react#1019]
**Is your feature request related to a problem? Please describe.**
Fiori guidelines have a `RowActions` concept to trigger action on a specific row. Basically, it adds a column at the end of the table with no header and a button for each row.
See: https://experience.sap.com/fiori-design-web/analytical-table-alv/#single-cell

SAPUI5 Table have this feature: https://sapui5.hana.ondemand.com/#/entity/sap.ui.table.Table/sample/sap.ui.table.sample.RowAction

This RowActions column is very useful to display navigation or delete buttons.

**Describe the solution you'd like**
A new property to the table where we could provide an icon to be displayed for each row with a callback that would be called (with the row data passed as parameter) when the button is clicked on.

**Additional context**
<img width="1419" alt="Screen Shot 2020-11-25 at 12 39 20" src="https://user-images.githubusercontent.com/7316793/100223538-ec4ca300-2f1b-11eb-9234-5ee4076e7c97.png">

Any other option/solution is appreciated 🙂

**Comment by Lukas742** [comment]
Hi @Neeko

If I understood you right, we already provide this feature, just without a prop. You can add a column with an icon/button that receives the data of the row on click.
I prepared a [codesandbox](https://codesandbox.io/s/vigorous-tesla-rpyk8?file=/src/App.js) that shows this feature.

Is this approach sufficient for you?

**Comment by Neeeko** [comment]
Hi @Lukas742 
Thanks for the codesandbox, it's exactly what we need! 👍 

I'm closing this issue.
