### ISSUE TITLE
Bar: BarDesign.FloatingFooter does not match styles shown in the Fiori Guidelines

### ISSUE THREAD

**Issue by Turao** [SAP/ui5-webcomponents-react#1045]
**Describe the bug**

Hi, 

first and foremost, thanks for the great project.

I've been working on a new form, trying to follow the [Fiori Guidelines](https://experience.sap.com/fiori-design-web/footer-toolbar/), and noticed the current implementation of the **Floating Toolbar** differs slightly from what is shown in the guidelines. Namely, there are no round corners nor any margins whatsoever, making it look like a normal footer when placed at the bottom of the viewport.

I wonder if it would be possible to update the component so as to have the exact same design shown in the Fiori Guidelines when selecting the `BarDesign.FloatingFooter` design.

**Isolated Example**
*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).*

https://codesandbox.io/s/immutable-wind-ptdvt?file=/src/App.js

**To Reproduce**
1. Add the Bar component
2. Add the `BarDesign.FloatingFooter` design to it

**Expected behavior**

The Bar component, when using the `BarDesign.FloatingFooter` design, should match the Fiori Guidelines' [Flooting Toolbar](https://experience.sap.com/fiori-design-web/footer-toolbar/).

**Screenshots**

![Fiori Guidelines' Footer Toolbar](https://experience.sap.com/fiori-design-web/wp-content/uploads/sites/5/2020/09/FOOTER_TOOLBAR_M-1.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.8
`@ui5/webcomponents-react` version: 0.10.3
Operating System: Windows 10
Browser: Chrome Version 87.0.4280.66 (Official Build) (64-bit)

**Additional context**

**Comment by Lukas742** [comment]
Hi @Turao 

we just merged the PR, which adds the border-radius to the `FloatingFooter` design. The margin is not part of the specs, but you can add a `width` (e.g. `90%`) to the Bar's `style` prop and then center it horizontally. 

We will let you know when this is released.

**Comment by Lukas742** [comment]
Released in [v0.12.2](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.12.2)

**Comment by Turao** [comment]
Hi, @Lukas742 

thanks for the very quick reply - and as mentioned before, this amazing project! 🚀
