### ISSUE TITLE
Popover: TypeError: Cannot read property 'getBoundingClientRect' of undefined

### ISSUE THREAD

**Issue by auryn31** [SAP/ui5-webcomponents-react#1055]
**Describe the bug**
If i use the popover from your example, i get the following issue:

```
TypeError: Cannot read property 'getBoundingClientRect' of undefined
```

**To Reproduce**
```js
function App() {
  const dialogRef = useRef();
  const onButtonClick = () => {
      dialogRef.current.open();
  };
  return (
    <ThemeProvider>
      <ShellBar primaryTitle="UI5 Web Components for React Template" />
      <FlexBox
        style={{ width: "100%", height: "100vh" }}
        direction={FlexBoxDirection.Column}
        justifyContent={FlexBoxJustifyContent.Center}
        alignItems={FlexBoxAlignItems.Center}
      >
        <Button onClick={onButtonClick}>
          Open Popover
        </Button>
        <Popover
          ref={dialogRef}
          headerText="Popover Header"
        >
          Press "Escape" or click outside to close the Popover.
        </Popover>
      </FlexBox>
    </ThemeProvider>
  );
}
```

**Expected behavior**
a popover will appear

**Screenshots**
![Screen Shot 2020-12-04 at 14 13 53](https://user-images.githubusercontent.com/24471955/101167942-f583f100-363a-11eb-90b4-b258196021ce.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.10
`@ui5/webcomponents-react` version: ^0.12.0
Operating System: MacOSX
Browser: Chrome

**Comment by MarcusNotheis** [comment]
Hey @auryn31,

Thanks for reporting!

The Popover can only be opened by using `.openBy(openerRef)`, so in your case this would be:
```js
const onButtonClick = (e) => {
  dialogRef.current.openBy(e.target);
};
```

Where did you find that code in our docs? Then we'll fix the wrong documentation.

**Comment by auryn31** [comment]
Thanks a lot, this worked. 

My bad.

Is there a way to type this in typescript?

**Comment by MarcusNotheis** [comment]
Hey @auryn31,

yes, you can use the following code snippet:
```ts
import { Ui5PopoverDomRef } from '@ui5/webcomponents-react/interfaces/Ui5PopoverDomRef';

// ... 

const ref = useRef<Ui5PopoverDomRef>();
```

**Comment by auryn31** [comment]
Thanks for the fast help
