### ISSUE TITLE
useI18nText cause multiple rerendering

### ISSUE THREAD

**Issue by nazarkulyk** [SAP/ui5-webcomponents-react#1069]
**Describe the bug**
using useI18nText rom '@ui5/webcomponents-react-base/lib/hooks' cause multiple rerendering of the component.

First time it will rerender with default value, even if there is an translated value, than it rerender with translated value.

If  useI18nText will be called even for more than one translation it will execute hook multiple times.

Expected is to get hook called only once for all values with default, or translated values only.

@ui5/webcomponents-react-base: 0.12.2

**Comment by MarcusNotheis** [comment]
Hey @nazarkulyk,
we've just released `@ui5/webcomponents-react` and `@ui5/webcomponents-react-base` `v0.12.3` which contains a new hook called `useI18nBundle`. This new hook should help to prevent unnecessary rerenders.
A migration guide can be found [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/migration-guide--page#migrating-from-013x-to-0140).

In case you are using a custom message bundle, we recommend to preload it as soon as possible, best place would be e.g. your `App` component:

```jsx
import { fetchI18nBundle } from '@ui5/webcomponents-base/dist/i18nBundle';
fetchI18nBundle('YOUR_CUSTOM_BUNDLE_ID');

// ...

function App() {
// ... 
}
```
