### ISSUE TITLE
DynamicPage: scrollbar for no reason

### ISSUE THREAD

**Issue by goodefroi** [SAP/ui5-webcomponents-react#1074]
Please have a look at [this example](https://codesandbox.io/s/magical-shaw-b1iyj). The DynamicPage is limited in height but although the content still fits, a scrollbar is displayed. I'd expect no scrollbar to appear as long as long as all content fits the page anyway. This issue seems to be resolved by setting the `height` parameter of `DynamicPage-contentContainer` to `auto`.

**Comment by MarcusNotheis** [comment]
Released in `0.13.1`
