### ISSUE TITLE
Inefficient bundeling still their

### ISSUE THREAD

**Issue by 23mluk** [SAP/ui5-webcomponents-react#1075]
**Describe the bug**
Hi, I have that warnings in my Console (Inefficient bundeling)
![inefficentbundle](https://user-images.githubusercontent.com/68957230/101613346-f1295080-3a0b-11eb-92a1-0be58d52d55f.PNG).

So I followed that tutorial to solve it: https://sap.github.io/ui5-webcomponents-react/?path=/docs/efficient-bundling--page

So my Code in config-overrides.js looks like:

```
const {override} = require('customize-cra');
const {addReactRefresh} = require('customize-cra-react-refresh');
const { addWebpackModuleRule} = require('customize-cra')
 
module.exports = override(
    addReactRefresh(),
    addWebpackModuleRule({
        test: /assets\/.*\.json$/,
        use: 'file-loader',
        type: 'javascript/auto'
    })
);
```
But their is still the warnings.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: latest
`@ui5/webcomponents-react` version: latest

**Comment by MarcusNotheis** [comment]
Hey @23mluk,
thanks for reaching out.
The example that you shared in your issue looks different to the example that we provide in our bundling guide.
Is there any specific reason why you need to add `customize-cra` and `customize-cra-react-refresh`? 

I just to followed the steps from our documentation in a fresh project and I don't get any inefficient bundling warnings.

**Comment by 23mluk** [comment]
yes I know its a little bit difffrent. I need customize-cra-react-refresh beacause of Redux. The React "hot changes push" doesn`t work that well with redux, together with redux. 

You think that package makes the problem.

**Comment by MarcusNotheis** [comment]
I would assume so, yes. With "plain" `react-app-rewired` it works, so I guess it is related to `customize-cra`. I unfortunately never worked with that library before, so I won't be able to give you some good advice here to be honest.

**Comment by 23mluk** [comment]
So, finally i solved the problem.

with the `customize-cra` you can make a function and then you get the config Object like `react-app-rewired`

ex.

```
function myOverrides(config) {
    config.module.rules.unshift({
        test: /assets.*\.json$/i,
        use: 'file-loader',
        type: 'javascript/auto'  
    });
    return config
}
 
module.exports = override(
    addReactRefresh(),
    myOverrides
);
```

But their is still not working. I dont know why but the regex doesn`t matched the imports. So I changed it from ```/assets\/.*\.json$/``` to `` /assets.*\.json$/i `` and now works.

**Comment by MarcusNotheis** [comment]
Good to hear you figured a way of solving the issue 🙂 
I just tested both regex in a tester and both regex were matching the asset import paths...

I'm going to close this issue, please feel free to reopen or create a new issue in case there are more open topics.
