### ISSUE TITLE
[AnalyticalTable] Adding a navigation indicator at the end of the row

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents-react#1083]
**Is your feature request related to a problem? Please describe.**
The AnalyticalTable currently handles row highlight using `withRowHighlight` which displays a row indicator at the start of the row.

Our use case requires us to add a "navigation highlight" which is very similar to the existing row highlight except it's positioned at the end of the row.

<img width="625" alt="Screen Shot 2020-12-10 at 11 45 04" src="https://user-images.githubusercontent.com/7316793/101763459-189d1d80-3adf-11eb-894e-b0052f4f490e.png">

[See the Fiori Guidelines here.
](https://ux.wdf.sap.corp/fiori-design-web/responsive-table/#indicate-navigated-item)

**Describe the solution you'd like**
Properties similar to `withRowHighlight` and `highlightField` (for example `withNavigationHighlight` and `navigationHighlightField`) that would allow us to display such an indicator at the end of the row.

**Additional context**
I'm open to any other suggestions or options 🙂

**Comment by MarcusNotheis** [comment]
Released in `0.13.1` and `0.129.0`
