### ISSUE TITLE
Dialog and MessageToast usages without requiring a `useEffect` and `useRef` hooks

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents-react#1101]
**Is your feature request related to a problem? Please describe.**
In a React app, in order to have a `<Dialog>` it is mandatory to have 2 hooks in order to open the Dialog: `useEffect` and `useRef` at the very least. In addition that that, there can be complications regarding the precise timing of when the `Dialog.prototype.open` function is "attached" to the actual `<ui5-dialog>` customElement, which surface to the consumer as an Exception that states `x.open is not a function`

**Describe the solution you'd like**
Either add a custom hook like `useDialog` or add a prop called `opened` to the `Dialog` that will open/close the Dialog. This same pattern could also be applied to other Components that are popups.

**Describe alternatives you've considered**
It is possible to "hide" these extra complexities in a custom general purpose hook that makes the usage code in the Renderer functions much cleaner and not have to be re-implemented for each place that needs to use a Dialog. I can provide a code snippet in a comment to show the hook implementation, vs. the "ideal" implementation with the Dialog component itself.

**Additional context**
In slack I can provide more details via Slack around the errors that seem to be happening only in edge cases, and in cases when the web component is "booting up" for the first time. Subsequent loads of the same code will work fine.

**Comment by codefactor** [comment]
### useDialog.js

The below code is an example `useDialog` hook that I wrote which shows one solution that we use to "hide" away the useEffects and useRefs hooks. Also there is a function called `useDialogSafe` which is a different version which protects against the `Dialog.prototype.open` function not available at the time the useEffect is called. Please take a look at the comments that I wrote inline for more information about those edge cases.

```javascript
import { useEffect, useRef, useState } from "react";
import RenderScheduler from "@ui5/webcomponents-base/dist/RenderScheduler";

/**
 * Hook alternative 1, sometimes this hook throws an exception if the hook useEffect fires too quickly
 * on startup prior to the `ui5-dialog` customElement being attached to the DOM. This happens a lot in
 * unit test cases, and sometimes if the React code is injected onto an existing page.
 * 
 * @param {Boolean} opened True if the dialog should be open, false if dialog should be closed.
 */
export function useDialog(opened) {
  // openState represents the "actual" open state, null means the dialog is pending to be opened or closed
  const [openState, setOpenState] = useState(false);
  const dialogRef = useRef();
  useEffect(() => {
    const { current } = dialogRef;
    // ignore state when dialog is pending open or close
    if (current && openState !== null && (!opened !== !openState)) {
      setOpenState(null);
      current[opened ? 'open' : 'close'](); // sometimes `current.open` is undefined here, throwing an error
    }
  }, [opened, openState, dialogRef]);
  return {
    dialogRef,
    onAfterOpen: () => { 
      setOpenState(true); 
    },
    onAfterClose: () => {
      setOpenState(false);
    }
  };
}

/**
 * This is another alternative to the useDialog hook above which is "safer".
 * This should not be necessary, but apparently it is necessary.
 * 
 * @param {Boolean} opened True if the dialog should be open, false if dialog should be closed.
 * @return {Object} A dialogRef, onAfterOpen, and onAfterClose to be set onto the <Dialog> component.
 */
export function useDialogSafe(opened) {
  // openState represents the "actual" open state, null means the dialog is pending to be opened or closed
  const [openState, setOpenState] = useState(false);
  const dialogRef = useRef();
  const available = useAvailableMethod(dialogRef, opened ? 'open' : 'close');
  useEffect(() => {
    const { current } = dialogRef;
    // ignore state when dialog is pending open or close
    if (current && openState !== null && (!opened !== !openState) && available) {
      setOpenState(null);
      current[opened ? 'open' : 'close'](); // sometimes `current.open` is undefined here, throwing an error
    }
  }, [opened, openState, dialogRef, available]);
  return {
    dialogRef,
    onAfterOpen: () => { setOpenState(true); },
    onAfterClose: () => { setOpenState(false); }
  };
}

/**
 * This effect will 
 * @param {*} checkFinished 
 */
export function useAvailableMethod(ref, methodName) {
  const [finished, setFinished] = useState(false);
  const [available, setAvailable] = useState(false);
  useEffect(() => {
    let subscribed = true;
    let timeoutId;
    const { current } = ref;
    if (current) {
      const nowAvailable = !!(current && current[methodName]);
      if (available !== nowAvailable) {
        setAvailable(nowAvailable);
      } else if (!nowAvailable) {
        if (finished) {
          const POLL_TIME = 100; // max 10 times per second
          timeoutId = setTimeout(() => {
            // If the finished flag is true, it means we already waited for being finshed
            // yet the function is still not available, this actually happens with newer versions of React!
            // so setFinished to false after a short timeout so that whenFinished will be called again
            timeoutId = null;
            setFinished(false);
          }, POLL_TIME);
        } else {
          RenderScheduler.whenFinished().finally(() => {
            subscribed && setFinished(true);
          });
        }
      }
    }
    return () => {
      subscribed = false;
      if (timeoutId != null) {
        clearTimeout(timeoutId);
      }
    };
  }, [available, finished, ref, methodName]);
  return available;
}
```
### App.js

The below example shows how to use the `useDialog` hook written above. To use the `useDialogSafe` function, it is the same exact pattern just replace `useDialog` with `useDialogSafe`. The App in this case is just opening a dialog, and has a button to close the dialog, and that's it.

```javascript
import React, { useState } from "react";
import { useDialog } from "./useDialog.js";
import { Button } from "@ui5/webcomponents-react/lib/Button";
import { Dialog } from "@ui5/webcomponents-react/lib/Dialog";

/**
 * The main entry point to the widget.
 *
 * @param {Object} props
 * @param {Function} props.cleanup Call this when the app is ready to be cleaned up
 */
export function App() {
  const [opened, setOpened] = useState(true);
  const { dialogRef, onAfterClose, onAfterOpen } = useDialog(opened);
  return (
    <Dialog ref={dialogRef} headerText={"Header"} onAfterOpen={onAfterOpen} onAfterClose={onAfterClose}>
      <Button data-testid="ok-btn" onClick={() => setOpened(false)}>OK</Button>
    </Dialog>
  );
}
```

### App.js Proposed Changes

If you were to instead implement the suggestion where the `opened` prop is now exposed on the `Dialog` Component, then the App.js above would be simplified to remove the hook all together, and the same hook code could somehow be embedded inside the Wrapper Dialog component itself.

```javascript
import React, { useState } from "react";
import { Button } from "@ui5/webcomponents-react/lib/Button";
import { Dialog } from "@ui5/webcomponents-react/lib/Dialog";

/**
 * The main entry point to the widget.
 *
 * @param {Object} props
 * @param {Function} props.cleanup Call this when the app is ready to be cleaned up
 */
export function App() {
  const [opened, setOpened] = useState(true);
  return (
    <Dialog ref={dialogRef} headerText={"Header"} opened={opened}>
      <Button data-testid="ok-btn" onClick={() => setOpened(false)}>OK</Button>
    </Dialog>
  );
}
```

**Comment by MarcusNotheis** [comment]
Hey @codefactor,
thanks for bringing up this detailed issue. We've started a mail thread together with the UI5 Web Components colleagues and included you there. As soon as we have found a common way to approach this issue I'll update it here as well.

**Comment by MarcusNotheis** [comment]
Will be addressed with https://github.com/SAP/ui5-webcomponents/issues/3527

**Comment by codefactor** [comment]
@MarcusNotheis ,

On this topic, when using typescript tsx, is there a proper way to type the HTMLElement such that we don't have to cast the element to "any" to expose functions like `show()`?

```javascript
(ref.current as any).open();
```

**Comment by MarcusNotheis** [comment]
Hey Scott, 
yes there is, e.g. https://sap.github.io/ui5-webcomponents-react/?path=/story/getting-started--page#typescript
You can exchange `Ui5PopoverDomRef` with `UI5DialogDomRef` or other interfaces that are exported [here](https://github.com/SAP/ui5-webcomponents-react/tree/main/packages/main/src/interfaces)

**Comment by MarcusNotheis** [comment]
Hey @codefactor,
I'm closing this issue here as it will be fixed in https://github.com/SAP/ui5-webcomponents/issues/3527.
If there is more to do after the UI5 Web Components have provided this functionality, please feel free to reopen this issue or create a new one.
