### ISSUE TITLE
Missing typescript definitions

### ISSUE THREAD

**Issue by dfenerski** [SAP/ui5-webcomponents-react#1102]
- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [x] Documentation is missing
- [ ] Other

On the main page of the ui5-webcomponents github repository it is clearly stated that typescript is supported. However, there is no documentation on this whatsoever and upon importing a button from example the tslint throws errors because the type definitions are missing. How do I get these?

**Comment by MarcusNotheis** [comment]
Hey @dfenerski,
which project are you using exactly? `@ui5/webcomponents` does not provide type definitions while `@ui5/webcomponents-react` does. Our type definitions are bundled with our library, so you should always get them when importing our components.

Example:

```jsx
import { Button } from '@ui5/webcomponents-react';
```

If that doesn't work, can you please share more details about your environment, especially the `@ui5/webcomponents-react` version, your `node` version as well your project setup? A reproducible example would be awesome as well.

**Comment by dfenerski** [comment]
Components do have types and the provided import does work. However I believe there are no types for the icons and for the event objects received in callback functions

**Comment by MarcusNotheis** [comment]
Yes, the icons are coming from the `@ui5/webcomponents-icons` package which has no type definitions. Event Objects should be typed.
Can you give one example for that?

**Comment by MarcusNotheis** [comment]
Closing this issue in favor of https://github.com/SAP/ui5-webcomponents-react/discussions/1136
Please feel free to continue the conversation there.
