### ISSUE TITLE
Input: not change its value if pass value prop as null or undefined

### ISSUE THREAD

**Issue by adeptb** [SAP/ui5-webcomponents-react#1115]
**Describe the bug**

1. Type some value in input;
2. Change input prop value to null or undefined
3. Input dont change its rendered value

**Isolated Example**
https://codesandbox.io/s/frosty-sound-4o2b6

**To Reproduce**
1. Type some value in input;
2. Change input prop value to null or undefined
3. Input dont change its rendered value

**Expected behavior**
Rendered value of input set to empty value

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: ^1.0.0-rc.10
`@ui5/webcomponents-react` version: ^0.12.2

**Comment by Lukas742** [comment]
Hi @adeptb 
this component is developed by the [ui5-webcomponents](https://github.com/SAP/ui5-webcomponents) team, so I created an [issue](https://github.com/SAP/ui5-webcomponents/issues/2616) there.

I've also created a [codesandbox](https://codesandbox.io/s/hungry-glade-e0c88?file=/src/App.js) that you can use as a workaround.

**Comment by MarcusNotheis** [comment]
Hey @adeptb,
I'm closing this issue here as this is now basically duplicate to https://github.com/SAP/ui5-webcomponents/issues/2616, so please follow the progress there.
Thanks!
