### ISSUE TITLE
Components aren't supporting right to left direction

### ISSUE THREAD

**Issue by arielazzi** [SAP/ui5-webcomponents-react#112]
### Describe the bug
We are trying to build an application that must support UIs with a right to left direction (e.g. Hebrew language), but when we activate this option, the components aren't placed right. We already tried to change the application language, but nothing happened.

---
### Expected behavior
Right to left support. 

---
### Screenshots

**Shell bar:**

The profile picture should be on the left side.

![image](https://user-images.githubusercontent.com/17055516/64377301-831ffd80-d000-11e9-9e70-14064e18db47.png)
---
**Segmented Button:**

It's inverted.

![image](https://user-images.githubusercontent.com/17055516/64377332-9337dd00-d000-11e9-979c-d448d356c1d6.png)
---
**Card:**

The title should be on the right, and also the subtitles and texts.

![image](https://user-images.githubusercontent.com/17055516/64377418-ca0df300-d000-11e9-8c94-d69bfbdc5b3a.png)
---

### Desktop (please complete the following information):
 - Chrome

**Comment by MarcusNotheis** [comment]
Hi @arielazzi,

thanks for submitting this issue.
How did you try to achieve the RTL behaviour? Did you set the `<html dir="rtl">`?

For the UI5 Web Components, that's not sufficient, you have to set the ui5-config as well:
```html
<script data-id="sap-ui-config" type="application/json">
{
  "rtl": true
}
</script>
```
I guess this should solve the ShellBar and the Card issue, but the Segmented Button will most likely need another fix from our side.

**Comment by arielazzi** [comment]
Hello @MarcusNotheis ,

Thank you so much for your fast response again!

Your suggestion works for us and would be awesome if your team can fix this for components that don't support RTL yet.
