### ISSUE TITLE
[AnalyticalTable] Add onRowClick prop

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents-react#1138]
**Is your feature request related to a problem? Please describe.**
Our project requires the following behavior for the AnalyticalTable:
1- Clicking on the checkbox of the row selects it (standard behavior using `selectionBehavior={TableSelectionBehavior.RowSelector}`, like this: https://codesandbox.io/s/inspiring-lamarr-hx416?file=/src/App.js)
2- Clicking anywhere else on the row should trigger an event so that we can do some actions on our side (like open a dialog, side-menu, etc..) **but it shouldn’t select the row**.

Currently there's no way to have this row selection alongside a row click behavior.

**Describe the solution you'd like**
Adding a `onRowClick` prop would allow us to execute actions when clicking on a row and to support row selection when clicking on the checkbox.

**Comment by MarcusNotheis** [comment]
Released in `0.13.1` and `0.129.0`
