### ISSUE TITLE
AnalyticalTable: Support Right-to-Left

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents-react#1139]
**Describe the bug**
Seems to be a regression as it was already addressed/fixed in the past (see: https://github.com/SAP/ui5-webcomponents-react/issues/460)
The AnalyticalTable isn't Right-to-Left compliant: in RTL mode, it should "mirror" LTR table.

**Isolated Example**
https://codesandbox.io/s/romantic-stonebraker-ygr38?file=/src/App.js
_See how only the text inside the cells is properly aligned. The columns order is incorrect (the selection column should be on the right and the columns order inverted)._

**To Reproduce**
Add `dir="rtl"` to the component itself or one of its parent

**Expected behavior**
Based on the configuration of the user, the AnalyticalTable in **RTL mode should mirror the AnalyticalTable in LTR mode**.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 0.27.2
`@ui5/webcomponents-react` version: 0.127.1
Operating System: macOs Big Sur
Browser: Chrome

**Comment by MarcusNotheis** [comment]
Released in `0.13.1` and `0.129.0`
