### ISSUE TITLE
Poor Performance when rendering many Table elements

### ISSUE THREAD

**Issue by Turao** [SAP/ui5-webcomponents-react#1144]
**Describe the bug**

Hi,
I've noticed a huge performance impact when rendering a Table component with many TableRows (e.g. 500).
This gets worse as we keep adding elements inside each TableRow component (e.g. Buttons, Inputs, Labels, ...).

We have implemented pagination, but as the user scrolls down the page (and fetches more and more data) we start noticing this dip in performance as well.

**Isolated Example**
Here's an [Isolated Example](https://codesandbox.io/s/thirsty-christian-g8pit) that simulates the behavior I've been trying to implement lately (a transition to a page with the custom table).

**To Reproduce**
1. Create a custom Table component with many TableRows
2. See dip in performance

**Expected behavior**
Although I expected some dip in performance, I'd not expect it to be that significant. Displaying elements to users can take seconds when first mounting the element.

**Screenshots**
Here's what the profiling shows when displaying my custom Table (~200 items).
![image](https://user-images.githubusercontent.com/3117991/104028777-e519e580-51a7-11eb-8e4f-2b5ced5c9068.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.10
`@ui5/webcomponents-react` version: 0.12.0
Operating System: Win 10
Browser: Chrome - Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by Lukas742** [comment]
Hi @Turao 

the `Table` component is more suited for smaller datasets as the table rows and columns are not virtualized.
For Virtualization (and many more features) I would recommend the `AnalyticalTable`.

You can find the documentation in our [Storybook](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable--default-story). (The default example renders 1000 rows)

**Comment by Turao** [comment]
Hi @Lukas742
Thanks for the reply, I'll give it a try :D

I think we can close this one then
