### ISSUE TITLE
BarChart/LineChart: Throwing errors on console

### ISSUE THREAD

**Issue by jcailan** [SAP/ui5-webcomponents-react#1145]
**Describe the bug**
When using react router, the chart component throws up errors in the console and the webpage becomes blank.

**Isolated Example**
See github repo below:
https://github.com/jcailan/ui5-webc-react

**To Reproduce**
1. Read the README file to understand how to run the application
2. After the application loads on the browser, click on **Progress List** to navigate to another view using react router
![image](https://user-images.githubusercontent.com/27951983/104115785-fef52d00-534d-11eb-9807-ea9fe9786db0.png)
3. Click on the **react icon** to navigate back to the home page view
![image](https://user-images.githubusercontent.com/27951983/104115829-77f48480-534e-11eb-8c8b-c7f0e6ddc722.png)
4. The screen will flicker and end up with blank page. See error:
![image](https://user-images.githubusercontent.com/27951983/104115846-ac684080-534e-11eb-86ca-897142e3f8ec.png)
![image](https://user-images.githubusercontent.com/27951983/104115646-5eead400-534c-11eb-9b9c-19f033ddaf6c.png)

**Expected behavior**
The home page should reload all the components including the Charts.

**Screenshots**
Already provided in the **To Reproduce** section

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: `^1.0.0-rc.11`
`@ui5/webcomponents-react` version: `^0.13.0`
Operating System: MacOS
Browser: Google Chrome

**Additional context**
I tried with the latest version of chart component `^0.13.0` but the error still exists there.

**Comment by MarcusNotheis** [comment]
Hey @jcailan,
thanks for reporting. It looks like this issue is related to https://github.com/recharts/recharts/issues/2385.
Unfortunately I'm not sure whether we can solve the issue on our side or if we need that fixed in recharts - we'll continue to investigate.

**Comment by MarcusNotheis** [comment]
We just released `@ui5/webcomponents-react-charts@0.13.4` which contains a fix for this issue :)
Please let us know in case you are still facing issues.
