### ISSUE TITLE
Table: highlight when hover the TableRow

### ISSUE THREAD

**Issue by Gavinyjl** [SAP/ui5-webcomponents-react#1163]
**Is your feature request related to a problem? Please describe.**
I'm on a task that when mouse hovering each row of the `Table` component, the row will be highlighted. I searched the component docs but didn't found a prop related. 

**Describe the solution you'd like**
I tried using `useStyles` to assign the css of `TableRow` with `hover` but it didn't work.

```
const useStyles = createUseStyles(() => ({
  tableRow: {
    margin: '0 0 0 0.5rem',
    '&:hover': {
      backgroundColor: '#B0D9FE',
    },
  },
}));

const classes = useStyles();
<TableRow className={classes.tableRow}>

```

I'm wondering whether `Table` component is able to highlight a row when the mouse is hovering on the row? If don't, how can I achieve that?

**Additional context**
This is my first time to raise an issue, I'm sorry for any inappropriate expression. I'd appreciate it very much if you could reply, thank you!

**Comment by Lukas742** [comment]
Hi @Gavinyjl,

no worries your issue description is very expressive, thanks for that :)

You can change the `backgroundColor` by setting the corresponding the `--sapList_Background` css variable. If you want to change the border color too, you can do with `--sapList_BorderColor `.

Here's a [codesandbox](https://codesandbox.io/s/hardcore-cloud-2f68c?file=/src/App.js) that shows this behavior.

**Comment by Gavinyjl** [comment]
It works! Thank you very much!

**Comment by Lukas742** [comment]
Glad to hear that. 

I'm going to close this issue, if there are any more question, please feel free to open another one or create a topic in our [discussions forum](https://github.com/SAP/ui5-webcomponents-react/discussions).
