### ISSUE TITLE
Input: SuggestionItems don#t show when Input inside of a Popover

### ISSUE THREAD

**Issue by d3nergy** [SAP/ui5-webcomponents-react#118]
**Describe the bug**
When Using an Input inside of a Popover, the suggestionItems will not show, eventhough the dom contains the <li>-elements and the <ul>

**To Reproduce**
Put Input inside of a Popover and search for an items out of the suggestionItems.
Popover will not show.

**Expected behavior**
Suggestions should show as overlay of Popover. Popover should not close on suggestionItemSelect.

**Desktop (please complete the following information):**
 - OS: MAC OS
 - Browser Chrome

**Additional context**
Z-Index of InputPopover and containing Popover seem to be fine.
Containing < InputPopover

**Comment by MarcusNotheis** [comment]
I added a `wontfix` label from our end as this will most probably be fixed by https://github.com/SAP/ui5-webcomponents/issues/776.
Let's keep this issue open until it is resolved.

**Comment by MarcusNotheis** [comment]
Fixed by the web components team
