### ISSUE TITLE
ObjectPage: ObjectPageSection hides the popup in the header

### ISSUE THREAD

**Issue by gurkirpalgill** [SAP/ui5-webcomponents-react#1193]
**Describe the bug**
When the header link has a popup on click, the tab bar hides a part of the popup. This is happening due to position sticky and possibly z-index:2 on the section in ObjectPageSection.

**Expected behavior**
When a link in the header opens a popup tab bar should not hide it.

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:0.29.0
`@ui5/webcomponents-react` version:0.129.0
Operating System: Mac OS
Browser: Chrome
<img width="1913" alt="Screen Shot 2021-01-20 at 2 40 20 PM" src="https://user-images.githubusercontent.com/65705637/105250116-0e366080-5b2e-11eb-8ddd-96dd05217c2c.png">

On removing position: sticky:

<img width="1915" alt="Screen Shot 2021-01-20 at 2 40 53 PM" src="https://user-images.githubusercontent.com/65705637/105250155-20180380-5b2e-11eb-9d74-dc26104835eb.png">

**Comment by MarcusNotheis** [comment]
Hey @gurkirpalgill,
as discussed, this issue can be solved by using `ReactDOM.createPortal`, also mentioned in our [docs](https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-popover--open-on-hover#using-popovers-inside-other-components).
Closing this for now, please feel free to reopen in case there is more to do on our side.
