### ISSUE TITLE
ObjectPage: Allow user to open ObjectPageSection tab programmatically

### ISSUE THREAD

**Issue by gurkirpalgill** [SAP/ui5-webcomponents-react#1194]
**Describe the bug**
We have a use case where user clicks on one of the links in the header section of ObjectPage, it should open one of the ObjectSection tabs. Current api does not provide a way to do this.

**Expected behavior**
Allow a way to programmatically open the ObjectPageSection tab.

**Screenshots**
<img width="1903" alt="Screen Shot 2021-01-20 at 2 31 10 PM" src="https://user-images.githubusercontent.com/65705637/105250902-60c44c80-5b2f-11eb-9655-aa331d287026.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 0.29.0
`@ui5/webcomponents-react` version:0.129.0
Operating System:MacOS
Browser: Chrome

**Comment by Lukas742** [comment]
Hi @gurkirpalgill, 

the `ObjectPage` already provides the ability to select tabs/sections programmatically. You can add the prop `selectedSectionId` and dynamically change it to the desired section id. 
I've created a [codesandbox](https://codesandbox.io/s/cocky-waterfall-s5rdn?file=/src/App.js) that explains this behavior.

**Comment by gurkirpalgill** [comment]
Suggested solution works. closing the issue.
