### ISSUE TITLE
AnalyticalTable: Remove column header borders for row/navigation highlights

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents-react#1197]
**Is your feature request related to a problem? Please describe.**
The AnalyticalTable offers a row highlight and a navigation highlight which displays a color at the beginning/the end of a row.
These highlights are basically columns with a small width.
The issue is that column headers for these two columns have borders that makes the table header a bit unaesthetic. 

![image-2021-01-19-12-46-55-407](https://user-images.githubusercontent.com/7316793/105330893-185e6a80-5bd3-11eb-98f1-eff0132c670c.png)

<img width="284" alt="Screen Shot 2021-01-20 at 19 05 30" src="https://user-images.githubusercontent.com/7316793/105330998-3b891a00-5bd3-11eb-8adb-c10c7fad6136.png">

**Describe the solution you'd like**
Remove these borders so that it doesn't feel like these row highlights are actual columns.
Without these borders, it'll look like a continuation of other columns.

**Expected result**
![image-2021-01-19-12-46-55-407](https://user-images.githubusercontent.com/7316793/105333117-a3d8fb00-5bd5-11eb-9dd7-89b7306673fc.png)
<img width="284" alt="Screen Shot 2021-01-20 at 19 05 30" src="https://user-images.githubusercontent.com/7316793/105333139-ab989f80-5bd5-11eb-9cd0-4d0dc7879226.png">

**Comment by MarcusNotheis** [comment]
Fixed and released with `@ui5/webcomponents-react@0.13.5`
