### ISSUE TITLE
ObjectPage: IE11: Pin button in the header does not display at the right place

### ISSUE THREAD

**Issue by gurkirpalgill** [SAP/ui5-webcomponents-react#1206]
**Describe the bug**
Pin button in the ObjectPage Header shows at the top in IE11

**Expected behavior**
It should show at the right place.

**Screenshots**
<img width="1899" alt="Screen Shot 2021-01-22 at 5 30 04 PM" src="https://user-images.githubusercontent.com/65705637/105564693-2813a700-5cd8-11eb-8dc2-aee24053559c.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:0.29.0
`@ui5/webcomponents-react` version: 0.129.1
Operating System: Windows
Browser:IE11

**Comment by Lukas742** [comment]
Released in [v0.13.10](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.13.10)
