### ISSUE TITLE
DatePicker: Unable to display DatePicker with the  error message "CLDR data for locale en is not loaded!" 

### ISSUE THREAD

**Issue by XerxesAS** [SAP/ui5-webcomponents-react#1212]
**Describe the bug**

**Isolated Example**
*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).*

**Screenshots**
The datePicker is unable to display, and in the console, we have the following error:
Uncaught (in promise) Error: CLDR data for locale en is not loaded!
    at Object.getModuleContent [as loadResource] (LocaleData.js:77)
    at getOrLoad (LocaleData.js:2664)
    at getData (LocaleData.js:2691)
    at new constructor (LocaleData.js:12)
    at Function.push../node_modules/@ui5/webcomponents-localization/dist/sap/ui/core/LocaleData.js.LocaleData.getInstance (LocaleData.js:2726)
    at getCachedLocaleDataInstance (getCachedLocaleDataInstance.js:7)
    at HTMLElement.get _primaryCalendarType [as _primaryCalendarType] (DatePicker.js:764)
    at HTMLElement.onBeforeRendering (DatePicker.js:470)
    at HTMLElement._render (UI5Element.js:533)
    at Function.renderImmediately (RenderScheduler.js:46)
    at HTMLElement.connectedCallback (UI5Element.js:145)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.10
`@ui5/webcomponents-react` version: 0.12.3
Operating System: macOS/Windows
Browser:Chrome

**Additional context**

**Comment by MarcusNotheis** [comment]
Hey @XerxesAS,
thanks for reporting!
Could you please give us some more information on how to reproduce this error, preferably using [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34)?

**Comment by XerxesAS** [comment]
Hi @MarcusNotheis,
Thanks for replying. I have solved this problem by updating @ui5/webcomponents-react version to 0.13.4.

**Comment by L3K0V** [comment]
![image](https://user-images.githubusercontent.com/2267270/175300126-02e9e25d-794a-4a71-8721-a18bf19757fb.png)

```
"@ui5/webcomponents": "^1.3.1",
"@ui5/webcomponents-fiori": "^1.3.1",
"@ui5/webcomponents-icons": "^1.3.1",
"@ui5/webcomponents-icons-business-suite": "^1.3.1",
"@ui5/webcomponents-react": "^0.23.2",
```

**Comment by MarcusNotheis** [comment]
Hi @L3K0V,
this issue is caused by https://github.com/SAP/ui5-webcomponents/issues/5394.
It is fixed in the meantime but not released yet.

Anyways, this error should only occur in dev environments - for production use cases it's recommended to [import Assets](https://github.com/SAP/ui5-webcomponents/blob/main/docs/1-getting-started/05-using-assets.md).

In you case this would be:
```
import '@ui5/webcomponents/dist/Assets.js';
import '@ui5/webcomponents-fiori/dist/Assets.js';
import '@ui5/webcomponents-react/dist/Assets.js';
```

Please note that this is currently not working in codesandbox but [is already fixed](https://github.com/SAP/ui5-webcomponents/pull/5298) and will be released soon.

**Comment by I533780** [comment]
@MarcusNotheis Even after importing the assets our E2E tests(Cypress) keep failing with the same error. Is there anything we can do to prevent it?

<img width="535" alt="Screenshot 2024-03-15 at 16 55 03" src="https://github.com/SAP/ui5-webcomponents-react/assets/72817007/e05ca9a3-9c40-49da-8931-380a7f52ba1a">
