### ISSUE TITLE
Bar: Doesn't work with false JSX "if" statements

### ISSUE THREAD

**Issue by jeff-fillmore** [SAP/ui5-webcomponents-react#1213]
**Describe the bug**
Bar web component doesn't work with false JSX "if" statements.

**Isolated Example**
Hopefully this works as I've never done this before:
https://codesandbox.io/s/headless-dust-bn76y?file=/src/App.js

**To Reproduce**
1. Create a new project for the UI5-webcomponent-react
2. Add a Bar web component
3. Use a false JSX "if" statement in start, middle, or end content:
```
const booleanVariable = false;
const jsxvariable = (<>{booleanVariable && <span>asdf</span>}<span>fdsa</span></>);
<Bar startContent={jsxvariable} />
```

Error
React.cloneElement(...): The argument must be a React element, but you passed null.

**Expected behavior**
Bar should render with:
`<span>fdsa</span>`

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.11
`@ui5/webcomponents-react` version: 0.13.4
Operating System: Mac 10.15.7
Browser: Chrome 87.0.4280.141

**Comment by MarcusNotheis** [comment]
Hey @jeff-fillmore,
thanks, your codesandbox was perfectly fine!
We fixed and released this issue with `@ui5/webcomponents-react@0.13.5`.

**Comment by jeff-fillmore** [comment]
@MarcusNotheis Thanks so much for the quick fix!  My team really appreciates this project and all the hard work that goes into it.
