### ISSUE TITLE
StandardListItem: onClick handler does not fire for child elements

### ISSUE THREAD

**Issue by charlie-maloney** [SAP/ui5-webcomponents-react#1222]
**Describe the bug**
`StandardListItem` doesn't allow child elements to fire onClick handler

**Isolated Example**
https://codesandbox.io/s/angry-lake-6y9e9?file=/src/App.js:475-491

**To Reproduce**
Click on any of the `StandardListItem` items and watch for the console.log()

**Expected behavior**
I expect the onClick handler to fire

**UI5 Web Components for React Information**
same as in the code sandbox above: 
`@ui5/webcomponents` version: 1.0.0-rc.11
`@ui5/webcomponents-react` version: 0.13.5
Operating System: Mac OS
Browser: Chrome

**Additional context**
We ran into this problem because we wanted to put nav items in the `menuItems` prop for the `ShellBar`, but couldn't get the click handlers to fire. 

Thanks in advance for looking into this!

**Comment by Lukas742** [comment]
Hi @charlie-maloney,

as mentioned in our [documentation](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-list--default-story#properties) (StandardListItem tab in the properties table), we strongly recommend to only use text as child of the `StandarListItem` component.
To trigger an event when clicking a list item you can use the `onItemClick` prop of the `List`.

If you want to render multiple children, or children that aren't text, the `CustomListItem` is probably the way to go for you.

I've prepared a [codesandbox](https://codesandbox.io/s/stupefied-surf-ymhis?file=/src/App.js) that explains this in more detail.

**Comment by charlie-maloney** [comment]
Hi @Lukas742,

Thanks for your quick reply and appreciate the sandbox example. I will plan on using the `CustomListItem` for our use case with the ShellBar `menuItems` prop.
