### ISSUE TITLE
SideNavigation: SideNavigation cannot show after using fixedItems

### ISSUE THREAD

**Issue by rkl1994** [SAP/ui5-webcomponents-react#1258]
**Describe the bug**
While updating version to "@ui5/webcomponents-react": "0.13.6", the fixedItems in SideNavigation will show error: 'Cannot read property 'some' of undefined'.

If remove fixedItems, SideNavigation works.

**Isolated Example**
*Please provide an isolated example if possible
https://codesandbox.io/s/mystifying-sky-obj9f

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: "1.0.0-rc.11"
 "@ui5/webcomponents-react": "0.13.6",

**Comment by Lukas742** [comment]
Hi @rkl1994 

Thanks for creating this issue.
The fix has been released in [v0.13.7](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.13.7)
