### ISSUE TITLE
FormItem: Label positioned vertically centred instead of on top for multi-line content

### ISSUE THREAD

**Issue by goodefroi** [SAP/ui5-webcomponents-react#1261]
**Describe the bug**
`FormItem` components arranged in horizontal layout have their `Label` rendered vertically centred instead of on the top (top-left for LTR languages and top-right for RTL languages, I assume).

**Isolated Example**
[Minimal example](https://codesandbox.io/s/gallant-drake-9i9z0?file=/src/index.js) on `codesandbox.io`.

**To Reproduce**
Steps to reproduce the behaviour:
1. Wrap a `FormItem` in a vanilla `Form` to force horizontal layout if there's enough space, add a `label` attribute to the `FormItem` and have it hold a multi-line component such as a `TextArea`.

**Expected behaviour**
The `Label` is rendered on the top-left/top-right, according to the Fiori 3 design spec.

**Screenshots**
Expected behaviour (taken from Fiori 3 spec):
![image](https://user-images.githubusercontent.com/27777253/107054977-100c4f00-67d1-11eb-9333-193de16d5e50.png)
Actual behaviour:
![image](https://user-images.githubusercontent.com/27777253/107054885-f4a14400-67d0-11eb-83fd-c4c2994befc3.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: `1.0.0-rc.11`
`@ui5/webcomponents-react` version: `0.13.6`
Operating System: macOS Big Sur
Browser: Chrome 88

**Comment by schamane** [comment]
Same expected behaviour here...

**Comment by Lukas742** [comment]
Fixed in [0.13.9](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.13.9)
