### ISSUE TITLE
Fiori guidelines - Side navigation and breadcrumb

### ISSUE THREAD

**Issue by CristianDDias** [SAP/ui5-webcomponents-react#127]
**Is your feature request related to a problem? Please describe.**
There is no Side Navigation and Breadcrumb components, such as presented in the [Fiori guidelines](https://experience.sap.com/fiori-design-web/side-navigation/#overview). Many modern applications have these components nowadays.

**Describe the solution you'd like**
I would like to have a Side Navigation and Breadcrumb components. There are these components in the Fiori Fundamentals. [Side Navigation](https://sap.github.io/fundamental/components/side-navigation.html) and [Breadcrumb](https://sap.github.io/fundamental/components/breadcrumb.html).

**Describe alternatives you've considered**
For the Side Navigation, I think about creating a component using the `List` component.
For the Breadcrumb, I think about creating a component using the `Link` component.

**Comment by MarcusNotheis** [comment]
Hi @CristianDDias,

thanks for submitting this issue.
We just released the [Breadcrumbs](https://ui5-webcomponents-react.netlify.com/?path=/docs/components-breadcrumbs--default-story) in version `0.5.1-rc.14`.
The SideNavigation is currently under development, we'll let you know as soon as we are ready.

Best regards,
Marcus

**Comment by CristianDDias** [comment]
Thank you @MarcusNotheis!

**Comment by CristianDDias** [comment]
@MarcusNotheis, do you have any expected release date for this Side Navigation feature?

**Comment by MarcusNotheis** [comment]
@CristianDDias I hope to have an initial version by end of this week

**Comment by CristianDDias** [comment]
Thank you @MarcusNotheis!

**Comment by MarcusNotheis** [comment]
Hi @CristianDDias,

the SideNavigation was just released in `0.5.1-rc.16` :)
