### ISSUE TITLE
AnalyticalTable: onRowClick event does not exist

### ISSUE THREAD

**Issue by toadslop** [SAP/ui5-webcomponents-react#1274]
**Describe the bug**
When implementing an onRowClick event on the AnalyticalTable, an error message is reported in the console saying that the onRowClick event does not exist and will be ignored.
![image](https://user-images.githubusercontent.com/31160338/107324883-2295c980-6aec-11eb-9558-2f329d453026.png)

**Isolated Example**
```
function App() {
  const handleClick = () => console.log('asdasd');
  return (
    <ThemeProvider>
    <AnalyticalTable
      selectionMode="SingleSelect"
      selectionBehavior="RowOnly"
      filterable="true"
      onRowClick={handleClick}
      withNavigationHighlight
      columns={[
        {
          Header: 'Name',
          accessor: 'name',
        },
        {
          Header: 'Age',
          accessor: 'age',
        },
        {
          Header: 'Friend Name',
          accessor: 'friend.name',
        },
        {
          accessor: 'friend.age',
          hAlign: 'End',
        },
      ]}
      data={[
        {
          age: 50,
          friend: {
            age: 33,
            name: 'Carl Klein',
          },
          longColumn: 'Really really long column content... don´t crop please',
          name: 'Rose DeAngelo',
          status: 'Information',
        },
        {
          age: 44,
          friend: {
            age: 20,
            name: 'Susanne James',
          },
          longColumn: 'Really really long column content... don´t crop please',
          name: 'Bob DeAngelo',
          status: 'None',
        },
        {
          age: 53,
          friend: {
            age: 55,
            name: 'Rick Herman of Longnameington the Third',
          },
          longColumn: 'Really really long column content... don´t crop please',
          name: 'Rick Franco',
          status: 'Information',
        },
        {
          age: 33,
          friend: {
            age: 43,
            name: 'Dan Herman of Longnameington the Third',
          },
          longColumn: 'Really really long column content... don´t crop please',
          name: 'Dan Grimes',
          status: 'Information',
        },
      ]}
    />
  </ThemeProvider>
  );
}
```

**To Reproduce**
1. Define a simple table with data, as shown above.
2. Add an onRowClick event handler.
3. Render the app.
4. Open the console to see the error.

**Expected behavior**
There should be no error telling me that the event doesn't exist. Alternatively, the documentation should not state that nonexistent events exist.

**UI5 Web Components for React Information**
@ui5/webcomponents: 1.0.0-rc.11,
@ui5/webcomponents-fiori: 1.0.0-rc.11,
@ui5/webcomponents-react: 0.13.8",
Operating System: Windows 10
Browser: Google Chrome

**Comment by MarcusNotheis** [comment]
Hey @toadslop,
thanks for reporting.
I just tried to reproduce this error but was not able to: https://codesandbox.io/s/vigorous-wood-zp7yd?file=/src/App.js
Did I miss something in the codesandbox?

This may sound now like the classical support advice, but have you already tried to delete all node_modules and run new `npm install` (or `yarn install`)?

**Comment by toadslop** [comment]
@MarcusNotheis Hi Marcus. Thanks for your response. Yes, I did try that. Could you try running it on your local machine rather than on code sandbox? I find that the code sandbox environment doesn't reflect an actual running environment enough to be a reliable way to test code. Consistently, when I run into issues I am also unable to reproduce them in code sandbox.

**Comment by MarcusNotheis** [comment]
Hey @toadslop,
@Lukas742 and myself tried to run the codesandbox locally, both in "standard" mode and `React.StrictMode` but we are still not able to reproduce this error.
Could you prepare a github repo where you create a reproducible sample for the error you are facing?

**Comment by toadslop** [comment]
@MarcusNotheis Thanks for checking on that for me. I'll try to get a repo up with the code that I'm using as soon as possible.
