### ISSUE TITLE
Page: Changing display none to display block the page body overlays the header

### ISSUE THREAD

**Issue by jeff-fillmore** [SAP/ui5-webcomponents-react#1286]
**Describe the bug**
The Page component doesn't calculate the header size correctly when the Page or a wrapping element changes from display: none to display:block.

This cause the body to overlay the header.

**Isolated Example**
https://codesandbox.io/s/headless-dust-bn76y?file=/src/App.js

**To Reproduce**
1. Go to https://codesandbox.io/s/headless-dust-bn76y?file=/src/App.js
2. Click on 'show page'
3. See page body overlaying the page header

**Expected behavior**
The page body should render below the header

**Screenshots**
![image](https://user-images.githubusercontent.com/69171783/107711461-ec3f8200-6c84-11eb-9ece-b0601dd00cc0.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.11
`@ui5/webcomponents-react` version: 0.13.9
Operating System: MacOS
Browser: Chrome

**Comment by Lukas742** [comment]
Hi @jeff-fillmore 

is there any particular reason, you have to manipulate the refs to change the css `display` type? When `Refs` are changed, they don't update the component, that's probably the reason why this is happening. 

Could you try setting the style directly to your `div` (with inline-style or style classes)? This should solve the issue:
[codesandbox](https://codesandbox.io/s/holy-night-wfwxr?file=/src/App.js)

Also, maybe you could even try to conditional render the component, so it only gets mounted when needed and thus should improve performance: [codesandbox](https://codesandbox.io/s/bold-glitter-qelce?file=/src/App.js)

**Comment by jeff-fillmore** [comment]
Hi @Lukas742 

Thanks for the information :)

The microservice I'm working on is wrapped by a hosting application.  The react application is inside a standard HTML web component.  The hosting applicaiton sets the web component to display none and then display block when the user is ready to use it.

I will try your suggestions and see if we can force a re-render when the styles are changed on the web component.

Thanks!

**Comment by jeff-fillmore** [comment]
Hi @Lukas742 

The team found a work around where we set the height of the web component to 0 instead of display: none and then increase the height when the user is ready.   This cause the resize event to fire and the page to work.

Thanks,

Jeff
