### ISSUE TITLE
FormGroup: Insufficient spacing between groups

### ISSUE THREAD

**Issue by goodefroi** [SAP/ui5-webcomponents-react#1291]
**Describe the bug**
Two consecutive `FormGroup`s have no spacing in between.

**Isolated Example**
[Isolated example on `codesandbox.io`](https://codesandbox.io/s/loving-bird-pl0vv?file=/src/App.js).

**To Reproduce**
Use this code:
```
import React from "react";
import {
  ThemeProvider,
  Form,
  FormGroup,
  FormItem,
  Text
} from "@ui5/webcomponents-react";

export default function App() {
  return (
    <ThemeProvider>
      <Form title="My Form">
        <FormGroup title="1st FormGroup">
          <FormItem label="1st FormItem">
            <Text>This is the content of my 1st FormItem.</Text>
          </FormItem>
        </FormGroup>
        <FormGroup title="2nd FormGroup">
          <FormItem label="2nd FormItem">
            <Text>This is the content of my 2nd FormItem.</Text>
          </FormItem>
        </FormGroup>
      </Form>
    </ThemeProvider>
  );
}
```

**Expected behavior**
Per Fiori 3 spec, I'd expect the `FormGroup` title to be vertically centred in a box that is `2rem` high; furthermore, all groups should have an additional top and bottom margin of `1rem`.

**Screenshots**
![image](https://user-images.githubusercontent.com/27777253/107797635-6e01df00-6d5b-11eb-9b5d-bc4c5de688c9.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: `1.0.0-rc.11`
`@ui5/webcomponents-react` version: `0.13.9`
Operating System: `macOS 11.2.1`
Browser: `Chrome 88`

**Additional context**
(The `Text` looks quite misaligned with the `FormItem` `Label` as well.)

**Comment by MarcusNotheis** [comment]
Released in `@ui5/webcomponents-react@0.13.10`
