### ISSUE TITLE
Pressing ENTER in AnalyticalTable row doesn't trigger selection

### ISSUE THREAD

**Issue by AustinEel** [SAP/ui5-webcomponents-react#1306]
**Describe the bug**
When a row in an AnalyticalTable is focused(via tabbing or arrow keys), pressing the ENTER key does not select the row.

**Isolated Example**
Sandbox [here](https://codesandbox.io/s/nervous-sound-qhwbv?fontsize=14&hidenavigation=1&theme=dark)

**To Reproduce**
1. Press Tab until a row in the AnalyticalTable is focused
2. Use arrow keys to navigate throughout the cells
3. Press enter on the row

**Expected behavior**
Pressing Enter should activate the row selection, cause the row to become highlighted and onRowSelected() functions to be called.

**Screenshots**

![image](https://user-images.githubusercontent.com/16329673/108257521-c34f3f00-7113-11eb-8a06-2cd88d254855.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0.rc-11
`@ui5/webcomponents-react` version: 0.13.4
Operating System: MacOS Big Sur 11.2.1
Browser: Google Chrome

**Additional context**
Pressing enter on the 'Select all' checkbox correctly selects the rows, but this does not work on any other individual row. When focus is on the checkbox specifically, pressing Enter triggers the checkbox to be checked, but doesn't trigger the actual row selection

**Comment by MarcusNotheis** [comment]
Released in `@ui5/webcomponents-react@0.14.2`
