### ISSUE TITLE
ObjectPage: Crash on re-mounting the component

### ISSUE THREAD

**Issue by nazarkulyk** [SAP/ui5-webcomponents-react#1315]
Thats followup bug report for https://github.com/SAP/ui5-webcomponents-react/issues/1300

![image](https://user-images.githubusercontent.com/22763871/108470060-a5a3e600-7289-11eb-82d6-a86c29dc0f8f.png)

UI5 Web Components for React Information
@ui5/webcomponents "^1.0.0-rc.11"
@ui5/webcomponents-react "0.13.10"

Please release also 0.13.x version fix also. We have some breaking changes for rc-12.

Thanks

**Comment by MarcusNotheis** [comment]
Hey @nazarkulyk,
we released a possible fix in `@ui5/webcomponents-react@0.13.11` and `@ui5/webcomponents-react@0.14.1`.
Unfortunately I was not able to reproduce the error so I tried to fix it on a best guess basis, please let me know whether it worked 🙂

**Comment by nazarkulyk** [comment]
We will test 0.13.11 today. Big thanks!

**Comment by nazarkulyk** [comment]
@MarcusNotheis once again thanks! I can confirm, bug is now fixed!
I close this issue.
