### ISSUE TITLE
Dialog: header and footer not being placed in proper slots

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents-react#1323]
**Describe the bug**
When placing a custom React component into the header or footer for a dialog, the elements in the DOM are placed in the default slot.

**Isolated Example**
https://codesandbox.io/s/beautiful-dewdney-fl5wc

**To Reproduce**
1. Go to https://codesandbox.io/s/beautiful-dewdney-fl5wc
2. Click on the "Open Dialog" button
3. Notice that the header and footer are not properly placed.

**Expected behavior**
The header and footer should be properly placed in the dialog.

**Screenshots**
![image](https://user-images.githubusercontent.com/8508119/108770081-be70fd80-750e-11eb-8f2c-27d6d23a66d4.png)

**UI5 Web Components for React Information**
"@ui5/webcomponents": "0.29.4",
"@ui5/webcomponents-fiori": "0.29.0",
"@ui5/webcomponents-react": "0.129.4",
Operating System: Windows
Browser: Chrome

**Comment by Lukas742** [comment]
Hi @agauyeung 

if you want to use custom components inside of `slot` props, you have to also add the `slot` to the most outer element of your component. 

[codesandbox](https://codesandbox.io/s/boring-solomon-2vjs7?file=/src/App.js)

We will [add](https://github.com/SAP/ui5-webcomponents-react/pull/1342) this to our documentation, sorry for the confusion.
