### ISSUE TITLE
NumberInput: Can't be rerendered

### ISSUE THREAD

**Issue by LucaFilitz** [SAP/ui5-webcomponents-react#134]
Hello,
You can't rerender the number input. Because of this it's very hard to build a validation. For example, that you can't go below zero.

**To Reproduce**
`
const [value, setValue] = useState(1);

const eventHandler = (e: Event) => {
    const value = +e.parameters.value;
    if(value < 1) setValue(1);
}

return(
<Input
      type={InputType.Number}
      onChange={eventHandler}
      onInput={eventHandler}
      value={value}
      valueState={error ? ValueState.Error : undefined}
/>
);
`

**Expected behavior**
If you input a number below 1 it should be changed to 1

**What happens**
Nothing. You can input negative numbers.

**Comment by LucaFilitz** [comment]
+ There are similar problems with the selection.
You can't rerender it aswell. If for example you want to change the options because of an other input, you can't.

**Comment by vbersch** [comment]
Hi @LucaFilitz ,

This is a problem with the underlying Web Component. We created an issue there: SAP/ui5-webcomponents#786.

Keeping this issue open until the other one is resolved.

best regards,
Viktor

**Comment by vbersch** [comment]
Hi @LucaFilitz ,

Please see this comment in the ui5-webcomponents repo on how to achieve the behavior you want:
https://github.com/SAP/ui5-webcomponents/issues/786#issuecomment-534434249

best regards,
Viktor
