### ISSUE TITLE
UI5 Web Components React with TypeScript

### ISSUE THREAD

**Issue by AnmolGoel93** [SAP/ui5-webcomponents-react#1375]
In our project we are using ui5-web-components-react along with typescript. But there is an issue that we are facing and would like to confirm if this is supported by web components.

Scenario : Click on a Button to open a UI5 Dialog. Using react useRef method to open the dialog. But since we are using typescript we need to specify the return type of the control for useRef method and it gives us error.

Code : 

import { ShellBar, ThemeProvider, Button, Dialog, Bar } from "@ui5/webcomponents-react";
import React, { useRef, useState } from "react";

const dialogRef = useRef<Dialog>();

const handleOpen = () => {
  dialogRef?.current?.open();
};
  
const handleClose = () => {
   dialogRef?.current?.close();
};
 
return (
   <ThemeProvider>
        <ShellBar primaryTitle="UI5 Web Components for React Template" />
        <Button onClick={handleOpen}> Open Dialog </Button>
        <Dialog
            ref={dialogRef}
            header={<Bar startContent={ <><Button icon="nav-back"/></>}>
          </Dialog>
      </ThemeProvider>
    );
    
Error : 'Dialog' refers to a value, but is being used as a type here. Did you mean 'typeof Dialog'?
If w change this statement : const dialogRef = useRef<Dialog>(); to const dialogRef = useRef<typeof Dialog>();, then the error is  : Property 'open' does not exist on type 'FC<DialogPropTypes>'.

Is there any method to solve this issue?? Are web components supported with typescript?

**Comment by MarcusNotheis** [comment]
Hey @AnmolGoel93,
if I have understood you correctly, you need to have typings for the Dialog DOM Ref? You can use the `Ui5DialogDomRef` interface for that, I've prepared a little sample [here](https://codesandbox.io/s/vigilant-hopper-42b00?file=/src/App.tsx)
