### ISSUE TITLE
Define function to be executed on MessageBox with custom actions

### ISSUE THREAD

**Issue by marceloschreiber** [SAP/ui5-webcomponents-react#1376]
**Describe the documentation issue**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [X] Documentation is missing
- [ ] Other

**Description of the issue**
I'm not sure how to define the function to be executed when using custom actions in a MessageBox.

On the example [MessageBox with custom actions](https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-messagebox--with-custom-action#messagebox-with-custom-actions) how can I execute a custom function when clicking on **A custom action**?

Based on the [source code](https://github.com/SAP/ui5-webcomponents-react/blob/33be6cca3b4d14a0156a8b496a56ab43961d8ebe/packages/main/src/components/MessageBox/index.tsx#L205) this does not seem possible, but I'd like the confirmation because it seems odd to have the option to add custom actions but not to define their behavior.

Thank you!

**Comment by Lukas742** [comment]
Hi @marceloschreiber 

to add some logic to the different actions you can use `event.detail.action` of the `onClose` callback. 
I prepared a [codesandbox](https://codesandbox.io/s/hidden-morning-tqyso?file=/src/App.js) that should explain this in more detail. I also created a PR (https://github.com/SAP/ui5-webcomponents-react/pull/1379) which adds this to our documentation. 

I hope this helps and thanks for bringing this up :)

**Comment by marceloschreiber** [comment]
Hi @Lukas742, thank you for the quick reply!

I missed the part of the `onClose` description, but it makes sense. Your PR is going to be a nice addition since others might have the same doubt that I did :)
