### ISSUE TITLE
MessageBox/Form: Wrapping Form in MessageBox causes it to shake around

### ISSUE THREAD

**Issue by goodefroi** [SAP/ui5-webcomponents-react#1387]
**Describe the bug**
Wrapping a `Form` in a `MessageBox` causes the form/dialog window to frantically change their size.

**Isolated Example**
[Isolated example on `codesandbox.io`.](https://codesandbox.io/s/agitated-fog-dyht9?file=/src/App.js)

**To Reproduce**
1. Wrap `FormItem` in `Form` in open `MessageBox` in `ThemeProvider`.
2. Enjoy blinkenlights.

It doesn't happen when leaving out the `Form` though, so my first guess would be a bug in the auto-layouting code of that component.

**Expected behavior**
`MessageBox` and containing `Form` don't change size.

**Screenshots**
A screenshot wouldn't do the bug justice, find a short video clip [here](https://user-images.githubusercontent.com/27777253/110147639-37f4cf80-7ddc-11eb-90d6-51e177faf386.mov).

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: `1.0.0-rc.12`
`@ui5/webcomponents-react` version: `0.14.3`
Operating System: macOS Big Sur
Browser: Chrome 88

**Comment by Lukas742** [comment]
Hi @goodefroi 

The `MessageBox` is intended to only receive text as child. If you want to add a custom message-box component, you could use the `Dialog` and add the necessary components there. 

The flickering is unfortunately also occurring in the `Dialog`, but can be fixed by applying a `width` to the dialog. 
I've created a [codesandbox](https://codesandbox.io/s/thirsty-brook-505m3?file=/src/App.js) that shows this small workaround.

I will investigate where this error originates from and will inform you when it is fixed.

**Comment by goodefroi** [comment]
Hi @Lukas742, thank you for your reply - sorry for filing a bug report for behavior that's out-of-spec, I hadn't read the docs carefully enough.
The `MessageBox` is a lot more convenient than the `Dialog` though and I'd love it to be more powerful. In case you don't have the resources available to extend it to allow for arbitrary content, I might be able to sink in the time to add that feature. Admittedly that creates even more overlap with the `Dialog` component but maybe there is a way to sort this out.

**Comment by Lukas742** [comment]
Thank you for wanting to take this on, but the `MessageBox` was built like this to conform to UX guidelines. There it is stated that MessageBoxes should only display text, so we decided to support text only as well. 

If you are mainly concerned with the way the MessageBox can be opened (compared to the `Dialog`), then I have good news for you, as we are already working with the ui5-webcomponents team to find a more user-friendly implementation. We don't have an ETA for it yet though. For more information you can have a look at [this issues](https://github.com/SAP/ui5-webcomponents-react/issues/1101).

**Comment by goodefroi** [comment]
As you suspected I'm mostly concerned with the opening behavior - it's great to hear there's ongoing work on that topic. Bonus points if `createPortal` isn't required anymore. ;)

**Comment by Lukas742** [comment]
Hi @goodefroi 

we fixed the flickering in [v0.14.4](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.14.4).

**Comment by goodefroi** [comment]
@Lukas742 Wonderful, thanks a lot!
