### ISSUE TITLE
ui5-webcomponents-react bundling / storybook and This method has been removed. Use `registerI18nLoader` instead.

### ISSUE THREAD

**Issue by nazarkulyk** [SAP/ui5-webcomponents-react#1401]
We have some separate npm package with ui5-webcomponents-react as bundle.
We have storybook with some preview.js file to handle Themes and ContentDensity.
Earlier wee needed this Assets import. Is it not needed anymore?

```js
import '@ui5/webcomponents-react/dist/Assets';
```
This line cause problems with i18n outdated api.

Error i get is:

```text
Uncaught Error: This method has been removed. Use `registerI18nLoader` instead.
    at registerI18nBundle (i18n.js:41)
    at Module../node_modules/@ui5/webcomponents-react/dist/json-imports/i18n.js (i18n.js:93)
    at __webpack_require__ (bootstrap:853)
    at fn (bootstrap:150)
    at Module../node_modules/@ui5/webcomponents-react/dist/Assets.js (Assets.js:1)
    at __webpack_require__ (bootstrap:853)
    at fn (bootstrap:150)
    at Module../.storybook/preview.js (generated-stories-entry.js:6)
    at __webpack_require__ (bootstrap:853)
    at fn (bootstrap:150)
registerI18nBundle @ i18n.js:41
./node_modules/@ui5/webcomponents-react/dist/json-imports/i18n.js @ i18n.js:93
__webpack_require__ @ bootstrap:853
fn @ bootstrap:150
./node_modules/@ui5/webcomponents-react/dist/Assets.js @ Assets.js:1
__webpack_require__ @ bootstrap:853
fn @ bootstrap:150
./.storybook/preview.js @ generated-stories-entry.js:6
__webpack_require__ @ bootstrap:853
fn @ bootstrap:150
./.storybook/preview.js-generated-config-entry.js @ preview.js-generated-config-entry.js:7
__webpack_require__ @ bootstrap:853
fn @ bootstrap:150
0 @ index.ts:1
__webpack_require__ @ bootstrap:853
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ main.54c5cce8294df68fb679.bundle.js:1
```

![image](https://user-images.githubusercontent.com/22763871/110618223-d4312480-8196-11eb-9ad2-8e087ca5928c.png)

**UI5 Web Components for React Information**
    "@ui5/webcomponents": "1.0.0-rc.12",
    "@ui5/webcomponents-base": "0.30.0",
    "@ui5/webcomponents-fiori": "1.0.0-rc.12",
    "@ui5/webcomponents-icons": "^1.0.0-rc.12",
    "@ui5/webcomponents-react": "0.14.4",
    "@ui5/webcomponents-react-base": "0.14.4",
    "@ui5/webcomponents-theme-base": "1.0.0-rc.12",

**Comment by MarcusNotheis** [comment]
Hey @nazarkulyk,

you still need the asset imports but we have faced the same issue with storybook to be honest. 
Our solution was to delete the `.cache` folder in the `node_modules` or the entire `node_modules` as storybook is caching some old references there.

**Comment by nazarkulyk** [comment]
Hi @MarcusNotheis,

i deleted whole node_modules from package folder. Browser cache. Also deleted my whole ~/.npm/ folder with no changes :(
Any other ideas, current we are not able to use latest versions... :(

Thats a full track stack window:
![image](https://user-images.githubusercontent.com/22763871/110630342-87a11580-81a5-11eb-8b81-7e9375b2f245.png)

**Comment by nazarkulyk** [comment]
Looks like npm still install old files. Event after complete removal:
![image](https://user-images.githubusercontent.com/22763871/110631225-93410c00-81a6-11eb-9cc7-899a0ea8cac0.png)

**Comment by nazarkulyk** [comment]
Ok, i found issue.
I have rised version by hand:

- "@ui5/webcomponents-react": "^0.13.10",
- "@ui5/webcomponents-react-base": "^0.13.10",

+ "@ui5/webcomponents-react": "^0.14.4",
+ "@ui5/webcomponents-react-base": "^0.14.4",

Now it works. We can cloud issue, problem was my side. Strange that npm does calculate versions in such kind.

**Comment by MarcusNotheis** [comment]
Hey @nazarkulyk,

good to hear that you found a solution.
Most probably npm does not install the `0.14.x` because we are still in the 0.x space and incrementing the minor version does not work the caret for those versions.

Will close the issue, thanks!

**Comment by nazarkulyk** [comment]
Yes, i did updated package.json on "peerDependancies" part, but didn't for "dependancies".
