### ISSUE TITLE
AnalyticalTable: onLoadMore e.detail.rowCount is not correct

### ISSUE THREAD

**Issue by tqq123** [SAP/ui5-webcomponents-react#1404]
**Describe the bug**
I didn't expand any row and then I scrolled down , the detail.rowCount is 20，but if I expanded one row and scroll down again, the detail.rowCount will be 21. It should be 20. The status of row should not impact the rowCount. 

**Expected behavior**
the detail.rowCount should be 20

**Screenshots**
![image](https://user-images.githubusercontent.com/19241167/110765684-661c5880-828f-11eb-99ea-2f776ce9649a.png)
![image](https://user-images.githubusercontent.com/19241167/110765725-6f0d2a00-828f-11eb-8bd9-42585146f2f2.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:1.0.0-rc.10
`@ui5/webcomponents-react` version:0.12.2
Operating System: Mac OS  11.2.1
Browser: Chrome  89.0.4389.82

**Comment by MarcusNotheis** [comment]
Fixed and released in `@ui5/webcomponents-react@0.14.5`
