### ISSUE TITLE
FormItem: Label position with checkbox children

### ISSUE THREAD

**Issue by ArneBuetergerds** [SAP/ui5-webcomponents-react#1409]
The position of the FormItem label, with a checkbox as its child, is not centered and changes when the value of the checkbox changes.

You can see and reproduce this in the default example of the Form component in the [storybock](https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-form--default-story).

Actually, the position should be centered and not change with actions of the child component.

![chrome_AOJ2npyg5g](https://user-images.githubusercontent.com/40249316/111130963-1338ee80-8578-11eb-8310-9ad45a80da7e.png)

`@ui5/webcomponents` version: 1.0.0-rc.12
`@ui5/webcomponents-react` version: 0.14.4
Operating System: Windows
Browser: Chrome

**Comment by Lukas742** [comment]
Hi @ArneBuetergerds 

we are currently discussing this topic with the ui5-webcomponents team. Just so you know that we have not forgotten this.

**Comment by MarcusNotheis** [comment]
Released in `@ui5/webcomponents-react@0.16.3`.

**Comment by Lukas742** [comment]
Released in [0.16.3](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.16.3)

Sorry for the delay.
