### ISSUE TITLE
MessageBox does not show actions correctly if actions array has promises with more than one action

### ISSUE THREAD

**Issue by gurkirpalgill** [SAP/ui5-webcomponents-react#1410]
When each action in the actions array is a promise as shown below, MessageBox shows an additional button with "..."
If actions array has only one action returning promise, it works fine.
Initial value in these action promises is "..." and then resolved with the actual text.

```
    const actions = [
      i18n.getText("RCM_APP_ACTION_INVITE_TO_APPLY_LABEL"),
      i18n.getText("COMMON_Cancel")
    ];
    <MessageBox
      key={dialogKey}
      data-testid="InviteToApply"
      type={messageBoxType}
      className={styles.inviteToApplyDialogWidth}
      open={messageBoxOpen}
      actions={actions}
      onClose={handleSubmit}
    >
      {inviteToApplyMessage}
    </MessageBox>
```

<img width="1676" alt="Screen Shot 2021-03-15 at 2 13 01 PM" src="https://user-images.githubusercontent.com/65705637/111222789-8e5ecc80-8599-11eb-83f9-0edd0a06b61a.png">

@ui5/webcomponents-react: "0.129.5"
@ui5/webcomponents: "^0.29.4"
Browser:Google Chrome
OS: MacOS

**Comment by MarcusNotheis** [comment]
Hey @gurkirpalgill,
we just released the fix in `0.129.7` and in `0.131.1`
