### ISSUE TITLE
Toolbar: click overflow button will not prevent the event propagation

### ISSUE THREAD

**Issue by sleric1024** [SAP/ui5-webcomponents-react#1414]
**Describe the bug**
When click the overflow button, the event propagation is not prevented, that may trigger the link navigation.

**Isolated Example**
Demo URL: https://zk8jr.csb.app/

**To Reproduce**
![2021-03-16_17-26-59](https://user-images.githubusercontent.com/5724592/111287598-57161b80-867e-11eb-9f06-6c9b9bdd17dd.jpg)

1. Click the (highlighted) overflow button on the right of the list
2. Button popover is not shown up
3. New window is opened.

**Expected behavior**
Button popover shown up

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: current version
`@ui5/webcomponents-react` version: current version
Operating System:
Browser: Chrome

**Additional context**
I am from SuccessFactors

**Comment by MarcusNotheis** [comment]
Hey @sleric1024,
we just released the current SuccessFactors versions `0.129.7` and `0.131.1` containing the fix.

**Comment by sleric1024** [comment]
Hi @MarcusNotheis @Lukas742 , thank you very much for your quick response. :)
