### ISSUE TITLE
Button: border is missing when hovering on the button

### ISSUE THREAD

**Issue by TinaC** [SAP/ui5-webcomponents-react#144]
# ui5

Hover on the transparent button, there is a blue border:
![image](https://user-images.githubusercontent.com/6975707/65492023-c2948800-dee2-11e9-821b-f037f86c69f3.png)
![image](https://user-images.githubusercontent.com/6975707/65492057-d9d37580-dee2-11e9-9eda-8f34b15eb43f.png)

# ui5 react web components

no border when hovering on the button
![image](https://user-images.githubusercontent.com/6975707/65492130-fa9bcb00-dee2-11e9-8c01-edda973d2b55.png)
![image](https://user-images.githubusercontent.com/6975707/65492146-01c2d900-dee3-11e9-9d5c-00057d037806.png)

# Reference:
Guideline: https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2025039257#Button(Fiori3)-TertiaryTransparentHighlightButton
UI5 Sample: https://sapui5.hana.ondemand.com/#/entity/sap.m.Button/sample/sap.m.sample.Button

**Comment by vbersch** [comment]
Hi,

Our button is just a wrapper for the ui5 webcomponents button. I opened an issue there:
https://github.com/SAP/ui5-webcomponents/issues/788.

best regards,
Viktor

**Comment by TinaC** [comment]
Thanks for the quick reply
