### ISSUE TITLE
SideNavigation: When SideNavigation set to collapsed, layout not display correct.

### ISSUE THREAD

**Issue by rkl1994** [SAP/ui5-webcomponents-react#1441]
**Describe the bug**
When set SideNavigation attribute collapsed to true, the SideNavigation layout messed.

**Isolated Example**
![Screen Shot 2021-03-24 at 11 35 01 AM](https://user-images.githubusercontent.com/5527455/112250784-fba6e780-8c94-11eb-8040-6ef1b4a91077.png)

**To Reproduce**
1. Go to Story Book 
https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-sidenavigation--customizable-side-navigation-item
2. set collapse to true
![Screen Shot 2021-03-24 at 11 35 46 AM](https://user-images.githubusercontent.com/5527455/112250833-15e0c580-8c95-11eb-97b9-7fa6bbec90ec.png)

The layout messed. Same thing happend in my project.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.12
`@ui5/webcomponents-react` version: 0.14.5

**Comment by Lukas742** [comment]
There is already an open issue in the the ui5-webcomponents repo: https://github.com/SAP/ui5-webcomponents/issues/2986

Closing this one.
