### ISSUE TITLE
StandardListItem: It's not possible to change the icon color

### ISSUE THREAD

**Issue by CristianDDias** [SAP/ui5-webcomponents-react#149]
**Describe the bug**
It's not possible to change the icon color within the `StandardListItem` component. The `StandardListItem` component accepts an `icon` prop, which is of the `string` type, so it's not possible to pass an `Icon` component as prop. The same is true for the `children` prop. Using JavaScript is possible to do this, as you can see in the following [link](https://codesandbox.io/s/silly-leftpad-s7vop), but with TypeScript is possible to do this only if it's used a `@ts-ignore` comment, as you can see in the following [link](https://codesandbox.io/s/react-typescript-tkdcq).

**To Reproduce**
[JavaScript link](https://codesandbox.io/s/silly-leftpad-s7vop).
[TypeScript link](https://codesandbox.io/s/react-typescript-tkdcq).

**Expected behavior**
A way to change the icon color within the `StandardListItem` component.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 76

**Comment by CristianDDias** [comment]
Here is an example of what I need ([codesandbox](https://codesandbox.io/s/react-typescript-f5049)). It works OK, but only if I add the `@ts-ignore`. 

Is it possible to change the `StandardListItemPropTypes` so that the `children` prop can accept a `string` and also a `ReactNode`?

**Comment by MarcusNotheis** [comment]
Released in version `v0.6.0-rc.4`
