### ISSUE TITLE
ActionSheet: Demo error & A11y issue

### ISSUE THREAD

**Issue by sleric1024** [SAP/ui5-webcomponents-react#1514]
**Describe the bug**

1. The action sheet dialog could not be opened.
2. Screen reader behavior are not the same as UI5 ActionSheet. https://sapui5.hana.ondemand.com/#/entity/sap.m.ActionSheet/sample/sap.m.sample.ActionSheet

**Isolated Example**
Demo from https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-actionsheet--default-story

**To Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-actionsheet--default-story
2. Click on ActionSheet button
3. Refresh page and click the button again
5. Screen reader behavior are different from UI5 ActionSheet. 

**Expected behavior**
Dialog could open correctly
Screen reader could have the correct behavior.

**Screenshots**

**1- Error when opening the dialog from** https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-actionsheet--default-story
![image](https://user-images.githubusercontent.com/5724592/115351796-33984080-a1e9-11eb-8969-9f833e463ba7.png)

**2- Expect behavior for screen readers**
![image](https://user-images.githubusercontent.com/5724592/115351933-5b87a400-a1e9-11eb-9ca6-208ac5919b17.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: master
`@ui5/webcomponents-react` version:
Operating System: Mac OS & Windows
Browser: Chrome

**Additional context**
I am from SuccessFactors

**Comment by Lukas742** [comment]
Released in [0.15.4](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.15.4)
