### ISSUE TITLE
ComponentName: FilterBar

### ISSUE THREAD

**Issue by 23mluk** [SAP/ui5-webcomponents-react#1515]
**Describe the bug**
I want use the FilterBar in a DynamicPageHeader. I have set the useToolbar to false. But when I do that, I don't see the button  
"FilterConfiguration" and the "Go" button.
![image](https://user-images.githubusercontent.com/68957230/115437212-335d6c80-a20c-11eb-810d-0b50264ef959.png)

I don't want my toolbar to be expandable because my DynamicPageHeader is it

**Expected behavior**
https://sapui5.hana.ondemand.com/#/entity/sap.ui.comp.filterbar.FilterBar/sample/sap.ui.comp.sample.filterbar.DynamicPageList

![image](https://user-images.githubusercontent.com/68957230/115438446-b4693380-a20d-11eb-962d-856496e7f09f.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.14
`@ui5/webcomponents-react` version: 0.15.3

**Comment by Lukas742** [comment]
Released in version [0.16.0](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.16.0).
