### ISSUE TITLE
ProgressIndicator: the progress bar is not smooth.

### ISSUE THREAD

**Issue by ggfer** [SAP/ui5-webcomponents-react#1534]
**Describe the bug**
The progress bar is not smooth from value x to value y.

**Isolated Example**
*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/goofy-chebyshev-9mrhr?file=/src/App.js).*

**To Reproduce**
1. first set value as 30.
2. progress bar loading is done.
3. then set value as 60.
4. progress bar loading is done once again.

**Expected behavior**
set value as 30, the progress bar from 0 to 30.
then set value as 60, the progress bar from 0 to 60 (it is still started from 0, it turns back to 0, then rise to 60.it is supposed to start from 30, and rise to 60.)

**Addition**
if codesandbox cannot open, please check this code manually.
```
import React, { useState } from "react";
import { FlexBox, Button, ProgressIndicator } from "@ui5/webcomponents-react";

export default function App() {
  const [progressIndicatorVal, setProgressIndicatorVal] = useState(0);

  const runtest = async () => {
    setProgressIndicatorVal(30);
    await sleep(1000);
    setProgressIndicatorVal(60);
    await sleep(1000);
  };

  function sleep(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
  }

  return (
    <FlexBox>
      <Button
        onClick={() => {
          runtest();
        }}
      />
      <ProgressIndicator
        style={{ height: "1rem", width: "25rem" }}
        valueState={"Information"}
        value={progressIndicatorVal}
      />
    </FlexBox>
  );
}

```

**Comment by MarcusNotheis** [comment]
Hey @ggfer,
I forwarded this issue to the UI5 Web Components Team, they'll follow up on this bug. (https://github.com/SAP/ui5-webcomponents/issues/3193)
--> Closing this issue then.
