### ISSUE TITLE
[rl-readme_file-2] README is incomplete. Please check the following sections: Licensing

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents-react#1549]
For details please see our wiki page at https://wiki.wdf.sap.corp/wiki/display/ospodocs/Repository+Linter+Findings#RepositoryLinterFindings-Readme(rl-readme_file-XX)

**Comment by Lukas742** [comment]
Closing this one, because we are using the "reuse" batch, which should be sufficient. -->  <a href="https://api.reuse.software/info/github.com/SAP/ui5-webcomponents-react" target="_blank">
    <img alt="REUSE Status" src="https://api.reuse.software/badge/github.com/SAP/ui5-webcomponents-react"/>
  </a>
  
  If we still need to change or add some information please feel free to re-open.
