### ISSUE TITLE
SideNavigationListItem: Tooltip properties 

### ISSUE THREAD

**Issue by arielazzi** [SAP/ui5-webcomponents-react#155]
**Describe the bug**
As mentioned in issue (#127), the release `0.5.1-rc.16` implemented Side Navigation. The component `SideNavigationListItem` has a property called `tooltip`, but when applied nothing happend.
The interface `SideNavigationListItemProps` extends `CommonProps`, that has `tooltip` property.

Is the `tooltip` implementation for this component planned?

**Expected behavior**
When property `tooltip` is added, in mouse is over the menu item, should appear a tooltip with the string message.

**Comment by MarcusNotheis** [comment]
Released in ’v0.6.0-rc.7’
