### ISSUE TITLE
Analytical Table: Customized Checkbox

### ISSUE THREAD

**Issue by eleminsoda** [SAP/ui5-webcomponents-react#1550]
**Is your feature request related to a problem? Please describe.**
The feature requires the checkbox to disable/disappear for certain rows according to the row item's status. However, the checkbox right row in Analytical table does not support any customization.

**Describe the solution you'd like**
Checkbox in Analytical table can be disabled/disappear for certain rows according to the row item's status.

**Comment by Lukas742** [comment]
Hi @eleminsoda 

We already provide a [plugin hook](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable--plugin-use-row-disable-selection) with which it is possible to mark rows as not selectable and thus deactivate the checkbox. We do not support hiding the checkboxes though. 
If you need this behavior you can create your own plugin hook. You should be able to use the [useRowDisableSelection](https://github.com/SAP/ui5-webcomponents-react/blob/main/packages/main/src/components/AnalyticalTable/pluginHooks/useRowDisableSelection.tsx) plugin hook as a reference. A general guide about plugin hooks can be found [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable--plugin-use-row-disable-selection#how-to-add-your-own-plugin-hooks).

**Comment by Lukas742** [comment]
Closing this issue.

If there are any more questions or something is unclear please feel free to reopen it or create a new one.
