### ISSUE TITLE
AnalyticTable: Clicking on row sub component will auto scroll to top

### ISSUE THREAD

**Issue by JackieWei** [SAP/ui5-webcomponents-react#1575]
**Describe the bug**
Create an analytic table instance and with an extend sub component. Then you click to expand any of the sub component, and click any area of the subcomponent(except input, select...) , for example, blank area, lable, p, any readonly fields, the whole table will auto scroll to top.

**Isolated Example**
*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).*

**To Reproduce**
1. Go to Analytic Table
2. Expand any sub component
3. Click on blank area of sub component
4. See the analytic table will auto go up to first cell.

**Expected behavior**
Remain focus on current item and sub component

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.14 
`@ui5/webcomponents-react` version: 0.15.2
Operating System: Mac OS Big Sur 11.3.1
Browser: Chrome 90.0.4430.93

**Additional context**
Click on sub component will goto this code block, in AnalyticTable.js
const onTableFocus = useCallback(e => {
    const firstCell = e.target.querySelector('div[role="row"]:first-child div[role="cell"]:first-child');

    if (firstCell) {
      firstCell.tabIndex = 0;
      firstCell.focus(); // This is the part of root cause of scroll top
      currentlyFocusedCell.current = firstCell;
    }
  }, [currentlyFocusedCell]);

And for the currentlyFocusedCell, I can only see that use Arrow up, down, right, left can change it.
Looks that no other way can change it.
And also another information is that, onTableFocus is trigger by focus event('focusin', native event type)

**Comment by Lukas742** [comment]
Hi @JackieWei 

Thanks for creating this issue. Please see my comments below.

> **Describe the bug**
> Create an analytic table instance and with an extend sub component. Then you click to expand any of the sub component, and click any area of the subcomponent(except input, select...) , for example, blank area, lable, p, any readonly fields, the whole table will auto scroll to top.
> 
> **Isolated Example**
> *Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).*
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Go to Analytic Table
> 2. Expand any sub component
> 3. Click on blank area of sub component
> 4. See the analytic table will auto go up to first cell.

I was not able to reproduce this behavior. Could you take a look at this [codesandbox example](https://codesandbox.io/s/hopeful-wilson-z5k8u?file=/src/App.js) and tell me if I missed something there?

> Click on sub component will goto this code block, in AnalyticTable.js
> const onTableFocus = useCallback(e => {
>     const firstCell = e.target.querySelector('div[role="row"]:first-child div[role="cell"]:first-child');
> 
>     if (firstCell) {
>       firstCell.tabIndex = 0;
>       firstCell.focus(); // This is the part of root cause of scroll top
>       currentlyFocusedCell.current = firstCell;
>     }
>   }, [currentlyFocusedCell]);

The whole cell navigation seems to be broken, we will look into this and let you know once we found a solution.

> And for the currentlyFocusedCell, I can only see that use Arrow up, down, right, left can change it.
> Looks that no other way can change it.

It's intended, that navigation between cells is only possible with the arrow keys or by clicking on them. (see [UI5 table](https://sapui5.hana.ondemand.com/#/entity/sap.ui.comp.smarttable.SmartTable/sample/sap.ui.comp.sample.smarttable) for reference)

**Comment by JackieWei** [comment]
https://user-images.githubusercontent.com/437693/118426603-167a6300-b6fe-11eb-9a12-9c6d8736160e.mp4

**Comment by JackieWei** [comment]
@Lukas742 Thanks very much for response. And I think I can reproduce the behavior I described in the codesandbox example you provide. Just as the above mp4 screen record showed.
The behavior: 1. I click expand some item's subcomponent, better to choose one in down part 2, click on the sub component, 3. The scroll and screen will auto go to top. And I expect when I click on the subcomponent, it will remain the scroll and visible area as I am doing some review or editing for subcomponent.
![image](https://user-images.githubusercontent.com/437693/118426705-49245b80-b6fe-11eb-9ab8-45424757a247.png)

**Comment by Lukas742** [comment]
Hi @JackieWei 

the fix is now available with [0.16.2](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.16.2)
