### ISSUE TITLE
Missing UI5CustomEvent from interfaces 

### ISSUE THREAD

**Issue by kbachl** [SAP/ui5-webcomponents-react#1576]
Hi,

after upgrading to 0.16.0 typescript support really went onto another level. However, it seems that something is off as the IDE doesnt give any more code completion on e.g.:

![greyed-out-idea](https://user-images.githubusercontent.com/451927/117950332-5cf14b80-b313-11eb-8b37-ed9d8b1f876e.png)

it has the UI5CustomElement behind the event (Intellij IDEA) greyed out, meaning it can pull its declaration from the Input Element, but not the source declaration of the UI5CustomEvent itself; After digging into the index.d.ts of Input element it shows 

` onInput?: (event: Ui5CustomEvent<HTMLInputElement>) => void;`

while its imported that way:

`import { Ui5CustomEvent } from '@ui5/webcomponents-react/interfaces/Ui5CustomEvent';`

However, opening the path it has no UI5CustomEvent file in it, e.g.:

![no-file](https://user-images.githubusercontent.com/451927/117950781-d721d000-b313-11eb-9388-63f87302dcc1.png)

see also https://github.com/SAP/ui5-webcomponents-react/tree/main/packages/main/src/interfaces and there it has a file Ui5CustomEvent.ts

package.json reads as this:
```
....
    "@ui5/webcomponents": "^1.0.0-rc.14",
    "@ui5/webcomponents-fiori": "^1.0.0-rc.14",
    "@ui5/webcomponents-icons": "^1.0.0-rc.14",
    "@ui5/webcomponents-react": "^0.16.0",
    "@ui5/webcomponents-react-base": "^0.16.0",
....
```

So it seems that interface is missing from the npm package

**Comment by kbachl** [comment]
PS: also check the tarball under https://registry.npmjs.org/@ui5/webcomponents-react/-/webcomponents-react-0.16.0.tgz
-> its missing the UI5CustomEvent  interface file in the interfaces directory!

So I suspect an incorrect build of 0.16.0

**Comment by Lukas742** [comment]
Hi @kbachl 

thanks for noticing and investigating. With [0.16.1](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.16.1) all interfaces are now exposed in the npm packages as well.
