### ISSUE TITLE
Keep subcomponent open status after rerender and also the focus item info

### ISSUE THREAD

**Issue by JackieWei** [SAP/ui5-webcomponents-react#1585]
**Is your feature request related to a problem? Please describe.**
When I set data to AnalyticTable and then trigger a rerender, all of my open status of subcomponent will be lost. Which is not user frendly if we are editing or update any content.

**Describe the solution you'd like**
Give a write back property just similar as selection, so that I can re-open all the specified sub components and keep user still have the current focus one in screen viewport.

**Describe alternatives you've considered**

**Additional context**
As I can see, I consider keep subcomponent open status should be easier than focus item as focus may have many other usage. So at least I think user should not need to re-open the subcomponent he/she opened, and it would be better if we can keep user working in same item before re-render.

**Comment by Lukas742** [comment]
Hi @JackieWei 

you can use `autoResetExpanded` of the `reactTableOptions` prop to achieve this. [Here](http://localhost:6006/?path=/docs/data-display-analyticaltable--default-story#how-to-stop-the-table-state-from-automatically-resetting-when-the-data-changes) you can find a more detailed explanation on how to use this.

I also created a [codesandbox example](https://codesandbox.io/s/sharp-chaplygin-x90sy?file=/src/App.js) showing a basic implementation of this behavior.

**Comment by JackieWei** [comment]
@Lukas742 OK, Thanks for help. I will and get back to you later

**Comment by JackieWei** [comment]
@Lukas742 Works fine to me. I will close this.
