### ISSUE TITLE
Add to SideNavigation onItemClick property

### ISSUE THREAD

**Issue by guedes4g** [SAP/ui5-webcomponents-react#161]
**Is your feature request related to a problem? Please describe.**
On the SideNavigation component the callback event triggered by onItemSelect is called only once.

**Describe the solution you'd like**
I would like to be able to handle the the click event on the SideNavigation component more than once, perhaps would be good to add a onItemClick property to handle the click event and keep the onItemSelect as it is.

**Comment by MarcusNotheis** [comment]
hi @guedes4g,

thanks for submitting this issue.
If I understood correctly, you want to have one `onItemClick` event fired per click - so if you would like the same item five times, the handler gets called five times?
Then I would move the current behaviour into an `onSelectionChange` event and update the `onItemClick` event?

**Comment by guedes4g** [comment]
Hi @MarcusNotheis 

Yes that is correct, but the current behavior we have is called `onItemSelect` and belongs to SideNavigation.

All you need to do is implement a new event called `onItemClick` that is triggered every click.

Thanks.

**Comment by MarcusNotheis** [comment]
Fixed and released in `0.6.0-rc.21`
