### ISSUE TITLE
The height in two columns of FormItems in a FormGroup cannot match.

### ISSUE THREAD

**Issue by eleminsoda** [SAP/ui5-webcomponents-react#1613]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when there are two columns of FormItems in a FormGroup, the height of the FormItem in these columns cannot match when the content is different, and the developer cannot adjust its style as the FormItems and FormGroup both do not accept style of class attribute.
![image](https://user-images.githubusercontent.com/27283476/119313168-d25f0380-bca5-11eb-91e1-53103c1e329a.png)

**Describe the solution you'd like**
An attribute in the layout to set the FormItem height that can match with FormItem in other columns.

**Describe alternatives you've considered**
The developers are allowed to set the styles by themselves.

**Additional context**

**Comment by Lukas742** [comment]
Hi @eleminsoda 

I see that in your screenshot the labels are misaligned. I tried to reproduce this behavior but was not able to. Could you share your Form component in a reproducible example? You can use this [codeSandbox](https://codesandbox.io/s/funny-moore-z2izo?file=/src/App.js) as template.
