### ISSUE TITLE
Analytical Table: Pop-In (SuccessFactors)

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents-react#1614]
**Is your feature request related to a problem? Please describe.**
If you have an Analytical Table with many columns, it does become cumbersome to scroll through columns with the table's horizontal scrollbar.

**Describe the solution you'd like**
It would be great if the Pop-In feature from Table could be implemented for Analytical Table.

**Describe alternatives you've considered**
Only real alternative here is the horizontal scrollbar.

**Additional context**
![image](https://user-images.githubusercontent.com/8508119/119383544-4e425700-bc78-11eb-80c3-524ebecf2bc9.png)

**Comment by Lukas742** [comment]
Hi @agauyeung 

this behavior is already available (see [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable--responsive-columns))

**Comment by agauyeung** [comment]
Thanks! Trying this out

**Comment by MarcusNotheis** [comment]
Hey @agauyeung,

are there any open action items on our side or can we close this issue?

**Comment by agauyeung** [comment]
Hi, I am running into an issue locally while using this feature locally but I'm unable to pinpoint it. I will open a new issue if I can track it down.
