### ISSUE TITLE
[Grid] [SF] Grid Column Should Support 16 Column

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents-react#1615]
**Dear colleagues,**
I am from SuccessFactors Web Experience Shanghai team.

**Grid Column Should Support 16 Column**

You can see this link: [https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2038570628](https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2038570628)

![Screen Shot 2021-05-25 at 10 25 20 AM](https://user-images.githubusercontent.com/78520316/119430539-8e224080-bd43-11eb-98b6-10caab27b5ab.png)

**Comment by MarcusNotheis** [comment]
Action Item: Create new component `ResponsiveGrid`

**Comment by MarcusNotheis** [comment]
Released in `@ui5/webcomponents-react@0.131.7`
