### ISSUE TITLE
AnalyticalTable : Keyboard navigations not working

### ISSUE THREAD

**Issue by SriramParamasivam** [SAP/ui5-webcomponents-react#1625]
**Describe the bug**
Keyboard navigations not working properly.

**Isolated Example**
https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable--with-navigation-indicator

**To Reproduce**
Following keyboard navigations not working.

TAB into the table.
Focus will be placed on the checkbox of the header.
Use the arrow keys to attempt to navigate to another cell.
**Issue 1:**
Expected behavior: Focus should change to the direction of the arrow key that was pressed.
Actual behavior: Focus does not change.
Press TAB again:
**Issue 2:**
Expected Behavior: Focus should be placed on the table header that is sortable.
Actual behavior: Focus will be placed on the first cell of the first row of data.
Press SHIFT+TAB
**Issue 3:**
Expected Behavior: Focus should go back to the previous actionable element.
Actual Behavior: Focus does not change.
Use the arrow keys to navigate to the column header that is sortable. (i.e. Average Rating)
Press ENTER or SPACE to open the sorting menu
**Issue 4:**
Expected Behavior: The sorting menu opens.
Actual Behavior: The sorting menu does not open.
**Issue 5:**
Home Key and End Key not working properly. It should navigate to the first cell when pressing on Home and it should go to the last cell when we press end key.

**Reference:** https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Grid_Role 

**Expected behavior**
above mentioned keyboard navigations should work as per standards.

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 0.29.7
`@ui5/webcomponents-react` version: 0.129.7
Operating System: Windows
Browser: Chrome, Firefox, Edge

**Additional context**

**Comment by Lukas742** [comment]
Hi @SriramParamasivam 

I've linked a PR that should solve most of the issues you mentioned here. Unfortunately we identified two more issues coming from our UI5 Web Components colleagues which will leave us with a bit of a shortcoming for this fix:

1. It is currently not possible to open the header modal with the SPACE key, only the ENTER key is supported.  https://github.com/SAP/ui5-webcomponents/issues/3601
2. It is currently not possible to select the Input field inside the filter modal with keyboard navigation. https://github.com/SAP/ui5-webcomponents/issues/3603

Once these issues are resolved we will fix them in the `AnalyticalTable` ASAP.

**Comment by Lukas742** [comment]
The fix for this issue has been downported to [v0.17.4](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.17.4).

**Comment by Lukas742** [comment]
Hi @SriramParamasivam 

do you need these changes in `0.129.x` as well?

**Comment by Lukas742** [comment]
The fix has been downported to [v0.131.16](https://github.com/SAP/ui5-webcomponents-react/blob/rel/0.131/CHANGELOG.md#013116-2021-08-12) as well.
