### ISSUE TITLE
FilterBar: Differences to Fiori Elements

### ISSUE THREAD

**Issue by texttechne** [SAP/ui5-webcomponents-react#1627]
**Describe the bug**
In Fiori Elements the FilterBar is displayed differently:
* There's no border and padding around the filter elements
* The size of the input fields is adjusted dynamically so that the whole width is filled up by multiple input fields
  * => we shouldn't have to use prop `filterContainerWidth`, which doesn't fulfill this functionality anyways
* when `useToolbar = false` then there's spacing missing between buttons
* wording: in Elements it's called "Adapt Filters(1)" not "Filters" 

**Expected behavior**
Same look & behaviour as Fiori Elements

**Screenshots**
Example of FilterBar in Fiori Elements app:
![grafik](https://user-images.githubusercontent.com/1963160/119707061-03346980-be5b-11eb-9084-36a55e05526b.png)

Example of FilterBar in React Webcomponents:
![grafik](https://user-images.githubusercontent.com/1963160/119708051-27447a80-be5c-11eb-8b5a-11054f4d0f0d.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.14
`@ui5/webcomponents-react` version: 16.0.1
Operating System: Windows / Linux
Browser: Chrome / FF

**Comment by Lukas742** [comment]
Hi @texttechne 

this was released in [0.16.2](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.16.2)

Please be aware that for some components like `DateRangePicker` you have to set the `minWidth` to `auto` or to the corresponding `filterContainerWidth` when using with smaller `min-width` than internally defined. Also there are known issues setting the `min-width` for the `DatePicker` and `StepInput` you can track this [here](https://github.com/SAP/ui5-webcomponents/issues/3377). As a workaround you can change the min-width by using `addCustomCSS`.

**Comment by texttechne** [comment]
Hi @Lukas742 

looks fine!

I see one issue left, however: No spacing between buttons, when `useToolbar={false}`


Thank you very much so far, for the nice work!!!

**Comment by Lukas742** [comment]
That's what you get for changing the styles in the last minute... Sorry for that.

I created another [PR](https://github.com/SAP/ui5-webcomponents-react/pull/1668) that will add the spacing.

Are you blocked by that?

**Comment by texttechne** [comment]
Never happened to me before 😉 

Nope, I'm not blocked. And FWIW I also need the [Footer in the Dynamic Page](#1626).

Again, thanks for your efforts!

**Comment by MarcusNotheis** [comment]
the button spacing fix is now also released: `@ui5/webcomponents-react@0.16.3`.
