### ISSUE TITLE
[Input] How change Width (< 210px is possible?)

### ISSUE THREAD

**Issue by sajermann** [SAP/ui5-webcomponents-react#1628]
Hi,

How to set width "INPUT" less than 210px ?
How to set width "DatePicker" less than 201px?

I need small inputs, but I can't decrease less than those values

https://codesandbox.io/s/new-template-webcomponent-react-icj8c?file=/src/App.js

Thanks :)

**Comment by texttechne** [comment]
You have to override the `minWidth` style prop first, before `width` takes effect.

**Comment by sajermann** [comment]
> You have to override the `minWidth` style prop first, before `width` takes effect.

Thanks very much my friend, it's work 👍 

`style={{ minWidth: "30px", maxWidth: "45px" }}`

**Comment by texttechne** [comment]
Actually this would be a clean solution for the inputs in your given example: `style={{ minWidth: "100%", width: "100%" }}`

However, styling the `DatePicker` won't work.

**Comment by mj-wow** [comment]
@texttechne any global kinda ovverride possible ? with a custom class ?

**Comment by Lukas742** [comment]
Hi @mj-wow 

sure, why wouldn't it?
https://codesandbox.io/p/sandbox/sleepy-chaum-ljwrjr?file=%2Fsrc%2Findex.css%3A9%2C2
