### ISSUE TITLE
CustomListItem: Not able to vertical-align CustomListItem's children

### ISSUE THREAD

**Issue by mdasari84** [SAP/ui5-webcomponents-react#1633]
**Describe the bug**
Not able to vertical-align CustomListItem's children

**Isolated Example**
Here is the code sandbox - https://codesandbox.io/s/youthful-moon-rs40s?file=/src/App.js

**To Reproduce**
Please check the code sandbox example

**Expected behavior**
Should be able to vertical-align CustomListItem's children

**Screenshots**
I am trying to achieve below mockup

![image](https://user-images.githubusercontent.com/84945056/119914226-9a112c80-bf14-11eb-829f-ab1c372ada70.png)

but ended up with below with CustomListItem

![image](https://user-images.githubusercontent.com/84945056/119914273-a9907580-bf14-11eb-9dea-79f77decfc3e.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:
`@ui5/webcomponents-react` version:
Operating System: I have tried Windows.
Browser: I have tried in Chrome browser.

**Additional context**

**Comment by Lukas742** [comment]
Hello @mdasari84

first of all you forgot to wrap your component inside `ThemeProvider`, apart from that you can use standard CSS, or for example use our `FlexBox` to achieve this behavior. A `CustomListItem` is, as the name suggests, completely controllable by the developer, so we don't provide format props for the content.

Also, I don't think you need a `CustomListItem` for your case. A `StandardListItem` should be sufficient here.

See [this](https://codesandbox.io/s/quirky-voice-b9kc8?file=/src/App.js) codeSandbox for reference.

**Comment by mdasari84** [comment]
@Lukas742 Thanks for the quick response and codeSandbox reference!
It works for my case.
