### ISSUE TITLE
MessageBox: Accessibility issue where it doesn't select first focusable element on load

### ISSUE THREAD

**Issue by Brahmansh** [SAP/ui5-webcomponents-react#1639]
**Describe the bug**
MessageBox: Accessibility issue where it doesn't select first focusable element on load. And onclick of tab button focus directly goes to cancel button.
Also In the description of applyFocus() method it says - "Focuses the element denoted by 'initialFocus', if provided, or the first focusable element otherwise."
But it's not clear how to set 'initialFocus' for buttons e.g. 'OK' button of the dialog.

**Isolated Example**
https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-messagebox--default-story

**To Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-messagebox--default-story
2. Click or press enter/spacebar on 'Open Messagebox' button
3. When Messagebox opens, there is no focus on any of the focusable element.
4. And then onclick of 'TAB' key, focus goes to cancel button.

**Expected behavior**
In this case expected behavior is to have 'OK' button focused once dialog renders. 

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 
`@ui5/webcomponents-react` version: v0.16.1

**Comment by Lukas742** [comment]
Hi @Brahmansh 

the fix is released in [0.16.2](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.16.2)
