### ISSUE TITLE
SideNavigation: Zero being rendered with the component

### ISSUE THREAD

**Issue by guedes4g** [SAP/ui5-webcomponents-react#164]
**Describe the bug**
A Zero __0__ is being rendered with the component

**To Reproduce**
1. render a SideNavigation

**Screenshots**
![image](https://user-images.githubusercontent.com/29311988/65908899-c1a99d80-e39d-11e9-8f43-918896082119.png)

**Desktop (please complete the following information):**
 - Windows
 - chrome 
 - Version 77.0.3865.90

**Comment by MarcusNotheis** [comment]
Fix released in `v0.6.0-rc.9`
