### ISSUE TITLE
AnalyticTable - SubComponent - should be able to click anywhere on the row to expand it, not just on the arrow

### ISSUE THREAD

**Issue by JackieWei** [SAP/ui5-webcomponents-react#1654]
**Is your feature request related to a problem? Please describe.**
We have a feature request from UX, as described "Also the user should be able to click anywhere on the row to expand it, not just on the arrow. I don't see these features in the dev environment. ". And we didn't find any way to do it. So we consider this is something not implemented. So we create this FR.

**Describe the solution you'd like**
Have ability to trigger the expand/collapse the sub component of a row by code, via properties or any other customize functions.

**Describe alternatives you've considered**
If this is FR is not a standard Fiori guideline, or it's againest any rule of fiori, pelase give the link of description.

**Additional context**
Currently we can control the check status(selection) by properties, but didn't have way to control expanding/collapsing the sub components. From user experenice perspactive. it will be better to have way to control it by code.

**Comment by Lukas742** [comment]
Hi @JackieWei 

you can use the `onRowClick` callback and toggle the row there. `e.detail.row.toggleRowExpanded();`

If you need custom styling for the rows you can either do it in each cell by using the `Cell` property or by hooking into the `getRowProps` hook with a custom hook.

[Here](https://codesandbox.io/s/snowy-microservice-tyk8k?file=/src/App.js) you can find a codeSandbox that implements this behavior.

Please note that passing style to the `getRowProps` hook has currently no effect, but I already created a [PR](https://github.com/SAP/ui5-webcomponents-react/pull/1664) that enables this as well.

**Comment by JackieWei** [comment]
Works for me. Thanks very much @Lukas742
