### ISSUE TITLE
[SF][Grouping List] support list grouping function

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents-react#1656]
Dear colleagues,
I am from SuccessFactors Web Experience Shanghai team.

Support grouping function in list

![Screen Shot 2021-06-02 at 10 04 12 AM](https://user-images.githubusercontent.com/78520316/120413266-88071200-c38a-11eb-86e8-76cc0d5cf304.png)

We can refer to this page: https://sapui5.hana.ondemand.com/#/entity/sap.m.List/sample/sap.m.sample.ListGrouping

**Comment by MarcusNotheis** [comment]
Hey colleagues,

We already support using Group Headers in Lists by using our `GroupHeaderListItem`, please see this codesandbox: https://codesandbox.io/s/still-cloud-00pu1?file=/src/App.js

Docs: https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-list--default-story#groupheaderlistitem

Or am I missing something?
