### ISSUE TITLE
[SF][ObjectPage][Urgent - Within 2 weeks] ObjectPage Component should obey the content container paddings (Fiori 3) rule

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents-react#1676]
**Dear colleagues,**
I am from SuccessFactors Web Experience Shanghai team.

ObjectPage Component should obey the content container paddings (Fiori 3) rule

![image](https://user-images.githubusercontent.com/78520316/120732612-34c2ca00-c518-11eb-93fc-cbd688a58f82.png)

You can see this link: https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2038567803
**Content Containers Section**

**Comment by sfsf-xweb-sh** [comment]
Hi @MarcusNotheis 
Is there a timeline for this component ?
This component is very urgent for us, can this component be finished in 2 weeks ?

**Comment by MarcusNotheis** [comment]
Released in `@ui5/webcomponents-react@0.131.7`
