### ISSUE TITLE
MessageBox: Single-button action for Error messages should use ButtonDesign.Transparent

### ISSUE THREAD

**Issue by goodefroi** [SAP/ui5-webcomponents-react#1687]
**Describe the bug**
`Error` message boxes with a single action button use emphasized instead of transparent button design.

**To Reproduce**
Configure the [MessageBox playground sample ](https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-messagebox--default-story) to use `type`: `Error` and add a single action.

**Expected behavior**
`Error` message box uses `ButtonDesign.Transparent` for single actions, as shown on the corresponding page of the [Fiori design guidelines](https://experience.sap.com/fiori-design-web/message-box/).

I'm neither a designer nor an Fiori expert but there might be cases where a single action needs to be emphasized so maybe consider making this configurable (or just check with the design team).

**Screenshots**
Example from playground page: 
![image](https://user-images.githubusercontent.com/27777253/120984608-1dcfe200-c77b-11eb-974f-da1ca23e2f56.png)

Example from design guidelines:
![image](https://user-images.githubusercontent.com/27777253/120984687-2de7c180-c77b-11eb-9f1d-56a3951b9d16.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.14
`@ui5/webcomponents-react` version:  0.16.2

**Comment by MarcusNotheis** [comment]
Hey @goodefroi,

thanks for bringing this up! 
Actually, there are some specs with an emphasised close button, so I'll double check with our designers and will come back to you.
![image](https://user-images.githubusercontent.com/8775211/120992604-0e549700-c783-11eb-8af4-01d54671ee70.png)

**Comment by MarcusNotheis** [comment]
Update from our designers:
Positive actions should be displayed as emphasized button, negative (like Cancel or Close) should be displayed as transparent button. Going forward we will add a new prop `emphasizedAction` and adapt our defaults to match the target design.

**Comment by goodefroi** [comment]
> Update from our designers:
> Positive actions should be displayed as emphasized button, negative (like Cancel or Close) should be displayed as transparent button. Going forward we will add a new prop `emphasizedAction` and adapt our defaults to match the target design.

Wonderful, thank you for the quick update!

**Comment by MarcusNotheis** [comment]
Released in `@ui5/webcomponents-react@0.16.3`

**Comment by MarcusNotheis** [comment]
@2bno1 the feature has been downported to 0.131.17
