### ISSUE TITLE
[SF] Support radiobutton group

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents-react#1688]
Is your feature request related to a problem? Please describe.
Now, the library provides a RadioButton component which is useful for the scenario that user can select/unselect the option.
However, many of the scenarios are that users have multiple options for a specified input and he can select one option among them. RadioButton does not provide a convenient way supporting such scenarios.

Describe the solution you'd like
I'd like to have a component (like named RadioButtonGroup) out-of-box supporting:

multiple options for user to select.
initial value indicates which option are selected by default
onChange callback passes selected value in argument
Describe alternatives you've considered
Write a wrapper component which composes of multiple RadioButton instances.
<img width="236" alt="WeChat2898bc487398ce494fde4f146c12081f" src="https://user-images.githubusercontent.com/1751846/120986778-8769e380-c7af-11eb-9898-aab2ba1e3ec2.png">

**Comment by 2bno1** [comment]
Here's a sample of radio group provided by ant-design:
https://ant.design/components/radio/#RadioGroup

**Comment by Lukas742** [comment]
Hi @2bno1 

this is already available. See [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-radiobutton--radio-button-groups).
