### ISSUE TITLE
How can I stylize my components using the UI5 Web Components CSS Variables?

### ISSUE THREAD

**Issue by CristianDDias** [SAP/ui5-webcomponents-react#170]
**Describe the documentation issue**
- [x] Documentation is unclear
- [ ] Documentation is incorrect
- [x] Documentation is missing
- [ ] Other

**Description of the issue**
I haven't found in the documentation a way to use the CSS variables to stylize my React components. I've seen something related to styles in this [file](https://github.com/SAP/ui5-webcomponents-react/blob/master/packages/base/src/styling/sap_fiori_3.ts), but it's not clear how to use it. Besides that, would you recommend using JSS or CSS to stylize the React components? I've been thinking about using the [SAP Fundamentals](https://sap.github.io/fundamental/resources/how-to-use-scss.html) SCSS to stylize my React components.

**Comment by MarcusNotheis** [comment]
Hi @CristianDDias,

I would recommend using [react-jss](https://cssinjs.org/react-jss/?v=v10.0.0) for styling your components.
The file you mentioned will be provided as theme parameter to the styling function.
The `theme` parameter is an object with 3 keys:
1. `theme`: the current theme as string
2. `parameters`: an object with all styling parameters, derived from [this file](https://github.com/SAP/ui5-webcomponents-react/blob/master/packages/base/src/styling/sap_fiori_3.ts).
3. `contentDensity`: Current Content Density mode, either `Compact` or `Cozy`.
Example:
```js
const myStyles = ({theme, parameters, contentDensity}) => ({
myClassName: {
   backgroundColor: parameters. sapBackgroundColor
}
});
```

**Comment by MarcusNotheis** [comment]
You can use the fundamental styles as well, but please be aware that these two "styling libraries" are not connected to each other, meaning if you change a theming parameter (e.g. the Button Background Color), this will have no effect to the fundamental styles

**Comment by MarcusNotheis** [comment]
I'll add a documentation page for that as well.

**Comment by CristianDDias** [comment]
Thank you @MarcusNotheis! 

I will try to use React-JSS, I've been reading about it and I think it's great.

**Comment by MarcusNotheis** [comment]
Documentation is now available here: https://sap.github.io/ui5-webcomponents-react/?path=/docs/welcome-style-web-components--page
