### ISSUE TITLE
FilterBar (0.16.3): spread filters to available width causes infinite readjusting

### ISSUE THREAD

**Issue by texttechne** [SAP/ui5-webcomponents-react#1707]
**Describe the bug**
Spreading the width of the filters to available width works most of the times. However, I get infinite readjusting when using the FilterBar inside of the `DynamicPage`.

Here's a [minimal example](https://codesandbox.io/s/filterbar-jump-around-v6v9p)

**UI5 Web Components for React Information**
`@ui5/webcomponents-react` version: 0.16.3

**Comment by Lukas742** [comment]
Hi @texttechne 

thanks for reporting this issue.
I created a [PR](https://github.com/SAP/ui5-webcomponents-react/pull/1719) that will fix this issue, but as we are currently working on refactoring the `ObjectPage` which is also affecting the `DynamicPage` we can only merge the fix when we are finished with the refactoring.

This [codeSandbox](https://codesandbox.io/s/filterbar-jump-around-forked-s9nrx?file=/src/App.tsx) shows a small workaround that you can use in the meantime.

**Comment by texttechne** [comment]
👍 and thanks for the workaround!
It was driving me a little bit crazy, since it happened with my standard resolution...
