### ISSUE TITLE
DonutChart: Labels of items with small values overlap with each other

### ISSUE THREAD

**Issue by todormikov** [SAP/ui5-webcomponents-react#1718]
**Describe the bug**
When using the DonutChart component, it is possible for the labels of the different items to overlap if their values are small when compared to the total values of all items. This makes the labels unreadable.

**Isolated Example**
 [codesandbox example](https://codesandbox.io/s/amazing-architecture-m53wx?file=/src/App.js).

**To Reproduce**
1. Go to [codesandbox example](https://codesandbox.io/s/amazing-architecture-m53wx?file=/src/App.js)
2. Create two entries in the dataset that have a small value (less than 1% of all values combined)
3. See the overlapping of these entries' labels

**Expected behavior**
It is expected that the overlapping is prevented in some way, possibly by hiding the labels of small items in the chart or by modifying the positioning of overlapping labels.

**Screenshots**
![image](https://user-images.githubusercontent.com/79699783/121516998-888d5180-c9f7-11eb-8c5d-7aeec2af932c.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.14
`@ui5/webcomponents-react` version: 0.15.4
`@ui5/webcomponents-react-charts` version: 0.15.4
Operating System: Any
Browser: Any

**Additional context**
A workaround for this problem would also be very helpful.

**Comment by MarcusNotheis** [comment]
This issue has been fixed in `v0.16.4`.
