### ISSUE TITLE
ShellBar: Side Navigation Menu Icon

### ISSUE THREAD

**Issue by arielazzi** [SAP/ui5-webcomponents-react#172]
**Is your feature request related to a problem? Please describe.**
When `ShellBar` is implemented there is no option to add a side navigation menu icon as described in the Fiori Guideline. There is only the option to add `Icon` property, but the icon is not aligned correctly. 

**Describe the solution you'd like**
`ShellBar` would have a React component property `SideNavigationMenuIcon` that activates the menu icon. 

**Additional context**
Fiori Guidelines references: 

- [Tool Header](https://experience.sap.com/fiori-design-web/tool-header/#side-navigation-menu-icon)
- [Side Navigation](https://experience.sap.com/fiori-design-web/side-navigation/)

**Comment by MarcusNotheis** [comment]
Hi @arielazzi  - sorry for the late response.
As the ShellBar is not a component that is built by us I have opened an issue for the Web Components to see if they have any idea.

I found some specs regarding the side navigation, but a "Menu-Button" is not mentioned there for Fiori 3:
![image](https://user-images.githubusercontent.com/8775211/72100160-6aaf4f00-3322-11ea-8205-5469e4a388a4.png)

**Comment by MapTo0** [comment]
I think that Tool Header and Side Navigation were part of the Fiori 2 (Tools harmonisation concept). The Fiori 3 Shellbar is not the Tool Header, it is similar but it has different UX design and requirements. I quickly checked the UX and visual spec for the Shellbar and it does not contain a "place" for the hamburger icon. All you can define is a button in the start (which should be used for a home icon or back icon).

Example: https://codesandbox.io/s/optimistic-brook-rbuoe

I will sync with some UX and get back.

**Comment by arielazzi** [comment]
Hi @MapTo0, Thank you for your explanation.

**Comment by m1trix** [comment]
Hello @MarcusNotheis 
Could you please post a link to the web components issue that you've created?

**Comment by MarcusNotheis** [comment]
Hi @m1trix, here is the link to the issue I've created: https://github.com/SAP/ui5-webcomponents/issues/1127.
