### ISSUE TITLE
SideNavigation: Overlay menu items 

### ISSUE THREAD

**Issue by arielazzi** [SAP/ui5-webcomponents-react#173]
**Description**
We have a use case that needs a menu with an overlay. (Please, follow references)

But we also need to keep the behavior `Condensed` of `openState`.

**References:**
[atlaskit](https://atlaskit.atlassian.com/)
[Youtube displaying video](https://www.youtube.com/watch?v=rdGW6rhkx-o)
[Material UI](https://material-ui.com/)

**Comment by MarcusNotheis** [comment]
Hi @arielazzi,

as far as I understood your request, you can quite easily achieve the desired behaviour by adding an element style `zIndex: 1` to the SideNavigation and apply a `position: absolute` to the element next to the sidebar.
I can send you a code snippet in one of our internal repos if you are interested.

Best regards,
Marcus

**Comment by MarcusNotheis** [comment]
Did the proposed solution work for you @arielazzi and can we close this issue?

**Comment by arielazzi** [comment]
Hi @MarcusNotheis,

I'm sorry for the late response. 

In our opinion, it should be implemented natively in the component because if there is any component size update or style update, it will probably break our application.

**Comment by MarcusNotheis** [comment]
Hi @arielazzi, you are right, I see your point. Is this something you want to try and open a pull request for or should we take care of that?

Best regards,
Marcus

**Comment by MarcusNotheis** [comment]
Hi @arielazzi, I'm just about to implement this feature. Do you see this as an additional prop on the `SideNavigation` component (like `expandedOverlay: boolean`)? Or would you rather see this as a new component like `SideNavigationContainer` which takes the `SideNavigation` as a prop and arbitrary children?

**Comment by arielazzi** [comment]
Hi @MarcusNotheis, in my opinion, a new boolean prop seems to be an awesome idea! 

Thank you, 
Ariel Azzi

**Comment by MarcusNotheis** [comment]
Hey @arielazzi,
sorry that this took so long. Many things changed in the meantime and now the component is developed by the UI5 Web Components, so we will remove ours and be a proxy for the new SideNavigation component instead.
Maybe we can build something like a Split-App or something in future.

--> Closing this issue for now. If you feel that there is still the need for such a feature or new component please reopen this issue or create a new one.

Best regards,
Marcus
