### ISSUE TITLE
FlexibleColumnLayout: Rendering issue on safari

### ISSUE THREAD

**Issue by gurkirpalgill** [SAP/ui5-webcomponents-react#1739]
**Describe the bug**
Flexible column layout does not render correctly in safari. screen fluctuates as you can see in the attached recording.
(recording is very short to keep the file size within upload limit < 10mb)
**Screenshots**
https://user-images.githubusercontent.com/65705637/122178898-dcef6180-ce3b-11eb-8b0a-0974347d3187.mov

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:~0.31.9
`@ui5/webcomponents-react` version: ~0.131.7
Operating System:Mac OS
Browser:Safari

**Additional context**

**Comment by Lukas742** [comment]
Hi @gurkirpalgill 

I tested the `FlexibleColumnsLayout` with Safari, Chrome and Firefox and couldn't notice any differences in one of the browsers.  I'm also not quite sure what the issue here is. Could you elaborate on this a bit more?

**Comment by gurkirpalgill** [comment]
@Lukas742 when you play the video, notice the title "Clywd Gimeo" and **delete** icon in the third column, they shake. this happens only in safari.
I had to keep the video very short otherwise it won't upload. To observe it clearly, try the same action here:
https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-flexiblecolumnlayout--with-different-columns

**Comment by Lukas742** [comment]
This seems to be a storybook specific problem and is also occurring in Chrome, it probably has something to do with storybook rendering the different stories (examples) in an iframe. For me it's working when used in [fullscreen mode](https://sap.github.io/ui5-webcomponents-react/iframe.html?id=layouts-floorplans-flexiblecolumnlayout--with-different-columns&viewMode=story).
