### ISSUE TITLE
ActionSheet: Unexpected margin exist on mobile device when there is only one primary action button

### ISSUE THREAD

**Issue by sleric1024** [SAP/ui5-webcomponents-react#1748]
**Describe the bug**

1. On mobile device mode, when open the ActionSheet dialog, the popover dialog should rendered and displayed with no margin to bottom on device screen. While when there is only one primary action button, the unexpected margin exists.

2.  According to Fiori guide line. The padding of each button on smartphone may need to keep consist.
https://ux.wdf.sap.corp/fiori-design-web/action-sheet/#responsiveness

![image](https://user-images.githubusercontent.com/5724592/122752546-ae520a80-d2c3-11eb-825c-be09de0e4115.png)

**Isolated Example**
https://codesandbox.io/s/angry-sutherland-30q83?file=/src/App.js:353-370

 https://30q83.csb.app/

**To Reproduce**
1. Go to https://30q83.csb.app/
2. Open chrome devTool
3. Change device type to iPhoneX
4. Click the Button  `Open ActionSheet`

**Expected behavior**

- The popover should display with no margin from bottom.
- The padding of each button on smartphone may need to keep consist.

**Screenshots**
![image](https://user-images.githubusercontent.com/5724592/122751009-cfb1f700-d2c1-11eb-86e8-52c082752e50.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.14
`@ui5/webcomponents-react` version: 0.16.4
Operating System: MacOS
Browser: Chome

**Additional context**
I am from SuccessFactors. We are using ActionSheet to deliver the new features. And currently in the project, we are using 
```json
"@ui5/webcomponents": "~0.31.9",
"@ui5/webcomponents-base": "~0.31.9",
"@ui5/webcomponents-fiori": "~0.31.9",
"@ui5/webcomponents-icons": "~0.31.9",
"@ui5/webcomponents-react": "~0.131.8",
```

**Comment by MarcusNotheis** [comment]
Fix has been downported to the 0.131.x branch and is released with version `0.131.11`
