### ISSUE TITLE
DynamicPage: Responsive paddings

### ISSUE THREAD

**Issue by AndrianStoikov** [SAP/ui5-webcomponents-react#1815]
**Describe the bug**
DynamicPage does not take in consideration the actual width of the component but the overall screen width.

**Isolated Example**
[Sandbox](https://codesandbox.io/s/weathered-forest-fmxup?file=/src/App.js)

**To Reproduce**
1. Open the sandbox in desktop mode
2. Click on the arrow to shrink the right part of the FlexibleColumnLayout
3. The paddings of the right DynamicPage are not changed 

**Expected behavior**
When the DynamicPage shrinks it should decrease its paddings.
The expected behaviour can be seen in the [FlexibleColumnLayout samples](https://sapui5.hana.ondemand.com/#/entity/sap.f.FlexibleColumnLayout/sample/sap.f.sample.FlexibleColumnLayoutWithOneColumnStart).

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.14 - latest
`@ui5/webcomponents-react` version: 0.16.6 - latest
Operating System: Windows 10 Version 20H2
Browser: Microsoft Edge: 91.0.864.64 (Official build) (64-bit)

**Additional context**
Looks like DynamicPage does not change its CSS classes when the width changes. 
Also, the DynamicPage and ObjectPage are quite similar so both might have the same issue.

**Comment by AndrianStoikov** [comment]
Hello @Lukas742,

I saw that the issue is closed and checked the next release in StoryBook. In the latest version I am not able to click with my mouse in the header component. Can you check that before releasing a new version?

Browser: Microsoft Edge Version 91.0.864.67

**Comment by Lukas742** [comment]
This is intended, since there is no hover effect the user should also not be able to click the header.
If you still need to click the title section of the header for some other interactions you can add `pointerEvents: 'auto'` to your style-class/inline styles.

 If this is not according to UX guidelines, could you point me to where I can find specs for this behavior?

**Comment by AndrianStoikov** [comment]
Hi,

Maybe I did not explain it correctly. The user should not be able to click that's right, but at the moment I am not able to click even on the buttons in the title and not able to select the text there.

Best regards,
Andy

**Comment by Lukas742** [comment]
Ok, now I got it, thanks for clarifying :) 

You are right of cause, active elements should always be controllable. I've created a PR (#1825) that should fix this.
