### ISSUE TITLE
Support for UI5 Message Manager?

### ISSUE THREAD

**Issue by d-schroeder** [SAP/ui5-webcomponents-react#1816]
In order to provide error messages and warnings to the user I am currently limited to using Message Boxes to temporarily display a message.

To display several errors and other messages at the same time, I'd like to use a Message Manager component as shown [here](https://sapui5.hana.ondemand.com/#/entity/sap.ui.core.message.MessageManager/sample/sap.ui.core.sample.MessageManager.BasicODataMessages). After clicking the "Delete"-Button you can see a couple of sample messages, which can be filtered by message type (error, warning, success, information).

Are there any plans to support this as a react web component?

**Comment by MarcusNotheis** [comment]
Hey @d-schroeder,

thanks for reaching out! 
I would doubt that we'll build an equivalent to the `UI5 Message Manager` (global store for messages, I would rather recommend to use a state management library like redux or recoil).

What I could imagine in the following:
We could build a component like the [MessageView](https://experience.sap.com/fiori-design-web/message-view/), which could then be connected to your own "MessageManager" and rendered in a dialog or other components as needed.

From an API perspective, I could imagine something like:
```tsx
<MessageView>
  <Message type="Error" titleText="My Error Message" subtitleText="A Description for the error" additionalInfo="3">
    The content of the "details" view goes here and can be any valid react element.
  </Message>
  ...
</MessageView>
```

**Comment by d-schroeder** [comment]
That'd be great! Can you give any estimation on how long the development and release of such a component would take?

**Comment by MarcusNotheis** [comment]
If nothing unexpected comes in between I would say within the next 2 weeks :)
