### ISSUE TITLE
Major problems in version 0.17.0

### ISSUE THREAD

**Issue by AndrianStoikov** [SAP/ui5-webcomponents-react#1835]
**Describe the bug**
After upgrading to version 17 we hit multiple issues on different browsers.

1. Memory leak warnings on _Chrome Version 91.0.4472.164_. I managed to debug it down to `DynamicPageTitle`. Once I remove that component from the tree the warning is not shown anymore. Looks like it happens between rerenders.
![image](https://user-images.githubusercontent.com/21200806/125933306-8eb310ec-8813-4566-99b1-92fdaccc5ba6.png)

2. useResponsiveContentPadding crashes the application on _Safari version 14.1.1 (16611.2.7.1.4)_

```
[Error] TypeError: undefined is not an object (evaluating 'n.inlineSize')
(anonymous function) — useResponsiveContentPadding.ts:28
```

```ts
  useEffect(() => {
    const observer = new ResizeObserver(([el]) => {
      // Firefox implements `contentBoxSize` as a single content rect, rather than an array
      const contentBoxSize = Array.isArray(el.contentBoxSize) ? el.contentBoxSize[0] : el.contentBoxSize;
      if (resizeTimeout.current) {
        clearTimeout(resizeTimeout.current);
      }
      resizeTimeout.current = setTimeout(() => {
        setCurrentRange(() => getCurrentRange(contentBoxSize.inlineSize).name); <- Here
      }, 150);
    });
    if (element) {
      observer.observe(element);
    }
    return () => {
      observer.disconnect();
    };
  }, [element]);
```
3.Cannot read property 'name' of null in Form _Chrome Version 91.0.4472.164_

```
index.tsx:141 Uncaught TypeError: Cannot read property 'name' of null
    at ResizeObserver.<anonymous> (index.tsx:141)
```

```ts
  useEffect(() => {
    const observer = new ResizeObserver(([form]) => {
      const newRange = getCurrentRange(form.contentRect.width).name; <- Here
      if (lastRange.current !== newRange) {
        lastRange.current = newRange;
        setCurrentRange(newRange);
      }
    });

    if (formRef.current) {
      observer.observe(formRef.current);
    }

    return () => {
      observer.disconnect();
    };
  }, [formRef, setCurrentRange, lastRange]);
```

**Isolated Example**
The sandbox illustrates some of the issues mentioned above. I was not able to mock the behavior of the form.
[Sandbox](https://codesandbox.io/s/gracious-cartwright-ujkyw?file=/src/Layout.js)

**To Reproduce**
1. Go to the sandbox using Safari. 
2. It will crash

---

1. Open the sandbox with Chrome
2. Check the console
3. Refresh the page
4. You will see a memory leak warning

I was not able to mock the Form bug in sandbox.
In our application it happens sometimes when you click on some item and then close it and vice versa

**Expected behavior**
1. Safari is one of the supported browser so the components should work with it.
2. There shouldn't be memory leaks
3. Observers should properly detect their elements

**Screenshots**

**UI5 Web Components for React Information**
"@ui5/webcomponents": "1.0.0-rc.14",
"@ui5/webcomponents-react": "0.17.0",

**Additional context**
- Once I have a codesandbox illustrating the issue with the form I will submit it. 
- The memory leak warning happens after the loader is hidden and the list of items is passed to the component.

### **Priority**
- [ ] Low
- [ ] Medium
- [ ] High
- [x] Very High

**Comment by MarcusNotheis** [comment]
Hey @AndrianStoikov,
thanks for reporting! I was able to reproduce the memory leaks as well as the responsive padding issues. I couldn't reproduce the Form issue, but I added an additional safeguarding in there in case `getCurrentRange` returns null.
Please let me know in case there are more open issues with our 0.17.1 version.

**Comment by AndrianStoikov** [comment]
Hi @MarcusNotheis,

Thanks for your fast reaction looks like all 3 issues are fixed. I'll let you know if we happen to find something. 

Best regards,
Andy
