### ISSUE TITLE
DynamicPage: actions and navigationActions are not properly positioned on big screens

### ISSUE THREAD

**Issue by AndrianStoikov** [SAP/ui5-webcomponents-react#1841]
**Describe the bug**
Actions and navigationActions are missing their separator and they are not inline when the screen width is more than 1295px. 

**Isolated Example**
[Sandbox](https://codesandbox.io/s/blazing-moon-46500?file=/src/App.js:684-689)

**To Reproduce**
1. Open the sandbox in desktop mode
2. Using the DevTools set the screen width to more than 1295px. 
3. The action will go bellow the navigation button

**Expected behavior**
The actions and navigationActions should be properly positioned even on bigger screens.

**Screenshots**

Expected
![image](https://user-images.githubusercontent.com/21200806/126157891-94d78caa-22ed-4c39-abf1-5920bfb5f7b5.png)

Actual
![image](https://user-images.githubusercontent.com/21200806/126157851-962ce562-39a7-419a-95cb-3fbe00eaec20.png)

**UI5 Web Components for React Information**
"@ui5/webcomponents": "1.0.0-rc.14",
"@ui5/webcomponents-fiori": "1.0.0-rc.14",
"@ui5/webcomponents-react": "0.17.1",
Operating System: Windows 10 Version 20H2
Browser: Microsoft Edge, Version 91.0.864.70 (Official build) (64-bit)

**Additional context**
The bug is also reproducible on Safari version 14.1.1 (16611.2.7.1.4)

**Comment by Lukas742** [comment]
Hi @AndrianStoikov 

this behavior is intended.

> Layout actions: The dynamic page offers a specific area for layout actions, which reacts to the predefined breakpoint of 1280 px:
> 
> Less than 1280 px: Navigation actions are placed in a separate row above the global actions.
> 1280 px or more: Navigation actions are placed to the right of the global actions on the same line.

https://experience.sap.com/fiori-design-web/dynamic-page-layout/#responsiveness

**Comment by AndrianStoikov** [comment]
Hi @Lukas742,

If I understand correctly as per the documentation the global actions and the navigation should be on the same line when it is more than 1280px(`to the right of the global actions on the same line`).

I tested tested it in the [OpenUI5 samples](https://sapui5.hana.ondemand.com/#/entity/sap.f.DynamicPage/sample/sap.f.sample.DynamicPageFreeStyle) and it seems that when it has enough space the actions and the navigation actions are inlined.

**Comment by Lukas742** [comment]
You are right of course, sorry for the confusion. 
We will let you know as soon as this is fixed and released.

**Comment by AndrianStoikov** [comment]
Thanks in advance 😄

**Comment by AndrianStoikov** [comment]
Hi Lukas,

I am sending one more sandbox related to that issue.

**Describe the bug**
The dynamic page hides some of the content on bigger resolutions and there is a weird blank space over the title.

**Isolated example**
[Sandbox](https://codesandbox.io/s/wild-bush-0ehoz?file=/src/App.js)

**Screenshots**
- White space is there but the form title is visible
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/21200806/126162968-5fd083aa-3773-42ab-bcdd-d43784e34555.png)

- Form title is not visible
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/21200806/126162963-ff052132-894a-4924-989c-e89e33ab6752.png)

**UI5 Web Components for React Information**
"@ui5/webcomponents": "1.0.0-rc.14",
"@ui5/webcomponents-fiori": "1.0.0-rc.14",
"@ui5/webcomponents-react": "0.17.1",
Operating System: Windows 10 Version 20H2
Browser: Microsoft Edge, Version 91.0.864.70 (Official build) (64-bit)

**Additional context**
The bug is reproducible in Safari as well

**Comment by AndrianStoikov** [comment]
> Hi Lukas,
> 
> I am sending one more sandbox related to that issue.
> 
> **Describe the bug**
> The dynamic page hides some of the content on bigger resolutions and there is a weird blank space over the title.
> 
> **Isolated example**
> [Sandbox](https://codesandbox.io/s/wild-bush-0ehoz?file=/src/App.js)
> 
> **Screenshots**
> 
> * White space is there but the form title is visible
>   ![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/21200806/126162968-5fd083aa-3773-42ab-bcdd-d43784e34555.png)
> * Form title is not visible
>   ![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/21200806/126162963-ff052132-894a-4924-989c-e89e33ab6752.png)
> 
> **UI5 Web Components for React Information**
> "@ui5/webcomponents": "1.0.0-rc.14",
> "@ui5/webcomponents-fiori": "1.0.0-rc.14",
> "@ui5/webcomponents-react": "0.17.1",
> Operating System: Windows 10 Version 20H2
> Browser: Microsoft Edge, Version 91.0.864.70 (Official build) (64-bit)
> 
> **Additional context**
> The bug is reproducible in Safari as well

I double-checked that. It actually looks like the Form does not render the passed title component. What might be the reason?

**Comment by Lukas742** [comment]
The `Form` only accepts `FormItem` and `FormGroup` as `children`, all other elements can lead to unintended side-effects or even break the component. To set a heading for the whole form you can use the `title` prop of the `Form`. You can also group form items with a dedicated heading for each group by wrapping your `FormItem` inside `FormGroup` components and pass the `title` prop there.

[codeSandbox](https://codesandbox.io/s/sparkling-architecture-f23yd?file=/src/App.js)

**Comment by AndrianStoikov** [comment]
> The `Form` only accepts `FormItem` and `FormGroup` as `children`, all other elements can lead to unintended side-effects or even break the component. To set a heading for the whole form you can use the `title` prop of the `Form`. You can also group form items with a dedicated heading for each group by wrapping your `FormItem` inside `FormGroup` components and pass the `title` prop there.
> 
> [codeSandbox](https://codesandbox.io/s/sparkling-architecture-f23yd?file=/src/App.js)

Thanks for your reply. We will fix the form on our side.
