### ISSUE TITLE
Toolbar: Vertical Alignment

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents-react#1843]
**Describe the bug**
Buttons are not vertically aligned in the Toolbar.

**Isolated Example**
You can see this directly in https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-toolbar--default-story when selecting "Solid" as the `design`.

**To Reproduce**
1. See the example above.

**Expected behavior**
Buttons should also be vertically aligned.

**Screenshots**
![image](https://user-images.githubusercontent.com/8508119/126201977-ee112e75-4b05-429f-b97a-8e3e6cc66bf3.png)

**UI5 Web Components for React Information**
"@ui5/webcomponents": "^0.31.11",
"@ui5/webcomponents-react": "^0.131.9"
Operating System: Windows
Browser: Chrome

**Additional context**
SuccessFactors

**Comment by Lukas742** [comment]
This issue has been resolved in the SF release [0.131.12](https://github.com/SAP/ui5-webcomponents-react/blob/rel/0.131/CHANGELOG.md#013112-2021-07-21).

We will release this with the next patch version of our main branch as well.
