### ISSUE TITLE
ObjectPage[SF]: padding of headeTitle is not suitable

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents-react#1872]
Hi Colleague,

When using ObjectPage, pass DynamicPageTitle to headerTitle, DynamicPageHeader to headerContent, we found that paddingTop and paddingBottom of  headerContent is larger than expected.  
![image](https://user-images.githubusercontent.com/78520316/126921213-b980b218-bb88-4a17-8dc7-9da5b7ec4166.png)

If you need more details, please click following url  : https://codesandbox.io/s/suspicious-cache-6gs71?file=/src/App.js.

**Expected behavior**

![image](https://user-images.githubusercontent.com/78520316/126921274-0ea45f2e-0ff1-4181-93cc-dcf704efe579.png)

Related dependence:
`@ui5/webcomponents-react` version: 0.131.12

**Comment by sfsf-xweb-sh** [comment]
Hi @MarcusNotheis,
Could you set this ticket to high priority and fix it in next release?

**Comment by MarcusNotheis** [comment]
Hey @sfsf-xweb-sh,
I just checked the Fiori 3 Specs and our implementation seems to be correct:
![image](https://user-images.githubusercontent.com/8775211/127172871-1164fc14-a003-44bf-8622-7dc1e2888de9.png)

A: padding: 0.5rem;
B: padding: 1rem;

Where did you get the expected screenshot from?

**Comment by sfsf-xweb-sh** [comment]
Hi @MarcusNotheis 

The screenshot you provide is using ObjectPage? How could "#83755 Regular Fit" to be fixed below "Men's Special Jacket"?

The following screenshot  is our design from UX, I try to use subheading , but subHeading is always display in the right of heading. So I use headerContent to display section "a" in the screenshot.
![image](https://user-images.githubusercontent.com/78520316/127252263-f2498397-5ed4-4099-9aaa-2b81c519afcf.png)

**Comment by Lukas742** [comment]
Hi @sfsf-xweb-sh 

you can display the `subheading` below the `heading` by using `showSubheadingRight={false}`. If this is still not sufficient for you, you will have to adapt the styles yourself by using custom css (e.g. reducing the padding of the `DynamicPageHeader`).

**Comment by sfsf-xweb-sh** [comment]
Hi @Lukas742 
 Thanks for your suggestions.

**Comment by Lukas742** [comment]
Hi @sfsf-xweb-sh 

I'm going to close this issue. If you need further support please feel free to reopen it or create another one.
