### ISSUE TITLE
Need indetermine status for checkbox anx AnalyticTable

### ISSUE THREAD

**Issue by JackieWei** [SAP/ui5-webcomponents-react#1875]
**Is your feature request related to a problem? Please describe.**
In checkbox selection, sometimes we need to show user part of it's content is selected, for example, in tree selection

**Describe the solution you'd like**
Just similar with SAP UI5, provide partiallySelected option
https://sapui5.hana.ondemand.com/#/api/sap.m.CheckBox%23controlProperties 
Or like material design it has indeterminate status
https://material-io.cn/components/checkboxes

And therefor, in analytictable, it should also have indetermine status for selection

**Describe alternatives you've considered**
No
**Additional context**

**Comment by MarcusNotheis** [comment]
Hey @JackieWei,
thanks for reporting! With our next release (https://github.com/SAP/ui5-webcomponents-react/pull/1873), the `CheckBox` will support the `indeterminate` prop. ([Preview](https://sap.github.io/ui5-webcomponents/master/playground/components/CheckBox/)).
As soon as we have merged this PR, we'll enhance the `AnalyticalTable` as well to make use of this new feature.

**Comment by JackieWei** [comment]
@Lukas742  @MarcusNotheis  Hi,  thanks for bring indeterminate status to select-all checkbox, and also checkbox control.
And in this issue, I original mean that can we have a way to control check status of each row
for example, current selectRowIds looks like
{
"0": true,
"0.1": true,
}
but I want that
{
"0.1": "selected",
"0": "indeterminate"
}
This is a just a purpose, anyway, I would like to have ways to control the checkbox status by myself including indeterminate status which I can show to user that part of it's content are selected
