### ISSUE TITLE
[ObjectPage][SF]: HeaderContent is mixed with ObjectPageSection when scrolling down and up

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents-react#1884]
Hi Colleague,

When setting following properties of ObjectPage: 
mode={ObjectPageMode.IconTabBar}
alwaysShowContentHeader={true},
and scrolling screen, HeaderContent section is mixed by ObjectPageSection.
For more detail please see screen recording:

https://user-images.githubusercontent.com/78520316/127079997-5ecf12cc-a54b-4b05-97f7-7dbd6cc4df55.mov

 BTW, this issue may have something in common with https://github.com/SAP/ui5-webcomponents-react/issues/1662

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 0.31.12
`@ui5/webcomponents-react` version:0.131.12

Could you fix it as quickly as possible?

**Comment by MarcusNotheis** [comment]
Hey @sfsf-xweb-sh,
I've cherry-picked the fix for this issue to the SFSF release branch and released it as version `0.131.13`.
