### ISSUE TITLE
Device.getCurrentRange: TypeError: Cannot read property 'name' of null when running tests

### ISSUE THREAD

**Issue by SVendittelli** [SAP/ui5-webcomponents-react#1885]
**Describe the bug**
When running jest snapshot tests using react testing library components that try to render `Form` and `DynamicPage` components error. The in these components the calls to the `getCurrentRange()` function in [Media.ts](packages/base/src/Device/Media.ts) is returning `null`. This does not happen in the browser, only in the tests.

**Isolated Example**
https://codesandbox.io/s/devicegetcurrentrange-typeerror-995m7

**To Reproduce**
1. Create a test that uses `@testing-library/react` to render a `Form` component
2. Run the test
3. See error

**Expected behavior**
The tests to run without an error.

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.14
`@ui5/webcomponents-react` version: 0.17.2
Operating System: macOS Big Sur 11.5
Browser: jest jsdom

**Additional context**
A similar bug was described in issue #1835. The root cause was not identified but the workaround of using the optional chaining operator (`?.`) was added anyway.

**Comment by MarcusNotheis** [comment]
Hey @SVendittelli,

the error is only occurring in tests but in your running application, right? Can you try to add this to your `src/setupTests.js` (in case you are using `create-react-app`)?

```js
import 'intersection-observer';
import ResizeObserver from 'resize-observer-polyfill';

const setupMatchMedia = () => {
  Object.defineProperty(window, 'matchMedia', {
    writable: true,
    value: jest.fn().mockImplementation((query) => {
      const maxWidth = parseInt(/max-width:(?<maxWidth>\d+)px/.exec(query)?.groups?.maxWidth);
      const minWidth = parseInt(/min-width:(?<minWidth>\d+)px/.exec(query)?.groups?.minWidth);

      let matches =
        (minWidth ? minWidth <= window.innerWidth : true) && (maxWidth ? window.innerWidth <= maxWidth : true);

      if (query === '(orientation: landscape)') {
        matches = window.innerWidth > window.innerHeight;
      }

      return {
        matches,
        media: query,
        onchange: null,
        addListener: jest.fn(), // deprecated
        removeListener: jest.fn(), // deprecated
        addEventListener: jest.fn(),
        removeEventListener: jest.fn(),
        dispatchEvent: jest.fn()
      };
    })
  });
};

beforeEach(async () => {
  window.ResizeObserver = ResizeObserver;
  window.scrollTo = jest.fn();
  setupMatchMedia();
});
```

**Comment by SVendittelli** [comment]
Yes, only in the tests. Thank you, that has solved my issue. My tests are now passing.

**Comment by wulinjie122** [comment]
followed your suggestion, still not work.
