### ISSUE TITLE
FilterBar: attached refs to FilterGroupItem children is ignored or recreated

### ISSUE THREAD

**Issue by apoorvsemwal** [SAP/ui5-webcomponents-react#1890]
**Describe the bug**
While trying to use webcomponents-react/FilterBar with react-hook-form [Github](https://github.com/react-hook-form/react-hook-form), we have the following two observations: 

1. When using [Register](https://react-hook-form.com/api/useform/register) from react-hook-form the value entered in Filter Dialog is reflected back properly to the main Input component on the Filter Bar. **However in this case the clear button functionality does not work at all.**

2. When using [Controller](https://react-hook-form.com/api/usecontroller/controller) from react-hook-form (**which as per the documentation is the recommended way for wrapping components that don't expose refs**) the value entered in Filter Dialog is not reflected back to the main Input component on the Filter Bar. **However in this case the clear button functionality works as expected.**
, 

**Isolated Example**
[Codesandbox](https://codesandbox.io/s/react-hook-form-with-ui5-web-components-react-filter-bar-clear-issue-nlhtz?file=/src/UI5FilterBarWithController.js)

**To Reproduce**
**Scenario 1:**
1. Go to [Codesandbox](https://codesandbox.io/s/react-hook-form-with-ui5-web-components-react-filter-bar-clear-issue-nlhtz?file=/src/UI5FilterBarWithController.js)
2. Click on 'Filters' Button in the **first section (With Register)**
3. Enter a text value in the dialog and click on Save
4. Entered value appears back in the Input component on the Filter Bar
5. Click on Clear
6. Value in the Input Component is not cleared

**Expected behavior**
Value in the Input Component should get cleared when clear is pressed.

**Scenario 2:**
1. Go to [Codesandbox](https://codesandbox.io/s/react-hook-form-with-ui5-web-components-react-filter-bar-clear-issue-nlhtz?file=/src/UI5FilterBarWithController.js)
2. Enter a text value directly in the Input component on the Filter Bar
3. Click on Clear
4. Input Value in the Input Component gets cleared
5. Click on 'Filters' Button in the **second section (With Controller)**
6. Enter a text value in the dialog and click on Save
7. Entered value DOES NOT appear back in the Input component on the Filter Bar

**Expected behavior**
Value Entered in the Filter Dialog should appear back in the Input Component.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.14
`@ui5/webcomponents-react` version: 0.16.3
`react-hook-form`: "7.3.0"

Operating System:
Browser: Chrome

**Additional context**

**Comment by majidzadeh** [comment]
Thank you for posting this. 

This is impacting our code and delivery as well. When can we expect to get a response on this?

Regards,
Khalid

**Comment by buddfung** [comment]
It would be very helpful if filterbar supports react-hook-form.

**Comment by MarcusNotheis** [comment]
Hey guys,

after crossing the finish line with our next release I had some time looking into the issue 🙂 

First of all, I would always recommend using Option 1 (register) with Web Components for React because all our components expose a `ref`. Wrapping our components into additional wrappers is introducing unnecessary complexity in my option or (in case of the FilterBar) will even break the component. Having said that, I'm going to focus on the `register` option now:

In general, resetting values using `useForm` works with Inputs in Web Components for React:

```jsx
import React from "react";
import { Button, Input } from "@ui5/webcomponents-react";
import { useForm } from "react-hook-form";
import "@ui5/webcomponents/dist/features/InputElementsFormSupport.js";

export default function StandaloneInput() {
  const methods = useForm();
  const { register, handleSubmit, setValue } = methods;
  const handleSubmission = (data) => console.log(data);
  const handleClear = () => {
    setValue("SearchStandalone", "");
  };

  return (
    <div>
      <Button onClick={handleClear}>Reset Manually</Button>
      <Input name="SearchStandalone" {...register("SearchStandalone")} />
      <Button onClick={handleSubmit(handleSubmission)}>Submit</Button>
    </div>
  );
}

```

When it comes to using the Input (or other components) within the `FilterBar`, it seems like the FilterBar is somehow destroying the attached `ref` and/or overrides it with a new, internal ref. --> We'll look into this issue.

**Comment by apoorvsemwal** [comment]
Thanks a lot, Marcus for taking a look into it. Yes, we would be using the REGISTER way considering the fact that all ui5 components are already exposing refs. Like you mentioned it's something to do with the way Filter Bar is discarding/overriding refs. Let us know in case you need any further inputs on this from our end.
