### ISSUE TITLE
VariantManagement add/delete functionality

### ISSUE THREAD

**Issue by mihirahlawat** [SAP/ui5-webcomponents-react#1898]
Hi, currently we are not having any functionality to manage (or add/delete) the variants in a VariantManagement Component. As per the Fiori guidelines and a standard Fiori app, we need to provide this feature.
1. Kindly let me know if this is already implemented or is something that is in production and might come up in the coming iteration.

2. Also, we are currently using the following dependencies - 
    "@eureka/ui-utils": "~0.2.6-93",
    "@ui5/webcomponents": "1.0.0-rc.12",
    "@ui5/webcomponents-fiori": "1.0.0-rc.12",
    "@ui5/webcomponents-react": "0.15.0",
    Please let me know whether these are the latest versions or are there any newer versions.

**Comment by MarcusNotheis** [comment]
Hey @mihirahlawat,

thanks for reaching out!
The first issue is already known (tracked in #1609), we will most likely tackle it after our next release (approx. in two weeks then).

You can always find our latest releases at our [GitHub Releases Page](https://github.com/SAP/ui5-webcomponents-react/releases) and you can even subscribe to new releases:

<img width="761" alt="Screenshot 2021-07-30 at 13 41 59" src="https://user-images.githubusercontent.com/8775211/127648326-72e827ce-bca8-413e-b4f0-7cc3545de8d7.png">

In the notifications button, click `Custom` and then tick the checkbox for `Releases`.

**Comment by MarcusNotheis** [comment]
As already mentioned, this is tracked in #1609, so I'm closing this issue here 🙂
