### ISSUE TITLE
Hide/Show columns from AnalyticalTable

### ISSUE THREAD

**Issue by Blerina** [SAP/ui5-webcomponents-react#1899]
**Is your feature request related to a problem? Please describe.**
We would like to show or hide columns on demand for an AnalyticalTable component especially when there are many columns it would be nice for the user to be able to select which columns to include in the table.

**Describe the solution you'd like**
Is there a plan to add a dialogue where the user can select which columns to show/hide of the table? Similar to the Filter Bar component where users can select which filters to show/hide.

Thank you!

**Comment by MarcusNotheis** [comment]
Hey @Blerina,

you can use the `useControlledState` feature of react-table to control the hidden columns:

```tsx
function MyComponent() {

const useControlledState = state => {
  return React.useMemo(() => {
     return { ...state, hiddenColumns: myHiddenColumns }
  }, [state, myHiddenColumns]);
}

return <AnalyticalTable reactTableOptions={{ useControlledState }}
}
```
where `myHiddenColumns` is an array of string with the name of the column `accessor` or `id` if present.

Further reading: 
https://react-table.tanstack.com/docs/faq#how-can-i-manually-control-the-table-state

**Comment by MarcusNotheis** [comment]
There is also a more elegant solution provided by react-table, but this one is currently not exposed in UI5 Web Components for React. We'll look into it whether we can expose it in a way that fits the current API of the `AnalyticalTable`

**Comment by Blerina** [comment]
Thank you for the quick reply and guidance @MarcusNotheis! 👍

**Comment by Lukas742** [comment]
Hi @Blerina 

you can now leverage the `tableInstance` prop, to programatically hide columns.

[codeSandbox example](https://codesandbox.io/s/anatable-programatically-set-states-forked-1leii?file=/src/App.js)


> <li><code>toggleHideColumn: Function(columnId: String, ?value: Boolean) =&gt; void</code><ul><li>This function can be used to toggle or set a column's hidden state</li><li>Passing a <code>value</code> is optional. If passed, the hidden state will be set to that Boolean value.</li><li>If a <code>value</code> is not passed, the visibility for this column will be toggled.</li></ul></li>

> <li><code>setHiddenColumns: Function(Array&lt;ColumnId: String&gt; | Function(oldHiddenColumns) =&gt; Array&lt;ColumnId: String&gt;) =&gt; void</code><ul><li>This function can be used to set the <code>hiddenColumns</code> state for the entire table.</li><li>If a value is passed, <code>hiddenColumns</code> will be set to that value</li><li>If a function is passed, it will received the previous <code>hiddenColumns</code> value and will be expected to return the new value.</li></ul></li>

(https://react-table.tanstack.com/docs/api/useTable)
