### ISSUE TITLE
AnalyticalTable: The user can’t back navigate out of table via keyboard (Shift+TAB)

### ISSUE THREAD

**Issue by DLaskov** [SAP/ui5-webcomponents-react#1932]
**Describe the bug**
When the user enters AnalyticalTable and goes through some rows, and after that tries to navigate back out of the table with Shift+TAB combo, it does not navigate out of the table.

**Expected behavior**
The user should be able to navigate out of the table in both forward and backward navigation with TAB and Shift+TAB key combos.

**Additional context**
https://support.wdf.sap.corp/sap/support/message/2180312084

**Comment by Lukas742** [comment]
Hi @DLaskov 

this is a duplicate to #1625: 

> Press SHIFT+TAB
> Issue 3:
> Expected Behavior: Focus should go back to the previous actionable element.
> Actual Behavior: Focus does not change.

All further discussions will be held in the linked issue, so I'm closing this one.
