### ISSUE TITLE
Dark theme in release 0.18.0

### ISSUE THREAD

**Issue by AndrianStoikov** [SAP/ui5-webcomponents-react#1933]
**Describe the bug**
I was looking through the docs of the next release and noticed that the `sap_fiori_3_dark` does not work for some reason. I understand that the next version is not release but wanted to let you know about it.

**Isolated Example**

**To Reproduce**
1. Go to the docs for the next release
2. Open any component 
3. Switch to dark theme
4. The styles for dark theme are not applied

**Expected behavior**

**Screenshots**
DynamicPage in 0.17.3
![image](https://user-images.githubusercontent.com/21200806/128343991-a1f2738a-34d5-43fb-b06c-77f18d8776fb.png)

DynamicPage in the next release
![image](https://user-images.githubusercontent.com/21200806/128344026-754141a1-c14c-46bf-a982-77e5f516c658.png)

**UI5 Web Components for React Information**
Operating System: Windows 10
Browser: Microsoft Edge, 92.0.902.62 (Official build) (64-bit)

**Additional context**

**Comment by MarcusNotheis** [comment]
Hey @AndrianStoikov,
thanks for letting us know! Where did you get the screenshot from? From here? https://sap.github.io/ui5-webcomponents-react/master/?path=/docs/layouts-floorplans-dynamicpage--default-story&globals=theme:sap_fiori_3_dark

**Comment by AndrianStoikov** [comment]
Hi Marcus,

Yes. The first screenshot is from the stable release documentation. The second one is from the next release docs.

Best regards,
Andrian

**Comment by AndrianStoikov** [comment]
Hmm,

When I revisited the page it seems to be working. Might have been a temporary issue.

**Comment by AndrianStoikov** [comment]
Marcus,

If you are not able to reproduce the issue feel free to close it.
Might have been an issue on my side.

Best,
Andrian

**Comment by MarcusNotheis** [comment]
I'll leave it open until we're ready for our final 0.18.0 version and will check from time to time whether the issue re-occurs. 
Thanks again for already checking the next docs :)

**Comment by MarcusNotheis** [comment]
Just tried to create a new app (using 0.18.1) and the dark theme was working fine, so I'm closing this issue 🙂
