### ISSUE TITLE
v0.6.0-rc is not available in npm

### ISSUE THREAD

**Issue by TinaC** [SAP/ui5-webcomponents-react#196]
Hi Team,

We need this fix in ui5-webcomponents v1.0.0-rc.3: https://github.com/SAP/ui5-webcomponents/pull/774/files 

In npm, 1.0.0-rc.4 is available: https://www.npmjs.com/package/@ui5/webcomponents

But only version 0.5.0 is available for ui5-webcomponents-react:  https://www.npmjs.com/package/@ui5/webcomponents-react

May I ask why is v0.6.0-rc.22 is not available in npm? 
https://github.com/SAP/ui5-webcomponents-react/tree/v0.6.0-rc.22

**Comment by MarcusNotheis** [comment]
Hi @TinaC 

i just checked the npm version of our project and `0.6.0-rc.22` is available on npm.
You can try to install them via `npm install @ui5/webcomponents-react@next --save` or `yarn add @ui5/webcomponents-react@next`.

If you run the install command without the `@next`, then the `0.5.0` will be installed as this version is still tagged as latest. (0.6.0 has still some minor bugs in the `AnalyticalTable` component - we hope to get them fixed soon to do a `latest` release of 0.6.0)

**Comment by MarcusNotheis** [comment]
FYI - `v0.6.0` is now released as `latest` version
