### ISSUE TITLE
[SF][ObjectPage]: overflow button displayed on header section when no action pass to header

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents-react#1965]
Hi Colleague，

When using responsive view,  set  long text to badge,  an overflow button will show even there are no actions. 

![image](https://user-images.githubusercontent.com/78520316/128979347-725f8de4-0132-48d0-8497-ebb0bdaa3ba3.png)

Isolation example: https://codesandbox.io/embed/nifty-pine-rtx97?file=/src/App.js&codemirror=1

Please help check this issue.

**Comment by sfsf-xweb-sh** [comment]
Hi @Lukas742 
Please add this to next release (0.131.x).
Thanks a lot.

**Comment by Lukas742** [comment]
Hi @sfsf-xweb-sh 

the fix is now also downported to [v0.131.16](https://github.com/SAP/ui5-webcomponents-react/blob/rel/0.131/CHANGELOG.md#013116-2021-08-12)
