### ISSUE TITLE
Input component: valueStateMessage property not working

### ISSUE THREAD

**Issue by mihirahlawat** [SAP/ui5-webcomponents-react#1966]
The valueStateMessage property of the Input component is not working. It crashes the app when any string is set to that property.

1. Go to [codesandbox](https://codesandbox.io/s/value-state-message-fail-s1i1i?file=/src/FormInput.js:2017-2034)
2. Click on 'Save' button. It works perfectly and valueState changes the color of input fields.
3. Now uncomment the 'valueStateMessage' property of Input component and reload the app.
4. The app crashes on clicking 'Save' button.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.14
`@ui5/webcomponents-react` version: 0.16.3
Operating System: Windows
Browser: Chrome

**Comment by MarcusNotheis** [comment]
Hey @mihirahlawat,

thanks for reaching out!
As the `valueStateMessage` is a slot property for UI5 Web Components, passing pure strings into this prop is not supported.
You have to wrap the message in a HTML Element like either `<Label>` component or you can also go for a plain `span` element (see second note of the `valueStateMessage` prop):
![image](https://user-images.githubusercontent.com/8775211/128994797-ba71f855-27c8-4687-a0f7-007383fe8bcf.png)

https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-input--default-story#properties

Please let me know if you need more information on this issue or whether we can close it 🙂

**Comment by mihirahlawat** [comment]
Hi @MarcusNotheis,
Thanks a lot! This works. I'm closing this issue.
