### ISSUE TITLE
Not able to override CSS property for side navigation

### ISSUE THREAD

**Issue by vishnucta** [SAP/ui5-webcomponents-react#1976]
**Describe the documentation issue**

- [x] Documentation is unclear
- [ ] Documentation is incorrect
- [ ] Documentation is missing
- [x] Other

**Description of the issue**
A clear and concise description.

@Lukas742  I am not able to change the sidenavigation color.

`<SideNavigation className="sideNav"
className=""
fixedItems={<></>}
onSelectionChange={function noRefCheck(){}}
slot=""
style={{height: '100vh',color:"blue"}}
tooltip=""

`
No change in color
I tried overriding it with custom css class but it didn't work.

**Comment by Lukas742** [comment]
Hi @vishnucta 

I already answered your question in the [issue](https://github.com/SAP/ui5-webcomponents-react/issues/998#issuecomment-897705138), but if anyone else stumbles over this I'll post it here again :) 

Ui5 Web Components for React use CSS Variables to apply styles. You can still apply styles by using `style` or `className` but in some cases the value will be overwritten or it can cause unwanted side effects. Also `Theming` will not be consistent anymore with overwritten CSS variables. 
You can find out more about styling UI5 Web Components for react [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/knowledge-base--page#styling).

I'm going to close this issue now, if there are still more questions please feel free to open it again or to create another one.

**Comment by vishnucta** [comment]
@Lukas742  thanks for your quick reponse ..it means a lot. Just now in the very early stage of learning

**Comment by Lukas742** [comment]
> @Lukas742 It takes lot of time to figure out from computed tab in chrome console to figure out variables.. Do you happen to know an easy way to find variables for a specific Component ?

Unfortunately there is no other option than to inspect the element in the console and check for the given CSS vars.
