### ISSUE TITLE
ObjectPage: Tabs are not rendered when customized elements are added suffix in micro-frontend apps

### ISSUE THREAD

**Issue by ccflower** [SAP/ui5-webcomponents-react#1993]
**Describe the bug**
Create an ObjectPage with two ObjectPageSection in it, which should render a page with two tabs and  two sub pages.  This works fine for the general case. But when it's in an micro-frontend application,  and adding a suffix for customized elements, the tabs are not rendered correctly. 

**Isolated Example**
https://codesandbox.io/s/objectpage-fw8mw?file=/src/App.js:1282-1299

**To Reproduce**
1. Refresh page, it should render a page with two tabs.

**Expected behavior**
This page should render two tabs.

**Screenshots**
issue: no tabs generated:
<img width="576" alt="noTabs" src="https://user-images.githubusercontent.com/11605187/129877848-7b897669-d24b-4aa9-aa19-086c2e53cf84.png">
expected:
<img width="581" alt="expected" src="https://user-images.githubusercontent.com/11605187/129877899-548b4621-b7d1-4d76-a8bc-a061832b24bc.png">

<img width="625" alt="tab" src="https://user-images.githubusercontent.com/11605187/129877913-956927ea-6b9c-42ab-a464-3904617dc9b0.png">
<img width="1077" alt="tab2" src="https://user-images.githubusercontent.com/11605187/129877936-b1ba2ac6-19ad-46ce-b7c1-9bfa6f12b1df.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.15
`@ui5/webcomponents-react` version: 0.18.0
Operating System:
Browser: chrome

**Additional context**

**Comment by JackieWei** [comment]
Hi, this should be caused by ui-object-page-anchor-tab is not following the suffix, so the tag will not get custom element definition from customElements.get
