### ISSUE TITLE
FilterBar: attached refs to FilterGroupItem children is ignored or recreated

### ISSUE THREAD

**Issue by apoorvsemwal** [SAP/ui5-webcomponents-react#2008]
**Describe the bug**
Hello @MarcusNotheis. This is with reference to a recent fix that was applied against 
[Issue-1890](https://github.com/SAP/ui5-webcomponents-react/issues/1890)
We tried testing the same with the specified version - v0.18.1 and also the latest version which is v0.18.4, however, the issue still seems to persist.
The clear button works fine only if we don't open the filter dialog. If we open the filter dialog, enter some value, save it and then try the clear button it does not work as expected.
Also when we open the filter dialog we receive a warning on the console like so:
![image](https://user-images.githubusercontent.com/45293238/130168399-ea35cb28-b1e3-4615-9c35-685daf1f0673.png)

Like you had shared on a standalone input it all works fine but the behaviour is not as expected with an input in the FilterBar.
I have provided an isolated example in the code-sandbox below with the **EXACT STEPS to reproduce the issue.**

**Isolated Example**
[Codesandbox](https://codesandbox.io/s/ui5-filter-bar-dialog-with-clear-button-sy7ey)

**To Reproduce**
1. Go to [Codesandbox](https://codesandbox.io/s/ui5-filter-bar-dialog-with-clear-button-sy7ey)
2. Click on 'Filters' Button
3. Enter a text value in the dialog and click on Save
4. Entered value appears back in the Input component on the Filter Bar
5. Click on Clear
6. Value in the Input Component is **NOT CLEARED**

**Expected behavior**
Value in the Input Component **SHOULD GET CLEARED** when clear is pressed.

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: `latest`
`@ui5/webcomponents-react` version: `latest`
`react-hook-form` version: `7.12.2`
Operating System:
Browser:

**Additional context**

**Comment by Lukas742** [comment]
Hi @apoorvsemwal 

the refs should now be stable. The `ResizeHandler` warning you see (which I couldn't reproduce) is coming from the dialog and our colleagues are already working on a fix: https://github.com/SAP/ui5-webcomponents/issues/3620
