### ISSUE TITLE
Need programing way to control indetermine status for any checkbox in AnalyticTable(tree table, not only for select all)

### ISSUE THREAD

**Issue by JackieWei** [SAP/ui5-webcomponents-react#2024]
**Is your feature request related to a problem? Please describe.**
In checkbox selection, sometimes we need to show user part of it's content is selected, for example, in tree selection

**Describe the solution you'd like**
@Lukas742 @MarcusNotheis Hi, thanks for bring indeterminate status to select-all checkbox, and also checkbox control.
And in this issue, I original mean that can we have a way to control check status of each row
for example, current selectRowIds looks like
```
{
"0": true,
"0.1": true,
}
```
but I want that
```
{
"0.1": "selected",
"0": "indeterminate"
}
```
This is a just a purpose, anyway, I would like to have ways to control the checkbox status by myself including indeterminate status which I can show to user that part of it's content are selected

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/SAP/ui5-webcomponents-react/issues/1875

**Comment by Lukas742** [comment]
Hi @JackieWei 

we just merged a PR which introduces the `useIndeterminateRowSelection` plugin hook for the AnalyticalTable. With the hook all rows which have selected sub-rows get marked as indeterminate in MultiSelect mode. We decided against implementing a feature which allows programatically setting a checkbox as indeterminate though. The indeterminate state is always connected with some kind of logic and programatically setting a checkbox as indeterminate will most probably break this logic. I hope the plugin hook approach is sufficient for you :)
