### ISSUE TITLE
[ObjectPage]: Header action bar is not responsive when overflow button exist

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents-react#2032]
Hi Colleague,
In the header of Object page component, when there are common button and overflow button, the layout is not responsive, see more details in following screenshots. 

### **Isolated Example**
https://codesandbox.io/embed/nifty-pine-rtx97?file=/src/App.js&codemirror=1

**Screenshots**

![image](https://user-images.githubusercontent.com/78520316/130813413-5694bc54-a65d-49e8-a2a1-1453365bba3b.png)

![image](https://user-images.githubusercontent.com/78520316/130813888-1ddc342e-aed3-4a74-9a34-19a3160f059a.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 0.31.15
`@ui5/webcomponents-react` version:0.131.15

**Expected behavior**
![image](https://user-images.githubusercontent.com/78520316/130813576-bf5315c0-5e55-4727-acc6-7ffb5ba883bb.png)

**Additional context**
Could you take a look and we hope that it will be fixed in next release 0.131.x. 
BTW, changing "visibility:hidden" to "display: none" is work as expected in my case.

**Comment by sfsf-xweb-sh** [comment]
Hi @Lukas742 ,
The problem is that the padding between overflow button and 'Action1' is too big:
![image](https://user-images.githubusercontent.com/78520316/131204019-508ff277-c772-4740-9ec0-743a049555df.png)

**Comment by sfsf-xweb-sh** [comment]
Hi @Lukas742 ,
Please add the fix code to next release.
Thanks！

**Comment by Lukas742** [comment]
Hi @sfsf-xweb-sh 

we didn't find the time yet to take a closer look at this, but since this will probably need a complete overhauling of the `Toolbar` this fix will take some time.

**Comment by mauroerta** [comment]
Does #2171  close this issue too?
In case it doesn't, I can work on it.

**Comment by Lukas742** [comment]
Hi @mauroerta 

no, the PR was linked by accident, so you are welcome to work on this issue :)
