### ISSUE TITLE
OData v2 support

### ISSUE THREAD

**Issue by softshipper** [SAP/ui5-webcomponents-react#2054]
Hi all 

Are you planning to provide OData V2 client for React?

Thanks

**Comment by MarcusNotheis** [comment]
Hey @softshipper,

thanks for reaching out!
Our library is currently only taking care of the rendering part and we are not planning to add further capabilities like an OData client anytime soon (especially for OData we don't have the experience to build such a client with confidence). I've reached out in parallel to our colleagues of the `odata-library` to check whether a web version of their library is planned anytime soon. (https://github.com/SAP/odata-library/issues/48)

In the meantime, you might look into the [SAP Cloud SDK](https://sap.github.io/cloud-sdk/docs/js/features/odata/generate-odata-client) to generate an OData client for your project or take a look into the [OData JavaScript Libraries](https://www.odata.org/libraries/).

I'm going to close this issue for now, feel free to reopen or create a new one in case there is more to do on our side.
