### ISSUE TITLE
[SF][ObjectPage]: Support overflow button or actionSheet in header when responsive view

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents-react#2060]
**Is your feature request related to a problem? Please describe.** 

In our design, there are three or more buttons in header section, and we prefer show one and hidden others in overflow button(Let me call it A, a1 & a2 are hidden in A). When zoom out screen, our overflow button will display in responsive overflow button(this one show due to  limit size, named B). Click B, will show A. Then there will be two overflow buttons. Could that be possible to show a1 & a2 instead of A?

**Describe the solution you'd like**

Show a1, a2 when click overflow button B when B exist.

**Comment by mauroerta** [comment]
Hello @sfsf-xweb-sh, I'll like to help you with this issue, can I ask you for some additional information or screenshots?

Also, I wanted to ask @Lukas742 if this issue is still open since it was mentioned in the closed issue #2291 saying that solving that issue could solve also this one.

**Comment by Lukas742** [comment]
@mauroerta, we didn't close this issue as it wasn't clear to us if the solution of https://github.com/SAP/ui5-webcomponents-react/issues/2291 is sufficient here as well. We probably should have marked @sfsf-xweb-sh in the comment so the team could check. Sorry about that.

@sfsf-xweb-sh could you please check the mentioned PR (https://github.com/SAP/ui5-webcomponents-react/issues/2291) and let us know if this approach is sufficient, or if we need to add more features? If not sufficient, please provide @mauroerta with the required additional information.
