### ISSUE TITLE
ColumnChart: negative accessor value not display on the graph

### ISSUE THREAD

**Issue by apryviazentsau** [SAP/ui5-webcomponents-react#2065]
### **Bug Description**
When using the ColumnChart component on a desktop,  negative `accessor` value which we get from `dataSet` not display on the graph

### **Isolated Example**
[Code sanbox](https://codesandbox.io/s/zealous-shirley-17x1k?file=/src/App.js)

### **Screenshots**
![Screenshot 2021-08-31 at 15 18 34](https://user-images.githubusercontent.com/10254781/131505281-2f7ac519-4cf3-4289-acc7-142e3292ca30.png)

### **UI5 Web Components for React Information**
`@ui5/webcomponents-react` version: 0.18.4
`@ui5/webcomponents-react-charts` version: 0.18.0

**Comment by MarcusNotheis** [comment]
Hey @apryviazentsau,

thanks for reporting! Just to make sure that I understand the issue correctly: The bug report is, that the datalabels, e.g. `-240` are not displayed as part of the "negative" bars, right?

**Comment by apryviazentsau** [comment]
Hi @MarcusNotheis ,
yep, you're correct. As you see "negative" bar on the screenshot - there is no value on it
