### ISSUE TITLE
[SF] [MessageBox] [A11y]: id attribute value must be unique

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents-react#2084]
**Describe the bug**
If I add two MessageBox component with the same primary action (for example 'OK'), axe will capture an a11y warning: id attribute value must be unique.

**Screenshots**
![image](https://user-images.githubusercontent.com/1751846/131866448-26d31ae6-106c-45c7-b4d8-ec049b70933c.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 0.31.16
`@ui5/webcomponents-react` version: 0.131.17
Operating System: macOS
Browser: Chrome

**Comment by Lukas742** [comment]
The fix is also available with [v0.131.19](https://github.com/SAP/ui5-webcomponents-react/blob/rel/0.131/CHANGELOG.md#013119-2021-09-14)
