### ISSUE TITLE
DynamicPage: No padding DynamicPageHeader and DynamicPageTitle

### ISSUE THREAD

**Issue by adeptb** [SAP/ui5-webcomponents-react#2096]
**Describe the bug**
headerContent and headerTitle does not have padding if DynamicPageHeader and DynamicPageTitle wrapped in another component

**Isolated Example**
*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/peaceful-brook-x6i3o?file=/src/App.js).*

**Expected behavior**
headerContent and headerTitle have padding

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: ^1.0.0-rc.15
`@ui5/webcomponents-react` version: ^0.18.4
Operating System:
Browser: Chrome

**Comment by Lukas742** [comment]
Hi @adeptb 

as mentioned in the docs, it is not supported to use other components than the `DynamicPageHeader`/`DynamicPageTitle` for the respective prop, this is also including wrapping it inside another component. The reason for this is that we have to do some internal calculation, for e.g. expanding/collapsing the header, disabling it, adding padding respective to the DynamicPage width, etc.

**Comment by Lukas742** [comment]
I am closing this issue now. If there are still open questions, feel free to reopen it or create a new one.
