### ISSUE TITLE
Popover: Page cannot be scrolled after closing the popover

### ISSUE THREAD

**Issue by sleric1024** [SAP/ui5-webcomponents-react#2109]
**Describe the bug**
Page cannot be scrolled after closing the popover

**Isolated Example**
https://9hr9r.csb.app/

**To Reproduce**
1. Go to https://9hr9r.csb.app/
2. Page can be scrolled by the scroll bar
3. Click the  **First Click to Open Popover** button to open the popover
4. Press the **Esc** button
5. Scrollbar disappeared and page cannot be scrolled anymore

**Expected behavior**
Page could be scrollable 

**Screenshots**
![image](https://user-images.githubusercontent.com/5724592/132855787-0f78beb6-203e-45a1-ac83-8bd7d00fade5.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 0.31.16
`@ui5/webcomponents-react` version: 0.131.18
Operating System: MacOS
Browser: Chrome

**Additional context**
I am from Successfactors

**Comment by sleric1024** [comment]
Demo edit url:
https://codesandbox.io/s/infallible-sea-9hr9r?file=/src/App.js:681-709

**Comment by Lukas742** [comment]
Hi @sleric1024 

thanks for reporting. This is a known [issue](https://github.com/SAP/ui5-webcomponents/pull/3696) with all popovers and a [fix](https://github.com/SAP/ui5-webcomponents/pull/3696) has already been merged but is not yet released. 

Once this has been released to version `0.31.x`, we're going to upgrade our dependencies accordingly and will let you know once this is available on `v0.131.x`

**Comment by sleric1024** [comment]
@Lukas742  thanks for your quick response.

**Comment by sleric1024** [comment]
@Lukas742 hope this fix could be released soon before  b2111 release. :)

**Comment by Lukas742** [comment]
I believe the next 0.31 release is coming soon, but since I'm not directly in the UI5 Web Components team, it's probably best to ask them. You can do this in the [original issue](https://github.com/SAP/ui5-webcomponents/pull/3696).

**Comment by sleric1024** [comment]
OK. Thanks
