### ISSUE TITLE
[SF][A11Y][ActionSheet]: Announcement issue found for the total count of button elements

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents-react#2120]
**Describe the bug**
When using actionSheet,  the total count of element is not right. Please help check this issue. 

**Isolated Example**
![image](https://user-images.githubusercontent.com/78520316/133227102-505fc03c-a34c-426d-bf70-01bfdc7cdac1.png)
![image](https://user-images.githubusercontent.com/78520316/133227285-8c666733-1495-4d58-a506-b10303d32009.png)

*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).*

**To Reproduce**
1. Login to instance -> go to Mock data url:
https://qacand.hcm.ondemand.com/sf/omp/?mock#/manage
2. Select "My Postings" tab
3. Click overflow button on list item (Draft or Published item，not Closed)
4.Check ariaLabel of button inside actionSheet.

**Expected behavior**
Visually button element should match programmatically

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 0.31.17
`@ui5/webcomponents-react` version: 0.131.17
Operating System:
Browser: chrome

**Additional context**
High Prio.

**Comment by Lukas742** [comment]
Hi @sfsf-xweb-sh 

I have no access to the link you posted and for me it seems to be working fine. Please take a look at this [codeSandbox](https://codesandbox.io/s/reverent-chaplygin-cp93u?file=/src/App.js) and tell me if I missed something.

**Comment by sfsf-xweb-sh** [comment]
Hi @Lukas742
I know why this issue happens, thanks for your example on codeSandbox.
