### ISSUE TITLE
Adding Table Personalization Dialog for hide/show column to AnalyticalTable

### ISSUE THREAD

**Issue by buddfung** [SAP/ui5-webcomponents-react#2149]
Hi,

Currently, we have a requirement for hide/show column on AnalyticalTable. 
We see that we can use "tableInstance" to hide/show the column in the code. 

From UI side, we found there was a Table Personalization Dialog (https://experience.sap.com/fiori-design-web/table-personalization-dialog/#components, https://experience.sap.com/fiori-design-web/table-personalization-dialog/) But it seems like not available in ui5-webcomponents-react library.

We would like to know if there is a plan to bring this dialog to this library. Or we should go ahead to build that dialog ourselves? We are looking for some more standardize solution. In our application, we have more than 5 tables need that functionality. It would be nice to have that component as it is kind of common features for table.

If you have any recommendation or input, we would like to hear more. 
Thank you.

**Comment by MarcusNotheis** [comment]
As this feature request has been added to the UI5 Web Components backlog, I'll now close this issue.
As soon as the UI5 Web Component is available, we'll expose it via our project as well.
