### ISSUE TITLE
MessageStrip: Does not use a theme text color

### ISSUE THREAD

**Issue by charlie-maloney** [SAP/ui5-webcomponents-react#2157]
**Describe the bug**
This is a very small bug, but it popped up when using the [UX Consistency tool](https://github.tools.sap/ux-consistency/UXCT/wiki/Getting-Started):
* the message strip text color is getting flagged for not being defined as a text color in the Fiori theme (it is currently `#000`)
* I believe it should be `--sapUiBaseText`

**Expected behavior**
* I believe it should be `--sapUiBaseText`

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: rc.15
`@ui5/webcomponents-react` version: 0.18.7
Operating System: mac
Browser: chrome

**Comment by Lukas742** [comment]
Hi @charlie-maloney 

I just checked and the `sapTextColor` CSS Var (retrieved from [here](https://github.com/SAP/theming-base-content/tree/master/content/Base/baseLib)) is used for the text of the MessageStrip. It is equivalent to the `sapUiBaseText` [Theme Parameter](https://sapui5.hana.ondemand.com/test-resources/sap/m/demokit/theming/webapp/index.html)

Could you please clarify where it was set as `#000` preferably with a reproducible example using this [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34)

<img width="280" alt="Screenshot 2021-09-23 at 07 50 40" src="https://user-images.githubusercontent.com/9749730/134460020-1d57f0c2-8335-43a4-aac8-ea2485c43241.png">

**Comment by charlie-maloney** [comment]
Hi @Lukas742 --

I just double checked, and you are right, the color is being correctly applied with the right variable. It looks like the UX Consistency tool was flagging the color in the message strip webcomponent (see screen shot). 

I should have caught that before opened this issue. Thanks for your time! 

![Screen Shot 2021-09-23 at 9 34 01 AM](https://user-images.githubusercontent.com/22550767/134547731-1aa275eb-5cc3-4acc-81ca-6a8b59a4902c.png)
