### ISSUE TITLE
[SF] Support Fiori's Select Dialog

### ISSUE THREAD

**Issue by ChristyFei** [SAP/ui5-webcomponents-react#2162]
Is Fiori's Select Dialog support right now? If not, is it in your roadmap? 
Fiori's Guide: https://experience.sap.com/internal/fiori-design-web/select-dialog/ 
![image](https://user-images.githubusercontent.com/16127196/134621823-f7528f31-27cb-4a55-94ae-a7a76356ba9c.png)

**Comment by Lukas742** [comment]
Hi @ChristyFei 

I just wanted to let you know that we have started implementing the SelectDialog. If nothing comes up, we should be able to finish it by the end of next week.

**Comment by Lukas742** [comment]
This feature has also been released in [v0.131.25](https://github.com/SAP/ui5-webcomponents-react/blob/rel/0.131/CHANGELOG.md#013125-2021-12-03)
