### ISSUE TITLE
Toolbar: Freezes page

### ISSUE THREAD

**Issue by AndrianStoikov** [SAP/ui5-webcomponents-react#2199]
**Describe the bug**
When using the toolbar it might freeze the page. 

**Isolated Example**
https://codesandbox.io/s/sweet-chihiro-ndgup?file=/src/App.js

**To Reproduce**
1. Go to the sandbox
2. Open the sandbox in a full screen mode
3. Use dev tools and set the resolution to 906px
4. The page freezes completely

Changing the resolution fixes the bug on Windows, however in our app the page is always freezed on MacOS using Chrome.

**Expected behavior**
The toolbar should not cause infinite rerenders

**Screenshots**
![image](https://user-images.githubusercontent.com/21200806/136379986-a32fa9b8-c875-4521-baf6-293a8e8cf61c.png)

**UI5 Web Components for React Information**
    "@ui5/webcomponents": "latest" - rc.15,
    "@ui5/webcomponents-fiori": "latest" - rc.15,
    "@ui5/webcomponents-react": "latest" - 0.18.9,
 
Operating System: Windows 10
Browser: Microsoft Edge, Version 94.0.992.38 (Official build) (64-bit)

**Additional context**
One of my colleagues uses MacOS and the page freezes every time in Chrome. I noticed that it might be related to the fact that we use `Fragment` inside the toolbar and the `Dialog` there, which in our case we render with portal, but in terms of code it looks right to me.

If you need more context about the bug I am here to help.

Best,
Andy

**Comment by Lukas742** [comment]
Hi @AndrianStoikov 

setting `width: "auto"` to the toolbar is not supported. Could you check if it's still not working after removing it?
If you want to align your toolbar items to the right you can use `flexGrow` and a toolbar spacer, for example. [codeSandbox](https://codesandbox.io/s/bold-joliot-uztk6?file=/src/App.js)

**Comment by Lukas742** [comment]
Ok, good to hear :) 

We added a `max-width` of 100% to the toolbar, so when setting the `width` to `auto` the component won't break.
