### ISSUE TITLE
replace `StyleClassHelper` with `clsx`

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents-react#2209]
UI5 Web Components for React is using a custom `StyleClassHelper` to concatenate CSS class names.
We would like to deprecate this class and switch over to the [`clsx` npm module](https://github.com/lukeed/clsx).

Required Steps:
1. [ ] Add `clsx` to the `package.json` of the `main` and the `charts` package
2. [ ] Replace all occurrences of `StyleClassHelper` in the `main` and `charts` package with the new `clsx` implementation
3. [ ] Add a deprecation warning to the [`StyleClassHelper` constructor](https://github.com/SAP/ui5-webcomponents-react/blob/2b621f46ac5bb6c9347771b001b47f2ea623a589/packages/base/src/styling/StyleClassHelper.ts#L8-L10)

Thank you for your support!

**Comment by lucas-barros** [comment]
@MarcusNotheis may I work on this issue?
