### ISSUE TITLE
replace `passThroughProps` with `...rest` spread operator

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents-react#2211]
Most of our components consume `passThroughProps` to prevent passing through some props, since we now wan't to give developers full customisation capabilities we decided to allow all props to be passed to the component, even if not defined in the PropTypes. 

Steps:

- Search for `usePassThroughHtmlProps` or `passThroughProps` to find one of the components which are still using it.
- Add a `...rest` parameter to the `props` object.
- Check whether some props should not be applied, because they are for example omitted in the PropTypes interface.
- Add the `...rest` parameter without the omitted props to the root container of the component and remove `passThroughProps` and the respective import.
- Remove  `createPassThroughPropsTest` in the corresponding test file of the component
- Run tests (`yarn/npm test`)

E.g.: https://github.com/SAP/ui5-webcomponents-react/pull/2210/files

__Note:__ You can refactor each component in a single PR or do it as a whole, but please always let us and others know when you are working on it by assigning yourself to this issue and explaining what you want to help with. 

__Thanks a lot and happy Hacktoberfest!__

**Comment by HrithikSawant** [comment]
Hey @Lukas742  I'm new To React and UI5-Webcomponent I need a help for better understanding !!
