### ISSUE TITLE
ActionSheet: Announcement and focusing issue of A11y

### ISSUE THREAD

**Issue by sleric1024** [SAP/ui5-webcomponents-react#2229]
**Describe the bug**
1) When the available actions modal dialog is opened, both the options got announced together in Demo though only the first option had the visual focus. 
2) **In Windows OS**, then using narrow keys to switch the option from modal dialog from ActionSheet, it can be announced,  but the focus didn't change at all, which in MacOS, it works correctly.

**Isolated Example**
https://codesandbox.io/s/charming-voice-lguld?file=/src/App.js

**To Reproduce**
1. Go to https://uvntf.csb.app/
2. Trun on JAWS or NVDA,
3. Using keyboard to open the dialog
4. Using narrow keys to change the options from modal dialog

**Expected behavior**
Only the focused item should be announced,
Can using the narrow keys to change the option with correct focusing in all operation system.
(The two points of accessibility requirements come from SF A11y Expert)

**UI5 Web Components for React Information**
    "@ui5/webcomponents": "0.31.20",
    "@ui5/webcomponents-fiori": "0.31.20",
    "@ui5/webcomponents-react": "0.131.20",
Operating System: Windows
Browser: Chrome

**Additional context**
I am from SAP Successfactors. And issues are for b2111 released project.

**Comment by Neeeko** [comment]
Hi, I'd like to also add that the ActionSheet role is announced twice when opening it:
![Screenshot 2022-02-03 at 16 22 55](https://user-images.githubusercontent.com/7316793/152372675-2f42f655-532a-4f29-812b-375a66f3d8b4.png)

@Lukas742 please let me know if you want me to raise a separate defect for this. Thanks!

**Comment by Lukas742** [comment]
Hi @Neeeko 

normally we prefer that a new issue is created, but since this fix should be straight forward, it's not necessary this time :) 
Here you can find the [PR](https://github.com/SAP/ui5-webcomponents-react/pull/2562) that should resolve this.

**Comment by MarcusNotheis** [comment]
I think this issue has been fixed via #3050
