### ISSUE TITLE
Rendering issue while adding Flexible Layout(with 2 Columns) inside an Object Page

### ISSUE THREAD

**Issue by apoorvsemwal** [SAP/ui5-webcomponents-react#2336]
### Discussed in https://github.com/SAP/ui5-webcomponents-react/discussions/2082

<div type='discussions-op-text'>

<sup>Originally posted by **apoorvsemwal** September  2, 2021</sup>
Hello,

We have a requirement where we need to add a Flex Col Layout(with 2 columns) inside an Object page, and the second column of flex layout is also an Object Page.
Here is an isolated code sandbox we have implemented as a sample:
[Codesandbox](https://codesandbox.io/s/ui5-flexible-layout-with-analytical-table-4plmx)
We observe that when the ObjectPage is first rendered the Analytical table contained inside the FlexLayout has some additional space below it (which we believe corresponds to the height of the second column of this flex layout. )
In our case, the second col of the flex layout is also an Object Page.    

However, once we click on any item (expands the second col of our flex layout) and close that object page the space below our analytical table is removed. From a UI perspective, this is exactly what we are expecting to see even when the component is rendered for the first time. 

To make it more clear here are the steps with snapshots.
**Step 1:**
![image](https://user-images.githubusercontent.com/45293238/131855030-7fc43fdc-5dab-4f4a-a976-fac8bfad0242.png)
**That red marked area is something that should not be there when the component first gets rendered.**
(We believe it is due to the fact that there is Flex Box working behind the scenes whose height is being referred from the second column of the flex layout)

**Step 2.**
Next, we click on any item from the list and the second col gets expanded. We then close the second col via the close button.
![image](https://user-images.githubusercontent.com/45293238/131855568-ba054c34-ccaf-41d5-a170-166783505bf5.png)

![image](https://user-images.githubusercontent.com/45293238/131855699-a0c0e886-22e4-4913-b934-70a17cf9e148.png)
As shown in the snapshot above there is no additional space below the Table - This is exactly the view we were expecting when the component first got rendered at Step1. **We DONT want that extra space below the table when the component first gets rendered at Step 1**

Any feedback on this would be highly appreciated.
Thanks 
</div>

**Comment by Lukas742** [comment]
Hello @apoorvsemwal 

According to UX guidelines, it is not recommended to nest a `FlexibleColumnLayout` inside an `ObjectPage`, especially if an additional `ObjectPage` is rendered inside the FlexColLayout. 

That being said, I guess your best option here is to conditionally render the mid component, so it will only be mounted inside the DOM when actually used. See [codeSandbox](https://codesandbox.io/s/ui5-flexible-layout-with-analytical-table-forked-1lbsl?file=/src/FlexTest.js:841-899)

**Comment by apoorvsemwal** [comment]
Hello @Lukas742 
Thanks for your quick response and the provided suggestion on this. Also it would be a great help if you could possibly point us to the UX guideline link. might serve as a good reference for us to verify such scenarios in the guidelines first. Thanks :)

**Comment by Lukas742** [comment]
Here you go :) 

- https://experience.sap.com/fiori-design-web/
- ObjectPage: https://experience.sap.com/fiori-design-web/object-page/
- FlexibleColumnLayout: https://experience.sap.com/fiori-design-web/flexible-column-layout/

**Comment by apoorvsemwal** [comment]
Thanks a lot @Lukas742
