### ISSUE TITLE
MessageBox: Block layer does not get removed after closing a MessageBox

### ISSUE THREAD

**Issue by MKraus92** [SAP/ui5-webcomponents-react#2359]
**Describe the bug**
Calling the hide function on MessageBox does not clear the UI5-Block-Layer

**Isolated Example**
[Isolated Exampe](https://codesandbox.io/s/delicate-hill-el0iy?file=/src/App.js)

**To Reproduce**
1. Clock on 'Open'
2. Click on Close'
4. See that Block Layer stays so 'Open' can not be pressed again

**Expected behavior**
Block layer gets removed after calling close of the MessageBox.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.2
`@ui5/webcomponents-react` version: 0.20.1
Operating System: Windows
Browser: Chrome

**Additional context**
The issue is maybe related to this one:
https://github.com/SAP/ui5-webcomponents/issues/4065

**Comment by MarcusNotheis** [comment]
Hey @MKraus92,
thanks for reaching out!
You can close the `MessageBox` with the `close` method, the `hide` method is in internal method of the UI5 Web Components.

You can find the [docs here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-messagebox--default-story#methods). 
I've also updated your sandbox to use the close method instead: https://codesandbox.io/s/elegant-leavitt-9ru43?file=/src/App.js

**Comment by MKraus92** [comment]
@MarcusNotheis 

Thanks!
