### ISSUE TITLE
[SF][0.131.24][DynamicPageTitle] please provide an event which is fired when buttons of "actions" added to overflow menu

### ISSUE THREAD

**Issue by i323808** [SAP/ui5-webcomponents-react#2375]
**Is your feature request related to a problem? Please describe.**
Action buttons will be added to a overflow menu automatically on small size screen. Buttons only have icons are supposed to be switched to text buttons.
![overflow_button](https://user-images.githubusercontent.com/30744017/144797054-013f59e2-c9b3-4a55-a7de-f98e96d6ebab.png)

**Describe the solution you'd like**
Please provide an event(e.g. onDisplayOverflow) which is fired when buttons of "actions" added to the overflow menu, then modules can bind an event handler to switch an icon button to text button.

**Comment by Lukas742** [comment]
This feature has been released in [v0.131.26](https://github.com/SAP/ui5-webcomponents-react/blob/rel/0.131/CHANGELOG.md#013126-2021-12-07)
