### ISSUE TITLE
wrappers should have type definitions

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents-react#2428]
**Is your feature request related to a problem? Please describe.**
When I'm using the wrapper classes, there are no type definitions available.

**Describe the solution you'd like**
All wrapper files should have copies of the type definitions of the dist files.

**Describe alternatives you've considered**
Adding something like this:
```typescript
declare module "@ui5/webcomponents-react/wrappers/*";
```

**Additional context**
Wrappers are the "Bring-your-own-component" solution allowing to share component from parent application.

**Comment by MarcusNotheis** [comment]
Hey @codefactor,

we are planning to revamp our whole build process for our next release - this should then also include types for the wrapper components. I would expect that we might have the new build system available mid of January.

**Comment by MarcusNotheis** [comment]
Reworking our build setup is more complicated that I initially thought, so I guess we'll rather have the typings for the wrappers available mid of February.
