### ISSUE TITLE
Toolbar: Fix SR announcement for the overflow button

### ISSUE THREAD

**Issue by lv75** [SAP/ui5-webcomponents-react#2453]
**Describe the bug**
It is probably not an actual bug, but... for the Toolbar component, which in this example is being used in the ObjectPage Actions, the QAS claims that the toolbar overflow button is "Logically not a toggle button". His claim is based on the fact that, as it shows in the screenshot, the screen readers are announcing it as a Toggle button, when visually, it rather looks like a Show More menu/button.

<img width="960" alt="Logically not looking like  a Toggle button" src="https://user-images.githubusercontent.com/8533257/147840612-94a3aa6f-ede0-4132-b197-db30ae6eebdb.png">

**To Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/story/layouts-floorplans-toolbar--with-overflow-button
2. Use a screen reader (e.g.  NVDA)
3. Tab-navigate to the Toolbar overflow button

**Expected behavior**
To skip the announcement .
His request is to remove or to skip the announcement that the button from the Toolbar overflow is a toggle button, as it shows in this screenshot.

![screenshot-1](https://user-images.githubusercontent.com/8533257/147841050-580b3897-84a0-4518-afe5-213052c4258e.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents-react` version:  0.20.5

**Comment by Lukas742** [comment]
Hi @lv75 

you are right, we are missing the "Show More" announcement. I've created a PR that adds the respective a11y attribute to the button. 
In my opinion, being a "toggle button" and a "show more button" at the same time is not mutually exclusive. I also checked how UI5 is handling this and there it's a toggle button as well. Could you elaborate on why you think this shouldn't be a toggle button?

**Comment by Lukas742** [comment]
Hi @lv75 

I could not reproduce the issue with nvda as only the `aria-label` of the `button` is announced when set.
![nvda_ex1](https://user-images.githubusercontent.com/9749730/158334362-a3ed9b23-871e-4088-9192-3f74f7b868f7.jpeg)

What browser and which tool are you using?

> So, in order for us to achieve our accessibility requests and requirements, we would like to be able to modify the default values of this toolbar overflow button's for aria-label, title/tooltip, and all accessibility or screen reader related attributes.

The Toolbar is implemented according to the UX guidelines and as the "show more" button is not customizable I don't see the point of making the a11y attributes of it customizable. If there is an issue with a11y we will fix it on our side. 
If you need to change the button more than just fixing the current problem, please elaborate so we can discuss it again.
