### ISSUE TITLE
IllustratedMessage: poor contrast in dark mode

### ISSUE THREAD

**Issue by michelfernandes** [SAP/ui5-webcomponents-react#2490]
**Describe the bug**
The IllustratedMessage texts don't have a good contrast when the application is on dark mode or opened on some dark incognito mode. The image itself looks good, but the text is very hard to read.

**To Reproduce**
This can be reproducible from the documentation storybook:
1. Go to https://sap.github.io/ui5-webcomponents-react;
2. Click on IllustratedMessage component on the left;
3. Click on the Canvas view to vizualise the component;
4. Select the darkmode;
5. The messages are hard to read due to contrast;

**Screenshots**
![image](https://user-images.githubusercontent.com/18291046/149326898-3b3385bb-1c70-4054-b6a8-00d32f29d75a.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.1
`@ui5/webcomponents-react` version: 0.20.0
Operating System: MacOS/Windows
Browser: Google Chrome

**Comment by Lukas742** [comment]
Hi @michelfernandes 

you can changes themes by clicking on the "Theme" button inside the toolbar. E.g.: [sap_fiori_3_dark](https://sap.github.io/ui5-webcomponents-react/?path=/story/user-feedback-illustratedmessage--default-story&globals=theme:sap_fiori_3_dark)

I also created a [PR](https://github.com/SAP/ui5-webcomponents-react/pull/2491) that will remove the default "backgrounds" button, as offering both could be confusing.
