### ISSUE TITLE
[SF][SelectDialog]: Number of selected items is wrong.

### ISSUE THREAD

**Issue by QiuranHu** [SAP/ui5-webcomponents-react#2492]
**Describe the bug**
In multi select mode of select dialog, the number of selected items is based on selected items in the current list, not based on totally selected items. To be specific, say the user first selects an item, then searches some text and selects another item. At this time, the number of totally selected items is 2, but 'Selected: 1' is displayed in the UI.

I think it might solve the problem if you provide a way to control the displayed number of selected items outside the select dialog component.

Also the number of selected items is not fixed on the top of the list. So, when the user scrolls down the list, he will not clearly see how many items he has selected already. The number of selected items should be fixed on the top of the list.

**Isolated Example**
https://codesandbox.io/s/nifty-lumiere-0jr9w

**To Reproduce**
1. Open the codesandbox (https://codesandbox.io/s/nifty-lumiere-0jr9w).
2. Click on 'Open dialog'.
3. Click the checkbox before 'Item1'
4. Input 'Text' in the search input and press enter.
5. Click the checkbox before 'Text search item1'.
6. The number of selected items should be 2 instead of 1.

**Expected behavior**
The number of selected items should based on totally selected items, not based on selected items in the current list. 
The number of selected items should be fixed on the top of the list.

**Screenshots**
![image](https://user-images.githubusercontent.com/55808904/149462689-d9cdc0c4-cc68-4cda-9c6d-0bafdf4a22e7.png)
![image](https://user-images.githubusercontent.com/55808904/149462715-cbff85a1-dc37-47a3-9a3f-abc2836b8056.png)
![image](https://user-images.githubusercontent.com/55808904/149462720-2155241c-1b48-44e2-b5e7-63f561baceb8.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.2
`@ui5/webcomponents-react` version: 0.20.5
Operating System: Linux
Browser: Chrome Version 97.0.4692.71 (Official Build) (64-bit)

**Additional context**
Organization: SAP SuccessFactors

**Comment by Lukas742** [comment]
Hi @QiuranHu 

I created a PR that should fix the first issue.

In the [UX guidelines](https://experience.sap.com/fiori-design-web/select-dialog/#infobar) it's stated that the infobar should be scrollable and not sticky, that's why we decided to implement it that way. 
Since UI5 still implemented it fixed to the top, I contacted our UX experts to clarify what the expected behavior here is.

**Comment by QiuranHu** [comment]
Thank you for your swift action!
