### ISSUE TITLE
FilterBar: Wrong Portuguese label on Adapt Filters dialog

### ISSUE THREAD

**Issue by anfavretto** [SAP/ui5-webcomponents-react#2534]
**Is your feature request related to a problem? Please describe.**
The label of the Cancel and Clear buttons in Portuguese on the filter configuration dialog (it opens when we click on "Adapt Filters" button).

**Describe the solution you'd like**
The [CANCEL label](https://github.com/SAP/ui5-webcomponents-react/blob/2b1b1cb0e5d4306b1daa502850751d84b1d0211e/packages/main/src/i18n/messagebundle_pt.properties#L9) should be "Cancelar" in Portuguese instead of "Anular".
The [CLEAR label](https://github.com/SAP/ui5-webcomponents-react/blob/2b1b1cb0e5d4306b1daa502850751d84b1d0211e/packages/main/src/i18n/messagebundle_pt.properties#L53) should be "Limpar" in Portuguese instead of "Anular".

**Describe alternatives you've considered**

**Additional context**
When we have the "Clear" and "Cancel" buttons on the filter configuration dialog both are with the same label.
![Screen Shot 2022-01-26 at 17 02 41](https://user-images.githubusercontent.com/18503607/151238281-b9bacad0-8fe5-47fa-b9d7-91c38507ed31.png)

**Comment by MarcusNotheis** [comment]
Hey @anfavretto,

I've created an internal incident to get this translation improved.
Thanks for reporting!
