### ISSUE TITLE
Combobox - Dropdown getting closed when using scrollbar

### ISSUE THREAD

**Issue by ayushnawani** [SAP/ui5-webcomponents-react#2568]
**Describe the bug**

I am trying the scroll the dropdown via the scrollbar with holding mouse left click. But as soon as I release the left click, the dropdown is getting closed. 

Is there any way to keep dropdown open so that we can select the item afterwards?

**Screenshots**
![image](https://user-images.githubusercontent.com/15374835/152781714-5549d2d2-bcc7-4444-8d04-656eed168a07.png)

Screenshot Ref- https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-combobox--default-story

**Comment by Lukas742** [comment]
Hi @ayushnawani 

this issue is already known with our UI5 Web Components colleagues. (https://github.com/SAP/ui5-webcomponents/issues/4523)
Once they fixed and released it on their end, we’re going to update our version as well.
