### ISSUE TITLE
Scrollbar inside Page + Wizard component

### ISSUE THREAD

**Issue by mihirahlawat** [SAP/ui5-webcomponents-react#2578]
**Describe the bug**
I am currently displaying a Wizard component inside a Page component. But unfortunately 2 scrollbars are occuring for both the Page component and the WizardStep component. disableScrolling={true} has been set in the Page component as well, but no help.
 
**Isolated Example**
On codesandbox, nothing is rendered when Wizard component is added to the children field of the Page component. Seems some issue with the website. But anyway, this is how my current code structure looks like - 

```
<Page
    disableScrolling={true}
    children={
      <>
        <Breadcrumbs>
          <BreadcrumbsItem>{"Test Route 1"}</BreadcrumbsItem>
        </Breadcrumbs>

        <Title>{"Test Title"}</Title>

        <Wizard>
          <WizardStep icon="product" titleText="Product Type" selected>
            <Title>1. Product Type</Title>
          </WizardStep>
        </Wizard>
      </>
    }
    footer={
      <Bar>
        <Button>{"Button Test"}</Button>
      </Bar>
    }
  ></Page>
```

**Screenshots**
![image](https://user-images.githubusercontent.com/38140078/153229849-ed3e353d-490c-475d-b505-fedcfed53694.png)

**Comment by Lukas742** [comment]
Hi @mihirahlawat 

could you checkout the [codeSandbox](https://codesandbox.io/s/silly-elgamal-8g97w?file=/src/App.js) example I created and let me know if this approach is feasible for you?

**Comment by mihirahlawat** [comment]
Hi @Lukas742 
Thanks for the reply. And yes you were correctly able to recreate the issue that I want to address.

![image](https://user-images.githubusercontent.com/38140078/153251424-1768067e-e8be-4c47-ae1e-557e66d8fe86.png)

Can you help in removing this scrollbar? I need to do this in a responsive manner such that, if the contents inside exceed the length then the scrollbar should appear. Otherwise it should be hidden.

**Comment by Lukas742** [comment]
Hi @mihirahlawat 

when there are more than one `WizardStep`s displayed, then this behavior is intended. Otherwise it wouldn't be possible to scroll back to the previous steps. If only the first step is displayed, there shouldn't be a scrollbar though. Since this is behavior is also happening for the Wizard without a `Page`, I created an [issue](https://github.com/SAP/ui5-webcomponents/issues/4726) in the UI5 Web Components repo since the component is developed by them.

**Comment by mihirahlawat** [comment]
Hi @Lukas742, FYI, the ticket on the webcomponents repository has been closed and the fix has been merged into the master branch.

**Comment by Lukas742** [comment]
I'm aware of that, thanks. We still have to wait for their next release though.
