### ISSUE TITLE
DateTimePicker: Error when manipulating value with onChange method

### ISSUE THREAD

**Issue by MKraus92** [SAP/ui5-webcomponents-react#2592]
**Describe the bug**
In DateTimePicker when binding the value with a State and editing in the onChange function this state the DateTimePicker component will error.

**Isolated Example**
[Example in this codebox](https://codesandbox.io/s/compassionate-snowflake-gxdtf?file=/src/App.js)

**To Reproduce**
1. Change Date with Datetimepicker
2. See that ValueState changes to Error
3. Try to change Date again and get TypeError

**Expected behavior**
If Value is set or manipulated it should be updated.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: latest (1.1.2)
`@ui5/webcomponents-react` version: latest (0.21.2)
Operating System: Windows 10
Browser: Chrome

**Additional context**
I guess the problem has to do with the DateTimePicker storing the value as string instead of Date object.

**Comment by Lukas742** [comment]
Hi @MKraus92 

as you already mentioned, the `value` attribute stores its value as string, so passing a `Date` won't work. To format a date object into a string according to the locale `formatPattern` you can use the `formatValue` method of the web component instance. 

If you want to use a date object as initial value, you will have to wait for the definition of the custom element of the underlying web component. We are currently working on a solution which makes this easier to consume, until then you could probably use an approach similar to this [codeSandbox](https://codesandbox.io/s/relaxed-grothendieck-n5zw0?file=/src/App.js).

**Comment by MKraus92** [comment]
Hi @Lukas742 ,

thank you, when using the `formatValue` method the `value` gets stored properly.

Still, i think it would be better to store a Date object within the DateTimePicker. Any chance this can be changed by the dev team? Should i open a feature request?

**Comment by Lukas742** [comment]
You are welcome to open a feature request. :)
Please do so in the https://github.com/SAP/ui5-webcomponents repo, as the `DateTimePicker` is being developed by our colleagues there. They will take a look at it and let you know if it is feasible.

**Comment by MKraus92** [comment]
Feature Request opened at [DateTimePicker: use Date object as Value #4764](https://github.com/SAP/ui5-webcomponents/issues/4764)
