### ISSUE TITLE
[SF] DynamicPageTitle  - Actions Overflow menu should close if an action in the menu is clicked

### ISSUE THREAD

**Issue by Vir-Mittal** [SAP/ui5-webcomponents-react#2602]
**Is your feature request related to a problem? Please describe.**
In the DynamicPageTitle component, the actions menu displays an overflow menu if there are several actions available. After clicking a particular action in this overflow menu, the menu remains open.

https://codesandbox.io/s/dynamicpagetitle-actions-overflow-menu-ih1jmn?file=/src/App.js

**Describe the solution you'd like**
Clicking an action should also close the overflow menu, similar to how it works in the ActionSheet component.

**Comment by Vir-Mittal** [comment]
Hi,

I was testing this on the ui5 webcomponents-react storybook and it seems to be working as intended now. However, it still does not work in projects and this sandbox - https://codesandbox.io/s/ui5wc-react-dynamicpagetitle-actions-eo7tok?file=/src/App.js

I'm not sure if I'm missing something on my side, could you please take a look at the above sandbox?

**Comment by MarcusNotheis** [comment]
Hey @Vir-Mittal,

using a `Fragment` as the root node of the `actions` prop was an edge case that we missed. This should now be fixed in [v0.22.1](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.22.1)

**Comment by Vir-Mittal** [comment]
Thank you
