### ISSUE TITLE
DynamicPage: Memory leak warning

### ISSUE THREAD

**Issue by AndrianStoikov** [SAP/ui5-webcomponents-react#2606]
**Describe the bug**
When I wrap the `DynamicPage` with `BusyIndicator` the component throws memory leak warnings. 

**Isolated Example**
[Sandbox](https://codesandbox.io/s/serverless-sea-l6sc7s?file=/src/App.js)

**To Reproduce**
1. Go to the sandbox
2. Observe the console
3. Refresh the page
4. The memory leak warning is shown

**Expected behavior**
Not to throw memory leak warnings

**Screenshots**
![image](https://user-images.githubusercontent.com/21200806/154443620-29026afb-ab3d-4668-ae21-b6c08af9249b.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.1.2
`@ui5/webcomponents-react` version: 0.21.2
OS/Platform: Windows 10
Browser: Microsoft Edge Version 98.0.1108.50

**Additional context**
I specifically set the timeout to 200ms because that is usually how much time our API call for the data takes. Increase/decreasing the timeout might hide the warning. Also, the issue seems related to the fact that in the code we switch between component tree with `BusyIndicator` and one without but at the time of writing it seemed more readable in our case.

**Comment by AndrianStoikov** [comment]
Hi @Lukas742,

This is great news. Thanks for the fast reaction.

**Comment by Lukas742** [comment]
We just released [v0.21.3](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.21.3) which should solve this issue. Could you confirm that it's fixed on your end as well?

**Comment by AndrianStoikov** [comment]
Hi @Lukas742,

I think the issue is resolved and it can be closed. However, I noticed a weird change. In version `0.21.2` we had imports of the form

`import { PopoverDomRef } from '@ui5/webcomponents-react/webComponents/Popover';`
and now it is changed to 
`import { PopoverDomRef } from '@ui5/webcomponents-react/dist/webComponents/Popover';`

Is this intended?

**Comment by Lukas742** [comment]
Hi @AndrianStoikov 

[v0.21.4](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.21.4) is now available, which should make it possible to import interfaces from the `webComponents` and `components` folder again.
Please note that these imports are deprecated though and will be removed in future versions. Please import directly from `"@ui5/webcomponents-react"` now. (We also added a deprecation warning when in dev env, describing which import to use.)
E.g.: 
```js
import { PopoverDomRef } from "@ui5/webcomponents-react";
```

**Comment by AndrianStoikov** [comment]
Hi @Lukas742,

Thanks again. I did not know the imports are deprecated. I'll sync that with my team and we will get rid of them. I'm closing the issue.

Best,
Andy

**Comment by MarcusNotheis** [comment]
Hey @AndrianStoikov,

just FYI: those imports have just been deprecated with the current release, so you'll definitely have some to migrate :) 
We'll also add an entry to our changelog / migration guide soon.
