### ISSUE TITLE
Unselect Rows of Table

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [SAP/ui5-webcomponents-react#2633]
![image](https://user-images.githubusercontent.com/9791364/156084535-2ea02f38-62c6-41d6-9716-ffa39504171b.png)

How remove selected row after action?

**Comment by Lukas742** [comment]
Hi @luizcarlospedrosogomes 

not 100% sure what you need help with but, if you want to programatically change selected rows, you can use the `selected` prop of the `TableRow` component. 

Next time, please give a clear and concise description of the issue so that we can help you more easily.

**Comment by luizcarlospedrosogomes** [comment]
Thanks for the answer
I believe that for those who use this lib it has become clear, if anyone uses it. It amazes me that there is no method to do this.
Another doubt I have is how to retrieve the table rows, should I use react's useRef?

**Comment by Lukas742** [comment]
It depends on how you want to access the rows. 

- By selecting a row --> `onSelectionChange` - `event.detail.selectedRows`
- By clicking on a row if `type="Active` --> `onRowClick` - `event.detail.row`
- In all other cases React refs is the way to go

https://codesandbox.io/s/table-programatically-select-forked-rxnr3x?file=/src/App.js
