### ISSUE TITLE
Dialog: Cannot reopen Dialog if closed by pressing ESC

### ISSUE THREAD

**Issue by pigozzo** [SAP/ui5-webcomponents-react#2661]
**Bug Description**

The bug consist in every time you close a Dialog(modals-popovers-dialog) by pressing 'ESC' for some reason you are not be able to reopen the Dialog until you refresh the page.

Note: If you close the Dialog by pressing the _Close Button_ you are able to reopen it without problems.

This behavior also happens in the official ui5-webcomponents-react page under the link bellow:
-  https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-dialog--default-story

**Example**
*Please check the example -> [codesandbox](https://codesandbox.io/s/ui5-dialog-webcomponent-dcgqgs).*

**To Reproduce**
1. Go to code sandbox above or you can access the official Dialog example -> [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-dialog--default-story)
2. Click on '_Open Dialog_' button
3. Close the Dialog by pressing '_ESC_' button
4. Reopen the Dialog by Clicking again in the '_Open Dialog_' button
5. See error -> The dialog will not open again until you reload the page

**Expected behavior**
What I expected to happen is even if I close the Dialog by clicking on the _close button_ or by pressing '_ESC_'  button, I may open the Dialog again by pressing the '_Open Dialog_' button.

**Screenshots**
not applicable

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 
`@ui5/webcomponents-react` version: v0.22.2 also v0.20.0
Operating System: macOS Monterey
Browser: Chrome

**Additional context**
Check the sapui5 Dialog behavior in the link bellow:
-  https://sapui5.hana.ondemand.com/#/entity/sap.m.Dialog/sample/sap.m.sample.Dialog

**Comment by Lukas742** [comment]
Hi @pigozzo 

the React state is never reset when closing the dialog with the ESC key and therefore stays `true`, we overlooked that in our storybook as well, that's why it's not reopening there either. I created a [PR](https://github.com/SAP/ui5-webcomponents-react/pull/2663) that fixes the issue in the storybook and extended your [codeSandbox](https://codesandbox.io/s/frosty-feather-qnles9?file=/src/App.js) to show you what was missing.

**Comment by Lukas742** [comment]
I'm going to close this issue. 

If there are any more questions please don't hesitate to ask :)
