### ISSUE TITLE
setCustomElementsScopingSuffix will break some Styles in 0.21.5

### ISSUE THREAD

**Issue by JackieWei** [SAP/ui5-webcomponents-react#2662]
### **Bug Description**
While we are using setCustomElementsScopingSuffix to have a customized Ui5 elements, it will break some styles, for example, the with, height for show/hide header content button

### **Expected Behavior**
Styles should work(mostly should be the add custom style not working as the root cause)

### **Steps to Reproduce**
1. Build an object page
2. See the button width,height for the show/hide header content button
3. Click it to see the edge

### **Isolated Example**
https://codesandbox.io/s/setcustomelementsscopingsuffix-bug-on-addcustomstyle-8h8gpy
https://codesandbox.io/s/setcustomelementsscopingsuffix-bug-on-addcustomstyle-disable-it-3ezquz

Here you can see the code in two examples are same except the setCustomElementsScopingSuffix is commented in one example, but the look and feel is not same for the button. I consider that this is not only for button, but maybe same for all functions with addCustomStyle

### **Context**
- UI5 Web Components version: 0.21.5(can be found in Ui5)
- OS/Platform: Mac
- Browser: Chrome@98.0.4758.109 (Official Build) (x86_64)
- Affected component: Object Page

### **Log Output / Stack Trace / Screenshots**
--
### **Priority**
- [ ] Low
- [ ] Medium
- [x] High
- [ ] Very High

**Note:** The priority might be re-evaluated by the issue processor.

**Comment by Lukas742** [comment]
Hi @lenient 

I could not reproduce the issue. Are you using the version @MarcusNotheis suggested?
If so please take a look at this [codeSandbox](https://codesandbox.io/s/setcustomelementsscopingsuffix-bug-on-addcustomstyle-forked-ptwwrj?file=/src/App.js) and let me know if I overlooked something.

**Comment by lenient** [comment]
Hi @Lukas742,
I still can reproduce the issue with the code Sandbox you provided.

Please shrink the page to a small size like below and have a try, 

<img width="173" alt="image" src="https://user-images.githubusercontent.com/3073402/158300284-e9167250-b5b2-4439-ae2f-10a5c4749e96.png">

**Comment by Lukas742** [comment]
Hi @lenient 

this was a tricky one, but I guess I found the issue. It has nothing to to with the tab-bar itself, the issue is occuring because of an error inside the internally used item navigation helper and is caused by the scoped `Breadcrumbs` component. I opened an issue (https://github.com/SAP/ui5-webcomponents/issues/4899) at the UI5 Web Components repo and we will have to wait until a fix is deployed on their side.

**Comment by Lukas742** [comment]
Hi @lenient 

there is a new `@ui5/webcomponents` version ([v1.2.4](https://github.com/SAP/ui5-webcomponents/releases/tag/v1.2.4)) that should resolve this issue. You can use the version with `v0.22.4` of `@ui5/webcomponents-react`. Could you please verify that updating fixes the issue on your end as well?
