### ISSUE TITLE
Tree: Dynamic render tree component with data

### ISSUE THREAD

**Issue by rkl1994** [SAP/ui5-webcomponents-react#2679]
**Describe the documentation issue**

[ X] Documentation is unclear
- [ ] Documentation is incorrect
- [ ] Documentation is missing
- [ ] Other

**Description of the issue**
Hi expert,

While I am trying to use Tree component(https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-tree--default-story), is there a way to render this tree component with a list of data, instead of the example showed with hard-code data. Thanks

for example the data is like 
`const data = {
	"id": 0,
	"name": "",
	"nodes": [{
		"id": 1,
		"name": "aaa",
		"nodes": [{
			"id": 2,
			"name": "all bbb",
			"nodes": [{
				"id": 138011116,
				"name": "bbb 2",
				"nodes": []
			}, {
				"id": 138011268,
				"name": "bbb 3",
				"nodes": []
			}, {
				"id": 138011309,
				"name": "bbb 4",
				"nodes": []
			}]
		}, {
			"id": 138011259,
			"name": "ccc",
			"nodes": []
		}, {
			"id": 138011266,
			"name": "ddd",
			"nodes": []
		}, {
			"id": 138011877,
			"name": "eee",
			"nodes": []
		}]
	}]
}`

**Comment by Lukas742** [comment]
Hi @rkl1994 

you can for example use a recursive function to render your tree items. 
https://codesandbox.io/s/stupefied-morning-8kjh2v?file=/src/App.js

**Comment by rkl1994** [comment]
That helps me, thank you
