### ISSUE TITLE
<Text>: Error when call him inside another object

### ISSUE THREAD

**Issue by pacheco7** [SAP/ui5-webcomponents-react#269]
**Describe the bug**
A error occured when I use the <Text> object. When I use this inside of <Card> object, the React server returns the error "TypeError: Cannot read property 'sapUiFontFamily' of undefined".

**To Reproduce**
1. Go to https://developers.sap.com/tutorials/ui5-webcomponents-react-card.html
2. Follow the steps.
3. See error

**Expected behavior**
Return the text.

**Screenshots**
![image](https://user-images.githubusercontent.com/13923231/72534078-fb22ed80-3854-11ea-8c48-d5eb594ff2db.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 79.0.3945.117

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MarcusNotheis** [comment]
Hi @pacheco7 
thanks for submitting this issue.
I tried to complete the tutorial and it was working fine on my side.
Which version of the UI5 Web Components for React are you using? Could you share your `package.json dependencies`?
In addition to that, could you run these commands and check if there are any conflicting versions?
```bash
npm ls @ui5/webcomponents-react
npm ls @ui5/webcomponents-react-base
npm ls @ui5/webcomponents
``` 

Thanks!

**Comment by pacheco7** [comment]
Hi @MarcusNotheis,

> Which version of the UI5 Web Components for React are you using? Could you share your package.json dependencies?
I checked my package.json and I have only the @ui5/webcomponents-react (In the tutorial are mentioned only this), the version of him is 0.6.2.

BR

**Comment by Lukas742** [comment]
Hi @pacheco7,

could you check if you wrapped your `<MyApp />` component inside of a `ThemeProvider` in `App.js`?
Tutorial reference: https://developers.sap.com/tutorials/ui5-webcomponents-react-introduction.html#4af62014-9461-43b7-9725-7ec79cc1505c

BR
Lukas

**Comment by pacheco7** [comment]
Hi folks!

I have tried using Ubuntu (same installation of Windows) and all tutorials works fine. Maybe my first error is something wrong with node installation on Windows or compatibility...

**Comment by Lukas742** [comment]
Hi @pacheco7,

we just released version [0.7.0](https://github.com/SAP/ui5-webcomponents-react/blob/master/CHANGELOG.md) and also updated the tutorial accordingly. With the new version there comes a new, easier to use, setup procedure. Can you check if the problem still persists with the new version?

Thanks and BR
Lukas

**Comment by pacheco7** [comment]
I installed the new version (0.7.0) and the problem was solved.

Thanks

**Comment by igorlauxen** [comment]
Hello Colleagues,

I'm a newcomer for React and UI5 web components and I'm creating a project not based in the tutorial informed above.  I'm receiving the same error message "TypeError: Cannot read property 'sapUiFontFamily' of undefined" when I'm instantiating a ObjectPage. Other objects such as ShellBar and Buttons from a different page are working perfectly.

I'm using the version 0.8.5 for the ui5 webcomponent react. Below my dependencies:
    "@ui5/webcomponents": "^1.0.0-rc.5",
    "@ui5/webcomponents-base": "^0.18.0",
    "@ui5/webcomponents-icons": "^1.0.0-rc.5",
    "@ui5/webcomponents-react": "^0.8.5",
    "@ui5/webcomponents-react-base": "^0.8.5",
    "@ui5/webcomponents-react-charts": "^0.8.5"

The exception happens in the following line under the ObjectPage.jss.ts

```
objectPage: {
    width: '100%',
    height: '100%',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    isolation: 'isolate',
    whiteSpace: 'normal',
    fontFamily: parameters.sapUiFontFamily, <-- Here line 12
    backgroundColor: parameters.sapUiBaseBG
  },
```

The code that I execute to make this exception to happen is the following: 

```
import React from "react";
import { useHistory } from "react-router-dom";

import { RouteComponentProps } from "react-router";
import { ObjectPage } from '@ui5/webcomponents-react/lib/ObjectPage';
import { ObjectPageMode } from '@ui5/webcomponents-react/lib/ObjectPageMode';
import { ObjectPageSection } from '@ui5/webcomponents-react/lib/ObjectPageSection';
import { Button } from "@ui5/webcomponents-react/lib/Button";
import { ButtonDesign } from '@ui5/webcomponents-react/lib/ButtonDesign';

export const CharacterSheet: React.FC<RouteComponentProps> = (props, context) => {
  return (

    <div style={{ height: '100%', width: '100%' }}>
        <ObjectPage
            title='Object Page Title'
            subTitle='Object Page Sub Title'
            headerActions={[
                <Button key="1" design={ButtonDesign.Emphasized} onClick={navToHome}> Nav to Home Dude </Button>
            ]}
            mode={ObjectPageMode.Default}
            showHideHeaderButton={true}
            showTitleInHeaderContent={true}
            noHeader={false}
            alwaysShowContentHeader={false}
        >
            <ObjectPageSection title="Test 1" id="1">
                <div style={{ height: '200px' }}>Test1</div>
            </ObjectPageSection>
            <ObjectPageSection title="Test 2" id="2">
                <div style={{ height: '800px' }}>Test2</div>
            </ObjectPageSection>
        </ObjectPage>
    </div>
  );
}
```

Could you please advice what I need to investigate to fix this?
