### ISSUE TITLE
Analytic Table: Can not input SPACE for text area or text input

### ISSUE THREAD

**Issue by JackieWei** [SAP/ui5-webcomponents-react#2709]
**Describe the bug**
Customize a cell inside analytic table, try to input space, it won't work, you can input other chars but not space

**Isolated Example**
https://codesandbox.io/s/bug-on-edit-input-for-analytic-table-pzo0x6?file=/src/App.js 

**To Reproduce**
Goto table and try input space into text are, it won't work, try other chars, like a b c d, works, Space not working
And also onInput for text are will not listen if you input a space

**Expected behavior**
Space can be input

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` 1.2.1:
`@ui5/webcomponents-react` 0.22.4:
Operating System: MAC
Browser: Chrome

**Additional context**

**Comment by Lukas742** [comment]
Hi @JackieWei,
you can add `event.stopPrapagation()` to the corresponding callback to prevent this. Currently the space event is bubbling up to the Cell and is therefore not firing inside the text area. See [codeSandbox](https://codesandbox.io/s/bug-on-edit-input-for-analytic-table-forked-u4j8cl)

**Comment by JackieWei** [comment]
Got that. Thanks  @Lukas742  Great help.
