### ISSUE TITLE
AnalyticalTable : Not able to select the table rows using keyboard

### ISSUE THREAD

**Issue by I516406** [SAP/ui5-webcomponents-react#2720]
**Describe the bug**
Not able to select the table rows using keyboard. Only the header row's select all button is accessible. We can't access other selection buttons using keyboard.

**Isolated Example**
Example - [CodeSandbox](https://codesandbox.io/s/jolly-kapitsa-6tdyyx).

**To Reproduce**

1. Go to the [CodeSandbox](https://codesandbox.io/s/jolly-kapitsa-6tdyyx).
2. Use keyboard Tab key to navigate to the Row Selection column. 
3. The highlight will not happen over the select button for any of the rows except for the header row.

**Expected behavior**
Every row's select button must be accessible using the keyboard.

**Comment by Lukas742** [comment]
Hi @I516406 

I could not reproduce the issue. Could you please let me know what OS, Browser and respective versions you are using? Thanks.

https://user-images.githubusercontent.com/9749730/160793795-a8bdcee9-f050-4d61-ad77-108ca777eeac.mp4

**Comment by I516406** [comment]
Hi @Lukas742  

Sorry I forgot to add one property in the [CodeSandbox](https://codesandbox.io/s/jolly-kapitsa-6tdyyx) . 
I have added it now. It doesn't work after we have selectionBehaviour as RowSelector. 

Kindly check once and revert.

Regards, 
Sparsh

**Comment by Lukas742** [comment]
Ok, I see it now. This is definitely a bug, thanks for reporting!
