### ISSUE TITLE
Modals: support react 18

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents-react#2730]
The [`Modals`](https://github.com/SAP/ui5-webcomponents-react/blob/main/packages/main/src/components/Modals/index.tsx) helper class is currently the only class which is using `react-dom` APIs directly.

Currently, we don't support the new React 18 features because we're still calling `ReactDOM.render` to open the modals. 
This should be refactored to use `ReactDOMClient.createRoot()`.

Challenge:
Is there a way of keeping supporting both react 16/17 and 18?

Options:
1. Keep the current API, but the rendered modals won't support any new React 18 feature
2. Drop support for react < 18. This would allow us using the `react-dom/client` module.
3. Is there any way of checking the react-dom version and then load `react-dom/client` on demand?
    I've played around with such a pattern:
    ```js
    import * as ReactDOM from 'react-dom';
   
   let createRoot;
    if ('createRoot' in ReactDOM') {
      createRoot = require(/* webpackIgnore: true */ 'react-dom/client').createRoot;
    }
    ```

**Comment by C3ntraX** [comment]
Or use createPortal() to be more flexible without an workaround.

https://reactjs.org/docs/portals.html

**Comment by MarcusNotheis** [comment]
> Or use createPortal() to be more flexible without an workaround.
> 
> https://reactjs.org/docs/portals.html

Thanks for your input!
I fully agree that using `createPortal` should always be the preferred solution over calling `ReactDOM.render`, but I think in this case using portals is not an option.

As far as I have understood, `createPortal` renders a React Element into an arbitrary container element **during the render phase**.
Our `Modals` helper is intended to be called **outside of the rendering phase**, e.g. after you have completed an API call and want show a success or error toast to the user without the need of toggling a state in your component.
In this case we have to go for `ReactDOM.render() / root.render()` in my opinion.

Did I miss something here?

**Comment by C3ntraX** [comment]
I mean, other very popular ui libraries using createPortal too.
See Material-UI for React: https://github.com/mui/material-ui/blob/master/packages/mui-base/src/Portal/Portal.js
And the using of Portal in Modals: https://github.com/mui/material-ui/blob/master/packages/mui-base/src/ModalUnstyled/ModalUnstyled.js

**Comment by MarcusNotheis** [comment]
We're using `createPortal` in our codebase as well - but the [Modals Class](https://sap.github.io/ui5-webcomponents-react/?path=/docs/user-feedback-modals--dialog) is a static helper for showing Dialogs, Popovers and Toast in an imperative way. 
In this case, `createPortal` doesn't work: https://codesandbox.io/s/pedantic-johnson-25td83?file=/src/App.js

I see your point that the name `Modals` might be misleading - do you have any naming suggestions for our current `Modals` class to be more descriptive?

**Comment by AndrianStoikov** [comment]
Hi @MarcusNotheis,

I saw a similar issue in the react repo - https://github.com/facebook/react/issues/24347.

You can see a link to the chakra implementation and how they have dealt with this issue. In our internal implementation we use a `NotificationProvider` that handles the rendering of Toasts and MessageBoxes using the standard react rendering cycle and expose the functionality with hooks. However, the drawback is that it is not possible to render any modal outside of react.

I hope this might help you in some way.

**Comment by MarcusNotheis** [comment]
I think we've found a solution using portals instead of creating new roots, I hope we can get the PR finished this week.

**Comment by reqyou** [comment]
Hey, 
I followed your discussion and I am left with the question: should `Dialog`, `PopoverMenu`, `MessageBox` and all the others (still) be within `createPortal`?

Best, req

**Comment by MarcusNotheis** [comment]
> Hey, I followed your discussion and I am left with the question: should `Dialog`, `PopoverMenu`, `MessageBox` and all the others (still) be within `createPortal`?
> 
> Best, req

As a rule of thumb I would say yes. When not using `createPortal` it might happen that your Dialog or Popover is not visible at all or you get some really strange box shadows in your application.
