### ISSUE TITLE
[SF][0.22.2][BUG][Expect within two weeks][DynamicPageTitle]overflowbutton under responsive mobile should be displayed in an actionSheet, not a popover

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents-react#2735]
**Describe the bug**
Component: DynamicPageTitle. Under responsive mobile, when click the overflowbutton of the DynamicPageTitle, the buttons popup in a Popover, expect in an action sheet

**To Reproduce**
1. Go to [ui5/webcomponent-react doc](https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-dynamicpage--default-story)
2. Switch to responsive mobile mode
3. Click on the overflowbutton of DynamicPageTitle
<img width="578" alt="image" src="https://user-images.githubusercontent.com/27538066/161369090-a1d5f308-ac05-4978-83f8-001089e3d087.png">

4. See the buttons displayed in a popover container

**Expected behavior**
overflowbuttons should be displayed in an action sheet under responsive mobile mode:
<img width="418" alt="image" src="https://user-images.githubusercontent.com/27538066/161369195-37c67ff9-b81e-4785-8716-df02ef7b5c5e.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.2.1
`@ui5/webcomponents-react` version: 0.22.2
Operating System: any
Browser: any

**Additional context**

**Comment by Lukas742** [comment]
Hi @ksblklu 

the Toolbar used inside the `DynamicPageTitle` component is - according to UX guidelines - not supposed to be rendered as ActionSheet on phones, but stretch to the available screen width. As this behavior is currently not implemented I created a PR which will add this behavior. 
Since rendering an ActionSheet on phones does not comply with the guidelines, we chose not to implement it.

**Comment by ksblklu** [comment]
Hi Lukas, thanks for the information. And is there any ux guideline docs about the DynamicPage toolbar interaction on phones?

**Comment by Lukas742** [comment]
[Here](https://experience.sap.com/fiori-design-web/dynamic-page-layout/#responsiveness) you can find more information about this.

> Global actions stay as long as possible. If there is no key information, the title and the global actions automatically get more space. The toolbar follows the standard [toolbar overflow](https://experience.sap.com/fiori-design-web/toolbar-overview/) guidelines, and adds the available buttons to the [overflow menu](https://sapui5.hana.ondemand.com/#/entity/sap.m.OverflowToolbar/samples) from right to left.
