### ISSUE TITLE
Filterbar with custom content 

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents-react#2737]
**Is your feature request related to a problem? Please describe.**
The FilterBar component as an toolbar is nice, but it lacks in term of customization.
The FilterBar takes up the space of a fully customizable toolbar. If you want to add additional clickable icons or text buttons, you have to define an additional toolbar. However, this takes up too much space overall, so that a search input with the customized components in the additional toolbar has to be combined in a single toolbar.

**Describe the solution you'd like**
The FilterBar component should have an additional property to add custom items to the toolbar. This items should be before or after the buttons on the right side. Maybe we need an additional property for this. In terms of missing space, the buttons should have an alternative presentation as icons. This would also result an better UX, because the searchfield can be bigger.

**Describe alternatives you've considered**

**Additional context**
The question is how to avoid multiple toolbars in a column. That can be solved by combining the toolbars.

**Comment by Lukas742** [comment]
Hi @C3ntraX 

the FilterBar header section is restricted per UX guidelines, so we don't plan on making it possible to add elements to it.

**Comment by C3ntraX** [comment]
Thats a bad decision, so really nice combinations like the FilterBar + ViewSettingsDialog are not possible. I think the UX guidelines should be updated. The components doesn´t work well togehter.

**Comment by Lukas742** [comment]
Since the FilterBar should have the same behavior across all applications, I think the guidelines make sense to be honest.

Maybe you could try explaining a bit more what you want to achieve, so we can check if there's another way to implement it.
E.g. if you want to render a fully customizable header section not directly in the FilterBar, but the DynamicPage instead or create one yourself, you could set `useToolbar` to `false`. Then all default buttons like "Go" or "Adapt Filters" are moved to the bottom of the FilterBar and you can create your own toolbar.

**Comment by C3ntraX** [comment]
Ok, let me explain:

![image](https://user-images.githubusercontent.com/44802503/161829871-31e26a75-6da1-47e9-ad33-49022b09c97f.png)

This image shows the filterbar with a List and my customcomponent ObjectListItem, which will be implemented soon (My Feature Request in the base repository). 

The userstory is, that he can filter the list with multiple filters for the different attributes:   

![image](https://user-images.githubusercontent.com/44802503/161830361-f441db32-6136-4d2c-98c6-ed058ce5198d.png)

At this point the user has access to filter the content. But what if the user wants to sort the list based on different aspects, like the different options that the filters offer the user?

For this, the only possible solution is to create another toolbar above it. But another toolbar at the top would not be a good solution.

Any ideas?
I mean making the FilterBar customizable would be the best solution for me since the user wants to use the app on the phone and not always see all the filters.

**Comment by Lukas742** [comment]
I have forwarded the request to our design team. Once they have responded, I will let you know.

**Comment by C3ntraX** [comment]
Hi @Lukas742,

its ok. I don´t want to add a ViewSettingsDialog to the Filterbar anymore. 
I thought it would be an improvement for the Filterbar to add custom content and I still think so. But I came to the conclusion that the design team's opinion cannot be changed and it is better to implement such a component myself if I need it.

However thank you for your help.
