### ISSUE TITLE
FilerBar issue with Adding Multi-field

### ISSUE THREAD

**Issue by saran85** [SAP/ui5-webcomponents-react#2775]
**Describe the bug**
1. Unable to add multiple Element are component inside the filter bar. Outside HTML Elements are accept only inside of the "FilterGroupItem".
2. We can't add more filter bar inside the filterbar without broken style.
3. if use multi-filterbar the "Adapt filter" property is not showing a children fields.
4. "onToggleFilters" event is not working(Expand and Collapse)
**Isolated Example**
We use multi time adding a filerbar, please check the image we need like this:

![image](https://user-images.githubusercontent.com/95576439/162747624-6b27b215-eaf1-40d6-b6dd-e08a49288f08.png)

And also you can see the "Adapt Filterbar" with wrong value, its not show all the field:
![image](https://user-images.githubusercontent.com/95576439/162747757-5e593b1b-bdcb-45cc-a32b-4909afedfd9d.png)

And We expecting Filterbar Collapse and Expand given below image refer:
![06 04 2022_11 59 12_REC](https://user-images.githubusercontent.com/95576439/162748230-352cce8b-f37a-4ceb-b882-31566413a379.gif)

*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).*

**To Reproduce**

**Expected behavior**

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:
`@ui5/webcomponents-react` version:
Operating System:
Browser:

**Additional context**

**Comment by Lukas742** [comment]
Hi @saran85 

I'm not quite sure what you are trying to achieve. Please add a reproducible example by forking this [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34) so it's easier for us to understand your problem.
