### ISSUE TITLE
Form: Component crashes the whole app

### ISSUE THREAD

**Issue by AndrianStoikov** [SAP/ui5-webcomponents-react#2799]
**Describe the bug**
When our application is resized the `Form` component breaks the whole application

**Isolated Example**
[codesandbox](https://codesandbox.io/s/charming-frog-rwf67k?file=/src/App.js).*

**To Reproduce**
1. Go to the sandbox
2. Open the example on a full window
3. Manually resize the application
4. It break around ~1050px. You might need to resize it a couple of times

**Expected behavior**
Resizing the `Form` component should not break the app

**Screenshots**
![image](https://user-images.githubusercontent.com/21200806/163572719-0da93981-28ce-4a6e-9890-384dc25dfaf9.png)

When I run the application locally, this is where the dev tools locate the exception
![image](https://user-images.githubusercontent.com/21200806/163572314-712ac068-0b5d-4b07-bf72-ec5c9e4bd285.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: "1.2.4"
`@ui5/webcomponents-react` version: "0.22.8"
Operating System: Microsoft Edge Version 100.0.1185.39
Browser: Windows 10

**Additional context**
I managed to isolated the issue to this setup. The problem is that all of the components when used alone work fine. I managed to reproduce the behavior only in this setup.

This is pretty much the structure that our application has

**Comment by Lukas742** [comment]
Hi @AndrianStoikov 

I wasn't able to reproduce the issue (see video), but since it seems like that for some reason `getCurrentRange()` is returning `null` in that case, I added a fallback for this(See PR).

I tested it with: 
- Mac: Chrome, Firefox, Safari
- Windows: Edge, Firefox

https://user-images.githubusercontent.com/9749730/164187605-c612dd4d-498c-4b57-bb77-02cd3fad9924.mp4

**Comment by AndrianStoikov** [comment]
Hi @Lukas742,

Thanks for your support. I think the changes in the MR will do the job. It really is a strange bug.

Best,
Andy
