### ISSUE TITLE
MultiInput: broken

### ISSUE THREAD

**Issue by aglebionek** [SAP/ui5-webcomponents-react#2800]
**Describe the bug**
I'm creating a form using your components and need a one that supports multiple inputs, so I looked at MultiInput at https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-multiinput--default-story and the example is clearly broken, there's no list with options, all options are selected by default and there is no way to deselect them. Same thing when I try to use the component on my website.

**Comment by Lukas742** [comment]
Hi @aglebionek 

the MultiInput example in our docs only shows the most basic implementation. Also I'm not sure what you mean by "selected". All tokens have can be set to an active status, when they are active, the background color changes which is per default not the case here.

Here you can find an [example](https://codesandbox.io/s/multiinput-add-and-delete-yxwnjw) of how a more complex `MultiInput` implementation could look like. I would add it to our documentation as well, but unfortunately we are currently having some issues with the Storybook, which we need to resolve first.

**Comment by aglebionek** [comment]
Hey!
Thank you very much for the provided example, it's great. For some reason I assumed the component is gonna manage it's own state, that's why I thought it was broken, so I'm sorry for that. Thanks for helping, and keep up the good work!
