### ISSUE TITLE
'useI18nBundle()' may be used only in the context of a '<ThemeProvider>' component.

### ISSUE THREAD

**Issue by Arora05** [SAP/ui5-webcomponents-react#2806]
**`'useI18nBundle()' may be used only in the context of a '<ThemeProvider>' component.`**
This error is coming up in useI18nBundle.js file in 
node_modules\@ui5\webcomponents-react\node_modules\@ui5\webcomponents-react-base\dist\hooks folder 
after updating the ui5-wecomponents-react version to **v0.22.6**

**Comment by ericwangdq** [comment]
Hi @Lukas742, I also have this error when I upgrade the ui5-wecomponents-react version from **0.21.2** to **v0.22.6**, please see the attached screenshots:

**Comment by ericwangdq** [comment]
By the way: I already wrapped the app inside the ThemeProvider component.
