### ISSUE TITLE
ObjectPage: Tab Navigation - Cannot read properties of undefined (reading '_hasOwnContent')

### ISSUE THREAD

**Issue by MKraus92** [SAP/ui5-webcomponents-react#2826]
**Describe the bug**
When clicking on the TabBar Navigation Points the error "Cannot read properties of undefined (reading '_hasOwnContent')" gets thrown.

**Isolated Example**
[Isolated Example](https://codesandbox.io/s/vigorous-meadow-cxkv5i).*

**To Reproduce**
1. Go to sandbox
2. Click on Personal
3. See error

**Expected behavior**
When clicking on the TabBar Navigation Points it should be scrolled down

**UI5 Web Components for React Information**
    "@ui5/webcomponents": "1.3.0",
    "@ui5/webcomponents-fiori": "1.3.0",
    "@ui5/webcomponents-react": "0.22.8",
    "react": "18.0.0",
    "react-dom": "18.0.0",
    "react-scripts": "5.0.1"

**Comment by MKraus92** [comment]
Seems to be a bug in @ui5/webcomponents. With version 1.2.4 it still works

**Comment by Lukas742** [comment]
Hi @MKraus92 

the latest version of `@ui5/webcomponents` (1.3.0) is not compatible with our latest version yet. We are currently working on v0.23.0 which should fix this issue. Until then, please use v1.2.4 of `@ui5/webcomponents`.
