### ISSUE TITLE
i18next with ui5 I18nBundle and languagechange

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents-react#2849]
I have some problems to unify i18next with I18nBundle. 

For my app I used --template @ui5/webcomponents-react-seed. In this template you are using i18next which is not the default 
internationalization package. But I really like the i18next functionallity because it provides more features like typescript support etc.
Your template offered a way to change the language of the user, but with this way the template has missing functionality to change the language of the webcomponents as well.

For my app I need some functionalities which are currently missing or I don't know about them:
1. How can I change the language of the I18nBundle from UI5 webcomponents?
2. Can I add a listener, if the language changes?

Another question:
If I use your I18nBundle, I´m able to overwrite the default text defined in your i18n files?

Thanks!

**Comment by anfavretto** [comment]
We have the same issue on our project. If have Portuguese as my language defined on the browser, and my application is set to English the MessageBox and FilterBar (two examples that I have right now) are shown in Portuguese instead of the correct one that is English.

**Comment by C3ntraX** [comment]
Yes other examples are IllustratedMessage and UploadCollection and all default titles.

**Comment by MarcusNotheis** [comment]
Hey @C3ntraX and @anfavretto,

thanks for reporting!
You can change the language of the UI5 Web Components by calling the `setLanguage` function. You can find an example of how to do that [here](https://github.com/SAP/ui5-webcomponents-react/pull/2872/files).
