### ISSUE TITLE
[SF][0.23.0][ObjectPage] ObjectPage needs to have ObjectPageHeader

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents-react#2861]
According to wiki(will provide link separately), the ObjectPage component should have a header component(just like DynamicPage has DynamicPageHeader), and the header should have responsive styles (header should have different font size in different screen, etc. see wiki for details)

**Comment by Lukas742** [comment]
Hi @sfsf-xweb-sh 

after looking into through the specs I didn't find an indication that there should be a dedicated `ObjectPageHeader` component. Instead I think the `DynamicPageHeader` should be used by both components.

Could you please clarify where it's stated that the `ObjectPage` needs a different header component than the `DynamicPage`?

**Comment by sfsf-xweb-sh** [comment]
If ObjectPage and DynamicPage's header/title behave the same or very similar, yes we can use `DynamicPageHeader` in both components.
