### ISSUE TITLE
VariantManagement: "A file with this name already exists" error

### ISSUE THREAD

**Issue by IoValidationTechUser** [SAP/ui5-webcomponents-react#2877]
**Describe the bug**
Currently, when using the 'VariantManagement' component, whenever you try to save a new variant using the "saveAs" function it raises an error saying "A file with this name already exists" even if you don't have created a variant with that name. It is occurring at the first time you click the 'saveAs' button, but if you click it again then it is saved. Also if the user focus out (click outside the input field) before saving, the error is not displayed and the new variant is normally saved.

**To Reproduce**
1. Render the 'VariantManager' component with a default 'VariantItem'
2. Click on 'saveAs' button
3. Write a new name for the variant
4. Click on the save button, you will receive the error
5. If you click it again, then it will save normally

**Expected behavior**
When clicking at the save button, after clicking on the 'saveAs' button, it is expected that a variant is saved without errors. Of course assuming that the name is new, in other words, that there is no variant with the same name listed

**Screenshots**
Here a screenshot with the created variants under "My Views" and the modal trying to create a new variant
![VariantManagement 1](https://user-images.githubusercontent.com/58480989/165829540-d37aedfb-7f37-45a4-adf1-30ac5b145fe1.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: "1.2.3"
`@ui5/webcomponents-react` version: "0.22.4"
Operating System: Macos
Browser: Chrome

**Comment by Lukas742** [comment]
Hi @IoValidationTechUser 

I could not reproduce the error. Could you please create a codeSandbox example using this [template](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34)?
