### ISSUE TITLE
[SF][ActionSheet]: Button with iconEnd doesn't displayed correctly in responsive scenario

### ISSUE THREAD

**Issue by tandan0813** [SAP/ui5-webcomponents-react#2884]
**Describe the bug**
Hi Colleague,
I am a member of Shanghai WEF team. When in the responsive mobile scenario, if we add "iconEnd=true" to the Button component, then the content of this button will have attribute"flex-direction: row-reverse", which is not in expectations. Could you please take a look at it? Thanks!

**Isolated Example**
Here is an isolated example if possible by forking: https://codesandbox.io/s/elastic-kilby-vlx2mn?file=/src/App.js

**Expected behavior**
In responsive scenario, text in the button still displayed from left to right

**Screenshots**
<img width="490" alt="image" src="https://user-images.githubusercontent.com/10113427/165873676-0b6fee4c-3ac8-4a26-a099-dee3ec56ca28.png">

**Comment by Lukas742** [comment]
Hi @tandan0813 

this behavior only happens internally in our ActionSheet. If you need to change the alignment of the content of the button you can use the [part](https://developer.mozilla.org/en-US/docs/Web/CSS/::part) pseudo element `"button"`.

**Comment by tandan0813** [comment]
Hi @Lukas742 
Thanks for your info
