### ISSUE TITLE
Stange behavior of iconbutton in overflow

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents-react#2892]
**Describe the bug**
If you forgot to listen for the onOverflowChange of the toolbar, you´ll see the icons in a strange width out of context

**Isolated Example**
https://codesandbox.io/s/priceless-dan-6oo9s1?file=/public/index.html

**To Reproduce**
1. Go to https://codesandbox.io/s/priceless-dan-6oo9s1?file=/public/index.html
2. Click on the overflow button
3. See error the overflowbuttons

**Expected behavior**
The overflowbuttons should remain its default behavior.
To generally avoid this case, it is possible to define an overflowtext?

**Screenshots**
![image](https://user-images.githubusercontent.com/44802503/165960719-e9daa395-66d8-494e-99d6-51772acd4bd1.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:
`@ui5/webcomponents-react` version:
Operating System:
Browser:

**Additional context**

**Comment by C3ntraX** [comment]
Hello @Lukas742 ,

that was fast wow.
Is there any chance to define an overflowtext for icon only buttons?

**Comment by Lukas742** [comment]
Hi @C3ntraX 

currently not, we will probably have to create a new component similar to the UI5 [OverflowToolbarButton](https://ui5.sap.com/#/api/sap.m.OverflowToolbarButton) for this.

**Comment by Lukas742** [comment]
Here you can find the feature request for the OverflowToolbarButton: https://github.com/SAP/ui5-webcomponents-react/issues/2900
