### ISSUE TITLE
Input onChange conflict with Formik library which causes template seed error and is confusing

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents-react#2911]
**Describe the bug**
You have changed the default behavior of the onChange event from firing on every keystroke to onBlur or Enter. This causes a conflict with the popular form library Formik, which is used in your template seed. 
The problem is this:
If you want to use the field component of Formik that is used in your template seed, Formik automatically assigns its own onChange event to the onChange event defined in the input component, which is wrong. The result is that you have to manually assign onChange to onInput, which is not very clear and confusing. I had to search for this bug for a very long time, because it causes problems with invalid states, often the last keystrokes were not registered.

**Isolated Example**
If you want, I can add an codeexample with the Formik library.

**To Reproduce**

**Expected behavior**
I think, it would be better, if you rename onInput to onChange and onChange to something other. To avoid confusing react users and avoid define an additional Input component only for the assignment from onChange to onInput.

Additional, you should fix your template seed.

**Screenshots**
![image](https://user-images.githubusercontent.com/44802503/166636049-5c087212-29d6-4fe7-b317-a2c77a7d892a.png)

Fixed:
![image](https://user-images.githubusercontent.com/44802503/166646188-c4842f0c-f24b-4272-9e4e-f7cda6403480.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:
`@ui5/webcomponents-react` version:
Operating System:
Browser:

**Additional context**

**Comment by C3ntraX** [comment]
This also applies to all onChange events used in inputs.

**Comment by MarcusNotheis** [comment]
Thanks for bringing this up!
I totally agree that this behaviour is super confusing, and we'll fixed the examples in our seed to use `onInput` instead of `onChange`. In addition to that, we added some notes in https://github.com/SAP/ui5-webcomponents-react/pull/2918 to all input `onChange` events that they behave differently from the standard react `onChange` event.

Anyhow, I've still some doubts about renaming the `onInput` event to `onChange` because this would basically violate our promise that our components are just wrappers around the UI5 Web Components - do you think this is a feasible solution as well?

**Comment by C3ntraX** [comment]
Hi @MarcusNotheis 
I think its ok this way. I understand, that this should only be a wrapper. Another thing I didn´t be aware of. My solution was wrong unforunalety. 
`{...field}`
`onInput={field.onChange}` 

should changed to 

`{...field}`
`onInput={onChange}` 

so spread the onChange out of the field or your will have the old behaviour as well.
so currently its
`{...field}`
`onInput={field.onChange}` 
`onChange={field.onChange}`

you know what I mean?

**Comment by MarcusNotheis** [comment]
Sorry for the late reply.
Our current solutions looks like:
``` jsx
const { onChange, ...formikProps } = field;

return (
    <ui5-input
        {...props}
        {...field}
        {...formikProps}
        onInput={onChange}
      />
);
```

So we're basically not binding the `onChange` event because in my understanding this would be duplicate to `onInput`.
I'm not sure whether this is now fitting your proposal?

**Comment by C3ntraX** [comment]
Hi @MarcusNotheis,

```
const { onChange, ...formikProps } = field;

return (
    <ui5-input
        {...props}
        {...formikProps}
        onInput={onChange}
      />
);
```
The output of the formikProps to the input assigns the onBlur event.
Formik uses both onBlur and onChange to trigger validation.
But you extend the onBlur event with the Enter key called onChange as I understand it.
Because of this, it would make more sense to bind onBlur to onChange to trigger validation when the user presses enter
This is basically missing from your code.

Finally, you're right, when the user types and focuses on another element, both the onBlur and onChange events fire. But this is a formik validation to face every possible situation. The same thing I want to archive when we press enter to avoid potential problems.
```
const { onChange, onBlur, ...formikProps } = field;

return (
    <ui5-input
        {...props}
        {...formikProps}
        onInput={onChange}
        onChange={onBlur}
      />
);
```
