### ISSUE TITLE
Highlight AnalyticalTable

### ISSUE THREAD

**Issue by giladvidal** [SAP/ui5-webcomponents-react#2921]
Hello,
I have a table with a button in one of the cells. When clicking the button, it open a window and I also want the relevant row in the table to be highlighted.

Appreciate ideas :)
Thanks!

            <AnalyticalTable
                header={
                    <FlexBox
                        className="m-2.5 w-full"
                        justifyContent="SpaceBetween"
                    >
                        <Title
                            level="H2"
                            style={{ paddingLeft: '5px' }}
                            className="font-sapFontFamily font-black leading-5 text-base text-[#1D2D3E]"
                        >
                            <b>Top 20</b>
                        </Title>
                    </FlexBox>
                }
                columns={[
                    {
                        Header: 'Name',
                        accessor: 'class_desc',
                        disableResizing: true,
                    },
                    {
                        Header: 'Suppliers',
                        accessor: 'supplier_count',
                        disableResizing: true,
                        width: 90,
                        hAlign: 'Right',
                    },
                    {
                        Header: '% Total',
                        accessor: 'total_perc',
                        disableResizing: true,
                        width: 120,
                        hAlign: 'Right',
                    },
                    {
                        Header: '',
                        id: 'supplier-actions',
                        width: 70,
                        disableResizing: true,
                        Cell: ({ row }) => {
                            return (
                                <FlexBox>
                                    <Button
                                        icon="edit"
                                        onClick={() => {
                                            navigate(
                                                `? open some page`
                                            )
                                        }}
                                    />
                                </FlexBox>
                            )
                        },
                    },
                ]}
                data={currCategories}
                loading={loading}
                visibleRows={numRows.toString()}
            ></AnalyticalTable>

**Comment by Lukas742** [comment]
Hi @giladvidal 

you can use `withNavigationHighlight` and `markNavigatedRow` to achieve this.

[codeSandox](https://codesandbox.io/s/navhighlight-a-table-r7fl64)

**Comment by giladvidal** [comment]
Thanks @Lukas742 
How is it possible to highlight the row in some color instead?

**Comment by Lukas742** [comment]
The navigation indicator column is implemented as described by our global design guidelines. It is not recommended to change that to keep a consistent look and feel across applications. That said, could you elaborate a bit more what you want to achieve? Do you want to change the color of the indicator on the right, or do you want to change the background color of the row?

**Comment by giladvidal** [comment]
Thanks @Lukas742 , I'll double check with the design team.
However, the plan is for background color of the row:
![image](https://user-images.githubusercontent.com/56625024/167382721-e4f57f2e-b224-47b3-a1b1-dbaf587d6aae.png)

**Comment by Lukas742** [comment]
This looks more like the default selection behavior to me, if this is really meant for indication of navigation only, this could be confusing when working with tables in different applications.

To change the background color of the row you can create a plugin hook and add/overwrite styles there. 
[codeSandbox](https://codesandbox.io/s/navhighlight-a-table-forked-m50rd6?file=/src/App.js)

**Comment by giladvidal** [comment]
Thanks @Lukas742 for helping in both options.
