### ISSUE TITLE
@ui5/webcomponents-react: unit testing issue - Jest cannot parse @ui5/webcomponents-react files

### ISSUE THREAD

**Issue by dimalapeto** [SAP/ui5-webcomponents-react#2926]
**Describe the bug**
Unit testing fails because of known issue (see screenshot below):
```
({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import * as AnalyticalTableHooks from './components/AnalyticalTable/pluginHooks/AnalyticalTableHooks';
SyntaxError: Cannot use import statement outside a module
```
I tried to implement solutions of https://github.com/SAP/ui5-webcomponents/issues/1176 and https://github.com/SAP/ui5-webcomponents-react/issues/150 issues, but haven't any success - it thows an error with other packages.

**Isolated Example**
Project's repo is in SAP corporate GitHub, so I can send you a link to it.

**To Reproduce**
_yarn test_

**Expected behavior**
Expecting rendered components for testing purposes.

**Screenshots**
![image](https://user-images.githubusercontent.com/18643415/167376575-f6fe20b0-ca6c-44ac-a7a2-380ffbd2914b.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: "^1.3.1"
`@ui5/webcomponents-react` version: "0.23.1"
Operating System: Windows 10 Enterprise version 21H1 build 19043.1645
Browser: Google Chrome Version 101.0.4951.41 (Official Build) (64-bit)

**Comment by C3ntraX** [comment]
The same problem is has Mode: "Multiselect" too and maybe the others as well

**Comment by dimalapeto** [comment]
UPDATE:
I've done all by guide here https://sap.github.io/ui5-webcomponents-react/?path=/docs/knowledge-base--page and what i have now:
![image](https://user-images.githubusercontent.com/18643415/167833344-4764a4bf-1350-49e0-ba0d-a60514e2ead4.png)
`react-jss` is in dependencies to `@ui5/webcomponents-react`.
Do anybody know the solution?

**Comment by dimalapeto** [comment]
UPDATE2: Issue fixed

**Comment by felixspringer** [comment]
@dimalapeto could you plz provide information about how you fixed that issue?
