### ISSUE TITLE
List: SingleSelect Mode: Controlled selected state not working and causes state to be unsyncroninized

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents-react#2928]
**Describe the bug**
If the list has one element with selected state in mode "SingleSelect" and the user clicks another item in the list, the item gets selected no matter if I have selected the item. This causes problems, if you want to prevent the user selecting the item for example, if the user has unsaved data and you want to prevent the user to change the site. Popular example are navigation blocker.
If you do not react to the click of the item, the state within the listchanges the selection, but you don´t and dont want to. 

**Isolated Example**
https://codesandbox.io/s/hopeful-alex-oxisrq?file=/src/App.js:376-388

**To Reproduce**
1. Go to https://codesandbox.io/s/hopeful-alex-oxisrq?file=/src/App.js:376-388
2. Click on a StandardlistItem
3. See that the StandardlistItem gets selected, no matter if selected.

**Expected behavior**
If a user want to change a state of a component. The component should not ignore or overwrite the selected state of other component. If I have a controlled component, than I need the be the owner of the selected state.

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:
`@ui5/webcomponents-react` version:
Operating System:
Browser:

**Additional context**

**Comment by Lukas742** [comment]
Hi @C3ntraX 

there's already an [issue](https://github.com/SAP/ui5-webcomponents/issues/4883) in the UI5 Web Components repo covering this topic. Please feel free to add any missing or additional information there.
