### ISSUE TITLE
AnalyticalTable: in TreeTable mode the subRows don't have properties and methods 

### ISSUE THREAD

**Issue by Feodorius** [SAP/ui5-webcomponents-react#2937]
**Describe the bug**
Hi!
I am using AnalyticalTable with TreeTable and MultiSelect modes. I've noticed that **when the subRows are collapsed**, their properties and methods are missing.

**Isolated Example**
https://codesandbox.io/s/lucid-raman-mmhqgr?file=/src/App.js

**To Reproduce**
1. Go to https://codesandbox.io/s/lucid-raman-mmhqgr?file=/src/App.js
2. In the list of categories select Hardware category **(the subRows should be collapsed)**
3. The list of sortedRows will appear in the console. (It is applicable for all types of 'rows', not only sortedRows)
4. The first item will show the Hardware category object, where we can see all the properties we can use: 
![image](https://user-images.githubusercontent.com/39455164/167957441-778f7b77-b680-4e50-b166-8b2f6958e2c5.png)

5. But when we open subRows property with the array of children, we cannot find a lot of properties and methods:
![image](https://user-images.githubusercontent.com/39455164/167958119-b08b6c07-76a9-4e7a-ae28-d30b62aa61ee.png)

**When the subrows are expanded, the row objects have all the needed properties.**

**Expected behavior**
All rows and subRows have the same properties and methods.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.3.1
`@ui5/webcomponents-react` version: 0.23.1
Operating System: Windows
Browser: Chrome

**Additional context**

**Comment by Lukas742** [comment]
Hi @Feodorius 

subRows are not "prepared" initially for perfomance reasons. If you need all properties of the rows right away, you can prepare them yourself by calling the react-table instance function `prepareRow(row)`. See [codesandbox](https://codesandbox.io/s/long-hill-75rnd5?file=/src/App.js).
If you only need to change a row's state (e.g. `expanded`, `selected`, etc.) you could also use the respective instance function for that. (e.g. `toggleRowExpanded("1.0.0")`, `toggleRowSelected(rowId: string)`, etc.)

**Comment by Lukas742** [comment]
You are right, I overlooked that only the methods are added when preparing a row. 

This functionality is unfortunately the default behavior of the underlying `react-table` (see [here](https://codesandbox.io/s/naughty-sky-00780s?file=/src/App.js)). Could you elaborate a bit on what you are trying to achieve? Maybe there's another solution which doesn't involve the `isSelected` property of sub-rows.

**Comment by Lukas742** [comment]
Hi @Feodorius 

if I understood correctly the main problem here is, that you cannot get all selected rows, right?
In that case you can use the internal table state to achieve this. I created another codeSandbox that should explain this more: https://codesandbox.io/s/sharp-butterfly-45x9cg?file=/src/App.js
