### ISSUE TITLE
MultiInput : Readonly is behaving wrongly for horizon theme

### ISSUE THREAD

**Issue by Arora05** [SAP/ui5-webcomponents-react#2957]
**Readonly mode in MultiInput for horizon theme**
For the Horizon theme MultiInput read-only mode is just showing a dotted line instead of the whole border, Can we have it like it is expected without read-only.

![image](https://user-images.githubusercontent.com/89779778/168794643-bc3c394d-a0e0-4295-822b-d4592b72ea0e.png)

**Comment by Lukas742** [comment]
Hi @Arora05 

the single dotted border line is implemented by design for the `readonly` state of theMultiInput, otherwise it's hard for users to determine whether the component is interactive or not.
