### ISSUE TITLE
[sf][ActionSheet][a11y]: Repetitive announcements in the list elements under ActionSheet

### ISSUE THREAD

**Issue by tandan0813** [SAP/ui5-webcomponents-react#2962]
**Describe the bug**
Hi, colleague, when the `ActionSheet` is opened, the list of items is read repeated twice by screenreader, the announcement seems a little repetitive(Attached snapshots for more details).
'This is my super long text!'-it reads "3 of 3 This is my ..." and then "This is my..."
example: https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-actionsheet--default-story 
<img width="830" alt="image" src="https://user-images.githubusercontent.com/10113427/169063225-e54d3bab-3aba-4c6e-92e8-a7a022054ef0.png">

**Isolated Example**
[*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).*](https://codesandbox.io/embed/affectionate-lichterman-5ee1o2?fontsize=14&hidenavigation=1&theme=dark)

**Expected behavior**
Ref:https://ui5.sap.com/#/entity/sap.m.ActionSheet/sample/sap.m.sample.ActionSheet
For this ref, it never announced repetatative.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.3.1
`@ui5/webcomponents-react` version: 0.23.2
Operating System:
Browser:

**Comment by MarcusNotheis** [comment]
Currently blocked by https://github.com/SAP/ui5-webcomponents/issues/5310
