### ISSUE TITLE
Show Code Preview in Docs is broken

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents-react#2966]
Our documentation is showing `args => <COMPONENT {...args} />` for almost every component.
This needs to be fixed and the args need to expand again.

**Comment by MKraus92** [comment]
Hi @MarcusNotheis,
that is what i meant in Issue [#2860](https://github.com/SAP/ui5-webcomponents-react/issues/2860#issue-1217055951)
