### ISSUE TITLE
[TabContainer+ AnalyticalTable]: Error when navigate between tabs

### ISSUE THREAD

**Issue by pacheco7** [SAP/ui5-webcomponents-react#298]
**Describe the bug**
When use a AnalyticalTable inside Tab component and is not set as "selected", the table starts compressed, when this tab set as "selected", the table starts okay.

**To Reproduce**
1. See this [code snippet](https://gist.github.com/pacheco7/0d1ea5cb7d6d868c1dcb3a31d80fc6dd)

**Expected behavior**
Show the table as expanded view, regardless of whether it is selected or not.

**Screenshots**
With "selected" parameter:
![image](https://user-images.githubusercontent.com/13923231/73681521-45053380-469d-11ea-9f99-8d32069a34b5.png)

Without "selected" parameter:
![image](https://user-images.githubusercontent.com/13923231/73681470-269f3800-469d-11ea-8a0d-583505901f87.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 79.0.3945.130

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vbersch** [comment]
Hi @pacheco7 ,

Could you please try with `@ui5/webcomponents-react@0.7.4-dev.10` and see if the errror persists?

best regards,
Viktor

**Comment by pacheco7** [comment]
Now I got new error:

![image](https://user-images.githubusercontent.com/13923231/73767286-07181600-4756-11ea-8118-45ee2aed3dbc.png)

**Comment by MarcusNotheis** [comment]
Do you have explicitly installed `@ui5/webcomponents-react-base`? If so, can you try to install `@ui5/webcomponents-react-base@0.7.4-dev.6` as well?

**Comment by pacheco7** [comment]
Hi @vbersch  and @MarcusNotheis!

Now works.

**Comment by MarcusNotheis** [comment]
We just released `@ui5/webcomponents-react@0.8.0` as the new latest version, so automatic dependency resolution should be fine again :)

**Comment by pacheco7** [comment]
> We just released @ui5/webcomponents-react@0.8.0 as the new latest version, so automatic dependency resolution should be fine again :)

Cool, I'll install this version. Thanks :)

**Comment by pacheco7** [comment]
Works fine in @ui5/webcomponents-react@0.8.0.

Closing this issue.

Thanks.
