### ISSUE TITLE
[SF][0.23.2]DynamicPage]add accesibleName for DynamicPageTitle & DynamicPageHeader

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents-react#2989]
Hi team, 
For page accessibility, we consider DynamicPageTitle and DynamicPageHeader as a region, and want to set an `aria-label` & `role="region"` attribute for screen reader to read it. So it is possible that these two component can provide an `accessibleName` attribute to let us configure the `aria-label` of it?
If you have any recommendation, we would like to hear more.
Thanks.

**Comment by ksblklu** [comment]
Hi @Lukas742 , thanks for your quick reply! The reason we raised this feature request, is we want to configure these a11y attribute using consistent attribute names. For example: the a11y attributes of `List` component, using `accessibleName` `accessibleRole` to configure a11y attributes:
<img width="1428" alt="image" src="https://user-images.githubusercontent.com/27538066/170213010-0e852a59-1c39-4ca2-888b-245e59df92ba.png">
And we would like to use consistent prop names in other component. Is that a proper way to coding?

**Comment by Lukas742** [comment]
Hi @ksblklu 

The "accessible" props like `accessibleName` are only used if there's a need to set or modify the respective a11y attribute of an element inside the shadow root (e.g.: `aria-label`). As this is not the case here, I don't see the need to add another prop that does exactly the same as the native a11y attributes. 
This is not only applicable for UI5 Web Components React but for standard UI5 Web Components as well, the `ui5-label` for example also has no dedicated "accessible" attributes as you can use all native a11y attributes instead.

**Comment by ksblklu** [comment]
@Lukas742 Sounds reasonable, thanks for your answer, I'll use native a11y attributes directly.
