### ISSUE TITLE
Badge on ShellBarItem

### ISSUE THREAD

**Issue by vinniimiranda** [SAP/ui5-webcomponents-react#299]
Hello, i am using this library to build an application similar of a e-commerce.

The problem is that i wat to show the amount"products" there are in the cart, but for this i need to display the number side to the ShellBarItem, which is not possible at the moment.

So i would like to ask if you guys can help with that.

Here's an example of  the code: 
``<ShellBarItem
          icon="download"
          onItemClick={() => history.push("/box")}
        />`` 

It would be nice if we can pass an number and this value be displaied side to the icon, like this:
``<ShellBarItem
          icon="download"
          amount={10}
          onItemClick={() => history.push("/box")}
        />``

**Comment by MarcusNotheis** [comment]
Hi @vinniimiranda - thanks for submitting this issue.
As the `ShellBarItem` is a UI5 Web Component and not 'directly' built by us I have opened a corresponding issue for the UI5 Web Components Project: https://github.com/SAP/ui5-webcomponents/issues/1177

**Comment by vinniimiranda** [comment]
Thanks, i'll be waiting.

**Comment by vinniimiranda** [comment]
Hi!

They already have implemented this feature on  UI5 Web Component.

**Comment by MarcusNotheis** [comment]
Hey :) yes, they merged it yesterday and as soon as they release their next rc we are going to update as well

**Comment by vinniimiranda** [comment]
Sure, thanks a lot!

**Comment by MarcusNotheis** [comment]
Released in `0.9.0-rc.9`
