### ISSUE TITLE
Variant Management: After Variant is selected the popover should be closed.

### ISSUE THREAD

**Issue by nidhi0104** [SAP/ui5-webcomponents-react#3011]
After variant is selected the popover is not getting closed by itself, for closing it, requires to click somewhere outside the popover.

1. Go to Variant Management
2. Click on list
3. Select one variant

**Expected behavior**
The popover should be closed by itself after selecting the variant.

**Screenshots**
https://github.tools.sap/crp/crp-manage-order-proposal-ui/pull/126

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:~1.3.1
`@ui5/webcomponents-react` version:0.24.0
Operating System:Mac OS
Browser:Chrome

**Comment by Lukas742** [comment]
Hi @nidhi0104 

you can use the `closeOnItemSelect` prop to achieve this. See [docs](https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-variantmanagement--default-story).
