### ISSUE TITLE
Analytical Table: Checkbox selection (Select All)

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents-react#302]
**Is your feature request related to a problem? Please describe.**
The `selectionMode` property for Analytical Table has a `MULTI_SELECT` option, but it involves clicking the row. Because of this, the `AnalyticalTable` does not have an option to select all the rows at once.

**Describe the solution you'd like**
Use checkboxes for selection, as well as a "Select All" checkbox at the top-left of the table as can be seen here in the design guidelines. https://experience.sap.com/fiori-design-web/analytical-table-alv/
![image](https://user-images.githubusercontent.com/8508119/73802115-6afc0800-4771-11ea-83f2-b2ff7423ac30.png)

**Describe alternatives you've considered**
I've tried manually adding a column of checkboxes, as well a checkbox for the header, but it becomes very messy and requires quite a bit of custom coding that is prone to error.

**Additional context**
None.

**Comment by MarcusNotheis** [comment]
Released in `@ui5/webcomponents-react@0.8.2`

**Comment by agauyeung** [comment]
Thank you for the quick turnaround! :)
