### ISSUE TITLE
Menu: component isn't exported

### ISSUE THREAD

**Issue by Scorze** [SAP/ui5-webcomponents-react#3022]
**Describe the bug:** 
When I try to import the Menu component, I get the error "Module '"@ui5/webcomponents-react"' has no exported member 'Menu'" in VSCode.

![menu_not_exported](https://user-images.githubusercontent.com/10748796/171567688-a6f40fe4-d8db-4af5-a241-eb1420e38f94.jpg)

Importing it from "@ui5/webcomponents-react/dist/webComponents/Menu" seems to work.

**Comment by MarcusNotheis** [comment]
Thanks for reporting, @Scorze!
Which version of UI5 Web Components React are you using?

**Comment by Scorze** [comment]
@MarcusNotheis 
The latest right now - version 0.25.0

**Comment by MarcusNotheis** [comment]
Which setup are you using? `create-react-app` or a custom setup?
I just tried to create a codesandbox and it's working fine there: https://codesandbox.io/s/strange-hofstadter-kc6ddv?file=/src/App.js

**Comment by Scorze** [comment]
@MarcusNotheis It's the create-react-app but actually I deleted my ui5 folder in node_modules and re-downloaded it and that fixed the problem. Thanks a lot for the time, not sure what originally caused it but it's all working now.

**Comment by MarcusNotheis** [comment]
You're welcome!
Good to hear that you were able to solve the issue 🙂
