### ISSUE TITLE
AnalyticalTable: Mouse wheel scrolling not working when mouse is in the same position

### ISSUE THREAD

**Issue by vostvesh** [SAP/ui5-webcomponents-react#3024]
**Describe the bug**
When I try to scroll the mouse wheel without changing the position of the mouse cursor, the scrolling stops. After that, the mouse wheel does not work in any direction. If I change the mouse position (move the cursor) the scrolling continues.

**Isolated Example**
https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable--default-story

**To Reproduce**
1. Open AnalyticalTable (table should be scrollable)
2. Scroll with wheel (middle) button without changing mouse postion.
3. Scroll stops

**Expected behavior**
Scrolling should work if turn the mouse wheel in any direction (up and down), if the position of the mouse cursor has not changed

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 0.25.0
`@ui5/webcomponents-react` version: 0.25.0
Operating System: Windows 10
Browser: Google Chrome (64-bit) Version 102.0.5005.63

**Comment by Lukas742** [comment]
Hi @vostvesh 

I could not reproduce the described behavior (I tested it with Windows and Mac os). Could you elaborate a bit more what your steps are and if possible add a video showing the issue?

https://user-images.githubusercontent.com/9749730/171604506-44d01b38-f11c-448a-a9a2-e61ecc065b3b.mp4

**Comment by MarcusNotheis** [comment]
Looks like we are dealing with a couple of upstream issues here:
Reported in the virtualization library:
- https://github.com/TanStack/virtual/issues/293
- https://github.com/TanStack/virtual/issues/292

And even reported as chrome bug: https://crbug.com/1331231

**Comment by Lukas742** [comment]
Hi @vostvesh 

could you check whether the behavior still occurs for you with this [codeSandbox](https://codesandbox.io/s/defaulttable-forked-jpec1s?file=/src/App.js)? I added the `will-change` css property to the respective container that holds the virtual items and a user suggested that this might help here. Unfortunately (or luckily - depends on the context), I still cannot reproduce this issue with the latest Chrome version (v102.0.5005.61) and with different mouses, so I wasn't able to check whether this is really working.

**Comment by vostvesh** [comment]
Hi, yes the issue is still reproduced and not only for me. I asked my colleague to reproduce this bug and make videos. So you can see
![mouse-scroll1](https://user-images.githubusercontent.com/8273105/171812893-a5528953-f85b-4dd2-beb4-95f7ff923e2c.gif)
![mouse-scroll2](https://user-images.githubusercontent.com/8273105/171812902-37de761a-db1e-40a5-9def-b44e5b037c4d.gif)

**Comment by Lukas742** [comment]
Thanks for the videos. As the `will-change` property doesn't seem to fix the issue as well, I guess we have to wait for the upstream issues to be fixed.

**Comment by MarcusNotheis** [comment]
The issue should be fixed in Chrome Version >= 103.0.5060.53.
Can you please try checking your [chrome version](chrome://version) and try again whether is the issue is now fixed?

**Comment by vostvesh** [comment]
After fix I can't reproduce issue. Closed
