### ISSUE TITLE
How to expand and collapse all row at once which is grouped in ui5 analytical table?

### ISSUE THREAD

**Issue by kundarsowjanya** [SAP/ui5-webcomponents-react#3025]
I'm using ui5 web component in my application and I'm using Aalytical Table.If I select group by for a particular column. Is there a way that I can collpse or expand all row at once? Instead of clicking single row every time to collapse or expand. Could anyone please suggest the soultion.

 <AnalyticalTable
              data={data}
              columns={Columns}
              filterable
              groupable
              sortable
              onGroup={onGroup}
            />

**Comment by Lukas742** [comment]
Hi @kundarsowjanya 

you can use the instance method `toggleAllRowsExpanded()` for this. See [codeSandbox](https://codesandbox.io/s/defaulttable-forked-utyt9t?file=/src/App.js)
