### ISSUE TITLE
List: noDataText is visible although the list contains items

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents-react#3045]
### **Bug Description**
In my application I use the List component to render all notifications as CustomListItem in the List.
If I reload the page, and add a notification to the List, the list still renders the noDataText although the list contains items.
The popover itself will be mounted once and never unmounts.
Once I unmount and mount the List, the noDataText does not appear anymore. 

Unfortunately I was unable to reproduce the problem but I can provide screenshots of my code if it helps.

Additional, I discovered the same problem with UploadCollection. But I couldn't reproduce the steps there either.

### **Expected Behavior**
If the List has items, then the list shouldn´t render noDataText.

### **Steps to Reproduce**
1. Reload the page
2. Add notification to the popover notificationslist
3. Open the popover (the popover and the list does not unmount)
4. See, that the List contains CustomListItems with visible noDataText.

### **Isolated Example**
I was unable to reproduce the steps

### **Log Output / Stack Trace / Screenshots**
![image](https://user-images.githubusercontent.com/44802503/172834504-a7871198-31f5-4f35-bba8-cefc22bd3e58.png)
![image](https://user-images.githubusercontent.com/44802503/172834816-76c8c5f8-ee6d-46ab-8a22-0f4371d7d60e.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.4.0
`@ui5/webcomponents-react` version: 0.24.0
`reacct` version: 18.1.0
Operating System: Windows
Browser: Chrome

**Additional context**

**Comment by MarcusNotheis** [comment]
Thanks for reporting. That looks like a really weird error to be honest. 
I also tried to reproduce using codesandbox but was not successful with that as well: https://codesandbox.io/s/dazzling-beaver-7vgqq9?file=/src/App.js

Is it reproducible in your application? 
Can you try to replace the `noDataText` with a static text? and how are the `classes` generated? are you using `react-jss` with dynamic styles?
