### ISSUE TITLE
Shellbar onClickLogo doesn't work on mobile device

### ISSUE THREAD

**Issue by vinniimiranda** [SAP/ui5-webcomponents-react#305]
Hello, i am having an issue when the user "clicks" the logo on mobile device.

The expected behavior should be execute the callback function insde the onLogoClick prop.

Im my case this is the code: 
``
<Shellbar.... onLogoClick={() => history.push('/list')}>....</Shellbar>
``

At the moment this is not working for me, could you guys help with that?

**Comment by MarcusNotheis** [comment]
Hi @vinniimiranda 
thanks for reporting that issue. As the `ShellBar` is sourced from the underlying `@ui5/webcomponents` package I have created a corresponding issue in their repo: https://github.com/SAP/ui5-webcomponents/issues/1188

**Comment by MarcusNotheis** [comment]
Released in `@ui5/webcomponents-react@0.9.0-rc.9`
