### ISSUE TITLE
[SF][0.23.2][I18nProvider] useI18nBundle will throw error after loading a mini app which is also including ui5-wc-react

### ISSUE THREAD

**Issue by i323808** [SAP/ui5-webcomponents-react#3061]
**Describe the bug**
useI18nBundle will throw following error('useI18nBundle()' may be used only in the context of a '<ThemeProvider>' component) after injecting a mini app which is also including ui5-wc-react.
The possible root cause is https://github.com/SAP/ui5-webcomponents-react/blob/f74d47b2b20e004c8d9abf4ae02e4b607e00fad4/packages/main/src/internal/I18nProvider.tsx#L26.

**Isolated Example**
https://codesandbox.io/s/i18nprovider-ijcgx1

**To Reproduce**
1. Go to https://codesandbox.io/s/i18nprovider-ijcgx1
2. Click on 'Open ActionSheet' button
3. Click on 'Click me to inject a mini app'
4. If there is syntax error: Unexpected token '<', please click the 'X' button on the top right corner to ignore it
5. Click on 'Open ActionSheet' button again
6. See error: 'useI18nBundle()' may be used only in the context of a '<ThemeProvider>' component,
    and the page turns into blank

**Expected behavior**
The page should not turn into blank.

**Screenshots**
<img width="663" alt="I18nProvider" src="https://user-images.githubusercontent.com/30744017/173554461-7c017f91-95ef-443a-9c92-a555f8127468.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.3.1
`@ui5/webcomponents-react` version: 0.23.2
Operating System: macOS Monterey version 12.4
Browser: Chrome Version 102.0.5005.61 (Official Build) (x86_64)

**Additional context**

**Comment by i323808** [comment]
Hi @Lukas742 ,

I saved the draft. Please try again. Bad VPN.

BR,
Jane

**Comment by Lukas742** [comment]
I needed our VPN to load the ressources, now I can reproduce the issue. 

Did you make sure that all of your micro frontends are wrapped inside the `ThemeProvider` component? If so please contact me internally so I can take a look at the implementation.
