### ISSUE TITLE
Form: Inner grid occupies only 50% of available space

### ISSUE THREAD

**Issue by maitefdupont** [SAP/ui5-webcomponents-react#307]
**Describe the bug**
When using the `<Form>` component, it creates two nested grids. The first occupies 100% of the available space, but the child grid occupies only 50%. 

**To Reproduce**
Use the form component on something like this:
```
<Form >
    {Object.entries(data).map(([key, value]) => (
        <FormItem key={key} labelText={`${value.i18nTag}:`}}>
            <Text wrapping>{value.metadata}</Text>
        </FormItem>
    ))}
</Form>
```

**Expected behavior**
I'd like the form to take all available space, or to allow me to configure the width. I have tried to set `style='width: 100%'`, but this sets the width of the outer grid, which is already correct. I'm not sure if the calculation of width is giving this result due to some other property of our project, so maybe just some guidance would solve the issue :)

**Screenshots**
Outer grid occupies all available space
![image](https://user-images.githubusercontent.com/1753795/74046478-63c13e00-49ad-11ea-9083-489595012a0b.png)

Inner grid occupies only 50% of available space
![image](https://user-images.githubusercontent.com/1753795/74046507-7176c380-49ad-11ea-84f2-cf393ce5602b.png)

Rule that calculates the width:
![image](https://user-images.githubusercontent.com/1753795/74045495-a08c3580-49ab-11ea-9ca3-49ab70d1514e.png)

**UI5 Web Components for React Information**
Operating System: Windows
`@ui5/webcomponents-react` version: 0.8.0
Do you have a dependency to`@ui5/webcomponents` in your package.json? If yes, which version?: 1.0.0-rc.5

**Additional context**
One other thing I found weird is that each <FormItem> is ecapsulated inside an individual <FormGroup>, not sure if this is expected behavior, and I think it has nothing to do with the issue at hand, but I thought to mention.

**Comment by MarcusNotheis** [comment]
Hi @maitefdupont - thanks for submitting your this issue.
I'm not 100% whether this is a bug or works as intended and will double check the specs. In the meantime you can work around this issue by wrapping your `FormItem` into a `FormGroup` and setting the `data-layout` property for the grid which is used internally. For your example this would look like:
```js
  return (
    <Form>
      <FormGroup data-layout={{ span: 'XL12 L12 M12 S12' }}>
        {Object.entries(data).map(([key, value]) => (
          <FormItem key={key} labelText={value.i18nTag}>
            <Text wrapping>{value.metadata}</Text>
          </FormItem>
        ))}
      </FormGroup>
    </Form>
  );
```

**Comment by maitefdupont** [comment]
Hi @MarcusNotheis! This solves my problem, so thank you! Just curious though if this is the expected behavior (could be added to the docs) or not. If you manage to find out let me know! In the mean time, if you'd like to close this, I'm fine with it :)

**Comment by maitefdupont** [comment]
On another topic, but related to the usage of Form, how would I go about preventing labels from being truncated? Is it possible?

**Comment by MarcusNotheis** [comment]
To be honest I'm not sure whether we have a feature for preventing labels to be truncated or not. @andybessm any idea?

**Comment by andybessm** [comment]
Hi! Sorry for the delay with my reply. Right now we don't have an ability to setup the Labels but since we're using standard SAPUI5 label it is possible to set up its properties such as 'wrapping' and 'wrappingType'.

**Comment by MarcusNotheis** [comment]
Hi @maitefdupont,
in the meantime we have refactored the Form and the underlying grid component a bit. You can now pass a prop `label` to a FormItem which accepts either a string or a label component. Then you can modify the label component as you wish.
For the Form Layout taking only half of the screen it looks like it is really intended. You can work-around that behaviour by setting the `data-layout` prop as outlined above. Will try to add some meaningful documentation for that.
