### ISSUE TITLE
export 'useId' (imported as 'React') was not found in 'react'

### ISSUE THREAD

**Issue by brampurnot** [SAP/ui5-webcomponents-react#3073]
Hi!

We have just upgraded to the latest version of  "@ui5/webcomponents-react" (v0.25.2) and we are getting the following error message when running the app: 
Attempted import error: 'useId' is not exported from 'react' (imported as 'React').

useId is a new hook in React 18 but are still running react 17. Is it a mandatory requirement to upgrade to the latest version of react? 

Thanks,
Bram

**Comment by MarcusNotheis** [comment]
Hey @brampurnot,

thanks for reporting!
Using React 18 should not be mandatory for this library, it should work fine with both 16 and 17 as well.
We'll look into this with highest priority.
