### ISSUE TITLE
[SF][Input][0.25.1]: error when using input component with showSuggestions props and in mobile scenario

### ISSUE THREAD

**Issue by tandan0813** [SAP/ui5-webcomponents-react#3082]
**Describe the bug**
There is something wrong with `Input` component when it has `showSuggestions` props and in mobile scenario, adding screenshots for more details.

**Isolated Example**
*https://codesandbox.io/s/inspiring-pine-ismwsi?file=/src/App.js

**To Reproduce**
please see the isolated example

**Expected behavior**
`Input` can render correctly in mobile scenario with props `showSuggestions`

**Screenshots**
![image](https://user-images.githubusercontent.com/10113427/173977946-cfdf235c-e4d9-4dd2-8284-46562c27ed93.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.4.0
`@ui5/webcomponents-react` version: 0.25.1

**Comment by Lukas742** [comment]
Duplicate https://github.com/SAP/ui5-webcomponents/issues/5367

Closed.

**Comment by tandan0813** [comment]
Thanks your info! @Lukas742 
And could you please let us know which version we can see this fixed in ui5-webcomponents, since we have some issues pending on this right now.

**Comment by Lukas742** [comment]
It's not released yet.

Please ask all further questions in the original issue as duplicate issues will not be tracked by us.
