### ISSUE TITLE
[SF][FastNavigation][DynamicPage]: 

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents-react#3083]
Hi Colleagues,

When testing fast navigation in mentoring program details page, we found that it is unable to go back to global header through F6 from DynamicPage header actions. The focus is stuck on "Join as ..." button in following screenshot. 

<img width="1571" alt="image" src="https://user-images.githubusercontent.com/78520316/173985777-ed6f5c36-0746-4b1f-aa9d-958d8433d062.png">

I also test f6 navigation in https://codesandbox.io/s/ui5-wc-react-fastnavissue-xqom0q, it failed.

But it work fine in https://codesandbox.io/s/ui5-webcomponents-forked-qbs92b?file=/index.html:1070-1073

**To Reproduce**
 Go to OMP mentoring program: https://qacand.hcm.ondemand.com/sf/OMP/Mentoring/ViewDetail?p=mentee&programId=77768&appType=mentoringProgram&from_module=omp#/mentor-program/mentee/77768

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:1.4.0
`@ui5/webcomponents-react` version: 0.25.1

Could you help take a look at this issue? Thanks a lot!
Josephine Su

**Comment by Lukas742** [comment]
Hi @sfsf-xweb-sh 

you have to make sure that the side-effect "features" imports are imported before all other imports (e.g. components), otherwise they are registered too late and will not work.

Working example: https://codesandbox.io/s/compassionate-alex-39gdv9
