### ISSUE TITLE
AnalyticalTable: Extra Height Issue

### ISSUE THREAD

**Issue by I516406** [SAP/ui5-webcomponents-react#3090]
While defining specific height for an AnalyticalTable using style property having a visibleRowCountMode as Auto, the table gets a weird extra height at the bottom. 

[Code Sandbox](https://codesandbox.io/s/practical-butterfly-shkh8t?file=/src/App.js)

**Comment by Lukas742** [comment]
Hi @I516406 

I'm not really sure what you mean with "weird extra height". In your example you set the height to `60vh` and therefore the table occupies the space. Could you elaborate on what you mean.

**Comment by I516406** [comment]
Hi @Lukas742 

If you look at the bottom of the table, there's an extra space added at the end of the table. 
<img width="712" alt="Screenshot 2022-06-17 at 13 07 38" src="https://user-images.githubusercontent.com/54435646/174250096-c62edf2f-ee5f-4c77-8664-3797cca40778.png">

**Comment by Lukas742** [comment]
Does the same happen if you wrap the table inside another container and apply the styles there? --> [codeSandbox](https://codesandbox.io/s/blissful-williams-tuw78m?file=/src/App.js:928-975)

**Comment by I516406** [comment]
No Lukas, it works in that case.

**Comment by I516406** [comment]
okay, thanks
