### ISSUE TITLE
Analytical Table: Checkbox Selection column is moved to the end of the table when column order is changed

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents-react#311]
**Describe the bug**
Checkbox Selection column is moved to the end of the table when column order is changed

**To Reproduce**
1. Drag one of the columns in the Analytical table to reorder it.
2. Notice that the checkbox column is moved to the end.

**Expected behavior**
The checkbox column should always stay in its position.

**Screenshots**
![image](https://user-images.githubusercontent.com/8508119/74196933-337ad900-4c13-11ea-8dc7-6a13a4d36e7d.png)

**UI5 Web Components for React Information**
    "@ui5/webcomponents": "^1.0.0-rc.5",
    "@ui5/webcomponents-react-charts": "^0.7.2",
    "react-router-dom": "^5.1.2",
    "namor": "^1.1.2",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@ui5/webcomponents-react": "^0.8.2",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-scripts": "3.3.1"

**Additional context**
None

**Comment by MarcusNotheis** [comment]
Released in `@ui5/webcomponents-react@0.8.3`
