### ISSUE TITLE
ObjectPageSection: Error happening after updating version

### ISSUE THREAD

**Issue by francinyreichert** [SAP/ui5-webcomponents-react#3113]
**Describe the bug**
After updating ui5-webcomponents version, `unhandled Rejection (TypeError): Cannot read properties of undefined (reading 'disabled')` error is happening when switching tabs (object page sections) in ObjectPage component.

**Expected behavior**
User changes tab in ObjectPage and new tab opens correctly.

**Screenshots**
In the screenshot, it is possible to see that the error is happening in `TabContainer.js`, because `tab._realTab` is coming as `undefined`, so when trying to access `tab._realTab.disabled`, the error happens:
![image](https://user-images.githubusercontent.com/65377988/175043963-f528403c-b831-4134-9a98-4bc964af44d6.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.4.0
`@ui5/webcomponents-react` version: 0.22.4
Browser: all browsers

**Additional context**
CIM Internal Project

**Comment by Lukas742** [comment]
Hi @francinyreichert 

your `@ui5/webcomponents` version is not compatible with your `@ui5/webcomponents-react` version (you should see a peer dependencies error when installing dependencies).
Either update to at least  v0.25.0 of `@ui5/webcomponents-react` version or downgrade `@ui5/webcomponents` to v0.22.x

**Comment by francinyreichert** [comment]
Thanks @Lukas742, that was exactly the problem. I updated to v.025.0, now it's working fine :)
