### ISSUE TITLE
Option: `disabled` prop completely hides the option

### ISSUE THREAD

**Issue by jens-ox** [SAP/ui5-webcomponents-react#3114]
A [typical pattern](https://stackoverflow.com/a/30525521) for select fields is to set the default option both to `disabled` and `selected`:

```html
<select>
  <option value="" selected disabled>Select...</option>
  <option value="1">One</option>
  <option value="2">Two</option>
  <option value="3">Three</option>
</select>
```

Building this with OpenUI5 won't work, as `disabled` will just hide the element. Instead, the first remaining option will be selected.

**Comment by MarcusNotheis** [comment]
Thanks for reaching out! 
This behaviour is intended according to the [Fiori Design Specification](https://experience.sap.com/fiori-design-web/select/#option-list1):

> Do not [disable](https://experience.sap.com/fiori-design-web/ui-element-states/#disabled) values. In most cases, it is completely unclear how to enable them. [Hide](https://experience.sap.com/fiori-design-web/ui-element-states/#hidden) the values instead.

We've also received a very similar issue last year that has been closed with the reasoning: https://github.com/SAP/ui5-webcomponents/issues/3731
