### ISSUE TITLE
Analytical Table: Highlight Items (rows)

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents-react#312]
**Is your feature request related to a problem? Please describe.**
Currently, there is no built-in option to highlight rows as shown in the [Fiori specifications](https://experience.sap.com/fiori-design-web/analytical-table-alv/#highlight-items).

**Describe the solution you'd like**
Implementation of the specifications.

**Describe alternatives you've considered**
I've considered doing it manually, but it is better to have a solution provided by the library, especially in the case where the specifications are modified in the future.

**Additional context**
![image](https://user-images.githubusercontent.com/8508119/74281237-f2e29480-4cd2-11ea-820c-b780444306e1.png)

**Comment by MarcusNotheis** [comment]
Released in `0.9.0-rc.6`
