### ISSUE TITLE
Analytical Table: disable operations on the table when user changes the filter on filterbar until the user clicks on GO button

### ISSUE THREAD

**Issue by PriyaPowar** [SAP/ui5-webcomponents-react#3134]
**Is your feature request related to a problem? Please describe.**
Considering an App with List Page floorplan like fiori, with and filterbar and a table below it. When user updates any filter in the filterbar then the analytical table below should be disabled till user clicks on GO button in filterbar. Refer FIORI for the behavior.
![image](https://user-images.githubusercontent.com/90389521/175918681-e17fbc94-1a74-495d-a84c-1bbef09b8d33.png)

**Describe the solution you'd like**
Provide a property at the analytical table component to set the table to be disabled, not allowing users to perform any actions on it.

**Describe alternatives you've considered**
We had considered adding the busyindicator component so that user is not allowed to perform any actions. However, the accessibility testing team mentioned that it would give a wrong meaning like a get call is currently in progress where as the call gets triggerred only on click on GO button for better performance.

**Additional context**
Refer behavior in fiori apps for list page floorplan.

**Comment by Lukas742** [comment]
Hi @PriyaPowar 

I couldn't find any design guidelines for this. Can you tell me where I can find them? If they're internal details, you can also send me the info through our internal channels.
