### ISSUE TITLE
Requesting icon in UI5 Webcomponent for react

### ISSUE THREAD

**Issue by ShivamGuptaSap** [SAP/ui5-webcomponents-react#3136]
### **Feature Request Description**
Need an icon for a SAC LiteViewer MenuItem "Edit Prompts" as currently we are in the middle of migrating the whole project from orca-react-ui to UI5 Web-Component for React
Kindly Refer to the screenshot

### **Proposed Solution**
We would like to have same icon as we currently have in orca-react-ui

### **Additional Context**
Screenshot:
![image](https://user-images.githubusercontent.com/107616257/175882299-5ca151e8-e793-493b-bb06-68d5aa524bed.png)

### **Priority**
- [ ] Low
- [ ] Medium
- [ ] High
- [x] Very High

- Organization: {SAP}

**Comment by Lukas742** [comment]
Hi @ShivamGuptaSap 

there's a similar icon available in the tnt icon package. See [here](https://openui5.hana.ondemand.com/test-resources/sap/m/demokit/iconExplorer/webapp/index.html#/overview/SAP-icons-TNT/?tab=details&icon=constrains) 
You can find out more about the different icon packages and how to consume them [here](https://sap.github.io/ui5-webcomponents/playground/getting-started/using-icons/).

**Comment by scameron** [comment]
Hi @ShivamGuptaSap, @Lukas742,

> there's a similar icon available in the tnt icon package. See [here](https://openui5.hana.ondemand.com/test-resources/sap/m/demokit/iconExplorer/webapp/index.html#/overview/SAP-icons-TNT/?tab=details&icon=constrains)
> You can find out more about the different icon packages and how to consume them [here](https://sap.github.io/ui5-webcomponents/playground/getting-started/using-icons/).

Thanks for the suggestion.   @ShivamGuptaSap, do you think this would work for you use case?  Have you had a chance to check out these links?

**Comment by ShivamGuptaSap** [comment]
Thanks @scameron,
Yeah, I had checked out tnt icon packages earlier and currently using the icon from there..
