### ISSUE TITLE
Feature Request - Required ShortcutText property in MenuItem in UI5 WebComponent for React

### ISSUE THREAD

**Issue by ShivamGuptaSap** [SAP/ui5-webcomponents-react#3137]
### **Feature Request Description**
In MenuItem we need a shortcutText property so that we can add shortcut texts along with the menu Item.

### **Proposed Solution**
Just like we have that property in Orca-React-UI

### **Additional Context**
Kindly refer to the screenshots:

Its Purpose:
![image](https://user-images.githubusercontent.com/107616257/174039259-06abb5e2-be26-4ee3-aa1d-ed6b4f34b336.png)

In Orca-React-UI they offer this:
![image](https://user-images.githubusercontent.com/107616257/174039091-7bd6f78a-2f99-402c-afb8-ffd5bf52accb.png)

### **Priority**
- [ ] Low
- [ ] Medium
- [ ] High
- [x] Very High

As we are in the middle of migrating the whole project "SAC Lite-Viewer" from Orca-React-UI to UI5-WebComponent for React. So we will be needing this feature on urgent basis.

- Organization: { SAP }

**Comment by Lukas742** [comment]
Hi @ShivamGuptaSap 

as you already opened the [same issue](https://github.com/SAP/ui5-webcomponents/issues/5369) in the UI5 Web Components repo (which is the right place, as the component is developed there), I'll close this issue as duplicate.

**Comment by ShivamGuptaSap** [comment]
Hi @Lukas742,
Just wanted to confirm if it gets developed in UI5 Web Components repo then will it be automatically added in UI5 Web Components for React?

**Comment by Lukas742** [comment]
Yes, as stated in our [documentation](https://sap.github.io/ui5-webcomponents-react/?path=/story/getting-started--page) all UI5 Web Components are available with UI5 Web Components for React as well. Depending on what has to be adopted on a version update of `@ui5/webcomponents` we may need some days to release a compatible version of `@ui5/webcomponents-react` but in most cases this will only take a day or two.
