### ISSUE TITLE
AnalyticalTable: event.detail is not correct

### ISSUE THREAD

**Issue by Bilal3120** [SAP/ui5-webcomponents-react#3147]
**Describe the bug**
event.detail is not correct in multi select analytical table.

**Steps to reproduce the behavior:**
1. Go to [CodeSandbox](https://codesandbox.io/s/hopeful-morning-lx8ot6?file=/src/App.js)
2. Try clicking select all and individual rows to check event.detail in the console.
3. Also try using SPACE key.

**Screenshots**
<img width="750" alt="Screenshot 2022-06-27 at 3 54 56 PM" src="https://user-images.githubusercontent.com/93638146/176088152-05072446-7bad-4249-bf1c-ae8aecd48b7e.png">

**Comment by MarcusNotheis** [comment]
Hey @Bilal3120,
thanks for reporting! Just to make sure we're not missing something:
You are using React 18 in your application like in your sandbox, right?

**Comment by Bilal3120** [comment]
Hi @MarcusNotheis 
We are using React 17.0.2 in our application but then the issue is, event is incorrect when we select table rows using SPACE Key.
This issue is reproduced here - [CodeSandbox](https://codesandbox.io/s/analyticaltable-selectrowwithkeyboard-bxlml0?file=/src/App.js)

**ScreenShot**
<img width="1740" alt="Screenshot 2022-07-07 at 11 31 02 AM" src="https://user-images.githubusercontent.com/93638146/177703215-d6028acf-f638-4e40-a3cc-be67e981ad71.png">

Best regards,
Bilal Ahmed Pasha

**Comment by MarcusNotheis** [comment]
Thanks for getting back - I guess then we have two individual issues here:
1. General: `event.detail` is incorrect when selecting with space
2. React 18: `event.detail` is completely off, looks like it lags always one render cycle

**Comment by Flora-manda** [comment]
Following this issue, as I'm currently experiencing the same bug on multi-select for the analytical table (react 18).
