### ISSUE TITLE
FilterBar: Filter Dialog Title name is not read out when opened, also focus not retained

### ISSUE THREAD

**Issue by sparkypro** [SAP/ui5-webcomponents-react#3152]
**Describe the bug**
Filterbar, filter dailog title name is not read out when opened

**UI Link**
https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-filterbar--default-story

**To Reproduce**
1. Go to UI link
2. Click on Filters button which will open Filters Dialog
3. Run screen reader, when filters dialog is opened. The title name is not read out. But directly the contents are read out.

**Expected behavior**
When the dialog opens up, the dialog title name must be read out while using with screen reader.

**Screenshots**
<img width="647" alt="image" src="https://user-images.githubusercontent.com/108118034/176165126-6202d498-372d-4130-8e8b-8075751282f8.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:1.4.0
`@ui5/webcomponents-react` version:0.25.6
Operating System:Windows 11
Browser:Chrome

**Comment by sparkypro** [comment]
@Lukas742  Please also see that, the Filters button once clicked & cancel back, then focus is not retained back to Filters button.

<img width="740" alt="image" src="https://user-images.githubusercontent.com/108118034/176831825-1c01bea1-c00e-45ad-bc1a-e0bc0b5b4c73.png">

**Comment by sparkypro** [comment]
Any update on this issue?

**Comment by Lukas742** [comment]
Hi @sparkypro 

this issue will be fixed with the linked PR. You can track the progress in the PR's description.
