### ISSUE TITLE
Add flag to control the behavior of `onChange`

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents-react#3180]
With React, the native `change` (`onChange`) is fired on every keystroke unlike it does with the custom `change` event of the UI5 Web Components, which is only fired on `blur`, ENTER or some other interactions like selecting an option of a `Select`.

We should add a flag that enables the default behavior of React for the `onChange`, so app developers can decide on their own how they want to handle this.

**Comment by MarcusNotheis** [comment]
Implementation is not feasible and would create a confusing behaviour to end users.
