### ISSUE TITLE
useRowHighlight.js issue in Analytical Table

### ISSUE THREAD

**Issue by knandan15** [SAP/ui5-webcomponents-react#3187]
![issue 1](https://user-images.githubusercontent.com/48648230/177082803-4e79dd58-227b-4969-abd6-f03653080e80.PNG)

![issue 2](https://user-images.githubusercontent.com/48648230/177082935-15e0b5bb-e307-4f73-9b25-e60cfa8ff2b0.PNG)
 
After updating the libraries to version "^0.25.7" also, this error is coming.

**Comment by Lukas742** [comment]
Hi @knandan15 

I cannot reproduce this issue. Could you check this [codeSandbox](https://codesandbox.io/s/defaulttable-forked-8548nx?file=/src/App.js) and tell me if I missed something?

**Comment by knandan15** [comment]
Hi @Lukas742 , while running my application if commented/uncommented the properties of AnalyticalTable. When I changed the **scaleWidthMode="Smart"** changed to **scaleWidthMode="Default"** - the app is working fine. Can you check over this issue if there is any other alternative?

**Comment by Lukas742** [comment]
I still cannot reproduce this even with `scaleWidthMode="Smart"`. (See [codeSandbox](https://codesandbox.io/s/defaulttable-forked-8548nx?file=/src/App.js))
Please add a reproducible example using this [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34?file=/src/index.js) template or you can reuse the one I posted above.
