### ISSUE TITLE
Bar: Items not aligning properly

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents-react#319]
**Describe the bug**
1. Placing an Input within a FlexBox within a Bar causes alignment issues with the Input placeholder text and inner Icon.
2. Placing a Title within a FlexBox within a Bar causes alignment issues with other items.

**To Reproduce**
Code to reproduce the behavior:
```
<Bar
	renderContentLeft={() => (
		<FlexBox>
			<Button icon="menu2"/>
			<Title>Title</Title>
		</FlexBox>
	)}
	renderContentRight={() => (
		<FlexBox>
			<Input placeholder="Type name" icon=<Icon name="search"/>/>
		</FlexBox>
	)}
/>
```
**Expected behavior**
The items should align properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/8508119/74372742-056ed380-4d90-11ea-80e7-7b3334f2710f.png)

**UI5 Web Components for React Information**
  "dependencies": {
    "@ui5/webcomponents": "^1.0.0-rc.5",
    "@ui5/webcomponents-react-charts": "^0.7.2",
    "react-router-dom": "^5.1.2",
    "namor": "^1.1.2",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "@ui5/webcomponents-react": "0.8.4-dev.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-scripts": "3.3.1"
  },

**Additional context**
None.

**Comment by agauyeung** [comment]
I am also running into issues with Button text as well in this scenario (inside FlexBox which is inside Bar).
![image](https://user-images.githubusercontent.com/8508119/74486178-3b37b900-4e71-11ea-95ab-dde9914ff1f8.png)

**Comment by MarcusNotheis** [comment]
Regarding the 1. issue with the FlexBox, Button and Title:
In this case, the FlexBox is "destorying" the layout. If you add `<FlexBox alignItems={FlexBoxAlignItems.Center}>` the layout is the expected one. Also if you omit the FlexBox and use a `<>...</>` fragment instead
