### ISSUE TITLE
Auto adjust width on double click between the columns

### ISSUE THREAD

**Issue by Bilal3120** [SAP/ui5-webcomponents-react#3196]
**Feature request**
When using analytical table if cell content is truncated, can we have a functionality by which the cell width gets auto adjusted when we double click in between the columns.

**Example**
<img width="785" alt="Screenshot 2022-07-05 at 2 44 56 PM" src="https://user-images.githubusercontent.com/93638146/177294837-abac869b-15f5-4486-a47d-c4ccd2e3fbb6.png">

Now when we click between the columns can the width be adjusted accordingly
<img width="785" alt="Screenshot 2022-07-05 at 2 45 02 PM" src="https://user-images.githubusercontent.com/93638146/177295519-daf7bf8c-0c61-49ca-a3d3-57c7daaf85e0.png">

**Comment by Papa-Santo** [comment]
Please assign this to me. I want this feature as well, and I have the time to implement it.

My only question: If a field is not truncated, but instead has extra width, should double clicking decrease the width of the field? 

Of course it should still show all of the content but it should have only enough width to show the largest amount of text content in that field. I vote yes on this, but I understand the request is specific to making truncated fields show their full content.

**Comment by MarcusNotheis** [comment]
Closed via https://github.com/SAP/ui5-webcomponents-react/pull/5758
