### ISSUE TITLE
Form: Focus on input inside form and press enter, will auto refresh page and jump to relevant target URL

### ISSUE THREAD

**Issue by JackieWei** [SAP/ui5-webcomponents-react#3207]
**Describe the bug**
Focus on any input inside form and press enter, will auto refresh page and jump to relevant target URL

**Isolated Example**
https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-form--default-story
Use the storybook can reproduce this issue

**To Reproduce**
1. Go to page with form, and add some inputs into form
2. Click on any input to gain focus
3. Knock on enter
4. See page refresh accidentally

**Expected behavior**
Enter on input should not trigger page refresh since we don't want, and no any submit called, this is not the original behavior we want

**Screenshots**
No need

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.4.x
`@ui5/webcomponents-react` version: 0.25.x
Operating System: Mac
Browser: Chrome

**Additional context**

**Comment by Lukas742** [comment]
Hi @JackieWei 

this problem is known and is being worked on by our ui5 web components colleagues. If you have any questions or can provide additional information, please do so in [this issue](https://github.com/SAP/ui5-webcomponents/issues/5427).

**Comment by JackieWei** [comment]
@Lukas742  Cool, got that
