### ISSUE TITLE
Analytical Table: Component documentation not working online

### ISSUE THREAD

**Issue by Vasu-p** [SAP/ui5-webcomponents-react#321]
**Describe the bug**
The documentation of the web-components for react throws error on safari but work on Chrome. On safari it throws a resize observer error as shown in the screenshots.

**To Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/components-analytical-table--default-table

**Expected behavior**
It should show the documentation

**Screenshots**
Safari : 
<img width="1403" alt="image" src="https://user-images.githubusercontent.com/9253278/74461318-30662f80-4e43-11ea-9c9b-db703f008544.png">

Chrome:
![image](https://user-images.githubusercontent.com/9253278/74461442-63102800-4e43-11ea-9066-6a5a34ea7a69.png)

**UI5 Web Components for React Information**
Operating System: OS X
`@ui5/webcomponents-react` version: N/A
Do you have a dependency to`@ui5/webcomponents` in your package.json? If yes, which version?:

*If you are not sure, you can find out by running `npm ls @ui5/webcomponents-react` or `yarn why @ui5/webcomponents-react`*

**Additional context**

**Comment by MarcusNotheis** [comment]
Hi @Vasu-p, 
thanks for reporting. 
Fixed in 83963d1dd3a19324a0a83aece126adfa981b958d.
