### ISSUE TITLE
List: How select All

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [SAP/ui5-webcomponents-react#3223]
![image](https://user-images.githubusercontent.com/9791364/178056496-2d1a111d-b3e9-4460-8289-25194f474473.png)

How to select all items from this using an onclick event?

**Comment by Lukas742** [comment]
Hi @luizcarlospedrosogomes 

I'm not 100% sure what you mean with onclick event. If you're asking how to programatically select all entries of a `List`, then please take a look at this [codeSandbox](https://codesandbox.io/s/list-select-all-poieqb). Otherwise please elaborate a bit more.
