### ISSUE TITLE
Range Slider Component

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents-react#323]
**Is your feature request related to a problem? Please describe.**
The library does not have a range slider implementation.

**Describe the solution you'd like**
I'd like for an implementation of Slider based on the [Fiori specifications](https://experience.sap.com/fiori-design-web/range-slider/).

**Describe alternatives you've considered**
Using 2 Input boxes side-by-side. (not a visually appealing)

**Additional context**
None.

**Comment by MarcusNotheis** [comment]
Hi @agauyeung thanks your feature request.
We are currently evaluating whether we should add this component to our React Wrapper or if it would make more sense to add it directly in the UI5 Web Components library.
Will keep this issue updated as soon as we have decided for one or the other way.

**Comment by MarcusNotheis** [comment]
FYI - We will develop this component as part of the UI5 Web Components so that other frameworks like Vue and Angular can benefit from the implementation as well.

**Comment by MarcusNotheis** [comment]
Closing this issue as progress will be tracked at https://github.com/SAP/ui5-webcomponents/issues/1242
