### ISSUE TITLE
[SF][Menu][MenuItem]: Interface className is not work for custom style

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents-react#3252]
**Describe the bug**
Hi Colleague,
It fails to add custom styles like padding and min-width of menuItems by using className.
Could you please help check it?

**Isolated Example**
**To Reproduce**
1. Go to https://github.wdf.sap.corp/pages/xweb/omp-lib/?path=/story/components-menubutton--primary

2. Click on "Manage My Opportunities" button
You will see custom style is not worked on menu.
<img width="1402" alt="Screen Shot 2022-07-17 at 19 20 55" src="https://user-images.githubusercontent.com/78520316/179395799-a18e4250-ca67-4946-88f3-d1e1280cb722.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.4.0
`@ui5/webcomponents-react` version: 0.25.0

Thanks!
Josephine Su

**Comment by Lukas742** [comment]
The `MenuItem` is an abstract component, that's why e.g. `className` and `styles` are not supported. 
Currently this isn't mentioned in our documentation and can only be found in the [UI5 Web Components docs](https://sap.github.io/ui5-webcomponents/playground/components/Menu/). --> We'll add an entry for that in our docs as well.

**Comment by sfsf-xweb-sh** [comment]
Hi @Lukas742 ,
Thanks for your information.  There is another question, I using set "children" to several buttons, and passed to menu. But those buttons are not wrapped in menu list, but displayed directly(see screenshot).  Do you have any idea about it? 
<img width="378" alt="image" src="https://user-images.githubusercontent.com/78520316/179775831-ef33abf4-2f85-4134-b0d2-7050175cb4c6.png">

**Comment by Lukas742** [comment]
The `Menu` component expects `MenuItem`s as `children`. 
I opened a [PR](https://github.com/SAP/ui5-webcomponents/pull/5531) to add a note about this in the UI5 Web Components repo, since the description for the props originates from there.
