### ISSUE TITLE
[SF][DynamicPageTitle]: Event when overflow button displayed due to limited screen size and support custom overflow button

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents-react#3253]
**Is your feature request related to a problem? Please describe.**
Hi Colleague,

There is a request to set information when overflowButton displayed on dynamicPageTitle. Would that possible to provide a slot for user to pass a "overflowButton?  And  an event to tell user when overflowButton shows is also needed.

Thanks!
Josephine Su

**Comment by sfsf-xweb-sh** [comment]
Hi @Lukas742,
May I ask your plan of this feature-request? This is a requested on OMP project to set first time guidance on overflow button when screen is limited. We hope it will be available as quick as possible.

Thanks a lot!
Josephine

**Comment by Lukas742** [comment]
Hi @sfsf-xweb-sh 

I just linked a PR that will add the option to change the overflow button of both `DynamicPageTitle` toolbars. 

An event indicating if the overflow button is displayed is already available. You can use `onToolbarOverflowChange` and then check if the `overflowElements`  `HTMLCollection` is not empty.
