### ISSUE TITLE
Text: full text should be shown as tooltip on hover over when wrapping is set as false 

### ISSUE THREAD

**Issue by PriyaPowar** [SAP/ui5-webcomponents-react#3264]
**Describe the bug**
Text component have a property of setting the wrapping to false. But when done, user has no way to see what was the complete text. There should be an option provided that on hover over, the complete text is shown as tooltip when wrapping is set as false. This feature is already existing in fiori apps.

**Isolated Example**
https://sap.github.io/ui5-webcomponents-react/?path=/story/data-display-text--default-story&args=wrapping:false
No option to see the complete text.

**To Reproduce**
Follow the above link in the sample shown in react ui storybook. There is no way user can see the complete text.

**Expected behavior**
On hover over, the complete text is to be shown as tooltip. Refer fiori apps for this behavior. 

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: latest version
`@ui5/webcomponents-react` version: latest version

**Additional context**

**Comment by Lukas742** [comment]
Hi @PriyaPowar 

the `Text` component supports all HTML attributes, so setting the `title` is up to the app developer. --> See [codeSandbox](https://codesandbox.io/s/keen-zhukovsky-5fys59?file=/src/App.js)
