### ISSUE TITLE
AnalyticalTable: Empty grouped rows if minRows exceeds data rows

### ISSUE THREAD

**Issue by codingfabi** [SAP/ui5-webcomponents-react#3266]
**Describe the bug**
In the analytical table, if a column is grouped and the minRows property is set to a number that is higher than the actual data rows, the surplus rows get added as empty grouped rows.

**Isolated Example**
https://sap.github.io/ui5-webcomponents-react/?path=/story/data-display-analyticaltable--default-story&args=minRows:510;groupBy[0]:name;groupBy[1]:age

Storybook url parameters do not seem to work :/

**To Reproduce**
1. Set minRows to a number that is higher than the actual data rows (in the storybook e.g. 510).
2. Group for one or more columns (e.g. "name" and "age". 
3. Scroll to the bottom of the table.
 
-> there is an empty grouped row that groups 10 empty rows.

**Expected behavior**
I would expect the empty rows to not get grouped and be ignored by the grouping.

**Comment by ritikadhamija** [comment]
@codingfabi I would like to work on this issue. Can you please assign it to me?

**Comment by Lukas742** [comment]
Hi @ritikadhamija 

I assigned the issue to you. Thanks for your support!

You should probably be able to solve this issue by leveraging the `groupByFn` [table option](https://react-table-v7.tanstack.com/docs/api/useGroupBy#table-options) and omitting the rows with `row.original.empty` there.

**Comment by Lukas742** [comment]
Hi @rit-clone

sorry to bother you, but we need this issue to be fixed by the end of this week, since we need it in one of our applications next week. Do you think you can solve this till then? If not that is not a problem, then I just take over the issue :) Please let me know by tomorrow.

**Comment by rit-clone** [comment]
Hi @Lukas742, sorry for the delay. I have just raised a [PR#3273](https://github.com/SAP/ui5-webcomponents-react/pull/3273)
Please review it and let me know if any changes need to be done.
