### ISSUE TITLE
[RadioButton - A11y] Radio button groups are not keyboard accessible when no buttons are initially checked.

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents-react#3276]
### **Bug Description**
Hi team,

When there is a group of radio buttons and none are initially selected, the user cannot tab or arrow to any of the buttons to select one. Only if one is initially selected can the user go into the group, then arrow through to select the next/prev one. 

Thanks,
Allen

### **Expected Behavior**
User can still access the radio button group even when no buttons are checked. 

### **Steps to Reproduce**
1. You can go to the react playground, [inputs-radiobutton--radio-button-groups](https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-radiobutton--radio-button-groups)
![image](https://user-images.githubusercontent.com/38701667/180325268-d7e2c59c-68f2-4639-a7e6-a4eccb8206ed.png)

### **Context**
- UI5 Web Components version: 1.3.1/0.23.1
- OS/Platform: 
- Browser: Chrome (All)
- Affected component: RadioButton

### **Priority**
- [ ] Low
- [x] Medium
- [ ] High
- [ ] Very High

The priority indicates the severity of the issue. To set the appropriate priority consider the following criteria:
- Breaks entire application or system - High or Very High
- Accessibility issue - Medium or High
- Functional issue - Medium or High
- Visual issue - Low or Medium

**Note:** The priority might be re-evaluated by the issue processor.

### **Stakeholder Info** (if applicable)

- Organization: SF
- Business impact: Medium

**Comment by Lukas742** [comment]
Hi @allen138 

I think this is more a problem with the iframe of the storybook, than with the `RadioButtonGroup`. Without the iframe it works as intended for me. See [here](https://sap.github.io/ui5-webcomponents-react/iframe.html?args=&id=inputs-radiobutton--radio-button-groups&viewMode=story)

**Comment by allen138** [comment]
@Lukas742 , I found the issue is when you have inner components of a main component. ex:
```javascript
const App = () => {
  const RadioButtonGroup = ({ name }) => {
    return (
        <RadioButton name={name} text="Gregorian" />
        <RadioButton name={name} text="Buddhist" />
        <RadioButton name=[name} text="Islamic" />
    )
  }
  const MainContent = () => {
    return (
      <div style={layout}>
         <RadioButtonGroup name="groupA />
      </div>
    )
  }

 return <MainContent />
}
```

So my solution was to consolidate it to one JSX object.
