### ISSUE TITLE
AnalyticalTable: Support for sorting, filtering and grouping on the back-end

### ISSUE THREAD

**Issue by Scorze** [SAP/ui5-webcomponents-react#3310]
**Is your feature request related to a problem? Please describe.**
The AnalyticalTable right now easily supports sorting, filtering and grouping only on the front-end. Since sorting, filtering and grouping on the back-end is a common approach, I would like to easily be able to display an indicator when a filter is applied. As of right now, only calling this function with a value displays the indicator on the column cell of the AnalyticalTable and forces front-end filtering.

![image](https://user-images.githubusercontent.com/10748796/181757193-a5b3828b-44d8-4006-b7ed-882559a64906.png)

The documentation states that columns must be memoized but if hooks are used inside the Filter Component (rendered in the column Header), memoize is not an option. When there is back-end sorting, there is a need to keep track of all of the already applied filters to construct the back-end call, but hooks cause re-rendering of the columns and the whole state of the Filter component is wiped and the filter icons disappear.

**Describe the solution you'd like**
To be able to use state within the AnalyticalTable columns array without memoizing it.

**Comment by Lukas742** [comment]
Hi @Scorze 

I think you can use the following `reactTableOptions` to achieve this.
```
<AnalyticalTable
  ...
  reactTableOptions={{
    manualSortBy: true,
    manualFilters: true,
    manualGroupBy: true
  }}
/>
```

[Here](https://codesandbox.io/s/at-basic-manual-sort-jc1czf) you can find a basic example on how to implement manual sorting, 

Also I'm not 100% sure what you mean with this section:
>The documentation states that columns must be memoized but if hooks are used inside the Filter Component (rendered in the column Header), memoize is not an option. When there is back-end sorting, there is a need to keep track of all of the already applied filters to construct the back-end call, but hooks cause re-rendering of the columns and the whole state of the Filter component is wiped and the filter icons disappear.

If you want to keep track of the applied filters, sorters or the grouped columns you can do so either in the corresponding callback, or by using the `tableInstance`.

**Comment by Lukas742** [comment]
Keeping this open until all questions are resolved.

**Comment by Scorze** [comment]
Hi @Lukas742
Thank you very much for the answer and for updating the storybook, this is what I was looking for.
That's all the questions I had.

**Comment by Lukas742** [comment]
Glad to hear :)
