### ISSUE TITLE
SAP Companion/Web Assistant support

### ISSUE THREAD

**Issue by draysams** [SAP/ui5-webcomponents-react#3311]
I have a requirement to add a guided tour and a context help for new users. It would be great if a guided tour and help context components consistent with the [SAP Companion guidelines](https://experience.sap.com/fiori-design-web/web-assistant/) was added.

The solution that comes to mind is a context help component that takes a ref, an event and a piece of text to display when the event is triggered. 

I'm currently considering styled popovers to achieve this requirement.

**Comment by MarcusNotheis** [comment]
Hey @draysams,
thanks for reaching out!

To be honest, I'm not 100% sure what exactly do you want to achieve:
1. Do you want to integrate SAP Companion in your App using UI5 Web Components for React?
2. Or do you want to build this context help by yourself and make it look like the SAP Companion?

For the first scenario there should be no need to implement such a popover by yourself as those are injected by the SAP Companion Library.
For the second scenario I would doubt that we can provide such a component as there are no Fiori Design Guidelines for such a popover component and we don't want to interfere with the SAP Enable Now product.
--> In this case I would recommend to style the popover by yourself.

Does that help?

**Comment by draysams** [comment]
Hi @MarcusNotheis thanks for the reply. 
Your suggetion is helpful and i will proceed to style the popover.
