### ISSUE TITLE
Dialog: Content part has incorrect padding when being used as Notification Center

### ISSUE THREAD

**Issue by guilhXavier** [SAP/ui5-webcomponents-react#3333]
**Describe the bug**
Whenever we open a popover containing a list of notification groups and notification items, as it opens a Dialog component, the content CSS shadow part has a padding which is not in accordance with Fiori Guidelines [as you can see here.](https://experience.sap.com/fiori-design-web/notification-center/)

**To Reproduce**
In [Dialog With Content Storybook](https://sap.github.io/ui5-webcomponents-react/?path=/story/modals-popovers-dialog--with-content)
1. Click on the Open Dialog button;
2. See that there is a padding in the dialog's content.

**Expected behavior**
When used in the notification center, there should be no padding in the content section, [as you can see here.](https://experience.sap.com/fiori-design-web/notification-center/) 
**Screenshots**
Actual
![image](https://user-images.githubusercontent.com/40150972/182674909-dcbcde50-d322-4b0e-81a2-d7d6a1a361e5.png)
Expected
![image](https://user-images.githubusercontent.com/40150972/182675209-a1d6c3ac-1ccf-4c0d-8f0b-31e58ad02e29.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.5.0
`@ui5/webcomponents-react` version: 0.26.0
Operating System: macOS Monterey 12.5
Browser: Chrome Version 103.0.5060.134 (Official Build) (x86_64)

**Additional context**
This is a request for our internal SAP project.

**Comment by Lukas742** [comment]
Hi @guilhXavier 

you can remove the default padding by using the [`::part` pseudo Element ](https://developer.mozilla.org/en-US/docs/Web/CSS/::part)of the dialog. You can find all available shadow parts [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-dialog--default-story#css-shadow-parts).
