### ISSUE TITLE
Adding "Pin" Button to ObjectPage Component

### ISSUE THREAD

**Issue by n-devlin** [SAP/ui5-webcomponents-react#334]
**Is your feature request related to a problem? Please describe.**
In the Fiori 3.0 designs, the ObjectPage component includes a button alongside the expand/collapse header button to allow a user to "pin" the header in an expanded state. We would like to use this functionality to follow Fiori.

**Describe the solution you'd like**
The addition of a button (or ability to add a button ourselves) that allows a user to "pin" the header content of the ObjectPage component in an expanded state. This would allow a user to continue to scroll through content without pushing the header content into a collapsed state.

**Additional context**
Thank you!

**Comment by MarcusNotheis** [comment]
Release Candidate available: `@ui5/webcomponents-react@0.8.7-rc.0`
