### ISSUE TITLE
AnalyticalTable: Tree Table arrows don't show up at proper place

### ISSUE THREAD

**Issue by Vasu-p** [SAP/ui5-webcomponents-react#336]
**Describe the bug**
In Analytical Table, if we use Tree Table, then the arrows to expand and collapse doesn't show up at proper position when the selection column is present. However when the selection column is hidden the arrows show up properly.

**To Reproduce**
Use the following [sandbox](https://codesandbox.io/s/analytical-tree-table-sorting-9vrpq?fontsize=14&hidenavigation=1&theme=dark). 
By default, it doesn't show the selection column. 
If we set noSelectionColumn to false, we can see the bug.

**Expected behavior**
We expect the arrows to show up in the first column and not in the selection column, same as we can see when the selection column is absent.

**Screenshots**
Current:
![image](https://user-images.githubusercontent.com/9253278/76019490-a572d500-5ed6-11ea-819e-1caeae663ad3.png)
Expected:
![image](https://user-images.githubusercontent.com/9253278/76019553-bf141c80-5ed6-11ea-94c7-00dc5f0efd69.png)

**UI5 Web Components for React Information**
Operating System: N/A
`@ui5/webcomponents-react` version: 0.8.5
Do you have a dependency to`@ui5/webcomponents` in your package.json? If yes, which version?:

*If you are not sure, you can find out by running `npm ls @ui5/webcomponents-react` or `yarn why @ui5/webcomponents-react`*

**Additional context**

**Comment by MarcusNotheis** [comment]
Release Candidate available: `@ui5/webcomponents-react@0.8.7-rc.0`
