### ISSUE TITLE
Table: First row's backgroundColor is changed when using Theme

### ISSUE THREAD

**Issue by Dschmitz1** [SAP/ui5-webcomponents-react#337]
**Describe the bug**
When using the Table component with a backgroundColor set on the body of the App, the first row of the table is being affected by this color.

![image](https://user-images.githubusercontent.com/11902967/76085656-3f975380-5f91-11ea-9f06-44f979636653.png)

**To Reproduce**
This can be seen on this [CodeSandbox](https://codesandbox.io/s/zealous-mclaren-w7e9g)

**Expected behavior**
I would like the page to have its backgroundColor set by the Theme, but the Table to remain with its default colors.

**Comment by MarcusNotheis** [comment]
hi @Dschmitz1 
thanks for submitting this issue. As the Table component is built by our colleagues from the ui5/webcomponents team, I forwarded this issue to them: https://github.com/SAP/ui5-webcomponents/issues/1273

I will keep this issue open until they have a released a new version and we have upgraded to use that version.

**Comment by Dschmitz1** [comment]
Thanks for the response, Marcus!

**Comment by MarcusNotheis** [comment]
Released in `@ui5/webcomponents-react@0.9.0-rc.9`
