### ISSUE TITLE
AnalyticalTable - sticky column

### ISSUE THREAD

**Issue by kishanrajdev** [SAP/ui5-webcomponents-react#3377]
**Is your feature request related to a problem? Please describe.**
I want to have certain columns in the table pinned to the left or right. something like this, https://www.ag-grid.com/angular-data-grid/column-pinning/

Please let me know if there already exists a way to do it. I couldn't find it from the doc or the implementation.

Thanks.

**Comment by MarcusNotheis** [comment]
Hey @kishanrajdev,
thanks for reaching out! Actually, we already have an open feature request in #566, so I'm closing this as duplicate.
With our current version of the `AnalyticalTable` is not feasible to have such a feature, but we're looking into building a completely new version where we want to look into sticky columns as well.
