### ISSUE TITLE
Variant Management: German terms for "View" inconistent - Sicht vs. Ansicht

### ISSUE THREAD

**Issue by nidhi0104** [SAP/ui5-webcomponents-react#3398]
In Variant Management,the text for 'view' is not consistent.In the "Save View" dialog box that opens after clicking on the "Save As" botton to save a view, the German term used for "View" differs from that use in the text "My Views" at the top of the screen.

**Isolated Example**
Check the below link - 
https://sap.github.io/ui5-webcomponents-react/?path=/story/inputs-variantmanagement--default-story&sap-language=de

**To Reproduce**
1. Go to Variant Management
2. Click on Save As
3. See error

**Expected behavior**
The translated text should be same.

Screenshot
![image](https://user-images.githubusercontent.com/105447668/186089455-b42d79ea-37ef-4037-91c9-b1481080cdae.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:'~1.4.0'
`@ui5/webcomponents-react` version:"0.25.7",
Operating System:
Browser:Chrome

**Comment by Lukas742** [comment]
Hi @nidhi0104 

I could not reproduce this behavior. (see [codeSandbox](https://codesandbox.io/s/variantmanagement-forked-tuzwpf?file=/src/App.js))
Could it be possible that you're using a custom header text (by setting `titleText`) instead of the build in one?

**Comment by nidhi0104** [comment]
![image](https://user-images.githubusercontent.com/105447668/186586063-3b5c5f3f-d250-44f1-8bec-ff54e79466db.png)

Hi @Lukas742 

In my system, the text is not the correct, I am using the following versions of @ui5/webcomponents-react.Can you please confirm this?

**Comment by Lukas742** [comment]
I just checked and for `0.25.7` the translation text already was "Meine Ansichten"

https://github.com/SAP/ui5-webcomponents-react/blob/v0.25.7/packages/main/src/i18n/messagebundle_de.properties#L75
