### ISSUE TITLE
Selecting checkbox while pressing the command/ctrl key

### ISSUE THREAD

**Issue by shivamdz** [SAP/ui5-webcomponents-react#3407]
### Discussed in https://github.com/SAP/ui5-webcomponents-react/discussions/3402

<div type='discussions-op-text'>

<sup>Originally posted by **shivamdz** August 23, 2022</sup>
Hi Everyone,

I want to select a checkbox while pressing the command/ctrl key. In my onChange event of the checkbox, I should know if the command/ctrl key was pressed or not. I tried reading the "window.event" variable but couldn't find any information related to the pressed command/ctrl key.

Any Suggestions?

Thanks,
Shivam</div>

**Comment by Lukas742** [comment]
Closed as this is more a general question on how to identify if CTRL or COMMAND is pressed and therefore has not much to do with UI5 Web Components for React. Please refer to the [Discussion](https://github.com/SAP/ui5-webcomponents-react/discussions/3402) if you need more information.
