### ISSUE TITLE
IllustratedMessage: The image and the text are not in the middle of the dialog when resizing

### ISSUE THREAD

**Issue by AlbertZ-prog** [SAP/ui5-webcomponents-react#3412]
Describe the bug :
We have a dialog containing a IllustratedMessage component.
The image and the text of this component are not in the middle of the dialog when resizing the dialog.

Sample to Reproduce :
import {
    Bar,
    Button,
    Dialog,
    DialogPropTypes,
    IllustratedMessage
} from '@ui5/webcomponents-react';
import React from 'react';

interface MemberSelectorDialogPropsImpl {
    /**
     * Whether or not the dialog is currently open
     */
    isOpen: boolean;

    /**
     * Mandatory callback for Cancel button
     */
    onCancel: () => void;
}

export const MemberSelectorDialogImpl = (props: MemberSelectorDialogPropsImpl) => {
    const onBeforeClose: DialogPropTypes['onBeforeClose'] = (event) => {
        // when the dialog is closed by pressing ESC,
        // we need to call onCancel() to notify the consumer
        if (event.detail.escPressed) {
            props.onCancel();
        }
    };

    const renderDialogHeader = () => {
        return (
            <Bar>
                {'Selector'}
            </Bar>
        );
    };

    const renderDialogFooter = () => {
        return (
            <Bar endContent={
                <>
                    <Button design='Emphasized'>
                        {'OK'}
                    </Button>
                    <Button onClick={props.onCancel}>
                        {'Cancel'}
                    </Button>
                </>
            } />
        );
    };

    return (
        <Dialog
            open={props.isOpen}
            header={renderDialogHeader()}
            footer={renderDialogFooter()}
            resizable={true}
            draggable={true}
            onBeforeClose={onBeforeClose}
        >
            <IllustratedMessage
                style={ { verticalAlign: 'middle', blockSize: '100%' }}
                name='EmptyList'
                titleText={'Title'}
                subtitleText={'Sub-Title'}
            >
            </IllustratedMessage>
        </Dialog>
    );
};

Just resize the dialog.

Expected behavior:
The expected behavior is to have the image and the text of the IllustratedMessage in the middle of the dialog.

Screenshots:

![Illustrated-message](https://user-images.githubusercontent.com/111968222/186461856-140d547f-0baa-433d-bb42-879bf0b9033a.png)

UI5 Web Components for React Information
@ui5/webcomponents version: "1.4.0"
@ui5/webcomponents-react version: "0.23.2"
Operating System: Win10
Browser: Chrome

Thanks a lot in advance!

**Comment by Lukas742** [comment]
Hi @AlbertZ-prog 

to center the `IllustratedMessage` it's probably easiest to just wrap it inside a flex container. Of course there are probably many more options to do this via css, but this is the first thing that came to my head.

See [codeSandbox](https://codesandbox.io/s/wcr-ts-template-forked-xb9jwz?file=/src/App.tsx)

**Comment by AlbertZ-prog** [comment]
Thanks very much Lukas for your help.
