### ISSUE TITLE
[SF]Dialog: The button in the dialog foot is flickering

### ISSUE THREAD

**Issue by BennyHuang** [SAP/ui5-webcomponents-react#3427]
**Describe the bug**
The button in the dialog foot is flickering

**Isolated Example**
It is reproducible in storybook https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-dialog--default-story

**To Reproduce**
1. Go to 'https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-dialog--default-story'
2. Click on 'Open Dialog'

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.6.0
`@ui5/webcomponents-react` version: 0.27.2
Operating System: MacOS 12.5.1
Browser: Chrome 104

**Comment by Lukas742** [comment]
Hi @BennyHuang 

I will close this issue as there is already another one covering this topic. If you have any questions or more informations, please address them in the [original issue](https://github.com/SAP/ui5-webcomponents/issues/5610).

Duplicate https://github.com/SAP/ui5-webcomponents/issues/5610
