### ISSUE TITLE
stableDomRef not working

### ISSUE THREAD

**Issue by kundarsowjanya** [SAP/ui5-webcomponents-react#3428]
Hi I'm using ShellBar component in UI5 but now after upgrade to latest version stableDomRef is not working in shellBarItem component is there any alternative way?

```
<ShellBarItem
        icon="sys-help"
        data-testid="webassistant-button"
        stableDomRef="webassistant-button"
      />
```
Thanks

**Comment by Lukas742** [comment]
Hi @kundarsowjanya 

just reposting the issue from `ui5-webcomponents` without any further information or linking the original issue doesn't really help us. In fact it makes our life harder as we may adress issues that are already solved. In this case I noticed that you already opened the same issue and also that you received some more information.

As @ilhan007 mentioned, the `stableDomRef` is deprecated and not supported anymore. To access the DOM node of the item you can use `getDomRef()` now. In React you can achieve this by attaching a ref and calling it there. Depending on your use case, you may have to wait until the item is defined.
