### ISSUE TITLE
Link: Click for one time but trigger twice

### ISSUE THREAD

**Issue by sleric1024** [SAP/ui5-webcomponents-react#3429]
**Describe the bug**
Link component will be triggered two times of events by clicking

**Isolated Example**
https://codesandbox.io/s/affectionate-sound-3svx07?file=/src/App.js

**To Reproduce**
1. Go to (https://codesandbox.io/s/affectionate-sound-3svx07?file=/src/App.js)
2. Click on link
3. Alert dialog will be shown twice

**Expected behavior**
Only one event should be triggered

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.6.0
`@ui5/webcomponents-react` version: 0.27.0
Operating System: Mac OS
Browser: Chrome

**Additional context**
**I am from SAP Successfactors, could you please help to look into this issues? Thanks**

**Comment by Lukas742** [comment]
Hi @sleric1024 

I will close this issue as there is already another issue covering this topic. If you have any questions or more informations, please address them in the [original issue](https://github.com/SAP/ui5-webcomponents/issues/5477).

Duplicate: https://github.com/SAP/ui5-webcomponents/issues/5477
