### ISSUE TITLE
SplitterLayout: with right-to-left layout, use of the splitter bar is reversed

### ISSUE THREAD

**Issue by ehn-sap** [SAP/ui5-webcomponents-react#3446]
**Describe the bug:** The splitter bar moves to the right when the mouse tries to drag it to the left, and respectively left when right.

**Isolated Example:** [Sandbox](https://codesandbox.io/s/magical-andras-3t5kbo?file=/src/App.tsx:152-375)

**To Reproduce**
1. Create a SplitterLayout with 2 SplitterElement
2. Set the layout to right-to-left
(by adding the html attribute dir='rtl' to the SplitterLayout,
or - not tested - by using a right-to-left language such as Hebrew or Arabic)
3. Using the mouse, drag the Splitter bar to the left: the bar moves to the right (resp. right and left)

**Expected behavior:** The splitter bar should follow the drag n drop move.

**Sandbox code**
```
import "./styles.css";

import {
  ThemeProvider,
  SplitterElement,
  SplitterLayout
} from "@ui5/webcomponents-react";

/**
 * Issue demonstration
 * When layout direction is right-to-left
 * (as in some locales such as Hebrew or Arabic),
 * Splitter bar use is reversed:
 * dragging the splitter bar to the right (resp. left)
 * actually moves it to the left (resp. right)
 */

export default function App() {
  return (
    <ThemeProvider>
      <SplitterLayout
        // Sets the html layout direction to right-to-left
        // It can be done also by using a right-to-left language,
        // such as Hebrew or Arabic
        dir="rtl"
        style={{ inlineSize: "100%", blockSize: "100%" }}
      >
        <SplitterElement
          size="60%"
          style={{ inlineSize: "100%", blockSize: "100%" }}
        >
          <h1>First part</h1>
        </SplitterElement>

        <SplitterElement
          size="40%"
          style={{ inlineSize: "100%", blockSize: "100%" }}
        >
          <h1>Second part</h1>
        </SplitterElement>
      </SplitterLayout>
    </ThemeProvider>
  );
}
```

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.4.0
`@ui5/webcomponents-react` version: 0.23.2
Operating System: W10
Browser: Chrome Version 104.0.5112.102 (Official Build) (64-bit)

**Comment by Lukas742** [comment]
Hi @ehn-sap 

I was only able to reproduce this issue in your codeSandbox when I changed the `dir` attribute and the app hot-reloaded. When manually refreshing the locale app, or when testing it in our storybook the issue didn't occur for me.

Could you verify if the behavior is the same for you?
In the Storybook you can change the directions here:
<img width="543" alt="Screenshot 2022-08-29 at 17 34 37" src="https://user-images.githubusercontent.com/9749730/187239886-70b99cc8-7ca8-440e-8bec-a672ef59593d.png">
https://sap.github.io/ui5-webcomponents-react/?path=/story/layouts-floorplans-splitterlayout--default-story

**Comment by ehn-sap** [comment]
Hi @Lukas742 

You're right, the behavior is not so systematic, I have the same results.

I noticed the issue while adding a RTL switch button in our own storybook to test our component (embedded version, and dialog version).
This button just sets the dir attribute on the embedded version (already displayed in the page), or on the dialog to display.

In my understanding, that's enough, but the issue could show an inconsistent DOM state? (same for the hot-reload of the sandbox app)
Maybe the button in your storybook is doing something more, leading to a better state?

**Comment by Lukas742** [comment]
Yup, you're right. The problem here is our rtl detection. In runtime we only observe the element itself (which in this case is the internal `Splitter` and not the layout - I will look into that), the `document.body` and the `document.documentElement`. That's why it's working in our storybook, as the direction is changed there directly on the `html` tag (`document.documentElement`). --> [codeSandbox](https://codesandbox.io/s/amazing-pasteur-zrhk3d?file=/src/App.tsx)

In general it's not recommended changing the direction in runtime or setting the `dir` attribute for productive apps, as the direction should be controlled by the localization, only then you can be sure that the correct direction is used. When it's necessary to change the direction, e.g. for demo apps like the storybook, then it's probably best to change it on a global level, so our observer is sure to pick up the change.

**Comment by Lukas742** [comment]
With the linked PR it is now possible to programmatically change the `dir` attribute of the SplitterLayout` component in runtime. The fix will be available with our next release.

**Comment by ehn-sap** [comment]
Gret, @Lukas742, thanks a lot!
It's going to help us to ensure our component behaves well in RTL contexts!
