### ISSUE TITLE
TextArea: 1 Row Shows ScrollBar

### ISSUE THREAD

**Issue by IrvinDelgado** [SAP/ui5-webcomponents-react#3455]
**Describe the bug**
Using property `rows={1}` shows a scrollbar which shouldn't be there.

**To Reproduce**
1. Go to '[ui5-webcomponents-react sandbox](https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-textarea--default-story)'
2. Change properties rows to 1
3. you will see a scrollbar

**Expected behavior**
No scrollbar should appear

**Screenshots**

<img width="1137" alt="Screen Shot 2022-08-31 at 11 11 43 AM" src="https://user-images.githubusercontent.com/62973847/187750321-ed63ff98-93a4-4bf8-aad2-f96b659f0032.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.6.0
`@ui5/webcomponents-react` version: 0.27.4
Operating System:
Browser: Chrome

**Comment by Lukas742** [comment]
Hi @IrvinDelgado 

thanks for reporting. The UI5 Web Components team is aware of the issue and are working on a fix. You can track the progress, or raise any questions here: https://github.com/SAP/ui5-webcomponents/issues/4512
