### ISSUE TITLE
AnalyticalTable: Loading shimmer bug

### ISSUE THREAD

**Issue by stsander07** [SAP/ui5-webcomponents-react#346]
**Describe the bug**
I believe there is a bug in the AnalyticalTable loading in v0.8.6. When the loading property is set to true, I am seeing the shimmer acting weird. It only seems to cover a small portion of the table. This codesandbox should show it:
https://codesandbox.io/s/stupefied-wilson-tcdn7

This didn't happen in v0.8.5

**To Reproduce**
1.Create an Analytical Table with one column
2. set loading to true

**Expected behavior**
Shimmer should cover the whole width of the table as in v0.8.4 / v0.8.5

**Screenshots**
https://codesandbox.io/s/stupefied-wilson-tcdn7

**UI5 Web Components for React Information**
Operating System:
`@ui5/webcomponents-react` version: v0.8.6
Do you have a dependency to`@ui5/webcomponents` in your package.json? If yes, which version?:

*If you are not sure, you can find out by running `npm ls @ui5/webcomponents-react` or `yarn why @ui5/webcomponents-react`*

**Additional context**

**Comment by MarcusNotheis** [comment]
Release Candidate available: `@ui5/webcomponents-react@0.8.7-rc.0`
