### ISSUE TITLE
ObjectPage/ObjectPageSection: Object Page is broken

### ISSUE THREAD

**Issue by BennyHuang** [SAP/ui5-webcomponents-react#3464]
**Describe the bug**
After upgrading UI5 Web Components to  1.7.0 and UI5 Web Components React to 0.27.5, ObjectPage is broken because of the javascript error thrown from TabContainer. `this.getDomRef()` returns undefined.

<img width="881" alt="image" src="https://user-images.githubusercontent.com/1995447/188216188-6ae0796f-fef5-4344-82cd-a6b9a3d90dd8.png">

**Isolated Example**
It can be reproduced here https://codesandbox.io/s/intelligent-panka-l4hujt?file=/src/App.js
<img width="1719" alt="image" src="https://user-images.githubusercontent.com/1995447/188216379-2596ab6c-c260-4979-91db-d71631412758.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.7.0
`@ui5/webcomponents-react` version: 0.27.5

**Additional context**

**Comment by Lukas742** [comment]
Hi @BennyHuang 

`@ui5/webcomponents` version 1.7.0 is not supported yet (you should see a peer-dependency error when installing this package). We're currently blocked from updating by exactly the issue you described. (See [here](https://github.com/SAP/ui5-webcomponents/issues/5778)).

**Comment by MarcusNotheis** [comment]
Closing this issue as UI5 Web Components 1.7.0 is not a valid peer dependency of our 0.27.x release.

**Comment by zariman** [comment]
This error is still happening even with @ui5/webcomponents 1.5.0. The issue seems to be with the 0.27.x release

**Comment by MarcusNotheis** [comment]
`@ui5/webcomponents@1.5` is not a valid peer dependency of `@ui5/webcomponents-react@0.27` as well, please either use `@ui5/webcomponents@1.6` or `@ui5/webcomponents-react@0.26`. Currently you should see a peer dependency warning in your terminal when installing dependencies.
