### ISSUE TITLE
[SF][MessageBox][a11y] Implement role="alertdialog" for Warning and Error type

### ISSUE THREAD

**Issue by lormanlau** [SAP/ui5-webcomponents-react#3480]
**Is your feature request related to a problem? Please describe.**
MessageBox does not label the role as an alertdialog when the type is set to Warning or Error.
UI5 WC team added the feature requested in https://github.com/SAP/ui5-webcomponents/pull/5587

**Describe the solution you'd like**
Update the state of the dialog https://github.com/SAP/ui5-webcomponents-react/blob/1ae40613c607c82a62bd600d161da2a0d341013e/packages/main/src/components/MessageBox/index.tsx#L244 to pass the type to the dialog so that it would set the role="alertdialog" as neccessary 

**Describe alternatives you've considered**
Add a way for MessageBoxes to add role to section of the shadowroot.

**Additional context**

**Comment by MarcusNotheis** [comment]
Thanks for reporting.
We'll look into this issue during the update for UI5 Web Component 1.7.0.

We've also raised another issue to expose the `accessibleRole` prop to allow modifying the role from the outside: https://github.com/SAP/ui5-webcomponents/issues/5781
