### ISSUE TITLE
SplitButton: doesn't work with React Router Link 

### ISSUE THREAD

**Issue by francinyreichert** [SAP/ui5-webcomponents-react#3509]
**Describe the bug**
I'm trying to use `SplitButton` with `Menu`, but I need to use `Link` from `react-router-dom` to open a link in a new tab and it's not working. 

`Link` is necessary because Router cannot find the route when opening a link in a new tab. `MenuItem` doesn't allow `Link` to wrap it or as children, and when using `Link` to wrap `SplitButton` everytime user clicks on the arrow icon, link opens in a new tab.

**Expected behavior**
When clicking on split button arrow, menu should open with menu items. When clicking on an item, a new tab should open.

**Screenshots**
This is the component that we have: 

<img width="158" alt="image" src="https://user-images.githubusercontent.com/65377988/189732539-9ea420db-d3e7-4607-8089-36dcdf148635.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:
`@ui5/webcomponents-react` version:
Operating System:
Browser:

**Additional context**
This is for a CIM internal project.

**Comment by Lukas742** [comment]
Hi @francinyreichert 

wrapping components is in most cases not recommended as it can break internal styles and behavior. Please use the respective hook for navigating instead. --> [codeSandbox](https://codesandbox.io/s/wcr-react-router-ecyybw?file=/src/Users.jsx)

**Comment by francinyreichert** [comment]
Hi @Lukas742, it worked using only window.open(), thank you!
