### ISSUE TITLE
Incorrect event property for Button in Getting Started

### ISSUE THREAD

**Issue by nitish-mehta** [SAP/ui5-webcomponents-react#351]
**Describe the documentation issue**

- [ ] Documentation is unclear
- [X] Documentation is incorrect
- [ ] Documentation is missing
- [ ] Other

**Description of the issue**

Getting Started guide mentions event for Button as `onPress`. 
https://sap.github.io/ui5-webcomponents-react/?path=/docs/1-welcome-getting-started--page

Correct event -> `onClick`
![image](https://user-images.githubusercontent.com/15953522/76771888-06978400-67c6-11ea-81fb-58bdc25c9829.png)

**Comment by MarcusNotheis** [comment]
Hi @nitish-mehta 
thanks for reporting that issue. We have fixed it in our documentation and the docs will update as soon as we will publish the next release.
