### ISSUE TITLE
VariantManagement: Cancel button should have design transparent 

### ISSUE THREAD

**Issue by francinyreichert** [SAP/ui5-webcomponents-react#3511]
**Describe the bug**
`VariantManagement` cancel button should have design transparent, not emphasized.

**Isolated Example**
https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-variantmanagement--default-story

**To Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-variantmanagement--default-story
2. Set `showCancelButton` to true
3. Open variant management
4. Button has design emphasized

**Expected behavior**
Button should have design transparent

**Screenshots**
On ui5-webcomponents-react documentation:

<img width="438" alt="image" src="https://user-images.githubusercontent.com/65377988/189764459-b6364c3a-36e7-4a5e-9de9-4d41ef8b96d5.png">

On fiori guidelines (https://experience.sap.com/fiori-design-web/variant-management/#responsiveness):

<img width="563" alt="image" src="https://user-images.githubusercontent.com/65377988/189764559-de07f8a3-e11f-46f5-bb04-8c510d9874f0.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:
`@ui5/webcomponents-react` version:
Operating System: all
Browser: all 

**Additional context**
This is for a CIM internal project.

**Comment by Lukas742** [comment]
Hi @francinyreichert 

when fixing the issue you mentioned here, I realized that the `showCancelButton` prop is a revenant of an older implementation and design. I'll discuss with a colleague if we should keep this prop and the respective button, or if we should remove it. Just a heads up, that this prop (and the respective button) could be removed with our 1.0.0 version coming end of the month.
