### ISSUE TITLE
OnLoadMore Functionaltity in UI5 table.

### ISSUE THREAD

**Issue by kundarsowjanya** [SAP/ui5-webcomponents-react#3518]
Hi I'm using ui5/webcomponents-react  version 0.13.11 , I have huge number of data more than 5000, and I'm using,
Array.map  as I have huge data rendering is too slow. So I wanted introduce onLoadMore, but is it possible to implement onLoadeMore without calling any API, because I already stored this 5000 records in state, I just want use that array.
I don't want to call API, Every click I want to load  100 records.

Could you please suggest me the solution?

Thanks

**Comment by Lukas742** [comment]
Hi @kundarsowjanya 

It shouldn't make a difference if you retrieve the data in whole or in parts from the server in the end you have to map it to the rows anyway. So, if you have 5000 entries in your dataset, shouldn't it be sufficient to split up the dataset in subsets containing 100 entries? If this is not what you meant, I think it's probably best if you could add an example of what you want to achieve. 
Also, I would recommend updating your version as 0.13.11 is over two years old and we can't offer support for deprecated versions.
