### ISSUE TITLE
Analytical Table : UI breaks when sorting is applied to a popIn column

### ISSUE THREAD

**Issue by Bilal3120** [SAP/ui5-webcomponents-react#3529]
**Describe the bug**
Table breaks after a column which is sorted is popped in

**Isolated Example**
[Codesandbox](https://codesandbox.io/s/popincolumnsort-g4eg7s?file=/src/App.js)

**To Reproduce**
1. Go to [Codesandbox](https://codesandbox.io/s/popincolumnsort-g4eg7s?file=/src/App.js)
2. Apply sorting on 2nd column
3. Decrease the table width so that the 2nd column is popped in
4. The screen breaks

**Expected behavior**
Sorting should be preserved even after popping in

**Screenshots**
<img width="758" alt="Screenshot 2022-09-15 at 11 42 50 AM" src="https://user-images.githubusercontent.com/93638146/190328049-88624bc8-c5a6-4e1d-96af-eaf1893d0aad.png">

<img width="502" alt="Screenshot 2022-09-15 at 11 37 22 AM" src="https://user-images.githubusercontent.com/93638146/190328119-9574cfb1-8fef-40d1-a994-e853b974f7da.png">

**Comment by Lukas742** [comment]
Hi @Bilal3120 

the linked PR should fix the issue. 
Please note, that sorting a table by a popped-in column is not supported. After the PR is merged and released a sorted popped-in column will reset its table sorting until it's visible again. It is recommended to only apply column options like filtering and sorting to columns that are always visible (never popped-in).
