### ISSUE TITLE
MultiComboBox: Scroll bar visible when more items selected than space available.

### ISSUE THREAD

**Issue by n-devlin** [SAP/ui5-webcomponents-react#353]
**Summary:**
For the MultiComboBox, according to Fiori, when there are more items selected than space available, scrolling behavior exists, but a scroll bar is not visible. Currently, when more items are selected, a scroll bar pops up, blocking the view of the Tokens selected.

**Current Behavior:**
1. MultiComboBox (with either less width or enough elements to take up at least the width of the MultiComboBox.
2. Multi-select items to fill the space.
3. See that a scroll bar appears, which in the Fiori images, does not become visible.

**Expected Behavior:**
1. MultiComboBox (with either less width or enough elements to take up at least the width of the MultiComboBox.
2. Multi-select items to fill the space.
3. As more items are selected, items are pushed to the left out of view, but no scroll bar is visible.

**Screenshots:**
Current behavior:
![Screen Shot 2020-03-16 at 9 44 58 AM](https://user-images.githubusercontent.com/61565124/76782982-5185ad00-676e-11ea-8f62-25a21a28b8a2.png)

Fiori expected behavior:
![Screen Shot 2020-03-16 at 9 52 21 AM](https://user-images.githubusercontent.com/61565124/76783019-5f3b3280-676e-11ea-9f22-416885c17dab.png)

**Comment by MarcusNotheis** [comment]
Hi @n-devlin 
thanks for reporting this issue with so many details. As the `MultiComboBox` Component is provided by our UI5 Web Components colleagues, I copy-pasted your issue describtion and created a new issue on their side. As soon as they have release a fixed we'll update to that new version as well.

https://github.com/SAP/ui5-webcomponents/issues/1304

**Comment by n-devlin** [comment]
Thank you so much!

Best,
Nora Devlin

**Comment by MarcusNotheis** [comment]
Released in `@ui5/webcomponents-react@0.9.0-rc.9`
