### ISSUE TITLE
webcomponents-react-base: Missing variable export 'useIsomorphicId'

### ISSUE THREAD

**Issue by okleberaraujo** [SAP/ui5-webcomponents-react#3546]
Error when using the component webcomponents-react-charts. Seems that one variable doens't exist yet and is beeing used in ColumnChartWithTrend component. the variable is: 'useIsomorphicId'.

**Isolated Example**
I did nothing but installing the last version of the react webcomponents, fiori, charts and base...

**To Reproduce**
1. Install all webcomponents
2. Install the chart component
3. Try to use one of the charts
4. The error "ERROR in ./node_modules/@ui5/webcomponents-react-charts/dist/components/ColumnChartWithTrend/ColumnChartWithTrend.js 52:17-32" will appear even you are not using the ColumnChartWithTrend component.

**Expected behavior**
ERROR in ./node_modules/@ui5/webcomponents-react-charts/dist/components/ColumnChartWithTrend/ColumnChartWithTrend.js 52:17-32

**Screenshots**
![image](https://user-images.githubusercontent.com/86311431/191341569-e9070f8a-c586-4f26-9f6d-8e052e7ba337.png)
![image](https://user-images.githubusercontent.com/86311431/191341631-30dae6ee-45b1-40c1-a969-a12fd3bfe674.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 0.28
`@ui5/webcomponents-react` version: 0.28
Operating System: Windows 10
Browser: All

**Comment by Lukas742** [comment]
Hi @okleberaraujo 

I could not reproduce this issue. Are you sure you're using the same minor version of `@ui5/webcomponents-react, `@ui5/webcomponents-react-charts` and if you manually installed the base package, `@ui5/webcomponents-react-base` as well.

Also, please have a look at this [codeSandbox](https://codesandbox.io/s/columnchartwithtrend-default-5ocye5) and tell me if I missed something there.

**Comment by okleberaraujo** [comment]
After upgrade the Node, NPM and the React the issue is gone. Thanks!
