### ISSUE TITLE
[SF][BUG][DynamicPage] The behavior of DynamicPage between Windows and Mac OS Should be same

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents-react#3549]
Dear colleagues,
I am from SuccessFactors Web Experience Shanghai team.

**Expected behavior:**
The behavior of DynamicPage between Windows and Mac OS Should be same

**Current behavior:**
In Mac OS, labels are aligned with icons and the header content size is reduced, however in Windows, icons are placed above the label section and the header size is growing.

<img width="1077" alt="image003" src="https://user-images.githubusercontent.com/78520316/191407612-34bf03eb-dee1-46ac-9f66-5b28989d60ce.png">

This is the Visual Core of DynamicPage: [https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2697896790](https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2697896790)

**Comment by Lukas742** [comment]
Hi @sfsf-xweb-sh 

please provide an example of the implementation and the screen resolution you used for both screenshots.
