### ISSUE TITLE
AnalyticalTable: tree table does not render components in cell

### ISSUE THREAD

**Issue by stsander07** [SAP/ui5-webcomponents-react#358]
**Describe the bug**
Creating a tree table does not render anything like Button's, Text's, etc in any cell. Only data accessors are shown

**To Reproduce**
https://codesandbox.io/s/dawn-http-e7o19

**Expected behavior**
I expect the Text components to be rendered inside of the first Actions column. I have two actions columns to demonstrate that it does not work in any column of the tree table. I wanted to use Buttons but codepen was not compiling the code correctly when I used them -- so I commented them out for now.

It works in a non-tree table as also shown in the codepen.

**UI5 Web Components for React Information**
Operating System:
`@ui5/webcomponents-react` version: 0.8.6

**Comment by MarcusNotheis** [comment]
Hi @stsander07  
the fix is released in `@ui5/webcomponents-react@0.8.7-dev.12`

**Comment by stsander07** [comment]
Hi Marcus,

After upgrading I am receiving this error:

Failed to compile.

./node_modules/@ui5/webcomponents-react/lib/ThemeProvider.js
Module not found: Can't resolve '@ui5/webcomponents-react-base/lib/ThemingParameters' in 'C:\Users\I858355\Documents\1 - Code\ibp-react-ui\node_modules\@ui5\webcomponents-react\lib'

Do you know if there is an issue with the build?

**Comment by MarcusNotheis** [comment]
Hi @stsander07, if you update to `0.8.7-rc.0` the build error should be fixed and you can remove the `resolutions` field we talked about yesterday.
