### ISSUE TITLE
SF-ACC: DynamicPage: font-family of title looks different between Safari and Chrome under horizon theme

### ISSUE THREAD

**Issue by sleric1024** [SAP/ui5-webcomponents-react#3583]
**Describe the bug**
The font-family of dynamic page looks different between Safari and Chrome **under horizon theme**

**Isolated Example**
We can reproduce in playground. 
https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-dynamicpage--always-show-header-content&globals=theme:sap_horizon

**Screenshots**
![image](https://user-images.githubusercontent.com/5724592/192712607-91c5cd7e-435a-49f8-9e0f-76f23533eed8.png)
![image](https://user-images.githubusercontent.com/5724592/192712619-cb13c0a6-7f3a-4c1e-bcae-17be17d25e82.png)

**Expected behavior**
The font-family should be same between Safari and Chrome

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.7.1
`@ui5/webcomponents-react` version: 0.28.1
Operating System: MacOS
Browser: Chrome & Safari

**Additional context**
I am from Successfactors.

**Comment by MarcusNotheis** [comment]
Hey Erick,
this is actually a bug in UI5 Web Components which is [already fixed](https://github.com/SAP/ui5-webcomponents/commit/d2fc095515de7c77f06a4d423f59702b14460a91) but not released yet.
Safari is not reading local fonts and the Font Family of the Dynamic Page Title is not loaded correctly as a network resource. Chrome reads the locally installed font, so this is why it is working in Chrome.

I'll keep this issue open until the new UI5 Web Components release is available.
