### ISSUE TITLE
RadioButton: "Tab" button control is stuck inside RadioButton group and not functioning adequately

### ISSUE THREAD

**Issue by knandan15** [SAP/ui5-webcomponents-react#3585]
**Describe the bug**
When switching between components using "TAB" and "SHIFT+TAB", when the control arrives inside RadioButton, it does not move out of the RadioButton group to other components.

**Isolated Example**
UI Link
Refer: https://codesandbox.io/s/radiobutton-tab-issue-r94oco?file=/src/App.js

**To Reproduce**
1. Click any component above Radio buttons say, on Button "Btn 1"
2. Press TAB on Keyboard. It will shift the focus to the next component i.e. the Input Field
3. Press TAB again, it will shift the focus to the first Radio Button. Now on pressing TAB or Shift+TAB, nothing is happening. If we press SPACE then the corresponding Radio Button will get selected and with arrow keys we can navigate among the radio buttons.

**Expected behavior**
Upon pressing TAB, the focus should have come out of the Radio Button group to the next component (Input field).

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: ^1.6.0
`@ui5/webcomponents-react` version: ^0.27.0
Operating System: Windows 10 Enterprise
Browser: Google Chrome, Edge

**Comment by Lukas742** [comment]
Hi @knandan15 

could you please check your codeSandbox, you probably didn't save the last edit as there are no RadioButtons used in it.

**Comment by Lukas742** [comment]
As described in our [documentation](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-list--default-story), the `List` component only supports `StandardListItem`, `CustomListItem` or `GroupHeaderListItem` as `children`, also I'm not sure why you are rendering a list for each RadioButton. If you to align the buttons vertically, you can for example use a flexbox. 

[Here](https://codesandbox.io/s/radiobutton-tab-issue-forked-sfvzql?file=/src/App.js) you can find an example of the implementation, using a flexbox.

There are a two more points that don't have something to do with your problem directly, but could cause issues in the future.

- You didn't wrap your components inside the `ThemeProvider` as described [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/getting-started--page). (section _Add @ui5/webcomponents-react to an existing app_)
- In most cases, a RadioButtonGroup should contain one selected RadioButton.
