### ISSUE TITLE
AnalyticalTable: useIndeterminateRowSelection and switch from TreeTable to flat give an inconsistent behavior

### ISSUE THREAD

**Issue by DanielCavemann** [SAP/ui5-webcomponents-react#3604]
When a AnalyticalTable with useIndeterminateRowSelection switch from TreeTable to flat table, if an element is selected in the subrows, the row keep as indeterminate state.

Example: https://codesandbox.io/s/cocky-nash-bgd8d7?file=/src/App.js

1. Click on 'SelectedRows' button (it selects a children in the tree)
2. Click on 'ChangeTreeTable' button (we change table property from TreeTable (true to false)
3. Click on 'UpdateTable' button (we update the table, so we reload it and it flattens the table)
4. The rows is still selected with indeterminate state

**Expected behavior**
We should have nothing selected, and we should selected or unselect the row.

**Screenshots**
See attachment for screenshot

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: all
`@ui5/webcomponents-react` version: all
Operating System: windows 10
Browser: chrome
![ScreenshotAnalyticalTableBug](https://user-images.githubusercontent.com/113375930/193548691-0c414b3b-14f2-4a3b-8b40-8e503cd0bb52.jpg)

**Comment by Lukas742** [comment]
Hi @DanielCavemann 

the linked PR should fix the issue, but when I looked into your codeSandbox I noticed that you often try to update the component with a ref that isn't supported. I have added a note to each line that I think is bad practice, or will not work at all: https://codesandbox.io/s/young-violet-d2e7yy?file=/src/App.js

**Comment by DanielCavemann** [comment]
Hi @Lukas742,
Thanks a lot for your fix and your comments. It will greatly help us.
Have a nice day

Daniel
