### ISSUE TITLE
AnalyticalTable: Lines between columns partly blurry

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents-react#3605]
**Describe the bug**
This bug was forwarded to me by one of our testers:
In an AnalyticalTable with 3 columns, the vertical line separating the 2nd and 3rd column is displayed a little blurry. It's barely visible, but here's a zoomed-in screenshot:

![Capture](https://user-images.githubusercontent.com/110408767/193584614-a911e18e-df1f-46e3-ac84-6b6b64609ae5.PNG)

Please note that the line is only blurry on the rows which contain data. In the screenshot, it's the first 2 rows. If I add a third row, the line is now blurry on 3 rows. The line is fine for the empty filler lines that are added at the end.

**Isolated Example**
[Here's a sandbox.](https://codesandbox.io/s/eloquent-brown-n5iqjc?file=/src/App.js)

**To Reproduce**
Just opening the sandbox suffices for me, the behavior can be seen in both the preview pane and full screen.

**Expected behavior**
The vertical line should be a single pixel wide on all rows.

Thanks a lot in advance!

**Comment by Lukas742** [comment]
Hi @ej612 

I can not reproduce this issue with the given codeSandbox (see screenshot). Could you please tell me which browser, os and screen resolution you're using?

<img width="268" alt="image" src="https://user-images.githubusercontent.com/9749730/193997278-facaa3cc-a8ce-49fd-8ada-68d971d93b15.png">

**Comment by Lukas742** [comment]
Hi @ej612 

We try to do our best :) 

In fact, I was just about to ask you if this issue was resolved on your end, since I couldn't reproduce it 100%, but we had a discrepancy in the calculation of cells in empty rows in some cases (1px was off), which could probably cause the lines to look blurry.
Where you able to already test the new version?
