### ISSUE TITLE
[SAP][Analytical Table] GlobalFilter does not work with tree table

### ISSUE THREAD

**Issue by thisisjasmeet** [SAP/ui5-webcomponents-react#3611]
**!! **It is needed for Internal SAP consumption** !!**

**Describe the bug**
In Analytical tree table there are nested nodes

Scenario - 1 
root node contains text - ABC
child node contains text - ABC

if I search ABC
both root and child nodes are displayed

Scenario - 2
root node contains text - ABC
child node contains text - XYZ

if I search XYZ
No Row is displayed

**Isolated Example**
Scenario is reproducible in Your story book tree table 
https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable--default-story

https://user-images.githubusercontent.com/57886348/193809430-e01e970a-cfc7-495b-8b32-2f9654cefb78.mp4

**Expected behavior**
Search should work for all nested rows

**UI5 Web Components for React Information**
`@ui5/webcomponents-react` version:  v 1.0.1
Operating System: macos
Browser: chrome

**It is needed for Internal SAP consumption**

**Comment by Lukas742** [comment]
Solved after internal discussing and by leveraging this [codeSandbox](https://codesandbox.io/s/treetable-forked-38lrm8?file=/src/App.js) example.
