### ISSUE TITLE
ObjectPageSection: Using fixed color on header title

### ISSUE THREAD

**Issue by lpohren** [SAP/ui5-webcomponents-react#364]
**Describe the bug**
The header Title of the object pages is using a fixed color and not a ui5 variable.
This blocks me form customizing the title color easily.

**To Reproduce**
1. Open a Object page
2. Inspect the header title color property

**Expected behavior**
Should be using a variable like var(--sapUiSomeColor)

**Screenshots**
![image](https://user-images.githubusercontent.com/16123699/77174718-41d4d400-6aa0-11ea-9f81-53972450532b.png)

**UI5 Web Components for React Information**
Operating System:
`@ui5/webcomponents-react` version: "0.9.0-rc.1"

**Comment by MarcusNotheis** [comment]
Hi @lpohren 
thanks for submitting this issue. The internally used Tab Container will use a CSS Variable in the upcoming release of the UI5 Web Components: `var(--_ui5_tc_headerItem_color)`.
We expect the release within the next week or two.

**Comment by lpohren** [comment]
Thanks a lot @MarcusNotheis ! :smile:

**Comment by lpohren** [comment]
@MarcusNotheis , can you also consider the Header tab of the `<TabContainer/>` ? The exact same problem happens there, using the same variable for both is fine :)
![image](https://user-images.githubusercontent.com/16123699/77585730-bdc98480-6ec3-11ea-8ca3-c4f3b7c2bc07.png)

**Comment by MarcusNotheis** [comment]
Hi @lpohren, yes this will be fixed with the new Web Components version as well. Actually the ObjectPage is now rendering the header of the TabContainer as Anchor Bar as there the whole RTL and Accessibility is already built-in.

**Comment by MarcusNotheis** [comment]
Released in `@ui5/webcomponents-react@0.9.0-rc.9`. You can now use `--_ui5_tc_headerItem_color` for overwriting the color of the header text.
