### ISSUE TITLE
Card; CardHeader; Wrapped Div: onClick event does not work for header

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents-react#3643]
**Describe the bug**
I can´t assign a click event to the card header. The click event will get somehone overwritten by something?
I tryed to assign the event to the card itself and the cardheader component, both do not work.
I event tried to wrap the card within a div element, and this will not work too?

**Isolated Example**
https://codesandbox.io/s/blissful-feynman-qooo3n?file=/src/App.js

Try click the header. And watch the console.

**To Reproduce**
1. Go to the sandbox
2. Click on the CardHeader
3. Open the Console
4. See that nothing happened

**Expected behavior**
A click event for all three events should be working.

1. Div Element
2. Card Component
3. CardHeader Component

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:  1.8.0
`@ui5/webcomponents-react` version: 1.1.0
Operating System: Windows
Browser: Chrome 106.0.5249.119

**Additional context**

**Comment by Lukas742** [comment]
Hi @C3ntraX 

the `interactive` prop is missing on the `CardHeader`. [codeSandbox](https://codesandbox.io/s/suspicious-napier-c3wfgm?file=/src/App.js)

>Defines if the component would be interactive, e.g gets hover effect, gets focus outline and onClick event is fired, when pressed.

**Comment by C3ntraX** [comment]
Hi @Lukas742,

Thanks! Simple solution yes, but I hadn't even thought of this kind of solution. It's an interesting design decision.
