### ISSUE TITLE
Lazy loading capability on AnalyticalTable

### ISSUE THREAD

**Issue by DanielCavemann** [SAP/ui5-webcomponents-react#3645]
Description
We are currently implemented a new brand member selector for SAC based on webcomponent-react and we would used this capabilities which is already implemented in ReactTable.

Add the capability in AnalyticalTable.

Without this, we will be force to write a by ourself a mechanism to reach the react-table and use the feature.

Additional context
See example provide by react-table: https://react-table-v7.tanstack.com/docs/examples/sub-components-lazy

**Comment by Lukas742** [comment]
Hi @DanielCavemann 

we do not plan to support this feature directly in the current implementation of AnalyticalTable, as this would require a complete refactoring of the component.

Depending on your implementation, you may be able to use a workaround to implement lazy loading anyway. However, you will need to adjust your data to do this. I created a codeSandbox that shows a basic example on how this can be achieved: https://codesandbox.io/s/treetable-lazy-j4grje?file=/src/App.js

**Comment by DanielCavemann** [comment]
Hi @Lukas742 ,
Thank you for your message and your codeSandbox, it will be very useful.
Thank you again.
