### ISSUE TITLE
Button: Control Icon Size

### ISSUE THREAD

**Issue by isaqueha** [SAP/ui5-webcomponents-react#365]
**Description**
I would like to control the size of an Icon inside a Button.

**Is your feature request related to a problem? Please describe.**
I was developing a feature where a Button with a big Icon was needed, but there is no simple way to achieve that.

**Describe the solution you'd like**
I would like a property inside the Button component to control the Icon size through CSS or so.

**Describe alternatives you've considered**
I tried to alter several different CSS properties in the Button component so the Icon would be affected. No result so far.
Some ideas:
- https://sapui5.hana.ondemand.com/#/api/sap.ui.core.Icon
- https://sap.github.io/ui5-webcomponents/playground/components/Icon (see Customized Icons)

**Additional context**
As seen in the screenshot below, I wanted to make the `sys-cancel` Icon inside the Button as big as the `search` Icon in the left of the Bar:

![image](https://user-images.githubusercontent.com/13629975/77176503-f53ec800-6aa2-11ea-8f65-902cc9f02668.png)

The `search` Icon size was controlled with the `width: 1.5rem` CSS property.

**Comment by MarcusNotheis** [comment]
Hi @isaqueha - thanks for submitting this issue.
As the Button and the Icon are both developed by our UI5 Web Components colleagues, I forwarded this issue to their repository: https://github.com/SAP/ui5-webcomponents/issues/1327

**Comment by MarcusNotheis** [comment]
Closing this as it was resolved in the Web Components Issue Thread.
