### ISSUE TITLE
Analytical Table: When selectionBehavior is RowOnly then ideally feeder-arrow should come in the last cell.

### ISSUE THREAD

**Issue by AkshitaDhiman77** [SAP/ui5-webcomponents-react#3654]
**Describe the bug**
When in Analytical Table selectionBehavior is RowOnly then the last column of every row should contain a "feeder-arrow" icon.

**Expected behavior**
There should be an out-of-the-box "feeder-arrow" icon present in the last row of the analytical table if the selectionBehaviour is RowOnly.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: ^1.6.0
`@ui5/webcomponents-react` version: 0.27.5
Operating System: windows 10 x64
Browser: Microsoft edge

**Comment by Lukas742** [comment]
Hi @AkshitaDhiman77 

the arrow indicates that you can navigate by clicking on the row. Since this is not always the case and I could not find any design guidelines for it, we do not plan to implement this feature.

**Comment by AkshitaDhiman77** [comment]
Hi @Lukas742,

As suggested by you I already have that part, but for the particular icon accessibleName mentioned in the cell is not getting accessible. 

So if possible can you add some property in icon component with labelTooltip kind of property behavior.

**Comment by Lukas742** [comment]
I'm not sure what you mean with "is not getting accessible". 
If you want the cell with the icon (or all cells) to read out a different text when focused, then you'll have to customize the `aria-label` of the cell(s). You can achieve this with a custom plugin hook.

E.g.:
https://codesandbox.io/s/defaulttable-forked-3v905q?file=/src/App.js

**Comment by AkshitaDhiman77** [comment]
Thank you for the suggestion, it worked for me.
