### ISSUE TITLE
AnalyticalTable Select All Not Work

### ISSUE THREAD

**Issue by observer1220** [SAP/ui5-webcomponents-react#3657]
AnalyticalTable has a "Select All Box", but when I click the box, it's not work.

I see the developer teams has fixed this issue on [v0.18.6](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.18.6)
but it seems broke again on [v0.28.2]

Procedure
1. Click"Select All Box" to trigger "onRowSelect" method.
2. When I use console.log to see the details
- event.detail.allRowsSelected shows true
- but isSelected in each selectedFlatRows are still false.

Please check the codesandbox here
https://codesandbox.io/s/boring-germain-kcebk3

Thanks for your works

**Comment by Lukas742** [comment]
Hello @observer1220 

this issue is related to React 18 Strict Mode, without it it works, so it should not affect your productive app.

The linked PR will fix the behavior in Strict Mode as well.
