### ISSUE TITLE
[SAP][Analytical Table][HIGH] SelectedFlatRows only contains only those selected rows which are visible in ui

### ISSUE THREAD

**Issue by thisisjasmeet** [SAP/ui5-webcomponents-react#3659]
**Describe the bug**
SelectedFlatRows only contains only those selected rows which are visible in UI

**To Reproduce**
1) Filter a row and select it.
2) filter another row (previously selected row should not be visible)

Observation
e.detail.selectedFaltRows only has 1 item in array (the selected row which got filtered is not part of array)
3) remove the filter
Observation
selected rows which got filtered are still selected.

**Expected behavior**
all the selected rows should be returned as flat rows

https://user-images.githubusercontent.com/57886348/196667474-fc7ac495-ce55-465f-ba4e-705b74fe4088.mov

UI5 Web Components for React Information
@ui5/webcomponents-react version: v 1.0.1
Operating System: macos
Browser: chrome

It is needed for Internal SAP consumption

**Comment by thisisjasmeet** [comment]
@Lukas742  this change is causing regression 

https://user-images.githubusercontent.com/57886348/197931780-eae5929b-d169-4453-957d-978a46066bca.mp4
please reopen the ticket

**Comment by Lukas742** [comment]
Fixed in #3659

Release is coming later today.

**Comment by thisisjasmeet** [comment]
@Lukas742  after upgrade i am getting this issue for all webcomponents 

Property 'nonce' is missing in type '{ children: string; onClick: () => void; }' but required in type 'Pick<ButtonPropTypes & WithWebComponentPropTypes, "onError" | "children" | "id" | "color" | "translate" | "hidden" | "slot" | ... 256 more ... | "submits">'.ts(2741)


		"@ui5/webcomponents": "1.9.0",
		"@ui5/webcomponents-fiori": "1.9.0",
		"@ui5/webcomponents-icons": "1.9.0",
		"@ui5/webcomponents-icons-business-suite": "1.9.0",
		"@ui5/webcomponents-react": "1.3.0",
		"@ui5/webcomponents-theming": "1.9.0",

**Comment by Lukas742** [comment]
Hi @thisisjasmeet 

your React types are outdated. Please update @types/react to the latest minor version, depending on the React version you are using. We are currently investigating if we can improve this for future updates. There is also an issue that is covering this. (https://github.com/SAP/ui5-webcomponents-react/issues/3711)

Since this has nothing to do with the issue, I will mark both comments as offtopic to keep the ticket clear.
