### ISSUE TITLE
Select component not prefill the value in edit mode

### ISSUE THREAD

**Issue by observer1220** [SAP/ui5-webcomponents-react#3663]
In edit dialog, I set two select componensts on my page. 

One is native HTML
![image](https://user-images.githubusercontent.com/60415107/196866100-c3e95c04-0914-4734-918a-b011e287c551.png)

The other is UI5 Select Component
![image](https://user-images.githubusercontent.com/60415107/196868833-e2d8e7eb-b90e-4272-8f89-0515deb6aa99.png)

And the output is like that. 
![image](https://user-images.githubusercontent.com/60415107/196867608-ae685275-de95-4b3d-81e5-dba0d7de00f9.png)

The Native HTML prefill the option value to the select field, but the UI5 component doesn't. 

The UI5 componet will show the value, once I click the select field.

**Comment by Lukas742** [comment]
Hi @observer1220 

please add a reproducible example, preferably by using this [codeSandbox ](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34) template otherwise we unfortunately cannot help you, especially as you're using another library or component (`Controller`).
