### ISSUE TITLE
MultiComboBox: There is no option to clean/remove selections programatically

### ISSUE THREAD

**Issue by gabrielrossetto** [SAP/ui5-webcomponents-react#368]
**Describe the bug**
I have a `MultiComboBox`, populated with `StandardListItem`. Since this component is a filter, I want to clear the selection always when any button is triggered but the component does provide nothing like: `clearSelection()` or `removeAllSelectedItems()` (as described in MultiComboBox UI5 documentation https://sapui5.hana.ondemand.com/#/api/sap.m.MultiComboBox%23methods/Summary)

**To Reproduce**
1. Create a `MultiComboBox` (create an id for this component to access by DOM after) and populate it with some `StandardListItem`;
2. Create any component in order to clear the `MultiComboBox` selection. Suggestion: `Button`.
3. Create `onClick()` for the component above;
4. On the function created, try to set the selected items in order the clean the component.

**Expected behavior**
It should have an option to clear the selection.

**Screenshots**
Not applicable.

**UI5 Web Components for React Information**
@ui5/webcomponents-react version: 0.9.0-rc.1

**Additional context**
Suggested code to test:

```
  const onCleanFilterClick = () => {
    const test = document.getElementById('companyIndustryFilterId');
    //test.removeAllSelectedItems()
  };
  return (
    <>
        <Button onClick={() => onCleanFilterClick()}>Clear MultiComboBox selection</Button>
        <MultiComboBox id="companyIndustryFilterId">
              <StandardListItem id="1" key="1">1</StandardListItem>
              <StandardListItem id="2" key="2">2</StandardListItem>
              <StandardListItem id="3" key="3">3</StandardListItem>
        </MultiComboBox>
    </>
  );
```

**Comment by MarcusNotheis** [comment]
Hi @gabrielrossetto 
thanks for submitting this issue. As this Component is developed by our colleagues from the UI5 Web Components, I forwarded this issue to their repo: https://github.com/SAP/ui5-webcomponents/issues/1326

**Comment by MarcusNotheis** [comment]
Closing this issue as it was resolved in the UI5 Web Components Issue Thread.
