### ISSUE TITLE
Form: On resize all form children dissapper with some breakpoint configurations. Sometimes even randomly on mobile devies.

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents-react#3707]
**Describe the bug**
All formitems/children or buttons disappear when resized. On tablets or smaller devices, sometimes the form randomly turns white and the user has to refresh the page. This is very critical....
This example is without formitems, but this happens with formitems as well.

**Isolated Example**
https://codesandbox.io/s/friendly-lalande-tb9u8w?file=/package.json

**To Reproduce**
1. Go to the sandbox
2. Resize the sceen. Make the sceen whide
3. See the button dissappers

**Expected behavior**
....

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.8
`@ui5/webcomponents-react` version: 1.2.2
Operating System: Windows
Browser: Chrome 

**Additional context**

**Comment by Lukas742** [comment]
Hi @C3ntraX 

In your codeSandbox you use a `Button` as direct child of the `Form` which is not supported. I couldn't reproduce the described issue when the button is wrapped inside a `FormItem`. Could you verify if the bug still occurs for you when you're wrapping your children?

https://codesandbox.io/s/magical-solomon-938jbe?resolutionWidth=106&resolutionHeight=675&file=/src/App.js

**Comment by C3ntraX** [comment]
Currently, I´m not using children without FormItem in the Form. But I had some situations were the screen turns white and I don´t know why.... its hard to reproduce.

**Comment by C3ntraX** [comment]
I´ll try to isolate the problem, If I have this again while testing my app. 
Another question, is there any feature planned, to support buttons in `FormItems` without using the label grid whitespace before?
Buttons are currently really bad supported in forms.

**Comment by Lukas742** [comment]
There is nothing planned for this, as the `Form` is following [these design specs](https://experience.sap.com/fiori-design-web/form/). If you want to display a button inside the html `<form>` tag, but outside of the layout of the `Form` component you can do so by creating your own Form. For this you need to set the `as` prop to e.g. `"div"` (to prevent nested form tags) and then implement the button outside of the `Form` component.
