### ISSUE TITLE
Grid: On RTL mode is not floating right

### ISSUE THREAD

**Issue by lpohren** [SAP/ui5-webcomponents-react#371]
**Describe the bug**
On the Grid component, when applying RTL, the elements are not being right oriented.

**To Reproduce**
1. Set dir='rtl' on the root element
2. Open a Grid element

**Expected behavior**
When on RTL mode, the property from the screenshot below should be `float: right`.

**Screenshots**
![image](https://user-images.githubusercontent.com/16123699/77344905-a0a18400-6d12-11ea-9450-221aaad0e323.png)

**UI5 Web Components for React Information**
Operating System:
`@ui5/webcomponents-react` version: 0.9.0-rc.1

**Comment by MarcusNotheis** [comment]
Released in version `0.9.0-rc.3`
