### ISSUE TITLE
Unnecessary nonce value

### ISSUE THREAD

**Issue by LucaFilitz** [SAP/ui5-webcomponents-react#3711]
**Describe the bug**
The components are requiring a nonce value in all cases. 

**To Reproduce**
Use the components in TypeScript.

**Expected behavior**
Nonce values are voluntary.

**Screenshots**
<img width="685" alt="image" src="https://user-images.githubusercontent.com/46955815/199804148-fec8fc34-8d84-49ca-913c-6773363e4a38.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: ^1.9.0
`@ui5/webcomponents-react` version: ^1.3.0
Operating System: MacOS
Browser: Opera/ Chrome

**Comment by Lukas742** [comment]
Hi @LucaFilitz 

Please update `@types/react` to the latest minor version, depending on the React version you are using. We are currently investigating if we can improve this for future updates.

**Comment by LucaFilitz** [comment]
This resolves the issue for me. Still a little weird behavior.
Thank you for your help.
