### ISSUE TITLE
ObjectPage: Subtitle doesn't render properly on small screens

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents-react#372]
**Describe the bug**
On mobile device, when the title of the ObjectPage is a too long, the subtitle is splitted in two lines. (see Sreenshot)

**To Reproduce**
1. Open Google Chrome Dev Tools then toggle the Device Toolbar.
2. Reduce the size to "Mobile L".

**Expected behavior**
The ObjectPage elements should be properly displayed regardless of the viewport size.

**Screenshots**
<img width="426" alt="Screen Shot 2020-03-24 at 10 41 04" src="https://user-images.githubusercontent.com/7316793/77412230-e1a2a280-6dbd-11ea-8bae-a813e7e9e691.png">

**UI5 Web Components for React Information**
Operating System:
`@ui5/webcomponents-react` version: 0.9.0-rc.2
Do you have a dependency to`@ui5/webcomponents` in your package.json? If yes, which version?: 1.0.0-rc.5

**Comment by MarcusNotheis** [comment]
Released in `0.9.0-rc.6`
