### ISSUE TITLE
ObjectPage: Reducing the screen size makes the ObjectSection grow

### ISSUE THREAD

**Issue by Neeeko** [SAP/ui5-webcomponents-react#373]
**Describe the bug**
Reducing the size of the Browser view port make the ObjectSection margin-bottom grow infinitely.

**To Reproduce**
1. Reduce the size of your browser window
2. You should see the ObjectSection expanding itself to the bottom

**Expected behavior**
The ObjectSection should only grow on resize to properly display its child elements.

**GIFs**
![objectpage1](https://user-images.githubusercontent.com/7316793/77415198-655e8e00-6dc2-11ea-8965-665eb288e8ea.gif)
NB: I changed the background color of the ObjectSection to better illustrate the "growing effect". When reducing the window size, we can see the ObjectSection expanding to the bottom.
The Scrollbar also reflects this.

![objectpage2](https://user-images.githubusercontent.com/7316793/77414543-82469180-6dc1-11ea-86df-b3c34d0b328c.gif)
Reducing the size of the window with the debugger tools opened shows the `margin-bottom` increasing.

**UI5 Web Components for React Information**
Operating System: macOS
`@ui5/webcomponents-react` version: 0.9.0-rc.2
Do you have a dependency to`@ui5/webcomponents` in your package.json? If yes, which version?: 1.0.0-rc.5

**Comment by Neeeko** [comment]
FYI: I cannot reproduce the issue when the header is collapsed (for example thanks to the HideHeaderButton)

**Comment by MarcusNotheis** [comment]
Hi @Neeeko 
I just opened a pull request which should fix the infinite growth issue by limiting the max height to the height of the window. In general I would recommend that some parent is limiting the height of the ObjectPage by using position fixed or absolute. I open put a `position:fixed; top:0; left:0; right:0; bottom:0` to the body tag and then I'm fine. But even without that the ObjectPage should now not grow any larger than the window.
Will let you know as soon as we have another release-candidate.

**Comment by MarcusNotheis** [comment]
Released in `0.9.0-rc.5`
