### ISSUE TITLE
AnalyticalTable: Resize delay

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents-react#3745]
**Is your feature request related to a problem? Please describe.**
We have an AnalyticalTable in a resizable container. When we resize that container, the table doesn't resize immediately. Instead, it seems that a debounce delay has been defined somewhere, and only after that delay has elapsed, will the table change its size. This delay seems to have been set to 1 second, which is noticeable in the UI.

**Describe the solution you'd like**
I assume that resizing has been debounced to save resources and to not resize multiple times per second as the user moves the mouse. However, at 1 second, it is quite noticeable, and our UX person would like this interval removed, or, if that is not possible or advised against, at least reduced.

I don't know if a lower delay could be hard-coded, or if you would expose it as a property of the component.

**Additional context**
I have created a [sandbox](https://codesandbox.io/s/focused-bouman-rx6h9p?file=/src/App.js) visualizing the current behavior.
I will provide further context via DM.

Thanks a lot in advance!

**Comment by Lukas742** [comment]
Hi @ej612 

the linked PR reduces the debounce wait time to 60ms. We decided against offering a prop to change this value as micro configuration like this rarely make sense and confuse the users more than they add value.
We also can't remove the debounce, as with each width or height change, some costly calculation is taking place and it would therefore reduce performance noticeably especially with large dataset.

If you only need a simple table with a small to medium dataset, I would recommend using the `Table` component. No filtering or sorting functions are integrated there, but in return you don't have any overhead that you might not need.
