### ISSUE TITLE
AnalyticalTable: Shift+Space to select row

### ISSUE THREAD

**Issue by mhchem** [SAP/ui5-webcomponents-react#3788]
**Describe the bug**
The AnalyticalTable should support Shift+Space to select the row. This is "the Fiori" way, for instance implemented at [UI5's TreeTable](https://sapui5.hana.ondemand.com/#/entity/sap.ui.table.TreeTable/sample/sap.ui.table.sample.TreeTable.JSONTreeBinding)

**To Reproduce**
1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable--default-story
2. Expand 'Show useIndeterminateRowSelection example'
3. Focus on a cell
4. Press Shift+Space

**Expected behavior**
Shift+Space should select the row. This is the established behavior. This is particularly needed when the focus is on the 2nd column where Space does the Expand/Collapse.

**Others**
While we are at it, why not consider the other deviations from UI5?
- Should space on the 3rd column really toggle the selection?
- F4 for collapse/expand
Or should I open extra issues?

**Comment by Lukas742** [comment]
Hi @mhchem 

Thanks for reporting! 

> * Should space on the 3rd column really toggle the selection?

Yup, in this case the `rowSelector` is set to `'Row'` therefore the whole row is selectable. If you set it to `'RowSelector'` then only the selection cell is togglable. 

> * F4 for collapse/expand
>   Or should I open extra issues?

We will consider this as well, so no need to open another issue :)
