### ISSUE TITLE
MultiInput: onTokenDelete event not triggered

### ISSUE THREAD

**Issue by Bilal3120** [SAP/ui5-webcomponents-react#3795]
**Describe the bug**
onTokenDelete event is not getting triggered in the MultiInput when the field is readonly.

**Isolated Example**
[Codesandbox](https://codesandbox.io/s/dynamicpage-multiinput-8drtd6?file=/src/App.js)

**To Reproduce**
1. Go to [Codesandbox](https://codesandbox.io/s/dynamicpage-multiinput-8drtd6?file=/src/App.js)
2. Click on cross icon in the token
3. onTokenDelete is not triggered

**Expected behavior**
A MultiInput read-only component should provide visual feedback upon user interaction, here onTokenDelete event trigger is missing.

**UI5 Web Components for React Information**
`@ui5/webcomponents` 1.9.0
`@ui5/webcomponents-react` 1.5.0

**Comment by Lukas742** [comment]
Hi @Bilal3120 

I will close this issue as there is already another one covering this topic. If you have any questions or more information, please address them in the original issue.

Duplicate: https://github.com/SAP/ui5-webcomponents/issues/5935
