### ISSUE TITLE
AnalyticalTable: Using the Selection Column always causes last the last table cell to go beyond the bounds of the parent element

### ISSUE THREAD

**Issue by Sepper007** [SAP/ui5-webcomponents-react#380]
**Describe the bug**
When the Selection Column of the Analytical Table is used, the last cell will always beyond the right bound of his parent, thereby causing a horizontal scroll behaviour. 

**To Reproduce**
1. Place an AnalyticalTable with Selection Column in a container with a fixed width (for example <div style="width: 900px">).
2. The width of the selection column is statically set to 36px However, the other cells do not take these 36px into account and calculate their width according to the 900px of the parent container.
3. The last column will extend exactly 36px beyond the right border of the parent container and thus cause the table to scroll horizontally

**Expected behavior**
The 36px of the Selection Column should be taken into account when calculating the width of the cells of the table

**Screenshots**
![23DE4D8E-BE41-49DD-AEFC-445389CE777A_1_105_c](https://user-images.githubusercontent.com/22964016/77492384-b049c700-6dfd-11ea-8f6b-b2632578c608.jpeg)

**UI5 Web Components for React Information**
Operating System:
MacOS Catalina, Google Chrome Browser

"@ui5/webcomponents-react": "0.8.7-rc.0"

**Comment by MarcusNotheis** [comment]
released in `0.9.0-rc.4`
