### ISSUE TITLE
AnalyticalTable: onRowExpandChange not always called when expanding with space bar

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents-react#3819]
**Describe the bug**
When using the space bar to expand a hierarchical node of an AnalyticalTable, the onRowExpandChange callback is not always called.

**Working case:**
If the highlight is on the arrow, pressing the space bar expands the node and calls the callback.
![image](https://user-images.githubusercontent.com/110408767/205072265-a608d134-a3af-46dd-8cd3-c738ba44077f.png)

**Buggy case:**
If the highlight is on the entire cell, pressing the space bar expands the node but does not call the callback.
![image](https://user-images.githubusercontent.com/110408767/205072542-2efa8f16-b461-4582-abb4-f5d882a0e0f1.png)

**Isolated Example**
I made a [sandbox](https://codesandbox.io/s/admiring-worker-ghiv49?file=/src/App.js).

Thanks a lot in advance!

**Comment by Lukas742** [comment]
Hi @ej612 

this was fixed in [v1.6.0](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v1.6.0) --> [codeSandbox](https://codesandbox.io/s/intelligent-yonath-7luf7r?file=/package.json)
