### ISSUE TITLE
DatePicker: Field is required and value state cannot be error if field is empty

### ISSUE THREAD

**Issue by matheushahn** [SAP/ui5-webcomponents-react#3822]
**Describe the bug**
The `DatePicker` component value state cannot be set to `Error` even tough the field is required.
In our case, we have a form and the date is required, therefore empty is not a valid value. 
The `DatePicker` component is preventing us from changing the value state to `Error`.

Note: I had to add the onInput event to the isolated example because sometimes the onChange is not triggered when clearing the value with Keyboard and leaving the focus. You might want to try to reproduce that as well.

**Isolated Example**
https://codesandbox.io/s/intelligent-architecture-j5puy9

**To Reproduce**
1. Open the date picker
2. Select a valid date
3. The value state will be `Success`
4. Clear this date using the keyboard
5. Focus out of the date picker 
6. See the error 

**Expected behavior**
If this field is required and I want the value state to remain as Error.

**Screenshots**
<img width="674" alt="image" src="https://user-images.githubusercontent.com/15281046/205298822-5d333d96-7f5b-465a-9276-4b75e9fbb746.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: latest
`@ui5/webcomponents-react` version: latest
Operating System: MacOS Ventura
Browser: Chrome

**Additional context**
I'm a developer from SAP Language Platform. Feel free to contact me in case of doubts.

**Comment by Lukas742** [comment]
Hi @matheushahn 

I had to adjust the steps a bit to reproduce the issue described by you:

1. type any invalid string inside the input field
2. focus out
3. delete the string
4. focus out
5. See that the `valueState` of the input is "None" even though it should be "Error"

UI5 web components are often setting their state internally (e.g. when selecting a day inside the popover, the value of the input is updated), the same goes for the `valueState`. In your case the `valueState` is updated by the component and set to "None". 

To prevent this behavior, you can call `event.preventDefault()` inside the handler of your events. This will make the web component fully controllable, meaning that no internal states are mutated. Please take a look at this [codeSandbox](https://codesandbox.io/s/kind-ptolemy-imd5x3?file=/src/App.js), to get more details. 

As I'm not sure if the default behavior is intended in this case, please let me know if you feel like this is a bug. I'll then forward this issue to the ui5-webcomponents repo.

___
> Note: I had to add the onInput event to the isolated example because sometimes the onChange is not triggered when clearing the value with Keyboard and leaving the focus. You might want to try to reproduce that as well.

Please create another issue with steps to reproduce this issue, as I wasn't able to reproduce it myself.

**Comment by matheushahn** [comment]
Hi @Lukas742,

I was able to prevent this behavior with your suggestion. 

Thanks for the quick response!
