### ISSUE TITLE
ObjectPage: Clicking on a section tab throws error

### ISSUE THREAD

**Issue by lpohren** [SAP/ui5-webcomponents-react#384]
**Describe the bug**
When clicking on a section tab button, and error regarding the section ID is thrown, even the ID being set on it. I tested it with 2 different version 0.9.0-rc.4 and 0.9.0-rc.3, the problem was implemented on 0.9.0-rc.4.

**To Reproduce**
1. Open an ObjectPage with section tabs(with IDs defined)
2. Click on one of the tabs
3. See error

**Expected behavior**
The Error should not be thrown.

**Screenshots**
![image](https://user-images.githubusercontent.com/16123699/77556556-71684f80-6e97-11ea-8801-a282fe7c37a1.png)

**UI5 Web Components for React Information**
Operating System:
`@ui5/webcomponents-react` version: 0.9.0-rc.4

**Comment by MarcusNotheis** [comment]
Hi @lpohren, bug fix is released in `0.9.0-rc.5`
