### ISSUE TITLE
Dialog: wrong display of the footer with a dark theme

### ISSUE THREAD

**Issue by ehn-sap** [SAP/ui5-webcomponents-react#3840]
**Describe the bug**
Using the dark theme 'Quartz Dark' ('sap_fiori_3_dark'), the background color of the footer is not complete. 

**Isolated Example**
[Sandbox](https://codesandbox.io/s/dialog-with-splitter-quartz-dark-7u9ozk?file=/src/App.tsx)

**To Reproduce**
1. Set the theme 'Quartz Dark'
2. Create a dialog
3. See that the footer of the dialog looks uncomplete, with lighter rectangles at left and right.

**Expected behavior**
The footer of the dialog should seem as large as the dialog.

**Screenshots**
![Footer](https://user-images.githubusercontent.com/112404107/205995818-ef0ecc26-10f6-4552-b1ac-7959f7a94784.PNG)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.9.1
`@ui5/webcomponents-react` version: 1.5.0
Operating System: Win11
Browser: Chrome

**Additional context**
The issue may not be specific to 'Quartz Dark', just visible with it.

**Comment by Lukas742** [comment]
Hi @ehn-sap 

you used the `"Header"` design for the footer `Bar`, if you set it to `"Footer"` then the same background color is applied. 
Also I would recommend removing the padding of the footer by using the respective [shadow part](https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-dialog--default-story#css-shadow-parts).

Please note, that the top border of the footer and bar are stacking, which is a known issue. (https://github.com/SAP/ui5-webcomponents/issues/5561)

**Comment by ehn-sap** [comment]
> you used the `"Header"` design for the footer `Bar`, if you set it to `"Footer"` then the same background color is applied. Also I would recommend removing the padding of the footer by using the respective [shadow part](https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-dialog--default-story#css-shadow-parts).
> 
> Please note, that the box-shadow/border of the footer and bar are stacking, which is a known issue. ([SAP/ui5-webcomponents#5561](https://github.com/SAP/ui5-webcomponents/issues/5561))

Thanks @Lukas742 for your quick answer and explanations, the design property was unclear to me, the footer looks good now.
