### ISSUE TITLE
DatePicker: Fail to render on product environment (CLDR not loaded issue)

### ISSUE THREAD

**Issue by hhhhzs** [SAP/ui5-webcomponents-react#3869]
**Describe the bug**
DatePicker fails to render on product environment but works well in local environment.

Uncaught (in promise) Error: CLDR data for locale en is not loaded!
    at B (<anonymous>:145:1284)
    at Object.loadResource (<anonymous>:173:11867)
    at R (<anonymous>:173:31353)
    at oy (<anonymous>:173:31713)
    at new constructor (<anonymous>:173:11973)
    at of.getInstance (<anonymous>:173:32467)
    at yu (<anonymous>:173:77971)
    at get _primaryCalendarType [as _primaryCalendarType] (<anonymous>:173:78673)
    at uf.getFormat (<anonymous>:173:79656)
    at uf.isValid (<anonymous>:173:144681)

I've tried to import assets in the tsx file that contains DatePicker, just as mentioned in [this issue](https://github.com/SAP/ui5-webcomponents-react/issues/1212):
`import '@ui5/webcomponents/dist/Assets.js';`
`import '@ui5/webcomponents-fiori/dist/Assets.js';`
`import '@ui5/webcomponents-react/dist/Assets.js';`
 but the problem still exists.

I've also tried to import more assets:
`import "@ui5/webcomponents-localization/dist/Assets.js"`
` import "@ui5/webcomponents-localization/dist/Assets-static.js"`
`import "@ui5/webcomponents-localization/dist/features/calendar/Gregorian";`
also doesn't work

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.5.0
`@ui5/webcomponents-react` version: 0.26.2
Operating System: Mac OS
Browser: Chrome

**Comment by hhhhzs** [comment]
Hi @Lukas742 I can't reproduce it in the codeSandbox, but the issue still exists on our product env after I upgraded ui5-webcomponents to the newest version.

**Comment by hhhhzs** [comment]
After checking, the assets were imported in the root, I wonder whether these assets are enough to avoid issue?
 import '@ui5/webcomponents-fiori/dist/Assets';
 import '@ui5/webcomponents-react/dist/Assets';
 import '@ui5/webcomponents/dist/Assets';

**Comment by Lukas742** [comment]
Yes, they should be sufficient. 

I just downloaded the [codeSandbox](https://codesandbox.io/s/adoring-ardinghelli-b7e7lu?file=/src/App.js) and when building it and then serving it locally (to test it in prod env) it also works.

**Comment by hhhhzs** [comment]
Hi @Lukas742 is the way of importing these assets in a TypeScript project the same as that of a JavaScript one?

**Comment by Lukas742** [comment]
Yes.
https://codesandbox.io/s/wcr-ts-template-forked-t5ifnk?file=/src/index.tsx
