### ISSUE TITLE
AnalyticalTable: Tree Table selecting parent selects all children

### ISSUE THREAD

**Issue by stsander07** [SAP/ui5-webcomponents-react#387]
**Describe the bug**
When the analytical table has tree data and the user selects a parent row, all children are selected

**To Reproduce**
1. create analytical table with tree data
2. expand a parent node to view the children
3. select the parent
 => see that the children are now all selected

**Expected behavior**
I would expect that only the parent node is selected

**Screenshots**

**UI5 Web Components for React Information**
Operating System:
`@ui5/webcomponents-react` version:
Do you have a dependency to`@ui5/webcomponents` in your package.json? If yes, which version?:

*If you are not sure, you can find out by running `npm ls @ui5/webcomponents-react` or `yarn why @ui5/webcomponents-react`*

**Additional context**

**Comment by MarcusNotheis** [comment]
@Lukas742 could you look into that one?
