### ISSUE TITLE
ObjectPage: scroll issue

### ISSUE THREAD

**Issue by arhigod** [SAP/ui5-webcomponents-react#3870]
**Describe the bug**
The ObjectPage scroll doesn't work correctly.
Most likely this happens when the height of the content is enough for the header to collapse. But the height of the content to cover 100% without a header is no longer enough

**Isolated Example**
https://ey24ku.csb.app/
https://codesandbox.io/s/ey24ku

**To Reproduce**
1. Try to scroll

**Expected behavior**
Scroll should work correctly

**Screenshots**
https://user-images.githubusercontent.com/19529418/207368649-b76f155a-039b-4515-b74a-27cb85877c1c.mov
![Screen Recording 2022-12-13 at 15 47 55](https://user-images.githubusercontent.com/19529418/207369041-83730e95-5948-4418-b9f1-da6afc69b7ae.gif)

**UI5 Web Components for React Information**
    "@ui5/webcomponents": "1.9.0",
    "@ui5/webcomponents-base": "1.9.0",
    "@ui5/webcomponents-fiori": "1.9.0",
    "@ui5/webcomponents-icons": "1.9.0",
    "@ui5/webcomponents-react": "1.6.0",
    "@ui5/webcomponents-react-base": "1.6.0",
    "@ui5/webcomponents-react-charts": "1.6.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-scripts": "5.0.1"

**Comment by Lukas742** [comment]
Hi @arhigod 

I noticed that this behavior only happens if only a single section is used. We will still take a look at the issue, but maybe the `DynamicPage` would be better suited here, because an ObjectPage with only a single section, isn't really the intended use-case.

**Comment by arhigod** [comment]
Hi @Lukas742,
Unfortunately, this bug is not only present when a single section is used. But also when several sections are used with a `mode=IconTabBar`

**Comment by Lukas742** [comment]
Got it, thanks.
