### ISSUE TITLE
AnalyticalTable: Sorting options fail to popup after upgrading

### ISSUE THREAD

**Issue by hhhhzs** [SAP/ui5-webcomponents-react#3885]
**Describe the bug**
When clicking the header of a sortable table, sorting options fail to popup with warning:'Valid opener id is required. ' after upgrading from 0.26.1 to 0.28.0 (along with the corresponding ui-webcomponents version) 

**To Reproduce**
1. Create a analytical table
2. Click on a column of the header

**Screenshots**
<img width="878" alt="image" src="https://user-images.githubusercontent.com/57512939/208057605-8cefea7a-29b1-47e1-b457-6eadadeb0743.png">
**UI5 Web Components for React Information**
`@ui5/webcomponents` version:
`@ui5/webcomponents-react` version:
Operating System: Mac OS
Browser: Chrome

**Comment by Lukas742** [comment]
Hi @hhhhzs 

please update to the latest version and check if the issue still persists there. You can use our [migration guide](https://sap.github.io/ui5-webcomponents-react/?path=/docs/migration-guide--page) as support.

**Comment by hhhhzs** [comment]
Yes, I think this issue occurs in all the versions after 0.27.1 (including v0.27.1)

**Comment by Lukas742** [comment]
Seems to be working fine for me. 

https://user-images.githubusercontent.com/9749730/208077071-ffed9f5d-2b95-4e72-87eb-d1206c8a0b69.mp4

Could you please add a reproducible example, preferably by leveraging this [codeSandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34) template.
