### ISSUE TITLE
Example for TreeItemCustom

### ISSUE THREAD

**Issue by maitefdupont** [SAP/ui5-webcomponents-react#3898]
**Describe the documentation issue**

- [x] Documentation is unclear
- [x] Documentation is incorrect
- [x] Documentation is missing
- [ ] Other

**Description of the issue**
A usage example is missing for TreeItemCustom. I'm trying to put together a sandbox for CustomTreeIcon but I'm having trouble using this component. The documentation is not helping either, please improve it.

The example available at https://sap.github.io/ui5-webcomponents-react/iframe.html?viewMode=docs&id=data-display-tree--default-story#tree-with-customizable-treeitem actually only includes standard TreeIcons, even though it's named "Customizable TreeItem".

![image](https://user-images.githubusercontent.com/1753795/208736233-cd50ffb0-bd12-4445-a472-58a165e6be58.png)

**Comment by Lukas742** [comment]
Hi @maitefdupont 

the "Tree with customizable TreeItem" is there to play around with a standard `TreeItem` and was written before the `TreeItemCustom` was available. 
With the linked PR I tried to outline that this is not about the `TreeItemCustom`. Also, I added a basic example of the `TreeItemCustom` to the default example. 

Could you tell me what exactly you had problems with in the implementation? The props of the `TreeItemCustom` component are almost the same as the props of the `TreeItem` except for the content and therefore it should be very similar usable.

**Comment by maitefdupont** [comment]
I have set up this sandbox: https://codesandbox.io/s/editor-proposals-4zn7pv?file=/src/App.js
Here I tried to use a Tree with TreeItems or with TreeItemCustom but every time I add TreeItemCustom anywhere in the hierarchy the compiler breaks. 
![image](https://user-images.githubusercontent.com/1753795/208903608-f69acfe5-f8af-45d6-b6b8-81c55dbb2412.png)

**Comment by maitefdupont** [comment]
I see... Thanks a lot for the support!
