### ISSUE TITLE
AnalyticalTable: onRowClick is overwriting onRowSelect property

### ISSUE THREAD

**Issue by I506645** [SAP/ui5-webcomponents-react#3903]
In the AnalyticalTable component, the property "onRowClick" is overwriting "onRowSelect" property. These two properties are completely different. "onRowClick" should be triggered when the user clicks on any of the row item of the table and "onRowSelect" should be triggered only when the user clicks on the selectionMode icon (either radio button in case of single select or checkboxes in case of multi-select).

`@ui5/webcomponents` version: 1.6.0
`@ui5/webcomponents-react` version: 0.27.5
Operating System: Windows
Browser: Edge and Chrome

Please reach out to me if you need any further details.

Best Regards,
Raghav

**Comment by Lukas742** [comment]
Hi @I506645 

I could not reproduce this issue in our latest version. Both events are fired as they should, if you want to distinguish between the selection cell click and the rest of the row you could check the `target` inside the `onRowClick` handler for the `data-selection-cell` attribute inside the `dataset`. -> `event.target.dataset.selectionCell`

See [codeSandbox](https://codesandbox.io/s/defaulttable-forked-rdy5fw?file=/src/App.js).
