### ISSUE TITLE
SuggestionItem: Unable to style input suggestion items - "className" and "style" properties for SuggestionItem does not get propagated to ui5-li-suggestion-item web component.

### ISSUE THREAD

**Issue by parthapal33** [SAP/ui5-webcomponents-react#3907]
**Describe the bug**
"className" and "style" properties for **SuggestionItem** does not get propagated to **ui5-li-suggestion-item** web component.
If we use Input with suggestions, two different elements are created for each suggestion items.
1) Empty **ui5-suggestion-item** which is located inside **ui5-input** shadow dom. Classnames and styles are propagated to these components.
2) **ui5-li-suggestion-item** which is located inside **ui5-static-area-item**. These elements contain texts and descriptions of suggestions. But classnames and styles are not propagated to these components. That is why it is not possible to customize styles of suggestion items. 

**Isolated Example**
[https://codesandbox.io/s/charming-bash-n0ti4e?file=/src/App.js](https://codesandbox.io/s/charming-bash-n0ti4e?file=/src/App.js)

**To Reproduce**
1. Type something in the input box
2. Suggestions will appear
3. Inspect the first suggestion item
5. Verify that **ui5-li-suggestion-item** does not have class names or styles

**Expected behavior**
ui5-li-suggestion-item should contain class names and styles that we add in **SuggestionItem** react component.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: "1.8.0"
`@ui5/webcomponents-react` version: "1.3.1"

Operating System: Windows 10
Browser: Edge/Chrome

This issue might be related to - https://github.com/SAP/ui5-webcomponents/issues/5685

**Comment by Lukas742** [comment]
Hi @parthapal33 

the `SuggestionItem` is a so called abstract web component. It mainly exists to pass props to the respective component inside the shadow root and therefore styles are not forwarded. I created an [issue](https://github.com/SAP/ui5-webcomponents/issues/6220) in the web components repo, so we can outline components like this and the linked PR will add a knowledge base entry as well as a note to the `style` and `className` prop about how these properties work with web components.
