### ISSUE TITLE
AnalyticalTable: Allow async event handlers

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents-react#3909]
**Is your feature request related to a problem? Please describe.**
We have an AnalyticalTable which implements event handlers for `onLoadMore`, `onRowSelect`, `onRowExpandChange`, and `onTableScroll`. In each of these cases, it is possible that we need to fetch data, so our event handlers are async. This collides with the type definitions for the AnalyticalTable props, which expect a function that returns `void`, and will throw an error if the function returns `Promise<void>`.

We're working around this on our end like this:
```
onLoadMore={() => {
    // eslint-disable-next-line promise/prefer-await-to-then
    onLoadMore().catch(e => { throw e; });
}}
```
Which is arguably much less appealing than this:
```
onLoadMore={onLoadMore}
```

**Describe the solution you'd like**
Would it be possible to extend the type definitions to allow async event handlers?

Thank you very much in advance!

**Comment by MarcusNotheis** [comment]
Hi @ej612,

thanks for reaching out!
In my opinion, react event handlers should not be async as the base type for all events in `@types/react` is also defined as:
```ts
type EventHandler<E extends SyntheticEvent<any>> = { bivarianceHack(event: E): void }["bivarianceHack"];
```

This type does not specify any `Promise<>` return type, so I guess we shouldn't allow that as well.

Do you use async callbacks for standard HTML tag in your project?
