### ISSUE TITLE
can't change the "save as" and "manage" button name in the variant management .

### ISSUE THREAD

**Issue by roshnijalan97new** [SAP/ui5-webcomponents-react#3912]
**Describe the bug**

Can't change the "save as" and "manage" button names in the variant management.

**Isolated Example**
*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/cocky-resonance-4l7drc?file=/src/App.js).*

**To Reproduce**
1. Go to 'https://codesandbox.io/s/cocky-resonance-4l7drc?file=/src/App.js'
2. Click on 'Selected'
3. This screen appears:
<img width="406" alt="Screenshot 2022-12-23 at 11 47 38 AM" src="https://user-images.githubusercontent.com/120740457/209282783-efb8167c-8432-4e6c-853b-5f6f79b88eba.png">
4. Can't change the footer text-"save as" and "manage".
5. click on the "manage" button.
6. A dialog box would appear:
<img width="480" alt="Screenshot 2022-12-23 at 11 47 47 AM" src="https://user-images.githubusercontent.com/120740457/209283854-a0881ed9-193f-4377-b69b-0d06af8cb751.png">
7. Cant changes the texts: "Manage Views", "View" title, "save" and "cancel"  texts on the dialog box.

**Expected behavior**
All these texts should be mutable.

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:
`@ui5/webcomponents-react` version:
Operating System:
Browser:

**Additional context**

**Comment by MarcusNotheis** [comment]
Hi @roshnijalan97new,

thanks for reaching out. All these button texts and titles in the `VariantManagement` component are part of the [design specification](https://experience.sap.com/fiori-design-web/variant-management/) and are not intended to be changed.
The [SAPUI5 implementation](https://ui5.sap.com/#/api/sap.ui.comp.variants.VariantManagement%23controlProperties) is not offering any props to change the naming as well, so we'll stick to that decision as well.

What exactly is your use case that you need to change all these texts?

**Comment by roshnijalan97new** [comment]
I want to change the text according to the language selected by the user.

**Comment by MarcusNotheis** [comment]
This is something we have already built-in in UI5 Web Components (for React):

First, import this file: `import '@ui5/webcomponents-react/dist/Assets';`, eg.g in your `index.js` or `App.jsx`.
Then, you can call the `setLanguage` method and all texts will change:
```js
import { setLanguage } from "@ui5/webcomponents-base/dist/config/Language.js";

setLanguage("fr");
```

**Comment by roshnijalan97new** [comment]
Thank you

**Comment by roshnijalan97new** [comment]
I dont want to simply translate it but to set the value manually.

**Comment by MarcusNotheis** [comment]
That's a feature request we can unfortunately not fulfil. There are more than 20 translatable texts in the VariantManagement only which would all need to be exposed as props. This would make the component API really complex (and as a consequence we would have to add that for all other components as well).

**Comment by manishcharsap** [comment]
Hi @MarcusNotheis,

How can I change to custom text for "save as" and "manage" button name in the variant management.
Please suggest.

**Comment by MarcusNotheis** [comment]
Hi @manishcharsap,
as mentioned in my response above, we have currently no option to modify the texts show in the `VariantManagement` from the outside.
What is your use case that you need to change these texts?
