### ISSUE TITLE
<Toolbar/> Background color is not matching as design in Morning Horizon Theme 

### ISSUE THREAD

**Issue by saorabhkr** [SAP/ui5-webcomponents-react#3914]
**Describe the bug**

Toolbar where Active is True and Design is Info, 
Below is the code snippet. 
```
<Toolbar design={ToolbarDesign.Info} toolbarStyle={ToolbarStyle.Standard} active>
{/*Content*/}
</Toolbar>
```
With this as per the design wiki the toolbar should suppose to have this background `--sapInfobar_Active_Background;` if the theme is **Morning Horizon**. 

Observation is `--sapInfobar_Active_Background;` color is there but with `undefined` color.

A screenshot is taken from the design wiki:

<img width="528" alt="Screenshot 2022-12-24 at 2 46 28 PM" src="https://user-images.githubusercontent.com/5204425/209429289-b177aaa5-584c-412c-b014-f32069a55bb4.png">

<img width="915" alt="Screenshot 2022-12-24 at 2 46 20 PM" src="https://user-images.githubusercontent.com/5204425/209429286-94ff68ac-19fe-4b73-9757-8cb9ecd322ae.png">

But with the same properties, I tried with storybook, and it's not having the same styling as per the design wiki defined. 

Storybook Link:
https://sap.github.io/ui5-webcomponents-react/?path=/story/layouts-floorplans-toolbar--default-story&args=design:Info;active:true

These colors (and related CSS variables) look correct for Quartz Dark w.r.t. Fiori 3 but these colors (and CSS variables) don't look correct for **Morning Horizon**. 

**Isolated Example**
(https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).*](https://sap.github.io/ui5-webcomponents-react/?path=/story/layouts-floorplans-toolbar--default-story&args=design:Info;active:true)

**To Reproduce**
Go To:
https://sap.github.io/ui5-webcomponents-react/?path=/story/layouts-floorplans-toolbar--default-story&args=design:Info;active:true

Click On Canvas:
Try changing different Theme from  Header Toolbar 

**Expected behavior**
Color Should be as per deisign wiki

**Screenshots**
This is what we can see after implementation 
<img width="792" alt="Screenshot 2022-12-24 at 1 01 01 PM" src="https://user-images.githubusercontent.com/5204425/209425994-f7c365b5-84c9-4573-bce7-568e58fd1a24.png">

**UI5 Web Components for React Information**
"@ui5/webcomponents": "1.8.0",
"@ui5/webcomponents-fiori": "1.8.0",
"@ui5/webcomponents-react": "1.3.1",
"@xweb/common-messagebundles": "^1.0.8",
"@xweb/common-messages": "3.3.0",
"@xweb/common-react": "3.3.7",

Operating System: MAC OS 
Browser: Chrome

**Comment by saorabhkr** [comment]
Hi @Lukas742,

Any idea when it will available for use?

Best Regards,

**Comment by Lukas742** [comment]
Release is on its way :)
