### ISSUE TITLE
Grid: key prop error

### ISSUE THREAD

**Issue by arhigod** [SAP/ui5-webcomponents-react#3915]
**Describe the bug**
Grid always show an Error `Warning: Each child in a list should have a unique "key" prop.`.
It doesn't matter if there are several elements in it or one. Whether they have a key prop or not. Used regular div or component.

**Isolated Example**
https://codesandbox.io/s/grid-kynzt2

**To Reproduce**
Check the console

**UI5 Web Components for React Information**
    "@ui5/webcomponents": "~1.9.3",
    "@ui5/webcomponents-fiori": "~1.9.3",
    "@ui5/webcomponents-react": "~1.7.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-scripts": "5.0.1"

**Comment by gibbsvjy007** [comment]
Getting the same
