### ISSUE TITLE
AnalyticalTable: Row Navigation with Navigation Icon

### ISSUE THREAD

**Issue by I506645** [SAP/ui5-webcomponents-react#3917]
For the AnalyticalTable, we need a row navigation with sticky navigation icon (>) at the end of the table similar to the existing GridTable of SAPUI5 https://sapui5.hana.ondemand.com/#/entity/sap.ui.table.Table/sample/sap.ui.table.sample.RowAction

The idea is to navigate to the details page from the table on click of the navigation icon (screenshot below). There are other columns in the table with links which either navigates or display a popup and some editable columns. So, we don't need navigation on click of row but instead on click of Navigation Icon which has to be placed at the end of the table with Sticky feature. Because there are lot of columns in our table and user has to scroll to the right to find the icon. We want to avoid that.

The idea is to display the navigation icon/column at the end with fixed position irrespective of the no. of columns in the table. Please let us know if this feature will be available anytime soon or please suggest if there are any workarounds to implement this functionality.

![image](https://user-images.githubusercontent.com/121158363/209505903-e35f36aa-35e9-48bf-86b1-d375e6a02600.png)

Best Regards,
Raghav

**Comment by Lukas742** [comment]
Hi @I506645 

this behavior would only be achievable when the sticky column support is implemented. You can find out more about the (unfortunately not very positive) progress in the corresponding feature request I linked below.  

Duplicate #566
