### ISSUE TITLE
RichTextEditor component request 

### ISSUE THREAD

**Issue by anfavretto** [SAP/ui5-webcomponents-react#3956]
**Is your feature request related to a problem? Please describe.**
We have a requisite to allow the user to edit rich text to be shown in a public application with 2.5 million users by month. 

**Describe the solution you'd like**
We need the Rich Text Editor that is already available on SAP UI5. [This component here](https://sapui5.hana.ondemand.com/#/api/sap.ui.richtexteditor.RichTextEditor). 

**Describe alternatives you've considered**
This component just needs to be aligned with Fiori Guidelines to be used on the application. 

**Additional context**
This is a requirement for an internal project inside SAP CIM SLE.

**Comment by Lukas742** [comment]
Due to the technical depth and the associated security risks, we have decided not to accept any contributions for the time being. However, this may change again and is therefore not final. If the decision should become final, I will report again.

**Comment by Lukas742** [comment]
We had another internal discussion about this and decided not to offer a RichTextEditor component in our library.
The main reason for this is the complexity and the related security aspects that we would have to consider if we were to implement the component, which in turn would lead to a very large maintenance effort that we cannot afford at this time.
