### ISSUE TITLE
ComponentName: Description

### ISSUE THREAD

**Issue by gagarin880120** [SAP/ui5-webcomponents-react#3967]
**Describe the bug**
When we pass Promise-returnes function to event handlers in MessageBox or AnaliticalTable we get following error in typescript:
`Promise-returning function provided to attribute where a void return was expected`

**Isolated Example**
*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).*

**To Reproduce**

**Expected behavior**
Elements should accept Promise-returned function, because it is frequent case, when we want to do some async in handlers.

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:
`@ui5/webcomponents-react` version:
Operating System:
any
Browser:
any

**Additional context**

**Comment by Lukas742** [comment]
I will close this issue as there is already another one covering this topic. If you have any questions or more information, please address them in the original issue.

Duplicate #3909
