### ISSUE TITLE
ShellBar: Magnifier-Button toggles searchField, but doesn't trigger a search

### ISSUE THREAD

**Issue by MetalCar** [SAP/ui5-webcomponents-react#3982]
**Describe the bug**
It's more a question instead of a bug report. But i want to be sure.
The ShellBar-Component provides a property called `searchField` that contains, in my case an Input-Component. The ShellBar then attaches to that Input a button with a magnifier icon. Clicking on this button just toggles the searchfield, but we expected, that if we entered some text in the searchfield, the button triggers a search. In every case, the button is just a toggle for that searchfield. Is that right?

**To Reproduce**
```
<ShellBar
    searchField={<Input/>}
/>
```
**UI5 Web Components for React Information**
`@ui5/webcomponents` version: latest
`@ui5/webcomponents-react` version: latest
Operating System:
Browser: Google Chrome

**Comment by Lukas742** [comment]
Hi @MetalCar 

yup, the button is there to toggle the `searchField` and not to trigger a search. You have to do that on your input component. If you want to display a search icon inside the `Input`, then you can add the corresponding icon:

```jsx
<Input showClearIcon icon={<Icon name="search" interactive onClick={()=>{/* your search logic */}} />} />
```

As this isn't clear from the documentation, I'd suggest opening an [issue](https://github.com/SAP/ui5-webcomponents/issues/new/choose) in the UI5 Web Components repo, as we retrieve our prop description from there.

**Comment by Lukas742** [comment]
I'm going to close this issue here as the component is developed in the ui5-webcomponents' repo and the discussion is continued there. https://github.com/SAP/ui5-webcomponents/issues/6273
