### ISSUE TITLE
SideNavigation: SideNavigationSubItem doesn't work in collapsed mode

### ISSUE THREAD

**Issue by arhigod** [SAP/ui5-webcomponents-react#4006]
**Describe the bug**
User can't select/click on SideNavigationSubItem in SideNavigation collapsed mode. SideNavigation `onSelectionChange` event is not fired

**Isolated Example**
https://codesandbox.io/s/sidenavigation-bug-ch0y11?file=/src/App.js

**To Reproduce**
1. Try to select SideNavigationSubItem in SideNavigation collapsed mode
2. See an error 

**Screenshots**
![image](https://user-images.githubusercontent.com/19529418/213741642-b80dc071-9254-4825-8810-e9b63a768ef6.png)

**UI5 Web Components for React Information**
    "@ui5/webcomponents": "~1.9.3",
    "@ui5/webcomponents-fiori": "~1.9.3",
    "@ui5/webcomponents-react": "~1.7.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-scripts": "5.0.1"

**Comment by Lukas742** [comment]
Hi @arhigod 

`@ui5/webcomponents` have updated their project to v1.10.0 which is containing the fix to this issue. We're currently working on integrating this version in our wrapper, but as unfortunately there were some changes that did break our wrapper script, we will need more time than usual, as in the worst case the ui5 web components team will have to release another version on their end before we can update.
