### ISSUE TITLE
Avatar: when using icon, always displays Employee

### ISSUE THREAD

**Issue by tomasanchez** [SAP/ui5-webcomponents-react#4007]
**Describe the bug**
The avatar component always shows the employee icon.

**Isolated Example**
https://codesandbox.io/s/avatar-always-employee-cjnebf?file=/src/App.js

**To Reproduce**
1. Look at any avatar icon
2. See that icon imported
3. See error

**Expected behavior**
Avatar should contain the specified icon name.

**Screenshots**
![avatar-employee](https://user-images.githubusercontent.com/59451689/213894575-19f82fba-465e-4fe2-8137-c538f3d56ec1.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: "~1.9.3"
`@ui5/webcomponents-react` version: "~1.7.0"
Operating System: Windows 10
Browser: Edge

**Comment by Lukas742** [comment]
Hi @tomasanchez 

I will close this issue as there is already another one covering this topic. If you have any questions or more information, please address them in the original issue. 
`@ui5/webcomponents` have updated their project to v1.10.0 which is containing the fix. We're currently working on integrating this version in our wrapper, but as unfortunately there were some changes that did break our wrapper script, we will need more time than usual, as in the worst case the ui5 web components team will have to release another version on their end, before we can update. 

Duplicate https://github.com/SAP/ui5-webcomponents/issues/6101
