### ISSUE TITLE
DynamicPage: Nesting DynamicPage components causes overlapping issues

### ISSUE THREAD

**Issue by AndrianStoikov** [SAP/ui5-webcomponents-react#4033]
**Describe the bug**
When two DynamicPage components are nested one inside the other it causes overlap issues in their headers during scroll.

**Isolated Example**
[sandbox](https://codesandbox.io/s/cocky-kirch-gyzb87?file=/src/App.js)

**To Reproduce**
1. Go to the sandbox
2. Start scrolling down
3. You will notice how the bottom header of the DynamicPage overlaps the other

**Expected behavior**
DynamicPages should work correctly when nested.

**Screenshots**
![image](https://user-images.githubusercontent.com/21200806/214574415-a51b7390-8e9a-4b34-9866-8f51ac51f06e.png)
![image](https://user-images.githubusercontent.com/21200806/214574451-4b483b27-9c69-453d-b6b2-c5dc0efb6048.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.9.3
`@ui5/webcomponents-react` version: 1.7.0
Operating System: Windows 10
Browser: Edge Version 109.0.1518.61

**Additional context**

**Comment by Lukas742** [comment]
Hi @AndrianStoikov 

nesting a page component inside another page component is not supported.
If you still want to implement it like this, you need to set a fixed height to the DynamicPage, or the surrounding container.
