### ISSUE TITLE
Form: Form width doesn't display correctly

### ISSUE THREAD

**Issue by rkl1994** [SAP/ui5-webcomponents-react#404]
**Describe the bug**
The width for component 'Form' doesn't work correctly when the first time open the page.

**To Reproduce**
1. Go to https://test-for-ui5.cfapps.eu10.hana.ondemand.com
2. First time you see the form is only a small width
3. After resize the browser window, the layout for form is the correct width

**Expected behavior**
The width for form should be correct

**Screenshots**
The first time open the link
<img width="783" alt="Screen Shot 2020-04-03 at 4 38 22 PM" src="https://user-images.githubusercontent.com/5527455/78341054-a11b0400-75c9-11ea-80f7-87c7ee7c4cb5.png">

After resizing the browser window
<img width="1221" alt="Screen Shot 2020-04-03 at 4 40 02 PM" src="https://user-images.githubusercontent.com/5527455/78341148-cb6cc180-75c9-11ea-92f6-577c14d2d81a.png">

**UI5 Web Components for React Information**
Operating System: Mac OS 10.15.3, Chrome:80.0.3987.149
`@ui5/webcomponents-react` version: 0.8.6

**Comment by MarcusNotheis** [comment]
Hi @rkl1994, thanks for submitting this issue. 
Can you try whether the Form works as expected in one of our latest versions like `0.9.0-rc.8` or `0.9.0-rc.9` (rc.9 includes the UI5 Web Components rc.6)? Would it be possible to share the code for the Form with me as I'm currently not able to reproduce this issue?

**Comment by rkl1994** [comment]
Hi Marcus, thanks for your reply.
1. After I tried 0.9.0-rc.9, it still doesn't work, the first time I open the page, like this
<img width="604" alt="Screen Shot 2020-04-04 at 11 14 30 AM" src="https://user-images.githubusercontent.com/5527455/78417726-7c756980-7667-11ea-8c08-c2953246ec09.png">
Some part of inputs are missing. Only after resizing the browser, it becomes correct.

2. The code for form is
<img width="874" alt="Screen Shot 2020-04-04 at 11 19 58 AM" src="https://user-images.githubusercontent.com/5527455/78417601-3ff53e00-7666-11ea-8ac2-aba38d7d8c85.png">

3. The whole project is here https://github.com/rkl1994/test-ui5-react.git
It's a simple project with Form only. I would appreciate if you could take a look. Big thank you!

4. I also push it on CF, here is the link: https://test-for-ui5.cfapps.eu10.hana.ondemand.com/
Thank you!

**Comment by MarcusNotheis** [comment]
fixed and released in `@ui5/webcomponents-react@0.9.0-rc.11`.
Please be aware that `@ui5/webcomponents` and `@ui5/webcomponents-fiori` are now peerDependencies and have to be installed separately.
