### ISSUE TITLE
Types: ReducedReactNode/UI5WCSlotsNode

### ISSUE THREAD

**Issue by arhigod** [SAP/ui5-webcomponents-react#4047]
**Describe the bug**
[Here](https://github.com/SAP/ui5-webcomponents-react/pull/4013/files#diff-6156d885aca74aa2e2692f44c5bdedbf6236bcaf27b9575d86a6474fa1dbfb87R3) was created a new type `ReducedReactNode` which excluded `ReactFragment`.
And for now we have TS errors in all places, where the new type `UI5WCSlotsNode` is used, like this:
![image](https://user-images.githubusercontent.com/19529418/215053453-ab43ab5e-aa70-4588-8e61-5b55fd178d6e.png)
In this example we try to use common `Icon` in common `MessageStrip`.

Could you please check this

**Comment by Lukas742** [comment]
Hi @arhigod 

I wasn't able to reproduce this issue. (See [here](https://codesandbox.io/p/github/Lukas742/test-tsc/draft/stoic-platform?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A10%2C%22endLineNumber%22%3A12%2C%22startColumn%22%3A10%2C%22startLineNumber%22%3A12%7D%5D))

Could you please create a reproducible example? You can leverage the codeSandbox I posted above.

**Comment by Lukas742** [comment]
With support of @ej612, we were able to reproduce this behavior and pin the root cause to React v17 & v16 as the types for `ReactNode` differ with these versions. The linked PR will fix this issue.

**Comment by arhigod** [comment]
@Lukas742 Thanks a lot.
I tried to reproduce something in the sandbox, but now even the default template is crashing there for me :( 
![image](https://user-images.githubusercontent.com/19529418/215457381-40c2428f-f765-45ea-91fd-a055d2594ae2.png)

**Comment by Lukas742** [comment]
Hi @arhigod 

You're welcome. :) 
I believe codeSandbox has problems resolving some type modules. Not sure why this is happening though. That's why I used the beta instance of codeSandbox as example above, because there this issue does not occur.

**Comment by arhigod** [comment]
Hi @Lukas742 ,
Could you please look at this bug again.
Fixed in all places except:
```
<MessageStrip icon={<Icon name='delete'/>}>text</MessageStrip>
```
![image](https://user-images.githubusercontent.com/19529418/215711863-8c2fd2a6-c9b4-4cb7-a08a-301f4ae8afd3.png)

**Comment by Lukas742** [comment]
Hi @arhigod 

the example you provided differs from the one shown in the error message. 

There it says that `messageStripProps?.icon` can be an empty string which is not supported. Could you please double check your implementation?

--> `"" && <Component />` will return `""` as `Boolean("")` is `false` and therefore the chain stops there. So I guess the updates types have already bore fruit, by exposing a possible bug ;)
