### ISSUE TITLE
Button: Enable to click the button when the disabled property is true

### ISSUE THREAD

**Issue by AsafMaman** [SAP/ui5-webcomponents-react#4079]
**Describe the bug**
Enable to click the button when the disabled property is true

**Isolated Example**
<Button disabled={true} onClick={()=>console.log('clicked')}>Disabled Button</Button>

**To Reproduce**
1. Create a new button <Button disabled={true} onClick={()=>console.log('clicked')}>Disabled Button</Button>
2. run the app
3. open the dev tool.
4. click on the button.
5. clicked is shown it the console.

**Expected behavior**
Adding disabled={true} will disable the clicking event.

**Screenshots**
N/A

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.10.3
`@ui5/webcomponents-react` version: 1.8.1
Operating System:
Browser: Chrome

**Additional context**

**Comment by Lukas742** [comment]
Hi @AsafMaman 

I will close this issue as there is already another one covering this topic. If you have any questions or more information, please address them in the [original issue](https://github.com/SAP/ui5-webcomponents/issues/6372).

Duplicate https://github.com/SAP/ui5-webcomponents/issues/6372
