### ISSUE TITLE
AvatargGroup: avatars showing only in one div 

### ISSUE THREAD

**Issue by ozreads** [SAP/ui5-webcomponents-react#4120]
**Describe the bug**
When using AvatarGroup inside a FlexBox to display them in different divs, the avatars of the first div only show but the rest fo the divs just show how many avatars are in a number. 

**Isolated Example**
*Check this sandbox [this codesandbox](https://codesandbox.io/s/brave-villani-62dx0r?file=/src/App.js).*

**To Reproduce**
Check the sandbox above

**Expected behavior**
it should display the same avatar group as the first div for the rest of the divs since they all have the same spacing.

**Screenshots**
![image](https://user-images.githubusercontent.com/115879540/217607326-019d06ce-50ef-4851-9966-6a7dec8a905a.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: ~1.10.3
`@ui5/webcomponents-react` version: ^1.8.1
Operating System: Windows 11
Browser: Chrome

**Additional context**

**Comment by Lukas742** [comment]
Hi @ozreads 

I will close this issue as there is already another one covering this topic. If you have any questions or more information, please address them in the [original issue](https://github.com/SAP/ui5-webcomponents/issues/6355).

Duplicate https://github.com/SAP/ui5-webcomponents/issues/6355
