### ISSUE TITLE
Button: Button is disabled yet listens to onClick events

### ISSUE THREAD

**Issue by ozreads** [SAP/ui5-webcomponents-react#4121]
**Describe the bug**
I have disabled the button using prop `disabled`, however, it still listens to onClick events when it should not. 

**Isolated Example**
*Use this sandbox [this codesandbox](https://codesandbox.io/s/polished-meadow-xleok0?file=/src/App.js).*

**To Reproduce**
1. Go to 'the sandbox'
2. Click on the 'Click me' Button
3. Open the console, and see the button is clicked although it is disabled.

**Expected behavior**
if the button is disabled it should not be clicked.

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: ~1.10.3
`@ui5/webcomponents-react` version: ^1.8.1
Operating System: Windows 11
Browser: Chrome

**Additional context**

**Comment by Lukas742** [comment]
Hi @ozreads 

I will close this issue as there is already another one covering this topic. If you have any questions or more information, please address them in the [original issue](https://github.com/SAP/ui5-webcomponents/issues/6372).

Duplicate https://github.com/SAP/ui5-webcomponents/issues/6372
