### ISSUE TITLE
Line chart: Allow to customize type of the graph

### ISSUE THREAD

**Issue by rvsia** [SAP/ui5-webcomponents-react#4124]
**Is your feature request related to a problem? Please describe.**

I want to be able to change type of the [line chart](https://sap.github.io/ui5-webcomponents-react/?path=/docs/charts-linechart--default-story).

**Current**

<img width="1124" alt="Snímek obrazovky 2023-02-09 v 10 31 47" src="https://user-images.githubusercontent.com/32869456/217773537-e98c6031-d707-4f08-a5fa-0252976feca7.png">

**Intended**

<img width="1120" alt="Snímek obrazovky 2023-02-09 v 10 32 38" src="https://user-images.githubusercontent.com/32869456/217773567-4a29a917-be61-4d02-a332-77b2248895c8.png">

**Describe the solution you'd like**

The [type](https://recharts.org/en-US/api/Line#type) is [hardcoded directly in the component](https://github.com/SAP/ui5-webcomponents-react/blob/0484ac51ad41ba344bbb5657862739007ef3b3f5/packages/charts/src/components/LineChart/LineChart.tsx#L295).

I would like to be able to change this type, using the `element.type` property in the configuration of the chart. 

```jsx
<LineChart
   ....
    measures={[
        {
            accessor: 'value',
            color: 'red',
            type: 'linear' // <<<<<<
        },
    ]}
    .... 
/>
```

**Describe alternatives you've considered**

n/a

**Additional context**

[Linear line charts are included in Fiori](https://experience.sap.com/internal/fiori-design-web/line-micro-chart/)

---

**I would like to work on this issue.** 😊

**Comment by rvsia** [comment]
@Lukas742  Oh, don't worry. Thank you for fixing it! 😊

**Comment by rvsia** [comment]
@Lukas742 When is going this feature to be released please? 🙏

**Comment by Lukas742** [comment]
Next week at the latest.
