### ISSUE TITLE
VariantManagement: Renaming the variant- Blank spaces allowed 

### ISSUE THREAD

**Issue by knandan15** [SAP/ui5-webcomponents-react#4129]
**Describe the bug**
In the framework component of VariantManagement, we can change the name of the variants from the Manage Views. If we put only spaces and no letters, still the renaming is successful which is not ideal behaviour. 

**Isolated Example**
On the framework component itself: ( https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-variantmanagement--default-story )

**To Reproduce**
1. Click on the dropdown for variant list.
2. Click on "Manage".
3. Let's rename "Author" variant. Remove the name and just type few space characters.
4. Click on "Save".
5. The Variant List has one variant with no name.

**Expected behavior**
As shown in the UI5 component: ( https://sapui5.hana.ondemand.com/#/entity/sap.ui.comp.smartfilterbar.SmartFilterBar/sample/sap.ui.comp.sample.smartfilterbar.example2 )
The user should not be allowed to save the variant name as blank. 

**Screenshots**

![Variant Mgmt - Blank Name](https://user-images.githubusercontent.com/48648230/218013565-bafc96d1-3c61-4f44-aa0d-09d8bbacdc86.PNG)

**Comment by knandan15** [comment]
@Lukas742 , in which release could we expect this fix?

**Comment by Lukas742** [comment]
Hi @knandan15 

the next one. We don't have a concrete timeline for it yet, but it should come next week at the latest.
