### ISSUE TITLE
Input: Missing support for `onSuggestionScroll` event

### ISSUE THREAD

**Issue by codefactor** [SAP/ui5-webcomponents-react#4142]
**Describe the bug**
The types for the `Input` element do not expose the `onSuggestionScroll` event which is available on the native web component with the custom event `suggestion-scroll` - see https://github.com/SAP/ui5-webcomponents/blob/main/packages/main/src/Input.ts#L238

**Isolated Example**
Not necessary

**To Reproduce**
Check the following links:
1. https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-input--default-story
2. https://sap.github.io/ui5-webcomponents/playground/components/Input/
3. https://github.com/SAP/ui5-webcomponents/blob/main/packages/main/src/Input.ts#L238

Notice that the `ui5-input` webcomponent has a custom event called `suggestion-scroll` but the documentation does not list that anywhere. Also the typescript definition for the `<Input>` component does not have any `onSuggestionScroll` available to use.

**Expected behavior**
When using the `<Input>` component we should be able to listen to the `onSuggestionScroll` event without having a layout effect to add the listener with the native dom ref.

**Screenshots**
N/A

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.10.3
`@ui5/webcomponents-react` version: 1.8.1
Operating System:
Browser: *

**Additional context**
This new event was added later in a feature request to support infinite scrolling behavior.

**Comment by Lukas742** [comment]
Hi @codefactor 

the `sugestion-scoll` event is not a public event (`@protected`) and therefore we don't expose it in our documentation (nor does the ui5-webcomponents' team) and don't support it as prop or on the element itself. If you feel like this should be made public, please open a feature request in the[ ui5-webcomponents](https://github.com/SAP/ui5-webcomponents) repo asking for this.
