### ISSUE TITLE
VariantManagement: Renaming the variant- No character validation and length check

### ISSUE THREAD

**Issue by knandan15** [SAP/ui5-webcomponents-react#4157]
**Describe the bug**
In the framework component of VariantManagement, we can change the name of the variants from the Manage Views. If we type very long names (say, 50+ characters), different symbols, etc. - all are allowed.

**Isolated Example**
On the framework component itself: ( https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-variantmanagement--default-story )

**To Reproduce**
1. Click on the dropdown for variant list.
2. Let's rename "Author" variant. Typing in various symbols and numerous letters making a long name.
3. Click on "Save".
4. The Variant List has the variant with long names and containing symbols.

**Expected behavior**
As shown in the UI5 component: ( https://sapui5.hana.ondemand.com/#/entity/sap.ui.comp.smartfilterbar.SmartFilterBar/sample/sap.ui.comp.sample.smartfilterbar.example2 )
The user should not be allowed to type a variant name exceeding a certain character limit (say, 50 characters). Also, validation checks should be there like no symbols (#$% etc.) shall be allowed in the names. There is no mechanism as for now to define the checks for the variant name.

**Screenshots**

![Name check in variant](https://user-images.githubusercontent.com/48648230/219007788-ab92c873-7683-4913-bd03-9f98340b6910.PNG)
![Screenshot (184)](https://user-images.githubusercontent.com/48648230/219008259-8c825c8c-6dc3-4b27-9f4e-02ec145b51da.png)

**Comment by knandan15** [comment]
@Lukas742  In the release, still there is no character limit for the Variant's name as requested in the above screenshot. We require character name limit to 50 character length if that is possible.

Attaching the UI5 component snapshot for reference again.
![image](https://user-images.githubusercontent.com/48648230/220048051-e4c6650e-db6a-4463-bc3c-e9504be968d6.png)

**Comment by Lukas742** [comment]
Hi @knandan15 

since each application can have different requirements, we won't add this behavior out of the box, but you're now able to adjust the validation as explained [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-variantmanagement--with-custom-validation).
