### ISSUE TITLE
AnalyticalTable [TreeTable]: Expand tree hierarchy to a specific level by default when its loaded

### ISSUE THREAD

**Issue by I506645** [SAP/ui5-webcomponents-react#4165]
Currently, AnalyticalTable doesn't have a property to expand the tree hierarchy by default to a specific level as it's in sap.ui.table.TreeTable (eg: property- expandFirstLevel) when its loaded initially. To expand the tree table, the user has to click the expand icon on each row to expand the subRows.

Solution would be to provide a property with which the Analytical TreeTable would expand the subrows by default to a specific level or all the levels when the component is loaded.

We don't see any alternatives except that the user has to click manually on each parent row to expand its children (subRows). If there's any alternative that you can provide at the moment, we would be happy to implement it.

![image](https://user-images.githubusercontent.com/121158363/219327733-1599f931-f778-40a0-bd78-659fe9e6d04d.png)

Best Regards,
Raghav

**Comment by Lukas742** [comment]
Hi @I506645 

you can use the `reactTableOptions` to achieve this. There you can pass all available react-table options (e.g. for [useExpanded](https://react-table-v7.tanstack.com/docs/api/useExpanded))

I've created a codeSandbox that should explain this in more detail: https://codesandbox.io/s/treetable-forked-83j30w?file=/src/App.js

**Comment by I506645** [comment]
Thanks @Lukas742!
This works.

Best Regards,
Raghav
