### ISSUE TITLE
Button: Disabled button can be clicked

### ISSUE THREAD

**Issue by samanr** [SAP/ui5-webcomponents-react#4168]
**Describe the bug**
A button with a disabled property can be clicked. Upon clicking the function passed to the onClick event is executed. This behaviour is not expected. 

**Isolated Example**
https://codesandbox.io/s/recursing-hamilton-h2jppy

**To Reproduce**
1. Add a Button component. 
2. Pass disabled property and onClick event.
3. Click the button and notice that the event is called.

**Expected behavior**
The button should not be pressed.

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.10.3
`@ui5/webcomponents-react` version: 1.8.1
Operating System:
Browser: Chrome

**Additional context**

**Comment by MarcusNotheis** [comment]
Hi @samanr,
this issue has already been fixed in [UI5 Web Components v1.10.4](https://github.com/SAP/ui5-webcomponents/releases/tag/v1.10.4). Please try upgrading to `@ui5/webcomponents@1.10.4` and `@ui5/webcomponents-fiori@1.10.4`.
