### ISSUE TITLE
DynamicPageTitle: Space button is not working in Inputs in actions

### ISSUE THREAD

**Issue by arhigod** [SAP/ui5-webcomponents-react#4190]
**Describe the bug**
Can't insert spaces using a Space button in Inputs in DynamicPageTitle actions (ctrl+с ctrl+v inserts spaces correctly).

**Isolated Example**
https://codesandbox.io/s/dynamicpagetitleactions-spaces-in-inputs-hchs82?file=/src/App.js:187-203

**To Reproduce**
Try to add spaces in the input field

**UI5 Web Components for React Information**
    "@ui5/webcomponents": "~1.10.3",
    "@ui5/webcomponents-fiori": "~1.10.3",
    "@ui5/webcomponents-react": "~1.8.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-scripts": "5.0.1"

**Additional context**
I also can't use Inputs if they are in a Dialog that is opened by a button from an action.

**Comment by Lukas742** [comment]
Hi @arhigod 

thanks for reporting. The linked PR will fix this issue. Until it's released you can use a workaround by preventing bubbling of the `key-down` event on your end by calling `event.stopPropagation` in the respective handler. --> [codeSandbox](https://codesandbox.io/s/dynamicpagetitleactions-spaces-in-inputs-forked-imn2ub?file=/src/App.js)

**Comment by GongRichard** [comment]
Hi @Lukas742 ,
I want to check with you when this fix will be released?
Thanks,
Richard

**Comment by Lukas742** [comment]
It's already available:
https://github.com/SAP/ui5-webcomponents-react/releases/tag/v1.9.2
