### ISSUE TITLE
MessageToast: This component could not be found.

### ISSUE THREAD

**Issue by ggfer** [SAP/ui5-webcomponents-react#422]
**Describe the bug**
The component of MessageToast could not found in lib.

**To Reproduce**
1. import module 'import { MessageToast } from '@ui5/webcomponents-react/lib/MessageToast';'
2. refresh
3. See error

**Expected behavior**
this module exists and could be imported.

**Screenshots**
![image](https://user-images.githubusercontent.com/19473701/79072989-90c7ff00-7d16-11ea-86d6-f7b08b6cb1f5.png)

**UI5 Web Components for React Information**
Operating System:
`@ui5/webcomponents-react` version:"^0.9.0-rc.10",

**Comment by MarcusNotheis** [comment]
Hi @ggfer, according to [our changelog](https://github.com/SAP/ui5-webcomponents-react/blob/master/CHANGELOG.md#090-rc9-2020-04-03) the `MessageToast` component was removed in `rc.9` in favour of the new `Toast` component built. Please use this one instead.

Best regards,
Marcus
