### ISSUE TITLE
Change column count in ProductSwitch

### ISSUE THREAD

**Issue by MetalCar** [SAP/ui5-webcomponents-react#4222]
### Is your feature request related to a problem?

As far as I know the `ProductSwitch`-Component always render a maximum of three items in a row. I would like to change this. So that is possible to show 4 or 5 in a row.

### Describe the solution you'd like

I found a possible solution in the original UI5-Webcomponents. There is a example were a `ProductSwitch` is used into the `ShellBar`. This example shows 4 items in a row within a `ProductSwitch`-Component. Unfortunately the property that is used, isn't documented and also not working with the react components. They used in their example a property called `desktop-columns`. In the example the `ProductSwitch` then shows 4 items. Maybe we can get this property for the react component?

**Comment by Lukas742** [comment]
Hi @MetalCar 

we don't change or limit the implementation of the web component, we just wrap it so it's easier to use in the React way. I checked and the property you're referring to is [private](https://github.com/SAP/ui5-webcomponents/blob/52134a6e323c923f970d5a84207e856be56d6aa5/packages/fiori/src/ProductSwitch.ts#L78-L83) (`@private` annotation), so we don't expose or support it as prop. Even though I wouldn't recommend it, you can always access the web component directly, for example by attaching a ref, and change the property there. 

In my opinion, it would be better to create a [feature request](https://github.com/SAP/ui5-webcomponents/issues/new/choose) in the ui5-webcomponents repo and ask there if this property could be made publicly available.
