### ISSUE TITLE
Example code not displaying on sap.github.io/ui5-webcomponents-react

### ISSUE THREAD

**Issue by qscheitlin** [SAP/ui5-webcomponents-react#4277]
### Describe the documentation issue

Documentation is missing

### Description

Hello, 

When I'm trying to look at example code for any of the ui5-react-webcomponents, it is not showing up.  Please see example below.  Is there an alternative source to view the example code?

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/127273220/223607660-6c523aa2-cb7a-422d-8fc7-3cc4c91a23df.png">

### Link to Documentation Page

https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-shellbar--docs

**Comment by MarcusNotheis** [comment]
Hi @qscheitlin,
thanks for reporting! We've fixed the codeblocks via #4275 and just deployed a new version of documentation.
The Code Blocks should now work as expected again 🙂
