### ISSUE TITLE
npm install @ui5/webcomponents-react-charts

### ISSUE THREAD

**Issue by cscheitl** [SAP/ui5-webcomponents-react#4288]
### Describe the bug

Hello - When I go to install "npm install @ui5/webcomponents-react-charts" into the terminal. It says 4 vulnerabilities are found.  I tried to use npm install @ui5/webcomponents-react-charts --no-audit, however, I could still not install the package effectively. Can you please look into this issue. 

### Reproduction steps

1.
2.
3.
...

### UI5 Web Components for React Version

Yes

### UI5 Web Components Version

No

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MarcusNotheis** [comment]
Hi @cscheitl 
thanks for reaching out! Can you please share more details about the version of `@ui5/webcomponents-react-charts` you are installing? I just tried it in a new project and got zero vulnerabilities reported:
```sh
npm i @ui5/webcomponents-react-charts

added 99 packages, and audited 100 packages in 33s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

npm audit
found 0 vulnerabilities
```

**Comment by Lukas742** [comment]
These are only source-map warnings which are rooted in the `@ui5/webcomponents` library and they should have nothing to do with the problem you're facing. 

Here you can find a [codeSandbox](https://codesandbox.io/p/sandbox/default-linechart-forked-82s938?file=%2Fsrc%2FApp.js) that implements a simple `LineChart` with the latest versions and it seems to be working fine. Could you please compare your implementation (especially the dependencies in the `package.json`) with the codeSandbox I provided and see if there is something off?
