### ISSUE TITLE
[MessageBox]: inconsistent title styles

### ISSUE THREAD

**Issue by Lultik** [SAP/ui5-webcomponents-react#4290]
### Describe the bug

We have many MessageBoxes in the application and MessageBoxes with `type={MessageBoxTypes.Confirm}` props have the following layot:
```html
<header slot="header" class="MessageBox-header-0-2-25">
  <ui5-icon accessible-role="presentation" design="Default" name="sys-help-2" aria-hidden="true" ui5-icon=""></ui5-icon>
  <span class="MessageBox-spacer-0-2-26"></span>
  <ui5-title level="H2" id="1ac0c15d-6459-4a4c-b2d5-c30c215ce183-title" ui5-title="">...</ui5-title>
</header>
```
At the same time there is such layout for all other `type` variants:
For `type={MessageBoxTypes.Warning}`
```html
<header class="ui5-popup-header-root" id="ui5-popup-header" part="header" state="Warning">
  <ui5-icon class="ui5-dialog-value-state-icon" name="alert" ui5-icon=""></ui5-icon>
  <h1 id="ui5-popup-header-text" class="ui5-popup-header-text">...</h1>
</header>
```
For `type={MessageBoxTypes.Information}`
```html
<header class="ui5-popup-header-root" id="ui5-popup-header" part="header" state="Information">
  <ui5-icon class="ui5-dialog-value-state-icon" name="information" ui5-icon=""></ui5-icon>
  <h1 id="ui5-popup-header-text" class="ui5-popup-header-text">...</h1>
</header>
```

### Reproduction steps

1. Create MessageBox component with `type={MessageBoxTypes.Confirm}` prop.
2. Create another MessageBox component with `type={MessageBoxTypes.Warning}` prop. (Or any other type, excepting Confirm)

### Expected Behaviour

Titles of both MessageBoxes have the same layout

### UI5 Web Components for React Version

"@ui5/webcomponents-react": "1.8.1"

### UI5 Web Components Version

"@ui5/webcomponents": "1.10.3"

### Browser

Chrome, Edge, Firefox, Safari

### Operating System

All

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @Lultik 

the `MessageBox` has different styles depending on its `type` because the underlying `Dialog` doesn't offer the `"Confirmation"` state. I checked the specs and it seems that they've been updated. The linked PR will fix the level of the title and the color of the icon. 

If you find more discrepancies please provide a screenshot so we can take a look.

**Comment by Lultik** [comment]
Thank you @Lukas742 !!!
