### ISSUE TITLE
ShellBar can't run on codesandbox

### ISSUE THREAD

**Issue by jeffhtli** [SAP/ui5-webcomponents-react#435]
**Describe the bug**
An error occurred when add ShellBar to code:
TypeError: Class constructor UI5Element cannot be invoked without 'new' 

But this code can run correctly in my local environment.

**To Reproduce**
1. open sample code: https://codesandbox.io/s/epic-elion-se2f0 
2. See error

**Expected behavior**
a ShellBar should be displayed

**Screenshots**
<img width="948" alt="shellbar-snapshot" src="https://user-images.githubusercontent.com/6480053/79522805-3f5d9e00-808f-11ea-938f-2e6a2df0bdce.png">

**UI5 Web Components for React Information**
  "dependencies": {
    "@ui5/webcomponents-react": "0.8.6",
    "react": "16.12.0",
    "react-dom": "16.12.0",
    "react-scripts": "3.0.1"
  },
  "devDependencies": {
    "typescript": "3.8.3"
  },

**Additional context**

**Comment by MarcusNotheis** [comment]
Hi @jeffhtli 
thanks for submitting this issue.
Can you try again with the URL you shared? I just opened it and it was working fine for me.

**Comment by jeffhtli** [comment]
It also works for me now.
I always failed few days ago, don't know why.

**Comment by MarcusNotheis** [comment]
I exactly know the issue you were describing but we didn't found a solution for that yet. We are even not sure if it is on our side or on the side of codesandbox. Maybe they fixed something 😄

**Comment by jeffhtli** [comment]
My another [demo](https://codesandbox.io/s/github/jeffhtli/todo-ui5) with ui5 is also can't run before, but worked correctly on codesandbox today. 

Maybe some dependencies have updated, maybe some changes have made in codesandbox side😁
