### ISSUE TITLE
[SF][1.10.0][ObjectPage]: There is no left&right padding in Firefox

### ISSUE THREAD

**Issue by i323808** [SAP/ui5-webcomponents-react#4359]
### Describe the bug

There is no left & right padding in Firefox.
![chrome](https://user-images.githubusercontent.com/30744017/225591085-42298821-4501-4cbf-8fd4-caf1245f1e18.png)
![firefox](https://user-images.githubusercontent.com/30744017/225591104-82291319-baf9-440c-adcf-d46ffd99c0c4.png)

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/story/layouts-floorplans-objectpage--default

### Reproduction steps

1. open https://sap.github.io/ui5-webcomponents-react/?path=/story/layouts-floorplans-objectpage--default using Firefox
2. there is no left & right padding

### Expected Behaviour

ObjectPage is supposed to have left & right padding.

### UI5 Web Components for React Version

1.10.0

### UI5 Web Components Version

1.11.0

### Browser

Firefox

### Operating System

macOS Ventura 13.2.1

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @i323808 

what version of Firefox are you using?

**Comment by i323808** [comment]
Hi @Lukas742 ,

My Firefox version is 109.0.1 (64-bit).

**Comment by Lukas742** [comment]
Hi @i323808 

this version is almost two months old and doesn't support container queries, that's why the padding is missing for you. Please update to the latest version (or at least to v110).

**Comment by i323808** [comment]
Hi @Lukas742 ,

I upgraded my Firefox and now ObjectPage is working fine.

Thanks,
Jane
