### ISSUE TITLE
[Analytical Table]: Inconsistent behaviour of scroll bars for Firefox and Chrome

### ISSUE THREAD

**Issue by Lultik** [SAP/ui5-webcomponents-react#4379]
### Describe the bug

Firefox: According to lib settings, scroll bars are included into analytical table content, whereas in Chrome - out of table content, which results in inconsistency across app functionalities by cross-browser testing.

On top of that, horizontal scrollbar overlap the content of the last row in Firefox

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

Scroll bar is set to be out of analytical table content

### Screenshots or Videos

Chrome:
![image](https://user-images.githubusercontent.com/60568127/226390606-74200364-715f-410a-b9b7-c80de1fda78a.png)
Firefox:
<img width="727" alt="image" src="https://user-images.githubusercontent.com/60568127/226390923-1307016c-cc27-4f82-af4f-353cd1cffaf0.png">

Firefox (horizontal):
![image](https://user-images.githubusercontent.com/60568127/226389906-3a486bf3-92c0-4b4c-a185-6f5c63304377.png)

### UI5 Web Components for React Version

1.11.0

### UI5 Web Components Version

1.11.0

### Browser

Chrome, Firefox

### Operating System

MacOS, Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by kozubikmichal** [comment]
Hi,
not sure if it's related or if I should create a new issue, but the scrollbars are also not working properly in Safari - they're hidden behind the table, so it's really hard to see/access them

![image](https://github.com/SAP/ui5-webcomponents-react/assets/26189327/66cea720-fb97-4278-ba4b-39625e63a5ed)
