### ISSUE TITLE
[SAP][Analytical Table]: OnRowSelect, OnRowClick event fired when space is pressed not on keyUp

### ISSUE THREAD

**Issue by thisisjasmeet** [SAP/ui5-webcomponents-react#4388]
### Describe the bug

click event should be fired on keyDown not onKeyUp 

analytical table onRowSelect and onRowClick is fired when space is pressed

### Isolated Example

Can be reproduced in https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable--docs

### Reproduction steps

1. got to https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable--docs
2. enable multiple selection
3. go to table and navigate to row selection checkbox using keys
4. press and hold space

Issue:- onRowSelect is triggered and row gets selected

### Expected Behaviour

Expected behaviour:- it should be triggered when space key is released.

Note:- This issue is raised by SAP internal Accessbility testing team BCP ticket n0:- 2370008332

### UI5 Web Components for React Version

1.10.3

### UI5 Web Components Version

1.10.3

### Browser

Chrome

### Operating System

macos

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @thisisjasmeet 

> click event should be fired on keyDown not onKeyUp

You mean the other way around, right?

Is there a guideline for this? And if so, could you send it to me?

**Comment by thisisjasmeet** [comment]
@Lukas742  SAP internal team has done accessibility testing for our product and they have reported this issue

also for Button component, onClick is fired when key is realised. so  I think both the components should have same behaviour

**Comment by Lukas742** [comment]
Hi @thisisjasmeet 

unfortunately, we haven't implemented this behavior in any of our components, and especially for the AnalyticalTable, this change could be considered breaking, as it's possible to hook into this behavior and change it on the developer side. That's why we decided to add this to our [roadmap](https://github.com/SAP/ui5-webcomponents-react/issues/3857) for the 2.0 release, but we can't implement it yet.
