### ISSUE TITLE
[SF][TextArea]: TextArea missing bottom border on horizon theme

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents-react#4398]
### Describe the bug

Hi team,
TextArea component missing bottom border on horizon theme.

### Reproduction steps

1.go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-textarea--docs

2.change theme to horizon see the TextArea missing bottom border.
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/78520316/227131705-2d793fda-748d-4026-93bc-31c22b0f119b.png">

### Expected Behaviour

TextArea should have bottom border on horizon theme. Like [ui5 webcomponents ui5-textarea](https://sap.github.io/ui5-webcomponents/playground/components/TextArea/) 
<img width="1442" alt="image" src="https://user-images.githubusercontent.com/78520316/227132221-a3f5378a-421c-4a01-a735-0e1ddc6733a8.png">

### UI5 Web Components for React Version

1.12.0

### UI5 Web Components Version

1.11.0

### Browser

Chrome

### Operating System

Mac OS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @sfsf-xweb-sh 

Thanks for reporting!
I will close this issue as there is already another one covering this topic. If you have any questions or more information, please address them in the original issue.

Duplicate https://github.com/SAP/ui5-webcomponents/issues/6746
