### ISSUE TITLE
[SAP][Analytical Table]: Focus is present at two positions when select box is used in analytical table.

### ISSUE THREAD

**Issue by chiragSAP** [SAP/ui5-webcomponents-react#4415]
### Describe the bug

When user tries to select an option in select box within analytical table using arrow keys the focus is present at two positions

### Reproduction steps

1. Click on select box present is analytical table
2. Press Up or Down arrow key to iterate through options available
3. Movement of focus can be seen at two positions
...

### Expected Behaviour

Focus should be present at a single place at a time.

### Screenshots or Videos

https://user-images.githubusercontent.com/129057796/227923845-baf49e34-b4ec-4d11-a630-6b3d839f0c3c.mp4

### UI5 Web Components for React Version

1.10.3

### UI5 Web Components Version

1.10.3

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @chiragSAP 

the event is bubbling up to the table, to prevent that you can call `event.stopPropagation()` in the respective handler.
--> [codeSandbox example](https://codesandbox.io/p/sandbox/defaulttable-forked-fwb601?file=%2Fsrc%2FApp.js)
