### ISSUE TITLE
Analytical Table: Selection Behavior Inconsistency

### ISSUE THREAD

**Issue by agauyeung** [SAP/ui5-webcomponents-react#442]
**Describe the bug**
Behavior for selecting rows (MULTI_SELECT) for Analytical Table is inconsistent.
Seems to have been caused by https://github.com/SAP/ui5-webcomponents-react/issues/428.

**To Reproduce**
- Click the checkbox to select --> the row is not selected
- Click a ui5-button inside the cell --> the row is selected
- Click a ui5-link inside the cell --> the row is selected
- Click the row --> the row is selected

**Expected behavior**
- Click the checkbox to select --> the row is selected
- Click a ui5-button inside the cell --> the row is not selected
- Click a ui5-link inside the cell --> the row is not selected
- Click the row --> the row is selected

**UI5 Web Components for React Information**
Operating System:
`@ui5/webcomponents-react` version:
Do you have a dependency to`@ui5/webcomponents` in your package.json? If yes, which version?:

*If you are not sure, you can find out by running `npm ls @ui5/webcomponents-react` or `yarn why @ui5/webcomponents-react`* 0.9.0-rc.15

**Comment by MarcusNotheis** [comment]
Hi @agauyeung 
thanks for reporting. We were able to reproduce the 1st and 4th error, but not the ones with the button and the link. After clicking those elements the table row was not selected. 
Can you share a reproducible example with us?

Thanks!
I will let you know as soon as we do our next rc.

**Comment by MarcusNotheis** [comment]
Released in `v0.9.0-rc.16`
