### ISSUE TITLE
Table: A large blank space on top of the table

### ISSUE THREAD

**Issue by rkl1994** [SAP/ui5-webcomponents-react#443]
**Describe the bug**
There is a large blank space on top of the table, but it is not margin or padding

**To Reproduce**
1. Go to 'https://ui5-webcomponents-react.netlify.app/?path=/story/ui5-web-components-table--generated-default-story'
2. In the table components in story book, you can see this bug.

**Expected behavior**
blank space should disappear.

**Screenshots**
<img width="1462" alt="Screen Shot 2020-04-22 at 10 49 15 AM" src="https://user-images.githubusercontent.com/5527455/79935301-29811c00-8487-11ea-9265-70bff351c353.png">

**UI5 Web Components for React Information**
"@ui5/webcomponents": "1.0.0-rc.6",
"@ui5/webcomponents-fiori": "1.0.0-rc.6",
"@ui5/webcomponents-icons": "1.0.0-rc.6",
"@ui5/webcomponents-react": "^0.9.0-rc.14",

**Comment by MarcusNotheis** [comment]
Hi @rkl1994 
Issue is fixed and will be part of our next release candidate.
Thanks for reporting!

Best regards,
Marcus

**Comment by MarcusNotheis** [comment]
Released in `v0.9.0-rc.16`
