### ISSUE TITLE
[DynamicPage/AnalyticalTable]: Anaytical Table is not completely visible even if there is lot of space in the window.

### ISSUE THREAD

**Issue by knandan15** [SAP/ui5-webcomponents-react#4436]
### Describe the bug

The AnalyticalTable has 100 records. But we can see only 3 entries even if lots of space is there on the window. Please refer to the codesandbox example provided. Here,  **visibleRowCountMode={"Auto"}**  still when the page is zoomed out, we still see 3 entries.

### Isolated Example

https://codesandbox.io/s/dynamicpage-flexiblecolumn-forked-b7wwid?file=/src/App.js

### Reproduction steps

1. Open the sandbox.
2. Zoom out or Zoom in.
3. It is observed that lots of remaining free space is there on the window and the number of entries  visible in the table regardless of the zooming out, remains the same.

### Expected Behaviour

The table should be responsive and upon zooming out and accordingly more entries of the table should be visible.

### UI5 Web Components for React Version

"@ui5/webcomponents-react": "^1.8.1"

### UI5 Web Components Version

"@ui5/webcomponents": "^1.10.3"

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Rahishsaifi** [comment]
Hi @knandan15 ,
You can set the height of the analytical table,  style={{ height: 300 }} , then this will work.
![image](https://user-images.githubusercontent.com/16429797/228807522-06d3c01d-c686-438b-95e1-59e3a93e8632.png)

I hope this will help you.
Thanks

**Comment by knandan15** [comment]
On setting the height:300, still the no. of rows appearing are fixed. We have set the visibleRowCountMode={"Auto"}. How can we have a responsive table in which more no. of rows appear when the resolution is zoomed out?

**Comment by knandan15** [comment]
Any updates for this ticket?

**Comment by MarcusNotheis** [comment]
Hi @knandan15,
this looks like a bug in the `DynamicPage` to me where the inner content `div` of the page does not occupy the full available height, we'll look into fixing this.
Until then, you can use the following CSS for a workaround:
```css
.dynamicPage [data-component-name="DynamicPageContent"] {
  height: 100%;
}
```
Then, apply the `.dynamicPage` class to the `DynamicPage` component and remove the fixed height of the `AnalyticalTable` again.

Codesandbox Example: https://codesandbox.io/s/dynamicpage-flexiblecolumn-forked-tjih01?file=/src/App.js

**Comment by knandan15** [comment]
Hi @MarcusNotheis ,
Thanks for replying. Will look into the workaround. Meanwhile if any fix is available, please let know.

**Comment by Lukas742** [comment]
Hi @knandan15 

depending on your use case, applying a height to the content element could solve the issue, but it can lead to side-effects (multiple scrollbars, wrong expand/collapse behavior, etc.), that's why we don't apply it out of the box.

You can use a relative height that is not dependent on the parent (e.g. `vh`), other than that I think a ResizeObserver is the best option then to set a static height, depending on the content area.

[Here](https://codesandbox.io/p/sandbox/gifted-black-37r1hr?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A62%2C%22endLineNumber%22%3A27%2C%22startColumn%22%3A62%2C%22startLineNumber%22%3A27%7D%5D) you can find a basic example how this could be achieved.

**Comment by knandan15** [comment]
Hi @Lukas742 
I tried implementing the approach you shared in our application. Once all entries are available in the Analytical Table (after scrolling to next page entries) then everything works fine. 
Scenario in our app is that when we load the app, by 20 entries are loading in the table (Default Page Size) and still upon zooming out we all not able to see the scroll bar(even if 40 entries are there in table). 

Can we have any property in analytical table where if we have the total count of rows and if it is greater than the page size then scroll bar will be visible?

**Comment by Lukas742** [comment]
Hi @knandan15 

unfortunately I don't really understand what you want to achieve. Could you please attach a video with a detailed description of the issue you're facing and if possible another codeSandbox?

**Comment by knandan15** [comment]
Hi @Lukas742 ,
Is there any approach how a paginated table (page size = 20) can load more entries when the resolution is zoomed out to increase the vacant area in the screen?

**Comment by knandan15** [comment]
> Hi @knandan15
> 
> depending on your use case, applying a height to the content element could solve the issue, but it can lead to side-effects (multiple scrollbars, wrong expand/collapse behavior, etc.), that's why we don't apply it out of the box.
> 
> You can use a relative height that is not dependent on the parent (e.g. `vh`), other than that I think a ResizeObserver is the best option then to set a static height, depending on the content area.
> 
> [Here](https://codesandbox.io/p/sandbox/gifted-black-37r1hr?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A62%2C%22endLineNumber%22%3A27%2C%22startColumn%22%3A62%2C%22startLineNumber%22%3A27%7D%5D) you can find a basic example how this could be achieved.

Hi @Lukas742 ,
In the example provided in the codesandbox, I observe that when you change the resolution of your screen (zoom out), then multiple scrollbar are observed. (Refer to the screenshot attached)

![image](https://user-images.githubusercontent.com/48648230/233956755-e04be6ae-2646-4a7d-b5b1-c63466bb8099.png)
