### ISSUE TITLE
[SAP][Analytical Table] Need to add accessibility support for "withRowHighlight" attribute

### ISSUE THREAD

**Issue by anshul-031** [SAP/ui5-webcomponents-react#4454]
### Describe the bug

![New Bitmap image](https://user-images.githubusercontent.com/18512766/229700527-605f92c7-b046-4696-bb71-34074f3bbdae.jpg)
We have a requirement for accessibility where screen reader should reads "Invalid Data" where if in a <AnalyticalTable> "withRowHighlight" attribute has a value something like "errorHighlight" as shown in figure. 

Is there any attribute which supports this?

### Reproduction steps

1.
2.
3.
...

### UI5 Web Components for React Version

1.8.0

### UI5 Web Components Version

1.10.3

### Browser

Chrome, Edge

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @anshul-031 

to add aria announcements, you can hook into the table by creating a custom [plugin hook](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable-recipes--docs#how-to-add-your-own-plugin-hooks).

See [codeSandbox](https://codesandbox.io/p/sandbox/defaulttable-forked-84xdfe?file=%2Fsrc%2FApp.js&selection=%5B%7B%22endColumn%22%3A56%2C%22endLineNumber%22%3A32%2C%22startColumn%22%3A56%2C%22startLineNumber%22%3A32%7D%5D)
