### ISSUE TITLE
MultiComboBox Always selects the first item

### ISSUE THREAD

**Issue by LuisValgoi** [SAP/ui5-webcomponents-react#448]
**Describe the bug**
First Item got always selected even if I select the other ones.
This happens only when I use the keyboard to filter by the one I want.

**To Reproduce**
1. Go to `MultiComboBox`
2. Click directly on the search area (not the dropdown).
3. Type `Item` to filter the items
4. Select w/ keyboard the 3rd one.
5. You will see that the first will also be selected.

**Expected behavior**
Only the selected value to be selected.

**Screenshots**

**UI5 Web Components for React Information**
Operating System:
`@ui5/webcomponents-react` version: `"0.9.0-rc.14"`
Do you have a dependency to`@ui5/webcomponents` in your package.json? `"0.0.0-185851a98"`

*If you are not sure, you can find out by running `npm ls @ui5/webcomponents-react` or `yarn why @ui5/webcomponents-react`*

**Additional context**
https://ui5-webcomponents-react.netlify.app/?path=/docs/ui5-web-components-multicombobox--generated-default-story

**Comment by MarcusNotheis** [comment]
Hi @LuisValgoi,
thanks for submitting this issue. I think this issue might be related to https://github.com/SAP/ui5-webcomponents/issues/1487.

**Comment by LuisValgoi** [comment]
Hi @MarcusNotheis, yes, it is!

**Comment by MarcusNotheis** [comment]
Hey @LuisValgoi, does this issue still occur with `@ui5/webcomponents-react@0.9.4` in combination with `@ui5/webcomponents@1.0.0-rc.7`?

**Comment by LuisValgoi** [comment]
Hey @MarcusNotheis, no, it is not.
Its working perfectly.
Thanks for that!
