### ISSUE TITLE
[VariantManagement]: Incorrect error message while saving a variant which already exists

### ISSUE THREAD

**Issue by I506645** [SAP/ui5-webcomponents-react#4496]
### Describe the bug

While saving the variant using 'Save As' button and user types a variant name suffixing a text for an existing variant and then hits the backspace button until the name is same as the existing variant, then an incorrect message is displayed saying "A file with this name already exists".

The message stating 'file' is incorrect. It should be 'view' instead of 'file'.

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-variantmanagement--docs

### Reproduction steps

Steps provided in the description. Please reach out to me if you need further details on reproducing the issue.

### Expected Behaviour

The expected behavior is that the message should read same as it's in UI5 components. "The view name already exists. Please enter a different name".

You could verify the message here from the UI5 component https://sapui5.hana.ondemand.com/#/entity/sap.ui.comp.smartfilterbar.SmartFilterBar/sample/sap.ui.comp.sample.smartfilterbar.Basic

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/121158363/232435959-b6b400b5-8f9e-47d2-b0aa-c57935fd6eeb.png)

### UI5 Web Components for React Version

1.12.0

### UI5 Web Components Version

1.11.0

### Browser

Chrome, Edge

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by I506645** [comment]
Hi @MarcusNotheis 
Thanks for the quick fix. Just wanted to know from which version of react-webcomponents, this fix will be available?

Best Regards,
Raghav

**Comment by MarcusNotheis** [comment]
Hi @I506645,

you're welcome 🙂 
The fix is not released yet as we're currently waiting for the translation service to provide a translation for all our supported language which will take a couple of days most probably.
As soon as we have the translation we'll create a new release (most probably `1.13.2`) - our release bot will add comment to this issue once it's released.

Best regards,
Marcus

**Comment by I506645** [comment]
Hi @MarcusNotheis 

Thanks for the update. We'll update our version once its released.

Best Regards,
Raghav
