### ISSUE TITLE
Form: Layout calculation failed if wrapping FormItem or FormGroup in other components - used in your template

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents-react#4497]
### Describe the bug

The Form calculates the Form based on the children FormItem or FormGroup but if you have wrapped them in other components, then the Form does calculate the layout false.

Everywhere in my applications I use my own simplyfied components which use FormItem as parent if necessary.
This approch is also used in your templates which also have the same problem.

But its very important that this works because you should able to simlyfiy your componnts.

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

The "displayName" property should searched recursive to calculate the layout correctly and enable wrapped elements.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/44802503/232480299-cee202c6-dcd8-4452-b415-905d9fc39d1a.png)

![image](https://user-images.githubusercontent.com/44802503/232481254-24979ac0-1495-4076-b7e9-e1d36e93431d.png)

### UI5 Web Components for React Version

1.13.0

### UI5 Web Components Version

Supplied UI5 Web Components for React

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by C3ntraX** [comment]
This may be the problem for other components as well if you search for "displayname". Pls consider to refactor them as well

**Comment by C3ntraX** [comment]
Hi @MarcusNotheis,

When will this issue be resolved? Are you waiting for someone to discuss?
I look forward to any news.

BR C3ntraX

**Comment by MarcusNotheis** [comment]
Hey @C3ntraX,

unfortunately this issue is very complex, and I don't think that there is a quick win available.

The main issue is that the `Form` is basically our only component with abstract children (`FormGroup` and `FormItem` and we are using these components internally for calculating the final layout.

The only solution I can think of right now is searching for our `FormGroup` and `FormItem` components recursively in all `children` of the `Form`, but I'm not sure how this will impact performance and how it can be implemented in the Form itself. I'll also double check with @Lukas742 whether we can come up with a feasible solution.
Do you have any proposal how we could implement this in our Form?

Thanks for the hint with the `displayName`, we'll take that into consideration as well.

**Comment by C3ntraX** [comment]
Hello @MarcusNotheis,

thanks for the info.

Yeah I know, its not easy to solve this problem but I think it will provide a good user-experience to use your form. Especially many people are using react and creating simplier or customized wrapper for many of your components.

One solution could be to search searching for `FormGroup` and `FormItem` components recursively in all children of the `Form`

Another solution I could think of is the `useContext` in `FormItem` and `FormGrouo` and  `Form` is the `Provider `. All children would be in the correct context and you could count calculate them in `Form`: 


```
const context = createContext()

const Form = () => {
 
const [formItemIds, setFormItemIds] = useState([])
const registerFormItem = useCallback((id) => {
  setFormItemIds(state => [...state, id])
}, [setFormItemIds])

const value useMemo(() => ({
  registerFormItem // This function will be called in FormItem with useContext(context)
  formItemInfo: [{ id: "xxx", layoutInfo }] // TODO: Calculate with the info from formItemIds
}),[formItemIds])

  return (
    <Context.Provider value={addFormItem}>
      <h1>{`Hello ${user}!`}</h1>
      <Component2 />
    </UserContext.Provider>
  );
}

const FormItem = () => {
 const id = "xxx" // TODO: Calculate

 const context = useContext(context)

 const layout = useMemo(() => {
  return context.find(x => x.id === id)
},[context])

// TODO: Rerender FormItem
}
```

This solution is a much cleaner "React" way and does not have any conflict with collidations menas the `displayName` etc.

**Comment by MarcusNotheis** [comment]
I really like the proposal of using React Context over cloning elements around depending on their display name, thanks for the codesandbox @C3ntraX!

We'll take a closer look on how we can leverage this proposal in our form next week.

**Comment by C3ntraX** [comment]
I futher reworked my sandbox. Had several problems but I think its a good solution now. 
I also learned a lot about context 👍

**Comment by C3ntraX** [comment]
Hi @Lukas742,

can I get some updates? Because the `Form` component is currently a bit broken and for newer projects I would downgrade your ui-library because the Form component is really important for many of my projects.
