### ISSUE TITLE
Self style for component 'Dialog'

### ISSUE THREAD

**Issue by rkl1994** [SAP/ui5-webcomponents-react#453]
**Describe the documentation issue**

- [ ] Documentation is unclear
- [ ] Documentation is incorrect
- [ ] Documentation is missing
- [x] Other

**Description of the issue**
For component 'Dialog', is there any way to style 'Dialog' by myself, such as I want to create a dialog which means 'Error', and the border-bottom-line should be red like the snapshot2. Thank you.
<img width="444" alt="Screen Shot 2020-04-23 at 5 17 11 PM" src="https://user-images.githubusercontent.com/5527455/80082272-b2cb4800-8586-11ea-922f-38672e9eba89.png">
<img width="368" alt="Screen Shot 2020-04-23 at 5 21 24 PM" src="https://user-images.githubusercontent.com/5527455/80082454-ff168800-8586-11ea-9ee7-a554065ba341.png">

**Comment by MarcusNotheis** [comment]
Hi @rkl1994 
you can use the `--sapPageFooter_BorderColor` CSS Variable to modify the color of the separator if you pass it as custom header content.
You can compare our [MessageBox](https://github.com/SAP/ui5-webcomponents-react/blob/master/packages/main/src/components/MessageBox/MessageBox.jss.ts#L24) implementation for this behaviour.
BTW: Your screenshot looks like you could use the message box for that
