### ISSUE TITLE
Dialog: ResizeObserver loop limit exceeded

### ISSUE THREAD

**Issue by maitefdupont** [SAP/ui5-webcomponents-react#4536]
### Describe the bug

After upgrading to the latest version from an older version we are getting ResizeObserver loop limit exceeded when opening a dialog.

### Reproduction steps

1. Upgraded to 1.13.0
2. Click card which triggers the Dialog
3. Dialog appears but an overlay with the error comes up

### Expected Behaviour

I saw no documentation of breaking changes in regards to the Dialog component, so I did not expect anything to break when I upgraded, even if it was a major upgrade.

### Screenshots or Videos

The error we get now when the dialog opens:
![image](https://user-images.githubusercontent.com/1753795/234411545-b75acbe4-b9c7-4ed5-a3a0-dd6e8e644b0d.png)

### UI5 Web Components for React Version

1.13.0

### UI5 Web Components Version

1.12.0

### Browser

Chrome

### Operating System

Windows

### Relevant log output

```shell
There is no log output. The error is thrown by listenToRuntimeError.
```

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @maitefdupont 

I will close this issue as there is already [another one](https://github.com/SAP/ui5-webcomponents/issues/6924) covering this topic. If you have any questions or more information, please address them in the original issue. Than you!

Duplicate https://github.com/SAP/ui5-webcomponents/issues/6924
