### ISSUE TITLE
Is there a dateRangePicker for component DatePicker

### ISSUE THREAD

**Issue by rkl1994** [SAP/ui5-webcomponents-react#455]
**Is your feature request related to a problem? Please describe.**
I‘m now doing a search function with the date value, and the value will be 'period', so it will be better if there is a date range picker. Thank you.

**Describe the solution you'd like**
I‘d like to have a date range picker like https://sapui5.hana.ondemand.com/#/entity/sap.m.DateRangeSelection

**Comment by MarcusNotheis** [comment]
Hi @rkl1994 
as far as I know there is no such component. I'll forward this to our UI5 Web Components Colleagues.

**Comment by MarcusNotheis** [comment]
Closing this issue as https://github.com/SAP/ui5-webcomponents/issues/1558 will track the progess.
