### ISSUE TITLE
[Popover]: Popover is invisible while its propoerty 'open' is true

### ISSUE THREAD

**Issue by SunnyWind** [SAP/ui5-webcomponents-react#457]
Hi there,

My page has multiple popover components whose visibility is controlled by the `open` property.

![image](https://user-images.githubusercontent.com/4338219/80300292-e9df6a80-87cd-11ea-8c24-f8b179c24ab9.png)

Occasionally, something weird happens:
There are two visible popovers. when I change the `open` property of one popover from true to false, both two popovers will disappear. Even though the `open` property of the other is true.

![image](https://user-images.githubusercontent.com/4338219/80300239-848b7980-87cd-11ea-8512-7e9e498ec208.png)

Do you have any suggestions about how to figure out this problem?

Thanks

**Comment by MarcusNotheis** [comment]
Hi @SunnyWind,
which version of web-components-react are you using? Maybe you can try to give unique IDs to the popovers?

**Comment by SunnyWind** [comment]
I'm using 
```
    "@ui5/webcomponents-react": "0.6.1",
    "@webcomponents/custom-elements": "1.4.0",
    "@webcomponents/webcomponentsjs": "2.4.0",
```
I've tried giving popovers unique keys, but that didn't solve my problem.

**Comment by MarcusNotheis** [comment]
Hi @SunnyWind 
`0.6.1` is a pretty old version to be honest - is there any chance for you upgrading to our latest `0.9.0` release?

**Comment by SunnyWind** [comment]
Hi @MarcusNotheis,

I've upgraded the version to 0.9.6, and the issue still exists.
Since there is no property `open` in the new version of Popover component, the exact behavior becomes that:
There are two popovers which are opened one by one. When the `close` method of the second popover is triggered, only the second one will disappear. It's expected. However, when the `close` method of the first popover is triggered, the two popovers both will disappear. It's NOT expected.

**Comment by MarcusNotheis** [comment]
Hey @SunnyWind, based on your description I was able to reproduce this issue in a sandbox. Could you check whether this fits your issue description? https://codesandbox.io/s/cool-gould-gqeqp?file=/src/index.js

**Comment by MarcusNotheis** [comment]
I also forwarded this issue to our UI5 Web Components colleagues: https://github.com/SAP/ui5-webcomponents/issues/1628

**Comment by SunnyWind** [comment]
That's exactly what I meant. Thank you!

**Comment by MarcusNotheis** [comment]
Closing this issue as it is followed up in the UI5 Web Components repo.
