### ISSUE TITLE
Form: Wrong column calculation

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents-react#4597]
### Describe the bug

Between the version ~1.8.0 and ~1.15.1 the `Form` changed the `grid-template-columns` this broke several apps in my environment. And there are other bugs as well.

Please see the screenshots

Please consider this in #4497 

### Isolated Example

https://codesandbox.io/p/sandbox/mystifying-snow-s4m0nw?file=%2Fsrc%2FApp.tsx%3A35%2C20

### Reproduction steps

1.
2.
3.
...

### Screenshots or Videos

![image](https://github.com/SAP/ui5-webcomponents-react/assets/44802503/20da2975-86fa-48ca-bece-00a860497562)

![image](https://github.com/SAP/ui5-webcomponents-react/assets/44802503/c1bcd6d8-299e-4cfa-b33d-73d67fd9682a)

![image](https://github.com/SAP/ui5-webcomponents-react/assets/44802503/b44b4ef8-878d-4705-bbae-2c42ea7d1e06)

And additional: The label text does not wrap if you set `labelSpanM={2}` previous in ~1.8.0 this was also the case, this is why I choosed a  `labelSpanM={6}` and 3 columns. I dont know if this is preventable with text wrapping:

![image](https://github.com/SAP/ui5-webcomponents-react/assets/44802503/84a6756d-5e17-48a5-9f9f-f983261734b2)

![image](https://github.com/SAP/ui5-webcomponents-react/assets/44802503/1a613aeb-190e-4b66-83d1-9bbe738242f1)

And previous:

![image](https://github.com/SAP/ui5-webcomponents-react/assets/44802503/e0390fb0-8332-424e-aace-5495d889b854)

![image](https://github.com/SAP/ui5-webcomponents-react/assets/44802503/e7e3a8a7-a50a-4480-a27a-6f307e190493)

### UI5 Web Components for React Version

~1.15.1

### UI5 Web Components Version

~1.13.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by C3ntraX** [comment]
Hi @Lukas742,

Even more errors :-( :

![image](https://github.com/SAP/ui5-webcomponents-react/assets/44802503/f20ec4a1-8907-49b3-b47d-a41d4faa7def)

With inpus: style={{ width: "100%", maxWidth: "30rem" }}

![image](https://github.com/SAP/ui5-webcomponents-react/assets/44802503/99152031-e55b-4af1-bcb7-cf25e7a216ea)

![image](https://github.com/SAP/ui5-webcomponents-react/assets/44802503/837dd624-2c47-454d-a16f-de5f5f566721)

**Comment by Lukas742** [comment]
Hi @C3ntraX 

The PR mentioned above my comment should fix the layout problem. The wrapping issue and the input field issue will take more time to investigate.
