### ISSUE TITLE
[DatePicker]: Datepicker will get null jsDate value in react 18

### ISSUE THREAD

**Issue by JackieWei** [SAP/ui5-webcomponents-react#4600]
### Describe the bug

In react 18.x(react dom too), when we try to update datepicker value, it will render twice, first time it will convert normal string like '01/01/2017', and success, but in second time, it will failed because the parameters will become a normal date string like "Fri May 12 2023 00:00:00 GMT+0800 (China Standard Time)"

this this.getFormat().parse(value, true) will return null when the parameter be Fri May 12 2023 00:00:00 GMT+0800 (China Standard Time)
And this error only happens in react 18, switch back to react 17.x it will works.

Code here
`	
/**
	 * The parser understands many formats, but we need one format
	 * @protected
	 */
	normalizeValue(value) {
		if (value === "") {
			return value;
		}

		return this.getFormat().format(this.getFormat().parse(value, true), true); // it is important to both parse and format the date as UTC
	}
`

### Isolated Example

https://codesandbox.io/p/sandbox/ui5-webcomponents-react-vite-j65vvg?file=%2Fsrc%2FApp.tsx%3A1%2C1-40%2C1

### Reproduction steps

1. In react 18.x, render datepicker
2. In onchange handler, set state and set value
3. It will throw error "preview-protocol.js:13 2023-05-12 12:12:10.385899 The given date instance isn't valid. -  "
4. Here is the error screenshot
![image](https://github.com/SAP/ui5-webcomponents-react/assets/437693/6d348f2b-79e4-4a50-b8b8-07b5a1669582)

### Expected Behaviour

No error and the value display in input of datepicker has correct format.

### UI5 Web Components for React Version

~1.15.1

### UI5 Web Components Version

~1.13.0

### Browser

Chrome

### Operating System

Mac

### Additional Context

This is a general issue, while in 1.7.2 also happen

"@ui5/webcomponents": "1.9.3",
    "@ui5/webcomponents-base": "1.9.3",
    "@ui5/webcomponents-fiori": "1.9.3",
    "@ui5/webcomponents-icons": "1.9.3",
    "@ui5/webcomponents-react": "1.7.2",

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @JackieWei 

the isolated example you provided is just our default template. Did you perhaps forget to save/fork the codeSandbox? Please update it so we can take a look.

**Comment by JackieWei** [comment]
![image](https://github.com/SAP/ui5-webcomponents-react/assets/437693/102a8ff0-06a5-4438-988e-7e9930757aa9)

**Comment by JackieWei** [comment]
@Lukas742  Cool, that works for me
