### ISSUE TITLE
DateTimePicker: Setting value to undefined writes value "undefined" in input

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents-react#4605]
### Describe the bug

If you set the value undefined as value in DateTimePicker (other maybe too) after you manually cleared the input then the value undefined is interpolated as string "undefined". But undefined is a valid value for an empty string datetime value.

### Isolated Example

https://codesandbox.io/p/sandbox/sparkling-microservice-9geblb?selection=%5B%7B%22endColumn%22%3A24%2C%22endLineNumber%22%3A43%2C%22startColumn%22%3A7%2C%22startLineNumber%22%3A43%7D%5D&file=%2Fsrc%2FApp.tsx%3A15%2C29

### Reproduction steps

1.
2.
3.
...

### Screenshots or Videos

![GIF 15 05 2023 11-57-04](https://github.com/SAP/ui5-webcomponents-react/assets/44802503/bc3fb238-6066-45c9-9841-fefc3e02e820)

### UI5 Web Components for React Version

~1.14.0

### UI5 Web Components Version

~1.12.2

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by C3ntraX** [comment]
Hello @Lukas742,

thanks for the information.

Yes thats true and I didn't thought about the interaction with controlled state and the uncontrolled state.

I think that It would make sense to simulate the same behaviour as react is using. That setting `undefined` sets the controlled state to `undefined`. 
For the `DateTimePicker` its currently not the case. If you had a controlled state and changed the state to `undefined`, then the `DateTimePickers` sets the value undefined as string value in the input instead of ignoring the undefined value that only the state changed to uncontrolled.

I think it would make sense, that your ui-library would make some adjustments to behave like normal react and does not write `undefined` in the input field.

BR C3ntraX

**Comment by Lukas742** [comment]
Hi @C3ntraX 

sorry, but we already decided against implementing something to mimic the React behavior of native inputs, as it would create an overhead (similar to the `onChange` - `onInput` behavior) which could affect maintainability and maybe even performance. Also the input components of ui5-webcomponents (e.g. `DatePicker`, `Input`, `MultiComboBox`, etc.) are not offering the same API as native inputs, there is, for example, no `defaultValue`, so we can never achieve identical behavior.
