### ISSUE TITLE
[Analytical Table]: Rows coming distorted in table

### ISSUE THREAD

**Issue by dhruvojha** [SAP/ui5-webcomponents-react#4615]
### Describe the bug

When we navigate to a particular tab, it has rows distorted (All superimposed on each other). Other tabs in the app also use the same component, but do not face this issue. Moreover, zooming in and out of the tab apparently seems to resolve this issue, but when we navigate back to the app, the issue resurfaces.

PS: This issue also may not arise when viewing on an external display such as a monitor.

### Reproduction steps

1. Navigate to the concerned app which has the tab with the issue go to the tab, one can see distorted rows.
2. Navigate to other tabs, one can see the table there is fine.
3. Go back to the tab, and zoom in and out, the issue seems to resolve itself.
4. Navigate to any other app and come back to the concerned app and tab, you can see the issue resufaces.
...

### Expected Behaviour

As the component is being used by multiple tabs and this is an isolated issue, the rows must load properly, as they do in other apps.

### Screenshots or Videos

https://sap-my.sharepoint.com/:v:/p/dhruv_ojha/EZcHU9tb_ZZAmhRMTgzqyMIB8BLUcFR0VryyJ6vpscwefA?e=SfCMsC

### UI5 Web Components for React Version

1.14

### UI5 Web Components Version

1.12

### Browser

Edge

### Operating System

Windows

### Additional Context

Link to tenant: https://app.stage.prp-stage-eu.eurekacloud.io/

Link to Passvault: https://password.wdf.sap.corp/passvault/#/pw/0000299094

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @dhruvojha 

I neither have access to the passvault, nor to the tenant. Also, we prefer an isolated example to be able to reproduce issues more easily, and it also has the advantage that all users can take a look at it, not just SAP employees.
You can leverage this [codeSandbox template](https://codesandbox.io/p/sandbox/ui5-webcomponents-react-vite-j65vvg?file=%2Fsrc%2FApp.tsx) for creating the example.
