### ISSUE TITLE
Adding Title/Tolltip into MultiComboBoxITem

### ISSUE THREAD

**Issue by tunahan** [SAP/ui5-webcomponents-react#4622]
### Is your feature request related to a problem?

As a response to some UI requirements, I sometimes need to add some small notes to items in MultiComboBox component. Yes, I now there is "additionalText" field in it but it does not answer to my need. When I want to add trivial information into UI, I would not want to use "additionalText" because every time combobox gets opened, trivial information gets displayed all the time. I want that information to be shown less.

### Describe the solution you'd like

So, adding regular title (or tooltip) feature can be added to MultiComboboxItem  and when I hover on the items inside MultiCombobox, additional information can be displayed in standard title box.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @tunahan 

I will close this issue as there is already [another one](https://github.com/SAP/ui5-webcomponents/issues/5683) covering this topic. If you have any questions or more information, please address them in the original issue.

Duplicate https://github.com/SAP/ui5-webcomponents/issues/5683
