### ISSUE TITLE
SideNavigationItem: Fires onClick Event also when clicking SideNavigationSubItems

### ISSUE THREAD

**Issue by MetalCar** [SAP/ui5-webcomponents-react#4634]
### Describe the bug

When a `SideNavigationItem` has prop `children` filled with one or more `SideNavigationSubItems` the parent `onClick` event, that is attached to the `SideNavigationItem` is also fired when clicking `SideNavigationSubItems`.

### Isolated Example

https://codesandbox.io/p/sandbox/optimistic-morning-ui3pl9?file=%2Fsrc%2FApp.tsx%3A35%2C9

### Reproduction steps

1. Build a `SideNavigation` structure with a `SideNavigationItem` and one or more `SideNavigationSubItem` as children of that `SideNavigationItem`
2. Set the `onClick` event that should trigger a `console.log()` when fired
3. Click on the `SideNavigationSubItem` 
4. You can see in your developer-console, that the `console.log()` was fired.

### Expected Behaviour

I expected that the event is fired, when i clicked only on the `SideNavigationItem`.

### UI5 Web Components for React Version

1.15.1

### UI5 Web Components Version

1.13.3

### Browser

Firefox

### Operating System

Windows 11

### Additional Context

Maybe it's working as intended and I use that component in a wrong way?

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @MetalCar 

This is the default behavior of how event propagation works. Almost all events (if not internally, or nativeley prevented) are bubbling up to its parent. To prevent this you can call `event.stopPropagation()` in the respective handler.

See [codeSandbox](https://codesandbox.io/p/sandbox/sidenavigationitem-with-children-and-onclick-forked-tpgqfd)

**Comment by MetalCar** [comment]
You are right. I was confused since I thought the onClick is an event specific for clicking this one item.
