### ISSUE TITLE
Prevent "escape" to close Dialog

### ISSUE THREAD

**Issue by vital487** [SAP/ui5-webcomponents-react#4635]
### Is your feature request related to a problem?

I don't want the user to be able to close the Dialog. He can do that using the "Escape" key.

### Describe the solution you'd like

Provide a property in the Dialog component that allows us to send a handler when the user uses the "Escape" key.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @vital487 

this is already possible by leveraging `onBeforeClose`:

>Fired before the component is closed. This event can be cancelled, which will prevent the popup from closing. This event does not bubble.
