### ISSUE TITLE
[Form]: labelSpan values overridden at medium/small screen sizes

### ISSUE THREAD

**Issue by rchrdchn** [SAP/ui5-webcomponents-react#4638]
### Describe the bug

labelSpan is overridden at medium/small screen sizes.

When I try using `labelSpanM={5}` `labelSpanS={5}` and resize or set the width of a parent component to medium or smaller screen size, i.e. `width: 30rem`, then `FormItem` is to the right/end while `Text` is to the left/beginning of the component.

See screenshots. 

### Isolated Example

https://codesandbox.io/s/spring-microservice-3jij7b?file=/src/App.js:467-468

### Reproduction steps

1. go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-form--docs
2. set `labelSpanS` and `labelSpanM` to `5`
3. resize screen slowly until it's of `width` = `878px`

### Expected Behaviour

<img width="638" alt="SCR-20230525-ohky" src="https://github.com/SAP/ui5-webcomponents-react/assets/11576789/f66fd811-ebe3-44bc-828d-4c0f15bb61de">

### Screenshots or Videos

![SCR-20230525-oako](https://github.com/SAP/ui5-webcomponents-react/assets/11576789/3e1a07bf-17a7-4828-a6eb-d48a1b74a061)
![SCR-20230525-oavg](https://github.com/SAP/ui5-webcomponents-react/assets/11576789/7df94049-61f8-4a63-91a3-f36f9f23489e)
![SCR-20230525-obpz](https://github.com/SAP/ui5-webcomponents-react/assets/11576789/ca064ec7-7c46-469f-8058-c843cceff1ca)
![SCR-20230525-ofkb](https://github.com/SAP/ui5-webcomponents-react/assets/11576789/220b8a35-126d-4024-8b01-a650cc1cbb96)
![SCR-20230525-ofox](https://github.com/SAP/ui5-webcomponents-react/assets/11576789/455278c9-75a3-4326-be5d-1149dba82fec)

### UI5 Web Components for React Version

1.15.1

### UI5 Web Components Version

1.13.2

### Browser

Chrome

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by C3ntraX** [comment]
I have the same issues. See #4597

**Comment by Neeeko** [comment]
@Lukas742 and @MarcusNotheis any updates?
