### ISSUE TITLE
Loading data in subRows asynchronously in AnalyticalTable

### ISSUE THREAD

**Issue by pakcheong** [SAP/ui5-webcomponents-react#4650]
### **Issue Description**
I am having an issue finding the relevant documentation for loading data in `subRows` asynchronously in AnalyticalTable.

How do I configure `AnalyticalTable` to load data in `subRows` asynchronously upon expanding its parent row? Does the component even support this feature?

I wanted to achieve this:
- Parent row always has a collapse and expand icon on the left.
- When it is expanded, it creates an ajax call to backend to get data.
- If there is data returned, append it to `subRows` and show accordingly. Otherwise nothing is shown and then hide the collapse button.
- Applies the same recursively for all subRows.

### **Issue Type**

- [x] Documentation is unclear
- [x] Other

**Comment by MarcusNotheis** [comment]
Thanks for reporting! I’ll forward this issue to the UI5 Web Components for React repo as the affected component is developed there.

**Comment by pakcheong** [comment]
Thanks @Lukas742 , that helps a lot!
