### ISSUE TITLE
[DynamicPageTitle]: Tooltip not present for the truncated header of DynamicPageTitle when viewed in 320px viewport

### ISSUE THREAD

**Issue by rama1990br** [SAP/ui5-webcomponents-react#4658]
### Describe the bug

When viewed in 320px viewport, `header` of `DynamicPageTitle` might be truncated with an ellipsis based on the length of the text. When this happens, there is no tooltip displayed on hover of the title and so there is no way to read the full header text.

<img width="327" alt="Screenshot 2023-05-30 at 9 22 46 AM" src="https://github.com/SAP/ui5-webcomponents-react/assets/32254036/39ec3128-19c9-40e8-9346-0801e59af688">

### Reproduction steps

1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/story/layouts-floorplans-dynamicpage--default. Change the page viewport to responsive width 320 x 700 height by following the steps in https://wiki.wdf.sap.corp/wiki/display/Acc/ACC-282+Details#ACC282Details-TestPreparationMethods.
2. Notice that "Header Title" heading shows up truncated with an ellipsis (as shown in the screenshot attached in "Describe the bug") within the 320px viewport and that there is no way to actually read the full text.

### Expected Behaviour

There should be a tooltip whenever the header is truncated so that there is a way to read the full text.

### Screenshots or Videos

<img width="327" alt="Screenshot 2023-05-30 at 9 22 46 AM" src="https://github.com/SAP/ui5-webcomponents-react/assets/32254036/d08fea52-fc42-4376-b277-62160fa497b5">

### UI5 Web Components for React Version

1.14.0

### UI5 Web Components Version

1.13.3

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @rama1990br 

since the `header` prop accepts `ReactNode` as value, it's up to developers to display the `title` of the component passed to the prop.

**Comment by rama1990br** [comment]
Hi @Lukas742,
I am trying to display the title in `header` of `DynamicPageTitle` like given below. However, the heading which is "Script-Based Integration Settings" gets cut-off in the 320px viewport and there is no tooltip displayed as well as shown highlighted in the screenshot below. Is there any way to add the tooltip in this case?
```
header={
        <div role="heading" aria-level={DEFAULT_HEADING_LEVEL}>
          <Title>{i18n.getText("ADMINV3_SCRIPT_INTEGRATION_SETTINGS")}</Title>
        </div>
      }
```

<img width="1680" alt="Screenshot 2023-06-08 at 3 06 57 PM" src="https://github.com/SAP/ui5-webcomponents-react/assets/32254036/bc338b70-6325-422f-af8d-e1a4ed09e17e">

**Comment by Lukas742** [comment]
Sure, you can just add the attribute `title` either on the div or the Title component.
