### ISSUE TITLE
Analytical Table not rendering properly

### ISSUE THREAD

**Issue by srinivasManduva** [SAP/ui5-webcomponents-react#4665]
Hi team,

An Analytical Table is being used as an tree table in a dialog from orca-react-ui 

the Table doesn't render correctly it has an extra empty space at the end any user input onto the table resets itself into the correct format as i have shown in the linked video below 

the column separators when hovered seem to be in the correct position but the actual tiles are not over lapping with then i.e. on the ui the column size are small than what is needed

link to the issue : https://sap-my.sharepoint.com/:v:/p/srinivas_manduva/ER-0khyFwcxEi-7huwKxJh8BZGcczWayJ8FCDvj-i3j62g?e=6m4mN6

im contacting from SAC ACN team, please provide a fix or workaround for this as this is needed for our user story

Thanks,
Srinivas
 

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

table to rendered without any extra space at the end

### Screenshots or Videos
![image](https://github.com/SAP/ui5-webcomponents-react/assets/135114737/69c29a10-5591-4c51-90c3-b947f8dc4815)
![image](https://github.com/SAP/ui5-webcomponents-react/assets/135114737/0caeeb62-619f-402f-993f-bc05a1016809)

### UI5 Web Components for React Version

1.81

### UI5 Web Components Version

1.10.3

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @srinivasManduva 

I could not reproduce this issue with our latest release. Please update your dependencies and check if the bug still occurs. If so, please create a reproducible example using this [codeSandbox template](https://codesandbox.io/p/sandbox/ui5-webcomponents-react-vite-j65vvg?file=%2Fsrc%2FApp.tsx).
