### ISSUE TITLE
Analytical Table: The width for scrollbar still remains in analytical table

### ISSUE THREAD

**Issue by rkl1994** [SAP/ui5-webcomponents-react#467]
**Describe the bug**
While using an analytical table, if data is enough to show the scrollbar, everything goes well, however, while there are only a few data and scrollbar doesn't appear, the width still remains.

**To Reproduce**
1. Create a component with analytical table with only a few data.

**Expected behavior**
The width for scrollbar should disappear while there is no scrollbar

**Screenshots**
This image shows the bug.
<img width="1021" alt="Screen Shot 2020-04-30 at 11 08 34 AM" src="https://user-images.githubusercontent.com/5527455/80668105-8d34c600-8ad3-11ea-876b-943cffd2bb54.png">

This image works good.
<img width="1032" alt="Screen Shot 2020-04-30 at 11 08 12 AM" src="https://user-images.githubusercontent.com/5527455/80668132-9f166900-8ad3-11ea-9721-360e8fbbd4a0.png">

**UI5 Web Components for React Information**
Operating System:
"@ui5/webcomponents": "1.0.0-rc.6",
"@ui5/webcomponents-fiori": "1.0.0-rc.6",
"@ui5/webcomponents-icons": "1.0.0-rc.6",
"@ui5/webcomponents-react": "^0.9.0-rc.14",

*If you are not sure, you can find out by running `npm ls @ui5/webcomponents-react` or `yarn why @ui5/webcomponents-react`*

**Additional context**

**Comment by MarcusNotheis** [comment]
Released in `@ui5/webcomponents-react@0.9.1`
