### ISSUE TITLE
Input: Auto complete does not work

### ISSUE THREAD

**Issue by vital487** [SAP/ui5-webcomponents-react#4671]
### Describe the bug

Hi,

The default HTML input allows the autoComplete attribute, which is then filled with the user email or password.

I cannot do the same with the ui5 react Input.

Do you know how I can achieve this?

### UI5 Web Components for React Version

^0.25.4

### UI5 Web Components Version

^1.4.0

### Browser

Chrome

### Operating System

Windows 10

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @vital487 

the `autoComplete` attribute is not supported by ui5-webcomponents. For more information please take a look at this [issue](https://github.com/SAP/ui5-webcomponents/issues/6995), where it’s explained why. If you have additional questions or input please also post them there, so we can keep all information in one place. Thank you :)

Duplicate https://github.com/SAP/ui5-webcomponents/issues/6995
