### ISSUE TITLE
Export conditions breaks node based test-environments

### ISSUE THREAD

**Issue by marpme** [SAP/ui5-webcomponents-react#4676]
### Describe the bug

When executing tests with `@ui5/webcomponents-react` in environments based on either `jest` or `vitest`, it will confuse imports and automatically import SSR components instead of the original browser-based components as it is being detected as a "node" environment. 

This behaviour was originally introduced in 81ab71960764ad66dc4949c20bed965753510c04 or alternatively in this PR #4640 (thank you @Matwog for researching this!).

### Reproduction steps

1. Upgrade to version `@ui5/webcomponents-react` to `1.15.3`
2. Create a test in either Jest or Vitest (or any other node-based test environment)
3. Test runners will import `@ui5/webcomponents-react` from the SSR distro

### Expected Behaviour

I would expect that test-environments would still import the components from `/dist/*` instead of `/ssr/*`

### UI5 Web Components for React Version

1.15.3

### UI5 Web Components Version

1.13.3

### Browser

Chrome

### Operating System

MacOS Ventura 13.4

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MarcusNotheis** [comment]
Hi @marpme,

thanks for reporting! Could you please elaborate a bit further was exactly breaks the Jest / Vitest environment?
I've tried to create a very very basic test using `vitest` in this [sandbox](https://codesandbox.io/p/github/MarcusNotheis/ui5-wcr-testing-node/main?workspaceId=690d6c07-42fe-4ff6-a0ae-d9d147ec68d3) and from a first look it looks fine.

The only difference between the `ssr` and the regular `dist` build is the moment where the web components are loaded.
In the `dist` folder there are loaded synchronously together with the React component, in the `ssr` build they are fetched while after the initial render in an effect.

**Comment by marpme** [comment]
Hi @MarcusNotheis,

I've looked into your code-sandbox and excuse myself for not providing one already with the issue. I created one sandbox over [here](https://codesandbox.io/p/sandbox/admiring-leftpad-c4qdii?file=%2Fsrc%2FApp.spec.tsx) that produces one of our many errors. 

This sandbox test now started failing due to the fact, that we are importing SSR components, which have different internal states. 

Therefore, we are not able to test input values and other tests may also fail due to this. Nevertheless, the DOM correctly renders the web-component values, but accessing those values via JS API is not feasible anymore.

Let me know if you need any further insights 👍

**Comment by marpme** [comment]
@MarcusNotheis Sadly the error persists with `vitest` in the [codesandbox](https://codesandbox.io/p/sandbox/admiring-leftpad-c4qdii?file=%2Fsrc%2FApp.spec.tsx) even after upgrading to the latest package.

**Comment by marpme** [comment]
Thanks for re-opening and adding the browser export condition. 

I deeper investigated the resolving of files in vitest and with the following configuration  we were able to enforce browser like module resolving in `vitest`:

```ts
import { defineConfig } from 'vitest/config'

export default defineConfig({
    test: {
        // a lot of configuration ...
    },
    resolve: {
        conditions: ['browser'], // enforces browser conditions or default
    },
})
```

**Comment by MarcusNotheis** [comment]
Good to hear that you were able to solve this issue, @marpme!
You're totally right that we never officially support `vitest` and also don't recommend `jest` anymore, but I think it would still make sense to add it to our docs somewhere 🙂
