### ISSUE TITLE
[ObjectPage/ObjectPageSection] - onToggleHeaderContent in expanded State when scrolled down add a lot of blank space

### ISSUE THREAD

**Issue by Rahishsaifi** [SAP/ui5-webcomponents-react#4693]
### Describe the bug

Object Page w/ long Header Section: Toggled - Expanded State when scrolled down add a lot of blank space

### Reproduction steps

1.Toggle Object Page
2.Ensure Header Section is expanded
3.Scroll Down

### Expected Behaviour

Empty screen should not show

### Screenshots or Videos

![image](https://github.com/SAP/ui5-webcomponents-react/assets/16429797/97954e6c-725d-4847-922d-649439b96355)
![image](https://github.com/SAP/ui5-webcomponents-react/assets/16429797/51a33a5e-5b6e-4760-b26e-57722b65e718)

### UI5 Web Components for React Version

1.7.3

### UI5 Web Components Version

1.9.3

### Browser

Chrome, Edge, Firefox, Safari

### Operating System

Windows

### Additional Context

I have update the version 
     "@ui5/webcomponents": "1.13.0",
    "@ui5/webcomponents-base": "1.13.0",
    "@ui5/webcomponents-fiori": "1.13.0",
    "@ui5/webcomponents-icons": "1.13.0",
    "@ui5/webcomponents-react": "1.15.1",
    "@ui5/webcomponents-react-base": "^1.11.0",

now I am getting babel error, and i clear cache and build the project but still issue is persist
This was the previous ticket which is closed.
https://github.com/SAP/ui5-webcomponents-react/issues/4364

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @Rahishsaifi 

> now I am getting babel error, and i clear cache and build the project but still issue is persist
This was the previous ticket which is closed.

Please open another issue for this, preferably with a reproducible example leveraging this [codeSandbox](https://codesandbox.io/p/sandbox/ui5-webcomponents-react-vite-j65vvg?file=%2Fsrc%2FApp.tsx) as for me no error is thrown.

> 1.Toggle Object Page
> 2.Ensure Header Section is expanded
> 3.Scroll Down

I wasn't able to reproduce this behavior anymore (see [codeSandbox](https://codesandbox.io/p/sandbox/async-moon-6bomdp?file=%2Fsrc%2FApp.tsx%3A186%2C1)). Please again add a reproducible example and a video or detailed steps how to reproduce the issue.
