### ISSUE TITLE
[Toolbar][Buttons]: Rendering differences compared with UI5 (default button, transparent/light button)

### ISSUE THREAD

**Issue by mhchem** [SAP/ui5-webcomponents-react#4737]
### Describe the bug

Rendering of button inside a toolbar differs between (JavaScript) UI5 and UI5 web components for react.

### Reproduction steps

In (JavaScript) UI5, when I put a default button into a toolbar, it renders as a transparent/light button ("transparent button" = UI5 terminology, "light button" = design terminology).
See https://sapui5.hana.ondemand.com/#/entity/sap.m.Toolbar/sample/sap.m.sample.ToolbarResponsive

In UI5 web components for react, default buttons render with a gray background.
See https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-toolbar--docs

### Expected Behaviour

Both UI5 technologies should follow the same theme.

### Screenshots or Videos

https://sapui5.hana.ondemand.com/#/entity/sap.m.Toolbar/sample/sap.m.sample.ToolbarResponsive
<img width="465" alt="Screenshot 2023-06-13 at 17 00 17" src="https://github.com/SAP/ui5-webcomponents-react/assets/16336692/68585f77-028b-4f95-b686-eccba2a93bca">

https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-toolbar--docs
<img width="304" alt="Screenshot 2023-06-13 at 17 00 29" src="https://github.com/SAP/ui5-webcomponents-react/assets/16336692/1e2cecb9-e3fa-42ea-a3f9-46da1d879f74">

### UI5 Web Components for React Version

latest

### UI5 Web Components Version

latest

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @mhchem 

in React, unlike as it is with SAP or OpenUI5, the `Button` doesn't "know" that it is displayed inside a toolbar, nor does the toolbar "know" that it has `Buttons` as children. Implementing this behavior would lead to overhead and also to discrepancies in between other components like the `Bar` where the same behavior can also be observed in SAPUI5 but not with ui5-webcomponents. 
Please keep in mind that the `Toolbar` is a standalone React component, whereas the `Button` is a web component developed by the ui5-webcomponents team. If this behavior should be available, I think it should be implemented in the `Bar` (also a web-component) first and only then we would adjust our Toolbar to these specs. 

If you feel like this feature is something that developers could benefit from, please raise an issue about the `Bar` in the [ui5-webcomponents repo](https://github.com/SAP/ui5-webcomponents).  However, in my opinion, this would cause more confusion than it would help in React and standard JS web development as this is not the common behavior of components there.

The linked PR will replace all standard buttons, with transparent buttons so it's more clear to developers what button should be used.
