### ISSUE TITLE
Popover: Unable to disable popover header

### ISSUE THREAD

**Issue by petejohnson84** [SAP/ui5-webcomponents-react#474]
**Describe the bug**
In the latest version 0.9.0, the popover header always displays despite omitting header prop. In addition, tried to pass null and false (which actually causes an error). In the previous version 0.8.6, this behavior was not noticeable. 

**To Reproduce**
Create a Popover component and attempt to not display a header. It always shows despite the omission of the prop or passing falsy values.

**Expected behavior**
The header area should be optional as stated in the ui5-webcomponents documentation.

**UI5 Web Components for React Information**
Operating System: macOS Catalina 10.15.4
`@ui5/webcomponents-react` version: 0.9.0
Do you have a dependency to`@ui5/webcomponents` in your package.json? If yes, which version?: ^1.0.0-rc.7

**Comment by MarcusNotheis** [comment]
Hi @petejohnson84,
thanks for submitting the issue. Can you try upgrading to `0.9.1`? This should solve the issue.

Best regards,
Marcus

**Comment by petejohnson84** [comment]
After upgrading to 0.9.1 the issue is fixed.

Thanks.
