### ISSUE TITLE
[Component Name]: Sticky header of table will overlap with flooting foter

### ISSUE THREAD

**Issue by JackieWei** [SAP/ui5-webcomponents-react#4747]
### Describe the bug

https://codesandbox.io/p/sandbox/gifted-monad-f7vk3z?file=%2Fsrc%2FApp.tsx%3A175%2C16-389%2C11
The condition is: In a object page, we have a floating footer, and a table with sticky column header will overlap with footer when scrolling. The hack way to avoid it is to change the footer inside z-index to 100, but this is not a valid way to do, and also may cause other risk.

### Isolated Example

https://codesandbox.io/p/sandbox/gifted-monad-f7vk3z?file=%2Fsrc%2FApp.tsx%3A175%2C16-389%2C11

### Reproduction steps

1. Place a Table with sticky column header inside object page
2. Leave enough space before and after
3. Scroll and let footer overlap with table header, then you will see table header is over footer
...

### Expected Behaviour

All content inside object page should always below objectpage including table header

### Screenshots or Videos

![image](https://github.com/SAP/ui5-webcomponents-react/assets/437693/4f6fb7af-3e2e-4689-a8cf-3afd2946bc27)

### UI5 Web Components for React Version

1.16.0

### UI5 Web Components Version

1.14.0

### Browser

Chrome

### Operating System

Mac

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @JackieWei 

Please follow the guidelines for opening issues. "[Component Name]" doesn't give information of the affected component.

I will close this issue as there is already another one covering this topic. If you have any questions or more information, please address them in the [original issue](https://github.com/SAP/ui5-webcomponents-react/issues/4586).

Duplicate https://github.com/SAP/ui5-webcomponents-react/issues/4586
