### ISSUE TITLE
[Table]: cannot style component through className

### ISSUE THREAD

**Issue by MetalCar** [SAP/ui5-webcomponents-react#4767]
### Describe the bug

I want to hide the `columns`. So there's no property for that on `Table`, I tried to hide them through css.
But I figured out, that `className` is only appended to ui5-webcomponent-element, and not to the `<table>`.

### Isolated Example

https://codesandbox.io/p/sandbox/wonderful-robinson-m9r5p9?file=%2Fsrc%2FApp.tsx%3A19%2C5

### Reproduction steps

1. Build a table using `Table`-Component
2. Set a class through `className`
3. Check DOM
...

### Expected Behaviour

I expected that `className` will also be available at `<table>`-DOM-Node. Or am I wrong?

### UI5 Web Components for React Version

~1.16.0

### UI5 Web Components Version

~1.14.0

### Browser

Chrome, Edge, Firefox, Safari

### Operating System

Windows 11

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @MetalCar 

this is the default behavior for elements inside the shadow root. You can find out more about it [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/knowledge-base-styling--docs#css-shadow-parts).

If you feel like, that the `table` element inside the shadow root should be customizable via CSS, please create a feature request in the UI5 Web Components repo, asking to add a `part` attribute to the element and an explanation of why you need this feature.
