### ISSUE TITLE
[SF][RatingIndicator]: Updated title attribute on the ui5 component will not be reflected in the shadow dom

### ISSUE THREAD

**Issue by Jasonl157** [SAP/ui5-webcomponents-react#4785]
### Describe the bug

Updated title attribute on the ui5 component `<ui5-rating-indicator>` will not be reflected in the shadow dom `<div class="ui5-rating-indicator-root"...>`

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-ratingindicator--docs

### Reproduction steps

1. Open the codesandbox link or the [UI5 storybook](https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-ratingindicator--docs)
2. Open the chrome devtool and inspect the rating indicator component `<ui5-rating-indicator>` and its shadow root `<div class="ui5-rating-indicator-root"...>`
3. Add/Update the title attribute of the UI5 component `<ui5-rating-indicator>` and you will find the title of shadow root `<div class="ui5-rating-indicator-root"...>` remains unchanged 

### Expected Behaviour

Title of shadow root `<div class="ui5-rating-indicator-root"...>` should be updated accordingly

### Screenshots or Videos

https://github.com/SAP/ui5-webcomponents-react/assets/131832797/b2d8fbfc-fc44-42ee-9013-cab04a6bcab8

### UI5 Web Components for React Version

1.16.3

### UI5 Web Components Version

1.14.4

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @Jasonl157 

when changing the `title` in the actual implementation and not inside the dev tools, the `title` attribute is forwarded correctly. (See [codeSandbox](https://codesandbox.io/p/sandbox/purple-water-298rs3?file=%2Fsrc%2FApp.tsx%3A6%2C42))

The same goes for many other attributes, so please always try to test the behavior by implementing it yourself, and not just by using the browser's dev tools.

**Comment by Jasonl157** [comment]
Hi @Lukas742 
I created a new issue with the actual implementation. please take a look https://github.com/SAP/ui5-webcomponents-react/issues/4797
The component has no problem forwarding the initial title but has the problem forwarding the updated title

**Comment by Lukas742** [comment]
Hello @Jasonl157 

you can simply comment updates or questions about the original issue. We will then check if it should be reopened. This way, it will be easier for other users facing the same or similar issue to find existing GitHub topics. 
I will now mark this topic as duplicate (even if it is the original) because the other topic you created describes the problem better.

Duplicate #4797
