### ISSUE TITLE
[Variant Management]: Default is not translated to "Padrão" in manage view dialog box when the language is set to Portuguese

### ISSUE THREAD

**Issue by roshnijalan97new** [SAP/ui5-webcomponents-react#4789]
### Describe the bug

"Default" is not translated to "Padrão" in the manage view dialog box when the language is set to Portuguese.

### Reproduction steps

1. Go to https://codesandbox.io/s/flamboyant-elbakyan-fg7qhy?file=/src/App.js
2. Click on the arrow beside the test "selected"
<img width="453" alt="Screenshot 2023-06-26 at 2 41 51 PM" src="https://github.com/SAP/ui5-webcomponents-react/assets/120740457/f7669293-4088-4b11-a1dd-c05185852662">

3. Click on "Administrar" button.
4. "Administrar visões" dialog box will apper.
5. Observe the table has a coloumn named "default"
<img width="916" alt="Screenshot 2023-06-26 at 2 37 53 PM" src="https://github.com/SAP/ui5-webcomponents-react/assets/120740457/d58986b8-1bc4-47fb-b822-e5bc404c53cd">

...

### Expected Behaviour

"Default" is not translated to "Padrão" in the Administrar visões/manage view dialog box 

### UI5 Web Components for React Version

1.7.3

### UI5 Web Components Version

1.9.3

### Browser

Chrome

### Operating System

Mac Os

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @roshnijalan97new 

thanks for reporting. I've created an incident in our internal system.

**Comment by roshnijalan97new** [comment]
Hi @Lukas742, Please provide ETA for this bug.
