### ISSUE TITLE
[Select]: Component is broken on value state "Error"

### ISSUE THREAD

**Issue by reqyou** [SAP/ui5-webcomponents-react#4793]
### Describe the bug

Once the value state `Error` is attached to Select, the component is rendered not correctly in the document after selecting an option. 

### Isolated Example

https://codesandbox.io/p/sandbox/dazzling-banzai-jrd5xs?file=%2Fsrc%2FApp.tsx%3A10%2C4

### Reproduction steps

1. render
2. select option
3. broken

error message: "Uncaught (in promise) TypeError: this.popover.showAt is not a function at HTMLElement.openValueStatePopover"

### Expected Behaviour

Should allow Error value state. 

### UI5 Web Components for React Version

1.16.0

### UI5 Web Components Version

1.16.0

### Browser

Chrome

### Operating System

windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @reqyou 

this was fixed in [v1.14.2](https://github.com/SAP/ui5-webcomponents/releases/tag/v1.14.2) of `@ui5/webcomponents`. Please update your dependencies and then it should work again. ([codeSandbox](https://codesandbox.io/p/sandbox/jolly-payne-vltzfs?file=%2Fpackage.json%3A16%2C27))
