### ISSUE TITLE
[ObjectPage]: On click of ObjectPageSection, the page doesn't scroll to the beginning of section 

### ISSUE THREAD

**Issue by I506645** [SAP/ui5-webcomponents-react#4799]
### Describe the bug

When we have an ObjectPage which has data greater than the page size and when user clicks on the ObjectPageSection, then the UI doesn't navigate to the beginning of that section but instead it also displays data which is part of the previous section. This can be reproduced in the below mentioned codesandbox with "@ui5/webcomponents-react": "~1.16.0".

In our case with "@ui5/webcomponents-react": "0.27.5", the UI navigates to the beginning of the section but there is no margin between the section title and the section itself when it is clicked as shown in the attached screenshot.

Can you please check?

Best Regards,
Raghav

### Isolated Example

https://codesandbox.io/s/great-tu-ndc76q?file=/src/App.js

### Reproduction steps

Check the codesandbox example and click on the second section with title "Calculation Results".

For "@ui5/webcomponents-react": "0.27.5", check the below screenshot

![image](https://github.com/SAP/ui5-webcomponents-react/assets/121158363/c32abf58-519a-453c-a8f4-d0b395c775a3)

### Expected Behaviour

The UI should scroll to the beginning of the section with specific margin.

### Screenshots or Videos

![image](https://github.com/SAP/ui5-webcomponents-react/assets/121158363/d27fdc92-4bd6-4451-876b-bbbc3cc96ee4)

### UI5 Web Components for React Version

1.16.0

### UI5 Web Components Version

1.14.0

### Browser

Chrome, Edge

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @I506645 

there a a few issues with your implementation that are not supported:

- According to out [global design guidelines](https://experience.sap.com/fiori-design-web/object-page/#components), the `headerTitle` (`DynamicPageTitle` component) area is mandatory, you're only using the `headerContent` area.  
- The `DynamicPageTitle` should only be used in the title area of the Dynamic- or ObjectPage, you're using it inside the `DynamicPageHeader`.
- The `header` prop of the `DynamicPageTitle` component prop should only be used for components representing a heading, VariantManagement, etc. and you're passing a grid with more than one title and subtitle there. It's similar with the `breadcrumbs` prop. Although, this will most likely not cause any strange behavior it's not supported to pass a `Button` there.

Could you please check if the error still occurs without these limitations.

**Comment by I506645** [comment]
Hi @Lukas742 

I made the changes you suggested as per the design guidelines and it seems to work fine in the latest version. But in the lower version (in our case "@ui5/webcomponents-react": "0.27.5"), when the user clicks on the section, the scrollbar directly navigates to the children component of the section and doesn't display the section title as it's displayed in the latest version. 

Was this an expected behavior in the lower versions?

Best Regards,
Raghav

**Comment by Lukas742** [comment]
The design has changed over the months, and if I remember correctly, that was the intended behavior at the time.

**Comment by I506645** [comment]
Okay, thanks for the confirmation @Lukas742
