### ISSUE TITLE
[Toolbar]: Toolbar + createPortal creates an invisible Toolbar-childContainer which causes wrong css & flickering

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents-react#4806]
### Describe the bug

If you use a `Toolbar` and within the toolbar you define buttons but sometimes also `createPortal` to open a dialog.

But as soon as you add a portal to the `toolbar` the toolbar add an empty childcontainer to the childrens.

This causes the css to move around because of:
![image](https://github.com/SAP/ui5-webcomponents-react/assets/44802503/9e57c5c4-ea13-461e-882a-a55598d047f5)

I dont know if this is preventable but I was wondering why my buttons move around this crazy and flickering.

Additional you may wondering why I also use `open` to conditionally render the Dialog, this is because of lifecycle methods & hooks I dont want to run, unless the dialog opens.

### Isolated Example

https://codesandbox.io/p/sandbox/serene-sinoussi-zqfvjt?file=%2Fsrc%2FApp.tsx%3A33%2C3

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

I think portals in react do not create childrens. So this should also not happen.

### Screenshots or Videos

![image](https://github.com/SAP/ui5-webcomponents-react/assets/44802503/ccb4983e-cee2-4eb5-94a9-85be508f9992)

### UI5 Web Components for React Version

1.16.0

### UI5 Web Components Version

1.14.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @C3ntraX 

passing portals as children is not supported. To be more specific, all elements that are outside of the document flow, are not supported as children, as for each child a container is created which is responsible for the calculation of the overflow popover. The linked PR adds this limitation to the description of the prop. Thank you for bringing this topic to our attention!
