### ISSUE TITLE
[SF][Wizard]: Wizard throws error after rendering

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents-react#4809]
### Describe the bug

Wizard now throws an error after the rendering, causing all of our test suites with Wizard component failed.

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-wizard--docs

### Reproduction steps

1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-wizard--docs
2. Inspect the browser console output
3. See Wizard component now throws error after the rendering.
<img width="1326" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/27538066/25dda0d8-56b6-4ea5-a951-a9623e009fb1">

### Expected Behaviour

Wizard component should not throw error when rendering

### UI5 Web Components for React Version

1.14.5

### UI5 Web Components Version

1.16.3

### Browser

Chrome

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MarcusNotheis** [comment]
Hi @ksblklu,

thanks for reporting! This issue is already tracked and fixed in the UI5 Web Components repository (https://github.com/SAP/ui5-webcomponents/issues/7198) and will be released with the new version in the next couple of days.

Best regards,
Marcus
