### ISSUE TITLE
[SF][AnalyticalTable] AnalyticalTable can fit its container automatically without setting visibleRows

### ISSUE THREAD

**Issue by zhangliangyi** [SAP/ui5-webcomponents-react#4826]
### Is your feature request related to a problem?

I am building a page with `AnalyticalTable` component. I would like to put the table component into a `FlexBox` layout and the table will take up all the rest vertical space of the container.
But I do not find a way to achieve this, and if I set the `visibleRows` with a large number and an additional scroll bar will appeared in the `FlexBox` container which is unexpected for me.

### Describe the solution you'd like

Provide a boolean property like `fitContainer`. If this property is set to true, then the AnalyticalTable will take up all the rest space of its container, just like the `SmartTable` in https://sapui5.hana.ondemand.com/#/entity/sap.ui.comp.smarttable.SmartTable/sample/sap.ui.comp.sample.smarttable

### Additional Context

If isolated example is required, please let me know and I will create one for this issue.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @zhangliangyi 

have you tried setting `visibleRowCountMode` to `"Auto"`? (see [docs](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable--docs#adjust-the-number-of-visible-rows-to-the-container-height))

**Comment by zhangliangyi** [comment]
@Lukas742 
Thanks for your advice. It works.
