### ISSUE TITLE
[Dialog]: Inoperable Dialog in ObjectPage Component

### ISSUE THREAD

**Issue by sayortanaka** [SAP/ui5-webcomponents-react#4831]
### Describe the bug

I'd like to upgrade to incorporate other bug fixes, but upgrading causes title issues.
I'd like to know the provisional response as it's urgent.

UI5 Web Components for React Version
version without issue: 1.1.0
version with issue: 1.17.1

### Isolated Example

https://codesandbox.io/s/infallible-sutherland-x65tzq?file=/src/App.js

### Reproduction steps

1. Click [open dialog]
2. Can't click button in dialog

### Expected Behaviour

Operable Dialog in ObjectPage Component

### UI5 Web Components for React Version

1.17.1

### UI5 Web Components Version

1.15.1

### Browser

Chrome, Edge

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @sayortanaka 

mounting popups, like the `Dialog` inside components can lead to undesired behavior. Please mount it outside of the component or use a React portal. You can find out more about portals [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/knowledge-base-working-with-portals--docs).

--> [codeSandbox](https://codesandbox.io/s/dialog-in-object-page-forked-pwc4q4?file=/src/App.js)

**Comment by sayortanaka** [comment]
@Lukas742 
Thank you for your quick reply !!
