### ISSUE TITLE
Shellbar and shellbaritem icons

### ISSUE THREAD

**Issue by brampurnot** [SAP/ui5-webcomponents-react#4834]
### Describe the bug

The icons in the shellbar (both the standard icons like notifications) but also the ones added by the ShellbarItem are very thin and do not look like the one in the example:
<img width="1233" alt="Screenshot 2023-07-05 at 12 24 52" src="https://github.com/SAP/ui5-webcomponents-react/assets/17197669/0bda8591-b744-40e9-8f07-1273694b499d">

Here is a screenshot of the one in the documentation:
<img width="1006" alt="Screenshot 2023-07-05 at 12 25 23" src="https://github.com/SAP/ui5-webcomponents-react/assets/17197669/a5329cbe-7c36-4601-a047-505b688cf8bb">

Is there a way to make them bold? 

### Reproduction steps

1.
2.
3.
...

### UI5 Web Components for React Version

Accent2

### UI5 Web Components Version

1.15.1

### Browser

Chrome, Firefox, Safari

### Operating System

macOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @brampurnot 

please add a reproducible example, preferably by using this [codeSandbox ](https://codesandbox.io/p/sandbox/ui5-webcomponents-react-vite-j65vvg?file=%2Fsrc%2FApp.tsx) template.
