### ISSUE TITLE
[Dialog]: dialog doesn't open again after closing using ESC key

### ISSUE THREAD

**Issue by rchrdchn** [SAP/ui5-webcomponents-react#4835]
### Describe the bug

The [dialog](https://sap.github.io/ui5-webcomponents-react/?path=/story/modals-popovers-dialog--with-content) doesn't open again after closing it by using the `ESC` key (keyboard).

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/story/modals-popovers-dialog--with-content

### Reproduction steps

1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-dialog--docs#dialog-with-content and click on the "Open Dialog" button
2. Dialog opens
3. Press the `ESC` key on your keyboard
4. Dialog closes
5. Click the "Open Dialog" button
6. Dialog doesn't open

### Expected Behaviour

Dialog opens as usual after closing it by using the `ESC` key.

### UI5 Web Components for React Version

1.17.2

### UI5 Web Components Version

1.15.1

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @rchrdchn 

we forgot to reset the React state when the dialog is closed with ESC. So this is not a bug in the component, but just an implementation error within the story.
