### ISSUE TITLE
Analytical Table: Disable movement with keyboard arrows

### ISSUE THREAD

**Issue by vital487** [SAP/ui5-webcomponents-react#4859]
### Is your feature request related to a problem?

When I am writing on an input that is inside a cell in the Analytical Table and I want to use the arrow keys to move inside that input, the selected cell changes.

### Describe the solution you'd like

Add a property to each column of the Analytical Table describing if we want to use the arrow keys. Maybe there could be other props saying if we want horizontal keys or vertical. For example, I would like to have vertical keys, but not horizontal, since I can already use Tab or Shift + Tab.

### Describe alternatives you've considered

No alternatives.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @vital487 

the `keydown` event of your input is bubbling up to the table. To prevent that you can call `event.stopPropagation()` in the respective handler of your input.

**Comment by vital487** [comment]
Hi @Lukas742,

It worked, thanks.
