### ISSUE TITLE
ObjectPage: header content throwing error

### ISSUE THREAD

**Issue by lpohren** [SAP/ui5-webcomponents-react#486]
**Describe the bug**
After changing from "0.9.0-rc.15" to 0.9.0" the when using any of the header properties an error is thrown. Tested with headerContent and renderHeaderContent properties.

**To Reproduce**
1. Add any element to a <ObjectPage> header
2. open it
3. the error is thrown

**Expected behavior**
The header rendered.

**Screenshots**
Error: ![image](https://user-images.githubusercontent.com/16123699/81230544-106c8500-8fc8-11ea-9cf0-b0d5bea1cc9e.png)

**UI5 Web Components for React Information**
Operating System:
`@ui5/webcomponents-react` version:
Do you have a dependency to`@ui5/webcomponents` in your package.json? If yes, which version?:
0.9.0

**Additional context**

**Comment by MarcusNotheis** [comment]
Hi @lpohren,
can you try with version `0.9.3` as our latest version? I just tried to reproduce this issue but was not able to. In case is still occurs, is there any chance to share a reproducible example with me?
Thanks,
Marcus

**Comment by lpohren** [comment]
Hi @MarcusNotheis ,
Yes, it is still happening, I got the code from the wiki to make sure nothing was wrong with the <ObjectPage> implementation. 
I believe it might be something related to the dependencies used. I'm sending the full list so we can compare with yours if that's fine.
```
  "dependencies": {
    "@webcomponents/webcomponentsjs": "^2.4.3",
    "@ui5/webcomponents": "1.0.0-rc.7",
    "@ui5/webcomponents-icons": "1.0.0-rc.7",
    "@ui5/webcomponents-fiori": "1.0.0-rc.7",
    "@ui5/webcomponents-base": "0.20.0",
    "@ui5/webcomponents-react": "0.9.3",
    "@ui5/webcomponents-react-base": "0.9.2",
    "@ui5/webcomponents-react-charts": "0.9.3",
    "axios": "^0.19.2",
    "express": "^4.17.1",
    "http-proxy-middleware": "^1.0.0",
    "i18next": "^19.0.3",
    "i18next-browser-languagedetector": "^4.0.1",
    "multireducer": "^3.1.2",
    "react": "^16.12.0",
    "react-app-polyfill": "^1.0.6",
    "react-dom": "^16.12.0",
    "react-i18next": "^11.3.1",
    "react-jss": "^10.0.4",
    "react-redux": "^7.1.3",
    "react-router-dom": "^5.1.2",
    "react-scripts": "3.4.0",
    "redux": "^4.0.5",
    "redux-actions": "^2.6.5",
    "redux-saga": "^1.1.3",
    "resize-observer-polyfill": "^1.5.1"
  }
```

**Comment by lpohren** [comment]
Issue solved!
