### ISSUE TITLE
FormGroup on New Line

### ISSUE THREAD

**Issue by mathlizee** [SAP/ui5-webcomponents-react#487]
Hi,

I currently have a `Form` with three `FormGroup`, each of them containing multiple `FormItem`. However, since my first `FormGroup` is bigger than the second one, the third `FormGroup` is displayed below the second `FormGroup` (see attached screenshot). What I would like is the third `FormGroup` to be displayed under the first one.

After reading all the documentation about the `Form` control, I didn't find any way of achieving what I want. Is there any way to do so? And if not, could the `Form` control provide a new property to change its `FormGroup` layout?

Furthermore, I noticed that the controls used in my `Form` (`Input`, `ComboBox` and `TextArea`) do not have the same width. Is it possible for them to have a consistent width?

Thanks!
Math

![Form](https://user-images.githubusercontent.com/15334138/81254121-37db4600-8ff8-11ea-872f-c2efc7718a08.png)

**Comment by MarcusNotheis** [comment]
Hi @mathlizee,
thanks for your issue, we will look into that. Is there any chance that you could provide us a reproducible issue template using e.g. codesandbox?

**Comment by mathlizee** [comment]
Hello @MarcusNotheis,

Here is a [sample demonstrating the issue](https://codesandbox.io/s/keen-keldysh-yem4f). Hope this helps!

Thanks,
Math

**Comment by MarcusNotheis** [comment]
Hi @mathlizee,

@Lukas742 fixed the issue and the fix is available in version `0.10.0-rc.0`. Unfortunately this required a larger amount of refactorings, so we were not able to provide that fix free of breaking changes in the grid.
