### ISSUE TITLE
[SF]Button style should be changed  when design is default.

### ISSUE THREAD

**Issue by hxempty** [SAP/ui5-webcomponents-react#4875]
This is Fiori  Guidelines  https://experience.sap.com/fiori-design-web/button/
![image](https://github.com/SAP/ui5-webcomponents-react/assets/34623782/e0951bd0-c4fa-4292-ac36-2a7ed4537667)

Now,The default button component  is like  this https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-button--docs
![image](https://github.com/SAP/ui5-webcomponents-react/assets/34623782/67528948-2311-4153-97f6-a109b7014aa9)

So the UI5 component should be update the style .

### Describe the solution you'd like

The question influences many pages.Such like 
![image](https://github.com/SAP/ui5-webcomponents-react/assets/34623782/f03fb370-a7bf-4f46-bf9a-c914814a6046)
Do you have any plans to update this component.If so, when will it be updated? Thanks you .

**Comment by Lukas742** [comment]
Hi @hxempty 

I will close this issue as there is already [another one](https://github.com/SAP/ui5-webcomponents/issues/7144) covering this topic. If you have any questions or more information, please address them in the original issue. 

Duplicate https://github.com/SAP/ui5-webcomponents/issues/7144
