### ISSUE TITLE
[Popover]: Popover won't open anymore after clicking outside or pressing ESC

### ISSUE THREAD

**Issue by matheushahn** [SAP/ui5-webcomponents-react#4878]
### Describe the bug

The popover has a bug that if click outside or press ESC instead of clicking the close button, the popover doesn't open anymore.

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/story/modals-popovers-popover--with-content

### Reproduction steps

1. Open the popover
2. Click outside the popover OR press ESC
3. The popover will close
4. The popover won't open anymore

### Expected Behaviour

The closing of the popover should work exactly the same, either by clicking on the close, the ESC or outside the popover.

### UI5 Web Components for React Version

latest (1.17.2)

### UI5 Web Components Version

latest (1.11.3)

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @matheushahn 

thanks for reporting. We forgot to reset the React state when the dialog is closed with ESC or by clicking outside of it. So this is not a bug in the component, but just an implementation error within the story. The linked PR will fix that.
