### ISSUE TITLE
FormItem: CSS for .FormItem-lastGroupItem does not align with the label

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents-react#4921]
### Describe the bug

I don't understand why the last item within a formgroup should have additional margin at the button, because this does not align with a label next to it

### Reproduction steps

1.
2.
3.
...

### Screenshots or Videos

![image](https://github.com/SAP/ui5-webcomponents-react/assets/44802503/70fd159a-ee96-496e-b068-b5c324c8b529)

![image](https://github.com/SAP/ui5-webcomponents-react/assets/44802503/4ec9b6fe-96af-4121-8987-c42b0f04dde4)

![image](https://github.com/SAP/ui5-webcomponents-react/assets/44802503/e6353fde-30c7-43ff-a0d2-81a993c45831)

### UI5 Web Components for React Version

1.17.1

### UI5 Web Components Version

1.15.1"

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @C3ntraX 

thanks for reporting!
According to the specs, there should be a margin of `1rem` at the beginning and at the end of a group. We forgot to apply this for custom label components (instead of plain text), that's why the label is misaligned. The linked PR will fix this.
