### ISSUE TITLE
[Form; FormGroup]: Performance issue

### ISSUE THREAD

**Issue by C3ntraX** [SAP/ui5-webcomponents-react#4922]
### Describe the bug

See the gif.

I guess when the performance drop then the GroupTitle should render at the same time as the FormItems will render.

So the GroupTitle should render at the second render.

Additional, I dont understand why the performance is this bad, but thats another topic.

To let you know, the change to the Form rendering does not changed the performance. The performance was bad before.

### Reproduction steps

1.
2.
3.
...

### Screenshots or Videos

![FormPerformanceIssue](https://github.com/SAP/ui5-webcomponents-react/assets/44802503/67ee2af0-bdd9-4d82-bd6e-a72705e009df)

### UI5 Web Components for React Version

1.17.1

### UI5 Web Components Version

1.15.1

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @C3ntraX 

in [v1.17.0](https://github.com/SAP/ui5-webcomponents/releases/tag/v1.17.0) of `@ui5/webcomponents` it was changed how ui5 web components apply CSS variables, as the previous approach was causing performance issues, especially when dynamically rendering. Could you please try out[ v1.19.0](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v1.19.0) of `@ui5/webcomponents-react` and see if the issue still exists and, if that's the case, create a reproducible [codeSandbox](https://codesandbox.io/p/sandbox/ui5-webcomponents-react-vite-j65vvg) example?
