### ISSUE TITLE
[ObjectStatus]:[SF]ObjectStatus style should be align with  Fiori guidelines

### ISSUE THREAD

**Issue by hxempty** [SAP/ui5-webcomponents-react#4934]
### Describe the bug

This is Fiori Guidelines:https://experience.sap.com/fiori-design-web/object-display-elements/#components
![image](https://github.com/SAP/ui5-webcomponents-react/assets/34623782/69821840-26cc-430f-9b9e-675b935bee2c)

This is the UI5 example :https://ui5.sap.com//#/entity/sap.m.ObjectStatus/sample/sap.m.sample.ObjectStatus
![image](https://github.com/SAP/ui5-webcomponents-react/assets/34623782/59d69846-c8bc-4358-96da-01d5dc63ba85)

Now  It's like this 
![image](https://github.com/SAP/ui5-webcomponents-react/assets/34623782/d13fbd6a-cee1-4d5c-b4ad-d7e35a9fbbba)
https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-objectstatus--docs
Maybe the border-radius is incorrect.

### UI5 Web Components for React Version

v1.17.3

### UI5 Web Components Version

~1.15.0

### Browser

Chrome

**Comment by hxempty** [comment]
Hi @Lukas742,  How long will it take to see the new features?,Thanks

**Comment by Lukas742** [comment]
Hi @hxempty 

PR #4939 will add the correct border-radius and some other style updates. 
Please note, that we had to split up the refactoring as the specs are already updated, but some CSS vars we're using aren't, so we need to wait for [theming-base-content](https://github.com/SAP/theming-base-content) to update the values of the corresponding CSS vars and then again have to wait for ui5-webcomponents to update their dependencies to the respective versions of theming-base-content.

Please also note, that the design you see on [experience.sap](https://experience.sap.com/fiori-design-web/object-display-elements/#components) is using Quartz Light (Fiori 3) and is also not updated to the latest specs and Sap/Open UI5 also seems to have some deprecated values for e.g. the border-radius implemented.
