### ISSUE TITLE
[DynamicPage/Popover]: Position of Popover changes when used inside DynamicPage and ShellBar

### ISSUE THREAD

**Issue by ozreads** [SAP/ui5-webcomponents-react#4961]
### Describe the bug

I am trying to create the following structure:
- ShellBar
- DynamicPage  
Inside the DynamicPage component, I want to have a Popover button. When I combine these three, the popover displays far from the button itself. When removing the ShellBar, then it displays close to the popover button. When I use a Shell and create just a normal div below (wihtout using DynamicPage) to contain the Popover component and button, it also displays normally. it only has a weird gap when used in combination with either of these two components. 
I am not sure if this is a bug but I could not get it to work properly.

### Isolated Example

https://codesandbox.io/s/damp-thunder-nfxt3m

### Reproduction steps

1. use this [codesandbox ](https://codesandbox.io/s/damp-thunder-nfxt3m)

### Expected Behaviour

it should not create any extra space between the popover button and the popover itself as per documentation that is not the expected behavior because it should display right next to the button without gaps.

### Screenshots or Videos
With ShellBar:
![image](https://github.com/SAP/ui5-webcomponents-react/assets/115879540/999d2a98-e627-45e9-9d36-b0bbb3c6fe83)

Without ShellBar:
![image](https://github.com/SAP/ui5-webcomponents-react/assets/115879540/3fd249d2-350e-49f9-b88a-71aee41c84fa)

### UI5 Web Components for React Version

18.2

### UI5 Web Components Version

1.16

### Browser

Chrome, Edge

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MarcusNotheis** [comment]
Hi @ozreads,

as mentioned in our documentation ([Using Popovers inside other components](https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-popover--docs#using-popovers-inside-other-components)), we always recommend to render `Dialog`, `Popover` and `ResponsivePopover` components using `createPortal` to ensure the correct positioning.
