### ISSUE TITLE
[Root]: [Errors when rendering the component in Chrome extension]

### ISSUE THREAD

**Issue by zhang928160849** [SAP/ui5-webcomponents-react#4995]
### Describe the bug

in contentScript of chrome extension, with code below to create a element in DOM and take it as root element of React, 
   ``` js
  const container = document.createElement("div");
  if (!container) {
    console.log("create container fail");
  }

  container.id = "someA";

  document.body.appendChild(container);

  const root = createRoot(container);
  root.render(
    <ThemeProvider>
      <Button>hello</Button>
    </ThemeProvider>
  );
  console.log(container);

 ```

 error raised by
```js
        customElements.get("ui5-static-area") || customElements.define("ui5-static-area", Ke);
```
 says"customElement is null"

### Reproduction steps

1.
2.
3.
...

### UI5 Web Components for React Version

1.18.0

### UI5 Web Components Version

1.16.0

### Browser

Chrome

### Operating System

Mac OS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MarcusNotheis** [comment]
Hi @zhang928160849,

thanks for reaching out. This sounds like a Chrome bug (or rather a missing feature) for me.
I also just found an [open chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=390807) which sounds pretty much like your use case.

Closing this issue as there is unfortunately nothing we can do from UI5 Web Components (for React) side.

**Comment by zhang928160849** [comment]
@MarcusNotheis  Hi Marcus, thanks for your reminder, in order to make UI web components to work in chrome extension, need to import this [Polyfill](https://github.com/webcomponents/polyfills/tree/master/packages/webcomponentsjs)
