### ISSUE TITLE
Panel with SegmentedButton: Collapsed Panel contains SegmentedButton with width 0

### ISSUE THREAD

**Issue by petejohnson84** [SAP/ui5-webcomponents-react#500]
**Describe the bug**
A default collapsed Panel containing a SegmentedButton renders oddly. The ToggleButton text is all ellipsis and renders partially outside of the Panel. If the default collapsed is false, the behavior does not happen.

**To Reproduce**
1. Use the create-react-app with @ui5/webcomponents-react template
2. Add the following code to App.js
```
<Panel collapsed={true}>
    <SegmentedButton>
        <ToggleButton>Left</ToggleButton>
        <ToggleButton>Center</ToggleButton>
        <ToggleButton>Right</ToggleButton>
    </SegmentedButton>
</Panel>
```

**Expected behavior**
The SegmentedButton should render correctly despite the default Panel collapsed variable.

**Screenshots**
![Screen Shot 2020-05-08 at 12 56 25 PM](https://user-images.githubusercontent.com/16767811/81440837-ec2ab880-912d-11ea-8776-fc91efbd31b4.png)

**UI5 Web Components for React Information**
Operating System:
`@ui5/webcomponents-react` version: 0.9.4
Do you have a dependency to`@ui5/webcomponents` in your package.json? If yes, which version?: 1.0.0-rc.7

**Comment by MarcusNotheis** [comment]
hey @petejohnson84 - thanks for the issue report. As the affected components are built by our UI5 Web Components colleagues, I've opened an issue on their repo: https://github.com/SAP/ui5-webcomponents/issues/1596

Thanks,
Marcus
