### ISSUE TITLE
[Analytical Table]: Incorrect indentation of hierarchy levels

### ISSUE THREAD

**Issue by mande-m** [SAP/ui5-webcomponents-react#5006]
### Describe the bug

With an analytic table and a hierarchy view, the indentation of levels is not constant and it makes the trees difficult to read.
For example the indentation between level 0 and level 1 is 16px (1rem), but the indentation between level 1 and level 2 is only 8px (0.5rem).
This behaviour can be seen using analytical table story book (please see [analytical story book](https://sap.github.io/ui5-webcomponents-react/?path=/story/data-display-analyticaltable--tree-table)).
According to Fiori specifications, indentation width should be constant (please see [Fiori Design](https://experience.sap.com/fiori-design-web/tree-table/)).

### Isolated Example

cf. story book

### Reproduction steps

cf. story book

### Expected Behaviour

As specified by Fiori, constant and wide enough indentation.

### UI5 Web Components for React Version

1.16.0

### UI5 Web Components Version

1.14.0

### Browser

Chrome

### Additional Context

The span used to display the expand collapse icon on nodes seems to have inconsistent padding or margin, and the user of the analytical table does not have access to the style of this element.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @mande-m 

we had the indentations for the different content density modes mixed up, Cozy was using the indentations of Compact and the other way around. 
By design the indentations have different indentations per level (up until level 4 then it's always `0.5rem`)
