### ISSUE TITLE
VariantManagement: Renaming the variant in Manage Views to violate custom condition causes Error strip in all variants in the list

### ISSUE THREAD

**Issue by knandan15** [SAP/ui5-webcomponents-react#5027]
### Describe the bug

In the framework component of VariantManagement, we can change the name of the variants from the Manage Views. In the provided example, I have set a condition that a Variant name should be less than 15 characters. When any variant from the list of variants in the Manage Views is renamed as such (>15 characters), it shows Error in all the Variants in the list.

In the event 'e', I could not find any unique value which would help identify the variant name **being** edited.

### Isolated Example

https://codesandbox.io/s/variantmanagement-name-validation-tqvx8c

### Reproduction steps

1. Click on the dropdown for variant list.
2. Click on "Manage".
3. Let's rename "Standard" variant. Rename it such that the name exceeds 15 characters.
4. The error message is shown across all the Variants.

### Expected Behaviour

Only the "Standard" variant which was renamed to have more than 15 characters should show the error message in the list. All the remaining Variant names should show no error.

### Screenshots or Videos

<img width="1691" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/48648230/6a91f354-5cdf-4831-b6cd-ad19dffc1ad2">

<img width="1583" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/48648230/7a386818-f6ce-49be-b0bb-723362d1046e">

https://github.com/SAP/ui5-webcomponents-react/assets/48648230/50a6dfc1-fb8c-4395-9112-d11fe62b3172

### UI5 Web Components for React Version

1.16.3

### UI5 Web Components Version

1.14

### Browser

Chrome, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @knandan15 

you update the state of each `VariantItem` if one of them is invalid. So, this is the expected behavior.

**Comment by knandan15** [comment]
Hi @Lukas742 ,
Is there a way to validate only that particular Variant? (As per my implementation)

**Comment by Lukas742** [comment]
You can use the same approach as you would, when working with dynamically rendered lists in combination with React state/props. Also, [this](https://sap.github.io/ui5-webcomponents-react/?path=/docs/knowledge-base-ids-via-dataset--docs) knowledge base entry might be relevant for you as well.

I've created a very basic [example](https://codesandbox.io/s/variantmanagement-name-validation-forked-cszxss?file=/src/App.js), to show how this behavior could be achieved.

**Comment by knandan15** [comment]
Hi @Lukas742 ,
Thanks for providing the above example. It is working as you demonstrated.

However one thing to be noticed:
- Click on the "Save As" or "Manage" button.
- Rename the variant to have more than 15 characters so it will show the error message in the error strip.
- Now keep it as it is and click on "Cancel" button.
- Open Save As/ Manage views again. 

The error messages are still displayed. Ideally, once we click on Cancel button, things should revert back to the initial scenario before editing. I found that in documentation, no explicit control/event listener was there for Cancel button.

**Comment by Lukas742** [comment]
Hi @knandan15 

could you create another Issue for this? This is something we need to take a closer look at, as this behavior cannot currently be achieved using standard means.
