### ISSUE TITLE
[Feature Request]: Support large design for ObjectStatus

### ISSUE THREAD

**Issue by 2bno1** [SAP/ui5-webcomponents-react#5035]
### Is your feature request related to a problem?

Per the Visual Core Doc (https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698914826), ObjectStatus should support "Large Design" in which icon and text are visually different from default.
<img width="1300" alt="image" src="https://github.com/SAP/ui5-webcomponents/assets/1751846/a7f9bf8f-5907-4116-b6c5-aefa58d7bc25">

### Describe the solution you'd like

ObjectStatus supports "Large Design"

### Declaration

- [ ] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @2bno1 

I just wanted to let you know that we will start working on this feature request once the updated CSS variables are available. (See https://github.com/SAP/ui5-webcomponents-react/pull/4935)
