### ISSUE TITLE
Remix starter

### ISSUE THREAD

**Issue by sachinbhutani** [SAP/ui5-webcomponents-react#5050]
### Is your feature request related to a problem?

Not able to use ui5 webcomponents with remix app (remix.run)

### Describe the solution you'd like

Provide a starter project template with remix

### Describe alternatives you've considered

Using vite, but we need to run loader functions on server with remix instead using browser loaders with vite and react router.

### Additional Context

https://remix.run/

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MarcusNotheis** [comment]
Thanks for the suggestion, @sachinbhutani!
I would also love to see a Remix template for UI5 Web Components (for React), but I think we would need some community contributions for this. I haven't used Remix before so far, so I guess creating a template without prior framework knowledge might not be the best idea 😄 
Would you be willing to kick something off and we'll try to support you with the special requirements of UI5 Web Components (for React)?

**Comment by sachinbhutani** [comment]
> Thanks for the suggestion, @sachinbhutani! I would also love to see a Remix template for UI5 Web Components (for React), but I think we would need some community contributions for this. I haven't used Remix before so far, so I guess creating a template without prior framework knowledge might not be the best idea 😄 Would you be willing to kick something off and we'll try to support you with the special requirements of UI5 Web Components (for React)?

I tried to replicate the vite template to Remix to create a starter, but get errors on some components like FlexBox and ThemeProvider. 
Most likely due to Remix SSR
Do you want me to create issues for each component with specific examples? 

Regards
Sachin
