### ISSUE TITLE
[SF_ACC][DynamicPage]: Cannot access actions overflow menu item through keyboard arrow keys

### ISSUE THREAD

**Issue by ksblklu** [SAP/ui5-webcomponents-react#5057]
### Describe the bug

1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-dynamicpage--docs
2. Reduce the width of the browser or switch to mobile mode
3. focus on the actions overflow menu, and press arrow keys to access the buttons
4. Keyboard arrow keys does not work, only tab key can access overflow buttons.
<img width="915" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/27538066/778e8ebd-225d-4245-98d3-4f81f4e1ea65">

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

Menu options must be navigable via arrow keys

### UI5 Web Components for React Version

1.18.0

### UI5 Web Components Version

1.16.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
I will close this issue as there is already another one covering this topic. If you have any questions or more information, please address them in the [original issue](https://github.com/SAP/ui5-webcomponents-react/issues/3704).

Duplicate https://github.com/SAP/ui5-webcomponents-react/issues/3704
