### ISSUE TITLE
ComboBoxItem: New property "value"

### ISSUE THREAD

**Issue by jannislmml** [SAP/ui5-webcomponents-react#5069]
### Is your feature request related to a problem?

It is cumbersome to determine a corresponding value in the onSelectionChange using the property "text".

### Describe the solution you'd like

It would be already if one could attach a value to a ComboBoxItem / MultiComboBoxItem. Value should be of any data type.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @jannislmml 

could you give some more information why you find it cumbersome? Please keep in mind that these props are attributes of the web-component, so passing anything else then primitives would only be accessible via properties of the element and you wouldn't be able to define it as React prop.

E.g.:

```jsx
<ComboBoxItem text="ExampleItem" value={{a:"b"}} />
```

Would result in: 

```html
<ui5-cb-item text="ExampleItem" value="[object Object]" ui5-cb-item=""></ui5-cb-item>
```

You therefore would only be able to set the object by setting it directly on the element. E.g.:

```js
    const cbiRef = useRef(null);

    useEffect(() => {
      if (cbiRef.current) {
        cbiRef.current.value = { a: 'b' };
      }
    }, []);
```

```jsx
<ComboBoxItem text="Austria" ref={cbiRef} />
```

**Comment by jannislmml** [comment]
had a wrong thought, has settled, sorry
