### ISSUE TITLE
[SF][MessageView]: Detail of message item cannot be opened via spacebar or ENTER key 

### ISSUE THREAD

**Issue by zhangliangyi** [SAP/ui5-webcomponents-react#5076]
### Describe the bug

When tab to a message item which have detail information, the detail view can only be navigated by mouse click. Keyboard action does not take any effect on the navigation.

### Reproduction steps

1. Go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/user-feedback-messageview--docs
2. Tab to the first message item `Error Message Type`
3. Press space bar or enter and nothing happens

### Expected Behaviour

The navigation should work via keyboard as well.

### UI5 Web Components for React Version

1.19.0

### UI5 Web Components Version

1.17.0

### Browser

Edge

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @zhangliangyi 

thanks for reporting. Once the linked PR is merged and released, you can access the details view of a `MessageItem` by pressing "Enter".
