### ISSUE TITLE
[SAP]: [Variant management Issue in SaveViewDialog while using SaveViewInputProps]

### ISSUE THREAD

**Issue by rupinder-kaur-sandhu** [SAP/ui5-webcomponents-react#5084]
### Describe the bug

A gentle request to look into this issue as we are using it for one of our customer projects in SAP.

As saveViewInputProps is provided to customize the input validation, there is basically a bug that our team is facing after using it.

### Reproduction steps

1. Click on any user created variant
2. Click on save As
3. Remove the name in the save View Dialog box
4. The input will display error message as "Please specify view name"
5. Now click on cancel button
6. Again open the same variant, the error message will still be displaying.
...

### Expected Behaviour

It should not retain the previous state and should open with no validation error message.

### Screenshots or Videos

https://github.com/SAP/ui5-webcomponents-react/assets/26716850/13b0946b-2abb-4dd7-bb6d-d221affcbe20

### UI5 Web Components for React Version

1.16.3

### UI5 Web Components Version

1.14.3

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @rupinder-kaur-sandhu 

I forgot to link the issue to the already merged [PR](https://github.com/SAP/ui5-webcomponents-react/pull/5123) that will implement a fix for this. The fix will be available with our next minor release.
