### ISSUE TITLE
Table: demandPopin doesn't work while a label is very long

### ISSUE THREAD

**Issue by rkl1994** [SAP/ui5-webcomponents-react#509]
**Describe the bug**
While using the component 'Table', if I resize the browser window to a small size, and I set the 'demandPopin' attribute, it works regularly, but if one cell is too long(because of the content of this field is long), it doesn't work. 

**To Reproduce**
1. Using the same code in the story book for table.
2. Set one field with a very long content.

**Expected behavior**
demandPopin should work no matter the length of one cell

**Screenshots**
This works 
![Screen Shot 2020-05-14 at 4 48 27 PM](https://user-images.githubusercontent.com/5527455/81913628-cce6cc00-9602-11ea-87f4-e6d3fa4773db.png)

But if the cell for 'Dimensions' is a very long value, it doesn't work.
![Screen Shot 2020-05-14 at 4 50 16 PM](https://user-images.githubusercontent.com/5527455/81913814-10d9d100-9603-11ea-908d-a274e30ce5da.png)

**UI5 Web Components for React Information**
"@ui5/webcomponents": "^1.0.0-rc.7",
    "@ui5/webcomponents-fiori": "^1.0.0-rc.7",
    "@ui5/webcomponents-icons": "^1.0.0-rc.7",
    "@ui5/webcomponents-react": "^0.9.1",

*If you are not sure, you can find out by running `npm ls @ui5/webcomponents-react` or `yarn why @ui5/webcomponents-react`*

**Additional context**

**Comment by MarcusNotheis** [comment]
Hi @rkl1994, 

this issue is caused by the fact that a `Label` does not wrap by default. You can achieve the desired behaviour by setting `wrap` prop on the `Label`.
You can find an example in [this codesandbox](https://codesandbox.io/s/hardcore-bird-u3yni?file=/src/App.js).

Does this work for you?

Best regards,
Marcus

**Comment by rkl1994** [comment]
Hi @MarcusNotheis,

Thanks for your solution. This works in your codesandbox example. However, in my real case, because of my label is not a sentence divided by blank space, so there is still problem existed.

Here is the link: https://codesandbox.io/s/hardcore-napier-0449y?file=/src/App.js

In this case, is there any solution? Thank you.

BRs,
Frank

**Comment by MarcusNotheis** [comment]
Hi @rkl1994, I just forwarded the issue to our UI5 Web Components colleagues, maybe they have a solution for that: https://github.com/SAP/ui5-webcomponents/issues/1621

Best regards,
Marcus
