### ISSUE TITLE
[SelectDialog]: [Unchecked boxes after selecting in MultiSelect mode]

### ISSUE THREAD

**Issue by aprasad888** [SAP/ui5-webcomponents-react#5104]
### Describe the bug

When working with the SelectDialog component in multiselect mode, I am running into a bug. When I select multiple items in the list and click the 'select' or 'cancel' button, after clicking on the dialog box again, it looks like all the items have been unselected (but in the top 'selected' section, you can see that they are still selected). Additionally, when trying to click on the already selected items, the box seems to temporarily show a check mark and clears immediately.

### Isolated Example

Can view bug in MultiSelect example here: https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-selectdialog--docs

### Reproduction steps

In the MultiSelect mode example shown in the docs, when selecting and unselecting items, can view the issue: 
1. Open the dialog box 
2. Begin selecting items
3. Click 'select' button 
4. Dialog box should close, click dialog box again 
5. Issue should appear (the selected items are no longer selected; while the selected count at the top remains the same) 

In the MultiSelect mode example shown in the docs, when re-clicking on previously selected items, can view the issue: 
1. Re-opening the dialog box (after selecting items) 
2. Re-click previously chosen items 
3. Issue should appear (the checkbox is checked and unchecked very quickly) 

### Expected Behaviour

After selecting items and clicking 'select' in the dialog box, when re-opening the box, the items that have been selected should still have check marks. After re-selecting these chosen items the items should be unselected and selected accordingly (not flicker in and out). 

### Screenshots or Videos

https://github.com/SAP/ui5-webcomponents-react/assets/43382394/e4dcfcaa-0e5e-4ddd-9d50-d70affb3f464

### UI5 Web Components for React Version

v.1.8.1

### UI5 Web Components Version

v.1.10.3

### Browser

Chrome

### Operating System

Venture 13.5.2

### Additional Context

N/A

### Relevant log output

```shell
N/A
```

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @aprasad888 

thanks for reporting!
We forgot to add `rememberSelections` to our example in the Storybook and the linked PR will fix this. So this is not an issue with the component, but only with our example.
