### ISSUE TITLE
SegmentedButton: Some toggle buttons contain ellipsis

### ISSUE THREAD

**Issue by petejohnson84** [SAP/ui5-webcomponents-react#513]
**Describe the bug**
A set of Toggle Buttons within Segmented Button will in some cases have ellipsis. For example, look at the documentation page for Segmented Button (see screenshot below as well). The second button has text "Butto..."

https://sap.github.io/ui5-webcomponents-react/?path=/docs/ui5-web-components-segmentedbutton--generated-default-story

**To Reproduce**
Create a SegmentedButton with three options, notice the second button has ellipsis.
```
<div>
    <SegmentedButton>
        <ToggleButton>Left</ToggleButton>
        <ToggleButton>Center</ToggleButton>
        <ToggleButton>Right</ToggleButton>
    </SegmentedButton>
</div>
```

**Expected behavior**
All text is fully shown

**Screenshots**
![Screen Shot 2020-05-14 at 8 00 42 AM](https://user-images.githubusercontent.com/16767811/81944431-fc251b00-95b9-11ea-9122-5e04a892bdd7.png)
![Screen Shot 2020-05-14 at 8 04 18 AM](https://user-images.githubusercontent.com/16767811/81944444-00e9cf00-95ba-11ea-911f-c32336cb4797.png)

**UI5 Web Components for React Information**
Operating System: macOS Catalina
`@ui5/webcomponents-react` version: 0.9.4
Do you have a dependency to`@ui5/webcomponents` in your package.json? If yes, which version?: ^1.0.0-rc.7

*If you are not sure, you can find out by running `npm ls @ui5/webcomponents-react` or `yarn why @ui5/webcomponents-react`*

**Comment by MarcusNotheis** [comment]
Hi @petejohnson84, this looks like a bug in the UI5 Web Components library. I forwarded the issue to their repository: https://github.com/SAP/ui5-webcomponents/issues/1616

Best regards,
Marcus
