### ISSUE TITLE
Missing variant Id information

### ISSUE THREAD

**Issue by arturnilson** [SAP/ui5-webcomponents-react#5141]
### Describe the documentation issue

Other

### Description

We had to update the web components in our project but we could not get the ID information of the variant as before.

Is there any workaround? how can I get the ID of the variant on VariantManagement properties? 

### Declaration

- [ ] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @arturnilson 

Unfortunately I don't know what you mean. Where do you expect an ID and from which version did you update?
