### ISSUE TITLE
ObjectPage: the screen shakes for certain desktop width

### ISSUE THREAD

**Issue by PriyaPowar** [SAP/ui5-webcomponents-react#5142]
### Describe the bug

It is sometimes observed that the object page is unable to set the width of its children for certain desktop width. It is also observed that this happens usually when the object page has analytical table in the content part. Please refer the video attached. However, if we set the overflow-y property of objectPage to hidden then the shaking stops. Please note that this does not happen all the time.

### Reproduction steps

please refer attached video

### Expected Behaviour

screen should not shake

### Screenshots or Videos

https://github.com/SAP/ui5-webcomponents-react/assets/90389521/ed143992-1396-4a4e-baf9-dfb4a18e114e

### UI5 Web Components for React Version

^1.17.3

### UI5 Web Components Version

^1.14.0

### Browser

Chrome

### Operating System

mac os

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @PriyaPowar 

I wasn't able to reproduce this, so please add a reproducible example, preferably by using this [codeSandbox ](https://codesandbox.io/p/sandbox/ui5-webcomponents-react-vite-j65vvg) template.
