### ISSUE TITLE
docs: missing delete information of FilterType enum in Migration Guide

### ISSUE THREAD

**Issue by sadie100** [SAP/ui5-webcomponents-react#5159]
### Describe the documentation issue

Documentation is missing

### Description

FilterType enum is deleted by [this PR](https://github.com/SAP/ui5-webcomponents-react/pull/717/commits/b60e4977564ba81674674ef8ade75d4894f554b5).
But there's no clear explanation about this deletion in [MigrationGuide.archive.md](https://github.com/SAP/ui5-webcomponents-react/blob/main/docs/MigrationGuide.archive.md#deleted-components-1).

### Link to Documentation Page

https://github.com/SAP/ui5-webcomponents-react/blob/main/docs/MigrationGuide.archive.md#deleted-components-1

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by sadie100** [comment]
As it's a minor task, I'm willing to update documentation file myself if that's acceptable.

**Comment by MarcusNotheis** [comment]
Hi @sadie100,

thanks for reporting. 
Sure, if you think it would beneficial to have this information in our Migration Guide, please feel free to add it and submit a pull request 🙂 
My personal opinion: The migration from 0.10.0 to 0.11.0 is pretty old in the meantime (we released this version over 3 years ago), so I guess there won't be many users on version - so I wouldn't invest too much time into this guide.

**Comment by sadie100** [comment]
Thanks for approval. You're absolutely right. Since it's not a major change, I just simply added a couple of words to make 'FilterType' searchable. Thank you 😊
