### ISSUE TITLE
UI5 Webcomponents React version upgrade: After upgrading to 1.20.0/1.21.1 many test cases in our SAC Lite-viewer are failing

### ISSUE THREAD

**Issue by ShivamGuptaSap** [SAP/ui5-webcomponents-react#5160]
### Describe the bug

After upgrading UI5Web components React to 1.20.0/1.21.1 and UI5 Webcomponents to 1.18.0 many test cases in our SAC Lite-viewer are failing

### Reproduction steps

1. Upgrade UI5 WebComponents for React  to 1.20.0 or 1.21.0 and above with UI5 Web Components version 1.18.0  in SAC Lite-viewer repo
2. npm install
3. Then it will throw error like "TypeError: Cannot read property 'replace' of undefined"
4. 
...

### Expected Behaviour

All the existing test cases should pass and there shouldn't be any regression.

### Screenshots or Videos

<img width="1324" alt="Screenshot 2023-10-14 at 6 50 26 AM" src="https://github.com/SAP/ui5-webcomponents-react/assets/107616257/5d5714fb-9899-4fe3-88f4-324da9fdf42d">

### UI5 Web Components for React Version

1.20.0 / 1.21.0 / 1.21.1

### UI5 Web Components Version

1.18.0

### Browser

Chrome

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MarcusNotheis** [comment]
Hi @ShivamGuptaSap,

can you please share some more details on your environment, especially from which UI5 Web Components React version you are trying to update?
In addition, a reproducible example using our [codesandbox template](https://codesandbox.io/p/sandbox/ui5-webcomponents-react-vite-j65vvg?file=%2Fsrc%2FApp.tsx) would help to debug and resolve this issue.

**Comment by ShivamGuptaSap** [comment]
Hi @MarcusNotheis ,
I've created a dummy app where you can run the testcases via "npm run test" and see the error,
We are upgrading from "@ui5/webcomponents": "1.14.0", "@ui5/webcomponents-react": "1.16.0".
https://github.com/ShivamGuptaSap/DummyApp

**Comment by MarcusNotheis** [comment]
Hi @ShivamGuptaSap,
it looks like your `src/setupTests.js` file is causing this error:
https://github.com/ShivamGuptaSap/DummyApp/blob/66776f110f53366e49cecb74843783077f895a17/src/setupTests.js#L8

With this mock, you are making `String.prototype.replaceAll` return undefined, which is not valid.
You should be able to remove this mock as all currently supported Node versions are supporting `replaceAll`: (see [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll#browser_compatibility))
