### ISSUE TITLE
[AnalyticalTable]: the Input in AnalyticalTable will lose focus after I typed in a character

### ISSUE THREAD

**Issue by Mipaprika** [SAP/ui5-webcomponents-react#5168]
### Describe the bug

I rendered an Input as a cell content of the AnalyticalTable, and:

1. if I listened to the `onInput`  event, as shown in the example below, the `name` column, then every time I typed a character into the Input, it will automatically lose focus, and I can not input anything until I clicked the Input and make it focused again.
2. if I listened to the `onChange` event, as shown in the example below, the `age` column, then after I finished my typing the age, and immediately clicked the `Click` button, it won't trigger the button's `onClick` event, until I clicked the button the second time.

I think these issues are due to re-render of the AnalyticalTable, the reason is if I don't change the value of the table data, then everything is ok(for example, comment out the `setData` line in the `handleNameChange` method, then I can type as normal).

### Isolated Example

https://codesandbox.io/p/sandbox/musing-james-sd6g3g

### Reproduction steps

1. as described above
2.
3.
...

### Expected Behaviour

1. If I listened to the `onInput` event, I can type in as normal Input
2. If I listened to the `onChange` event, after I finished my typing into the Input and click the button immediately, the `onClick` event can be triggered immediately as well.

### UI5 Web Components for React Version

~1.21.0

### UI5 Web Components Version

~1.18.0

### Browser

Chrome, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @Mipaprika 

your changing the data array on every input inside the name cell and on every ENTER press or focus-out inside the age cell. Because of that the components are unmounted and therefore lose focus. I've added two `useEffects` to your codeSandbox to show what I mean: https://codesandbox.io/s/dawn-breeze-khdq4x?file=/src/App.js

Since this is standard React (and DOM) behavior, I'm going to close this issue.

**Comment by Mipaprika** [comment]
Hi @Lukas742  thanks for your reply! but I don't think it's a standard React behavior, or I don't think the unmount behavior is necessary. 

I implemented a simple table using the Table element of ui5, which has the same `columns` property as AnalyticalTable, it just simply render the rows and cells, and I found everything is ok, the `Input` element would not be unmounted. The example is here https://codesandbox.io/p/sandbox/xenodochial-surf-nv4m5h?file=%2Fsrc%2FApp.tsx%3A26%2C56, the example only replace `AnalyticalTable` with my own table element.

I understand that if I didn't modify the `data` array then my original example can work as expected, but the `data` as a state, it should be an immutable object which is recommended by React, and moreover in my real project situation, I can not always pass the unmodified `data` to the table because the data has to be transformed(a `map` function is executed e.g.) before it is passed to the table. 

So I think this behavior is really confused and not intuitive.

**Comment by Mipaprika** [comment]
Hi @Lukas742  thanks for your reply! but I don't think it's a standard React behavior, or I don't think the unmount behavior is necessary. 

I implemented a simple table using the Table element of ui5, which has the same `columns` property as AnalyticalTable, it just simply render the rows and cells, and I found everything is ok, the `Input` element would not be unmounted. The example is here https://codesandbox.io/p/sandbox/xenodochial-surf-nv4m5h?file=%2Fsrc%2FApp.tsx%3A26%2C56, the example only replace `AnalyticalTable` with my own table element.

I understand that if I didn't modify the `data` array then my original example can work as expected, but the `data` as a state, it should be an immutable object which is recommended by React, and moreover in my real project situation, I can not always pass the unmodified `data` to the table because the data has to be transformed(a `map` function is executed e.g.) before it is passed to the table. 

So I think this behavior is really confused and not intuitive.

**Comment by Lukas742** [comment]
Hi @Mipaprika 

you're totally right, this is indeed not standard React behavior, seems like I'm so used to the implementation of the `AnalyticalTable` that I just took it as standard, even though it's not. Sorry about that. I'll reopen the issue and try to investigate why the data is remounting the table, currently I have a gut feeling, that it's connected to the virtualisation, but I'll come back to you once I know more. Since my schedule is pretty packed at the moment this could take some time, but I'll try to look into it next week.

**Comment by Lukas742** [comment]
Hi @Mipaprika 

sorry for the late reply, I only now found the time to investigate this.

Internally we're using `react-table` v7, there the `data` and `columns` is passed into a hook that i.a. prepares the rows and cells which makes it possible to control selection, grouping, custom renderer etc.
This hook creates new rows with every data and columns update (calls `prepareRow`) and therefore the `Cell` components are unmounted and the focus is lost. That's also the reason, why `columns` and `data` need to be memoized.
Unfortunately, there's nothing we can do about it except create a new table (which is already on our roadmap, but we won't get around to it any time soon). 

So I wasn't able to find a way to prevent this behavior when updating the data after every keystroke, but setting it after the user is done typing should lead to the same result, right?

I've also edited your codeSandbox a bit (e.g. added `useMemo`). You can find it here:
https://codesandbox.io/s/mystifying-hopper-ccjmn5?file=/src/App.jsx
