### ISSUE TITLE
[AnalyticalTable]: Trigger expand and collapse row events

### ISSUE THREAD

**Issue by ruzickam** [SAP/ui5-webcomponents-react#5181]
### Is your feature request related to a problem?

We want to add custom buttons for expanding and collapsing rows in our `AnalyticalTable` component. On pressing these buttons, certain row is either collapsed or expanded. To trigger the collapse and expand events in the table, we tried to use `AnalyticalTable.tableInstance.toggleRowExpanded` method. It works for expanding. Unfortunately after the collapse event, the whole table is re-rendered. This means that the top of the table is always shown after collapsing a row. This can be annoying when the user scrolled down to the bottom of the table.

### Describe the solution you'd like

Please add and expose two functions:

`fireRowExpand: (rowId: string) => void`
Row with id `rowId` is expanded when this function is called. Alternative to `AnalyticalTable.tableInstance.toggleRowExpanded`.

`fireRowCollapse: (rowId: string) => void`
Row with id `rowId` is collapsed when this function is called. Alternative to `AnalyticalTable.tableInstance.toggleRowExpanded`, but without re-rendering the whole table after the collapsing event is fired.

### Describe alternatives you've considered

Please remove the re-rendering of the whole table when a row is collapsed via `AnalyticalTable.tableInstance.toggleRowExpanded` call.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @ruzickam 

the current behavior is a bug of the component. After the linked PR is merged and released, you will be able to toggle the row by calling `toggleRowExpanded` without the table scrolling to the top.

**Comment by ruzickam** [comment]
Hi @Lukas742, thank you very much!
