### ISSUE TITLE
ResizeObserver loop completed with undelivered notifications

### ISSUE THREAD

**Issue by saradasilva** [SAP/ui5-webcomponents-react#5185]
### Describe the bug

Hello team.

This error is appearing to me when I try to change layout for FlexibleColumnLayout, not sure if it's the component what it's throwing this error, it's not happening every time but it throwing frequently, this was not happening before I updated the webcomponent version:

ResizeObserver loop completed with undelivered notifications.
    at handleError (http://localhost:3000/static/js/bundle.js:70906:58)
    at http://localhost:3000/static/js/bundle.js:70925:7

### Reproduction steps

This is the initial screen:
<img width="1516" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/64361857/05a1c624-46f5-4a22-a8e8-ef6d5b8728cc">

I click to see the detail, but when I click cancel to turn back then error is throwing

<img width="1510" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/64361857/f6239994-7cca-4dfb-835e-4b99f680aaf6">

### UI5 Web Components for React Version

1.21.1

### UI5 Web Components Version

1.17.2

### Browser

Chrome, Edge

### Operating System

macOS Sonoma 14.1

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @saradasilva 

the versions of `@ui5/webcomponents-react` and `@ui5/webcomponents` are incompatible (see [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/getting-started--docs#add-ui5webcomponents-react-to-an-existing-app)), you should also see a warning about this when installing modules.

Apart from that, I wasn't able to reproduce this, so please add a reproducible example by leveraging this [codeSandbox](https://codesandbox.io/s/elegant-https-jjtlc4?file=/src/App.js) template.
