### ISSUE TITLE
Analytical Table: Is it accessible to put component into analytical table data？

### ISSUE THREAD

**Issue by ggfer** [SAP/ui5-webcomponents-react#520]
**Is your feature request related to a problem? Please describe.**
I want the analytical table to display my data, with a feature of crud. 
![image](https://user-images.githubusercontent.com/19473701/82170832-2a776300-98f8-11ea-9d36-c118710a1fee.png)

**Describe the solution you'd like**
However, it doesn't work when I put the event click buttons in analytical table data.
![image](https://user-images.githubusercontent.com/19473701/82171074-d91ba380-98f8-11ea-83cb-bd470552da00.png)

**Describe alternatives you've considered**
use Table component, map TableRow, and TableCell manually. But it is not the best practice.

**Additional context**
Maybe it has already been in documents while I did not find it, and there is no such relevant information in other places to refer to. 
Could you please complete this chapter?

**Comment by MarcusNotheis** [comment]
Hi @ggfer,

thanks for submitting this issue! You are absolutely right, this is a missing recipe in our documentation, will add it as soon as possible.
You can render custom cells by using the `Cell` property in the column definition. Here's an example:
```jsx
const columns = [
...otherColumns,
{
    id: 'actions',
    accessor: '.',
    width: 100,
    canResize: false,
    Cell: ({ cell, row }) => {
      console.log('This is your row data', row.original);
      return (
        <FlexBox>
          <Button icon="edit" />
          <Button icon="delete" />
        </FlexBox>
      );
    }
  }
]
```
Does this work for you?

**Comment by ggfer** [comment]
Hi @MarcusNotheis,

thanks for your reply! It works!
![image](https://user-images.githubusercontent.com/19473701/82199656-8eb61900-9930-11ea-8863-95cebfe0c8d9.png)
