### ISSUE TITLE
[TabContainer] Component question

### ISSUE THREAD

**Issue by TheStelarek** [SAP/ui5-webcomponents-react#5213]
Hello, are you planning to introduce Tab Container component from UI5?

Like this one https://sapui5.hana.ondemand.com/#/entity/sap.m.TabContainer

**Comment by Lukas742** [comment]
Hi @TheStelarek 

There is already a [TabContainer](https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-tabcontainer--docs) component available. If you think there is a feature missing, please raise an issue in the [ui5-webcomponents](https://github.com/SAP/ui5-webcomponents) repo, as this web component is developed there.
