### ISSUE TITLE
[AnalyticalTable]: [cell data is incomplete when the content of the column moves to the first column]

### ISSUE THREAD

**Issue by yzy415** [SAP/ui5-webcomponents-react#5224]
### Describe the bug

When the column has the `Cell`,  `responsivePopIn` as `true`, and the width of the table is smaller than the `responsiveMinWidth`, the content of each cell will move to the first cell in the row.

However, at this time, the data provided to the `Cell`  function is incomplete compared with the data provided when the columns are shown separately.

### Isolated Example

https://codesandbox.io/s/amazing-haibt-x33lhw?file=/src/App.js

### Reproduction steps

1. open the isolated example
2. adjust the size of the preview panel to make its width larger than 301px
3. you'll see the checkbox is checked and the console logged `{checked: true}` and "Alex"
4. make the width of the preview panel smaller than 301px
5. you'll see the checkbox is unchecked and the console only logged "Alex"

### Expected Behaviour

The cell data provided to the Cell function should always be the same regardless of whether the content is merged into the first column.   

### UI5 Web Components for React Version

1.21.0

### UI5 Web Components Version

1.18.0

### Browser

Chrome

### Additional Context

I'm from SAP SuccessFactors and this issue blocked our development. Could we prioritize it? Thanks.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @yzy415 

please use `instance.value` instead of `instance.cell.value`.`cell` always reflects properties of the current cell the content is in, so in this case the cells of the `name` column.

https://codesandbox.io/s/green-mountain-qff24g?file=/src/App.js
