### ISSUE TITLE
UI5 Webcomponents React version upgrade: [Button] design = Emphasized

### ISSUE THREAD

**Issue by lirazhayatSap** [SAP/ui5-webcomponents-react#5228]
### Describe the bug

After upgrading UI5Web components React to 1.20.2 and UI5 Webcomponents to 1.18.0, buttons with design="Emphasized" are displayed incorrectly. background is white, and font color it white as well, causing it to be blank.
attached a screenshot.

### Isolated Example

https://codesandbox.io/s/compassionate-waterfall-d84w6k

### Reproduction steps

1. create component Bar
2.add button with design="Emphasized" inside
3. upgrate to components React to 1.20.2 and UI5 Webcomponents to 1.18.0
4. button text disappeared

### Expected Behaviour

Button stays with same design as before the upgrade.

### Screenshots or Videos

![Screenshot 2023-11-09 at 13 03 50](https://github.com/SAP/ui5-webcomponents-react/assets/107845664/f71ce782-d411-4a74-8d49-63c90db15c7f)

### UI5 Web Components for React Version

1.20.2

### UI5 Web Components Version

1.18.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @lirazhayatSap 

your codeSandbox example only shows our default template. Did you forget to save it?
Also, there is no version 1.20.2 of `@ui5/webcomponents-react`.

I've created a [codeSandbox](https://codesandbox.io/s/amazing-rhodes-x5lvfm?file=/src/App.jsx) using `v1.21.2` and tested the described behavior in both `sap_horizon` and `sap_fiori_3`(Quartz) theme but wasn't able to reproduce it. So please update your or my example to show the issue.

**Comment by lirazhayatSap** [comment]
Thank you for your detailed answer, we have found an inner problem.
