### ISSUE TITLE
[Analytical Table]: Subcomponent does not resize Table

### ISSUE THREAD

**Issue by gitgdako** [SAP/ui5-webcomponents-react#5229]
### Describe the bug

As can be seen in your Storybook "Data Display" -> "Analytical Table" -> "Subcomponents"
https://sap.github.io/ui5-webcomponents-react/?path=/story/data-display-analyticaltable--subcomponents
the table does not resize when opening a Subcomponent. When there are less rows the Subcomponent may be impossible to see and hidden behind the page itself

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/story/data-display-analyticaltable--subcomponents

### Reproduction steps

1. Anaytical Table with 1 row and a subcomponent
2. Open Subcomponent
3. Subcomponent is hidden

### Expected Behaviour

Tables does resize to create enough space for at least the Subcomponent and 1 row, if it is limited to that size it should scroll in a way that the row and subcomponent fill the entire space. I understand this is a more complicated task because of automatically adjusting scrollability, but the edge case of a dynamically sized table that in on specific case has only one row and a subcomponent needs to be handled in some way

### UI5 Web Components for React Version

1.20.0

### UI5 Web Components Version

1.18.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
I will close this issue as there is already another one covering this topic. If you have any questions or more information, please address them in the [original issue](https://github.com/SAP/ui5-webcomponents-react/issues/5229).

Duplicate https://github.com/SAP/ui5-webcomponents-react/issues/5229
