### ISSUE TITLE
ObjectStatus: Font-Weight Bold getting blurry on Safari Browser

### ISSUE THREAD

**Issue by stefanomantova** [SAP/ui5-webcomponents-react#5247]
### Describe the bug

ObjectStatus component seems to have a wrong behavior accross different browsers when including `inverted` prop and setting the `fontWeight` CSS style to `bold`. While the bold font seems not to be effective in Chrome, the same style prop results in a blurry display of this component in Safari browser, as below:

![2023-11-14_11-34-08](https://github.com/SAP/ui5-webcomponents-react/assets/44717272/0d7edd4a-8195-4f05-83b2-2e51eb64106a)
![2023-11-14_11-38-01](https://github.com/SAP/ui5-webcomponents-react/assets/44717272/b91af193-5b9f-4787-a7e2-881c56f09ca1)

This issue is reproducible on SandBox using the libraries version reported below, although it seems to not happen on previous versions.

### Isolated Example

https://codesandbox.io/s/multi-input-test-forked-9xjcnx?file=/src/App.js

### Reproduction steps

1. Create ObjectStatus component.
2. Set `inverted` prop
3. Set style = {{ fontWeight: "bold" }}
4. Compare the behavior on Safari and Chrome.
...

### Expected Behaviour

- Text content should not be blurry in Safari. 

- Text content should react to bold setting on Chrome.

### UI5 Web Components for React Version

1.19.0

### UI5 Web Components Version

1.17.0

### Browser

Chrome, Safari

### Operating System

Mac OS 14.0

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by stefanomantova** [comment]
Hi @Lukas742 
Thanks a lot for your fast response! The mentioned CSS variable `var(--sapFontBoldFamily)` seems indeed to solve the issue on Safari. However, it seems to cause no difference on the component design at all design. Looks like removing this variable completely results in the same behavior as keeping it now (I'm not sure if bold is being applied or not in case we remove or keep it).

**Comment by Lukas742** [comment]
Sorry, my mistake. The default `font-family` is `sapFontBoldFamily`, therefore no changes are visible, but the font is already bold compared to standard Text (which is using `sapFontFamily`).
It seems like that `font-weight` behaves differently in Safari for custom fonts. Unfortunately we can't offer support for overstyling for the reason mentioned before and because it would also lead to a tremendous increase of maintenance effort on our end.
