### ISSUE TITLE
[MessageViewButton]: "Information" and "None" are styled with same colors

### ISSUE THREAD

**Issue by gnseo** [SAP/ui5-webcomponents-react#5297]
### Describe the bug

There are specific colors for "Information" Type, but the "Information" is treated as "None" in `MessageViewButton`.

Theming Parameters: https://sap.github.io/ui5-webcomponents-react/iframe.html?viewMode=docs&id=knowledge-base-public-utils--docs#theming-parameters

At the below code, I think we should add following lines for "Information" Type.
https://github.com/SAP/ui5-webcomponents-react/blob/6e7002d79826c8bb413406f244013a78f873b113/packages/main/src/components/MessageViewButton/index.tsx#L28C27-L28C27
```js
    case ValueState.Information:
      cssType = 'Information';
      break;
```

### Reproduction steps

```jsx
<MessageViewButton
        type={ValueState.Information}
/>
```

### Expected Behaviour

Screenshot of expected output: 
<img width="52" alt="Screenshot 2023-12-01 at 14 28 04" src="https://github.com/SAP/ui5-webcomponents-react/assets/12092761/2dd83b6d-8e18-45d0-a65b-33e138eaddc7">

### UI5 Web Components for React Version

1.22.0

### UI5 Web Components Version

1.19.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @gnseo 

this is by design, since there is no representation for the "None" type of the `MessageItems` neither. The linked PR will add a note about it to the `type` prop.

**Comment by gnseo** [comment]
@Lukas742 : 
<img width="727" alt="Screenshot 2023-12-01 at 22 32 27" src="https://github.com/SAP/ui5-webcomponents-react/assets/12092761/1f7b85c1-f0a5-4d83-af68-f10551c4dcfb">

I think "None" and "Information" should be different, and we can see as above image, there are already different colors for the each of two types by design.

**Comment by Lukas742** [comment]
Hi @gnseo 

I noticed, that we need to update some styles of the `MessageViewButton` component, but the colors are correct. As the `MessageItem` basically only has four colors (`type`) the `MessageViewButton` also only has four colors (`type`).

It's the same for the the [SAP/OpenUI5 `ButtonType`](https://sapui5.hana.ondemand.com/#/api/sap.m.ButtonType), `Critical`, `Negative`, `Neutral`, and `Success` are the four available types for MessageViews. We will deprecate our component, once the `ui5-button` (`Button`) also allows these types.
