### ISSUE TITLE
AnalyticalTable: selection logic of selectionMode prop

### ISSUE THREAD

**Issue by ggfer** [SAP/ui5-webcomponents-react#531]
**Describe the bug**
allRowsSelected is still to be selected when unselected some subselection under allRowsSelected

**Isolated Example**
- step 1:
![image](https://user-images.githubusercontent.com/19473701/82523564-3022b200-9b5f-11ea-9027-531da77cb7bc.png)
- step 2: click the first one, allRowsSelected.
![image](https://user-images.githubusercontent.com/19473701/82523613-4b8dbd00-9b5f-11ea-8d56-b658df9c8902.png)
- step 3: click second selection
![image](https://user-images.githubusercontent.com/19473701/82523664-74ae4d80-9b5f-11ea-8f4f-8c6803ba3da1.png)
- step 4: click the third one.
![image](https://user-images.githubusercontent.com/19473701/82523706-94de0c80-9b5f-11ea-855b-b1b057b5874a.png)

**Expected behavior**
The first selection, allRowsSelected is **supposed to be unselected** when I execute step 3.
And thus step 4 as the same.

**Comment by ggfer** [comment]
here some clues you are. it will not work out if it is in **strict mode**.

- version one - no 'use strict'
https://codesandbox.io/s/modern-tdd-fefgx?fontsize=14&hidenavigation=1&theme=dark&file=/src/index.js

- version another - 'use strict'
https://codesandbox.io/s/modern-tdd-fefgx?fontsize=14&hidenavigation=1&theme=dark&file=/src/App.js

**Comment by Lukas742** [comment]
Hi ggfer,
thanks for submitting this issue. 

You are right, the 'select-all' behavior is broken in `StrictMode` but is working fine without it. 
The `AnalyticalTable` leverages [react-table](https://github.com/tannerlinsley/react-table) hooks and apparently one of them doesn't work as intended in `StrictMode`. 

You can find the corresponding issue here: https://github.com/tannerlinsley/react-table/issues/2170

We will let you know when this is fixed.

**Comment by ggfer** [comment]
@Lukas742 thanks for your confirmation. please notify me when fixed.

**Comment by ggfer** [comment]
@Lukas742 
It seems inanity about espousing `StrickMode` or not. 

- could not get information on the event of `onRowSelected` without `StickMode`
![image](https://user-images.githubusercontent.com/19473701/83148222-461a0f00-a12b-11ea-8d23-f9a606786aec.png)

- could get information on the event of `onRowSelected` with `StrickMode`
![image](https://user-images.githubusercontent.com/19473701/83147819-c2602280-a12a-11ea-8000-29210a047309.png)

**Comment by Lukas742** [comment]
Hi @ggfer 
this issue should be fixed in (0.11.0-rc.1)[https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.11.0-rc.1].

If you have any other problem with using the webcomponents-react in strict mode, please don't hesitate to open another issue.
