### ISSUE TITLE
[SF][DynamicPageHeader]: The breadcrumbs are supposed to be displayed above image when set showTitleInHeaderContent true

### ISSUE THREAD

**Issue by i323808** [SAP/ui5-webcomponents-react#5314]
### Describe the bug

When set `showTitleInHeaderContent` prop of ObjectPage true
1. Breadcrumbs are supposed to be displayed above image;
2. The title is supposed be aligned horizontally with the image

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-objectpage--docs

### Reproduction steps

1. set `showTitleInHeaderContent` true
2. Breadcrumbs is on the right side of image

### Expected Behaviour

Breadcrumbs are supposed to be displayed above image, and the title is aligned horizontally with the image

### Screenshots or Videos

<img width="605" alt="page_header" src="https://github.com/SAP/ui5-webcomponents-react/assets/30744017/75689dc1-b188-4ad1-9f37-f1ada2f37261">

<img width="605" alt="page_header_current" src="https://github.com/SAP/ui5-webcomponents-react/assets/30744017/de2a6a34-0159-4d02-b124-79fc4c4d342c">

### UI5 Web Components for React Version

1.21.2

### UI5 Web Components Version

1.19.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @i323808 

we unfortunately only now realized that the `showTitleInHeaderContent` is an remnant of an old implementation and is not recommended anymore. In SAPUI5 this prop only works with the `ObjectPageHeader` which is also not recommended to be used. See [here](https://experience.sap.com/fiori-design-web/object-page/#top):

> Always build the object page using the dynamic page header and not the former object page header. Using the old object page header creates issues that can’t be fixed retrospectively. Using the dynamic header will also ensure consistency across all floorplans and provide greater flexibility. For details, see the [Header](https://experience.sap.com/fiori-design-web/object-page/#header) section below.

Therefore, we decided to deprecate this prop and remove it with our next major release (v2.0.0) and not improve this feature further. [This PR](https://github.com/SAP/ui5-webcomponents-react/pull/5574) will add a deprecation notice to it.
