### ISSUE TITLE
AnalyticalTable: ui - allRowsSelected(the master selection) is off the right position

### ISSUE THREAD

**Issue by ggfer** [SAP/ui5-webcomponents-react#532]
**Describe the bug**
the master checkbox is off the right position after upgrading to the new version("@ui5/webcomponents-react": "^0.9.5" ).

**To Reproduce - codesandbox**
https://codesandbox.io/s/modern-tdd-fefgx?fontsize=14&hidenavigation=1&theme=dark

**Expected behavior**
change the version back to "@ui5/webcomponents-react": "0.9.4"  or some version before.
![image](https://user-images.githubusercontent.com/19473701/82536717-7a199100-9b7b-11ea-9b9d-7da530ad7b82.png)

**Comment by MarcusNotheis** [comment]
Fixed and released in `@ui5/webcomponents-react@0.9.10`
