### ISSUE TITLE
ObjectPage: Header buttons overlay title and header

### ISSUE THREAD

**Issue by lpohren** [SAP/ui5-webcomponents-react#533]
**Describe the bug**

**Isolated Example**
*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).*

**To Reproduce**
1. Go to a Object Page with button on header
2. resize the screen to a small size
3. Buttons overlay the rest of the content

**Expected behavior**
Do not overlay the title and headers

**Screenshots**
![image](https://user-images.githubusercontent.com/16123699/82600397-43944400-9b84-11ea-8b50-bbd889c1dd2f.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: "1.0.0-rc.7"
`@ui5/webcomponents-react` version: "0.9.4"
Operating System:
Browser: Chrome

**Additional context**
The screenshot is from the documentation, so it's probably happening on the latest versions as well.

**Comment by MarcusNotheis** [comment]
Hey @Iphoren
thanks for reporting. Actually this fix is a bit more complicated than expected. We need to get #543 merged first and then we can tackle this issue.

**Comment by MarcusNotheis** [comment]
Released in `@ui5/webcomponents-react@0.10.0-rc.2`
