### ISSUE TITLE
AnalyticalTable: include empty rows in `AnalyticalTableVisibleRowCountMode.Auto`

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents-react#5341]
### Describe the bug

Hi there,

We have an AnalyticalTable that we want to grow with its container, i.e. it's supposed to take up all available vertical space by adding blank rows. From the docs, it seems to me that this is what `AnalyticalTableVisibleRowCountMode.Auto` is supposed to do:
```
"Auto": The number of visible rows displayed depends on the height of the surrounding container.
```
However, that doesn't work for me. I have created a [sandbox](https://codesandbox.io/s/trusting-sara-3f4tk3?file=/src/App.js):

### Expected behavior
The red container has a fixed height and should be completely covered by the table, i.e. no red should be visible.

### Actual behavior
The table adds only exactly 3 blank rows, whether I use `Auto` or `Fixed`.

Am I doing it wrong? Thanks a lot in advance.

### UI5 Web Components for React Version

1.21.0

### UI5 Web Components Version

1.18.0

### Browser

Chrome

### Operating System

Windows 11

**Comment by Lukas742** [comment]
Hi @ej612 

the table will only fill the content of non empty rows (visible rows). You can control how many empty rows you always want to show by using the `minRows` prop. 

https://codesandbox.io/s/wild-wildflower-s3djyd?file=/src/App.js

**Comment by Lukas742** [comment]
Hi @ej612 

this is a valid feature request as this behavior makes sense and is also present in the SAP/OpenUI5 table. I am now reopening this issue and making it a feature request. I hope you don't mind that I have updated the title accordingly.
