### ISSUE TITLE
[SF][DynamicPage]: Keyboard focus is not in logical order after upon DynamicPageAnchorBarExpandBtn activation 

### ISSUE THREAD

**Issue by sfsf-xweb-sh** [SAP/ui5-webcomponents-react#5401]
### Describe the bug

When focus on the accordion icon of a collapsed section, expands the section and on next tab key press focus is not moved within next focusable/interactive element within section of content(accordion panel) associated with an accordion header.
For example, focus on collapsed icon first, then should focus on "active element" upon pressing tab. 
<img width="1120" alt="Screenshot 2024-01-08 at 14 12 20" src="https://github.com/SAP/ui5-webcomponents-react/assets/78520316/58c57d1e-f7e2-4056-affc-a95b91467856">

Please take a look, thanks!
Josepine Su

### Reproduction steps

1. go to https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-dynamicpage--docs
2. open inspect, and change the text to an active element
<img width="1085" alt="Screenshot 2024-01-08 at 14 41 22" src="https://github.com/SAP/ui5-webcomponents-react/assets/78520316/6f3c09c1-6be9-4801-a40d-1bc4e2f00252">
3. use keyboard to expand/collapse

### Expected Behaviour

When focus is on the accordion header for a collapsed panel, expands the associated section/panel and upon pressing tab key focus is expected to go to first interactive element within panel/accordion content.

### UI5 Web Components for React Version

1.23.2

### UI5 Web Components Version

1.20.1

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @sfsf-xweb-sh 

please add a reproducible example, preferably by using this [codeSandbox ](https://codesandbox.io/p/devbox/ui5-web-components-for-react-vite-template-rcpmd4) template.

**Comment by sfsf-xweb-sh** [comment]
As we discussed with QAS team, they accept current behavior, no need to change.
