### ISSUE TITLE
[ObjectPage] Hide tabs naigation option

### ISSUE THREAD

**Issue by adeptb** [SAP/ui5-webcomponents-react#544]
Hello!

Basing on the FIORI guidelines, it will be nice if `ObjectPage` component has option to hide TabContainer(look screenshot below).

<img width="963" alt="Screenshot 2020-05-27 at 15 21 47" src="https://user-images.githubusercontent.com/9465033/83018414-ed188100-a02d-11ea-81e8-aebb8e600ccf.png">

It can easy done by adding `noNavigation` prop to `ObjectPage` component and then pass it to `ObjectPageAnchorBar` with conditional render of `TabContainer` in it(screenshot below).
Already checked it in local Storybook - works like a charm.

<img width="1098" alt="Screenshot 2020-05-27 at 16 00 43" src="https://user-images.githubusercontent.com/9465033/83021866-518a0f00-a033-11ea-959f-329821380296.png">

**Comment by MarcusNotheis** [comment]
Hey @adeptb,
thanks for submitting this issue! As you already tried it out: do you want to try to shoot for a Pull Request or should we take care of it?

Best regards,
Marcus

**Comment by MarcusNotheis** [comment]
One more thing: I think your screenshots refers to the Dynamic Page example from this page, right: https://experience.sap.com/fiori-design-web/dynamic-page-layout/#floorplans

Then I think we should rather create a new component instead of trying to plug this into the ObjectPage to be honest. The ObjectPage contains lots of complexity for selecting tabs while scrolling, etc. so I think a new component will be cleaner. I guess then I would be better if we would implement it or would you like to give it a try anyways?

**Comment by adeptb** [comment]
@MarcusNotheis Thank you for fast reply,
Yes you are right, screenshot is from Dynamic Page example and I agree with you that new component will be cleaner solution. 
But implementation of new component will take much longer time than add custom logic to existing `ObjectPage`. 
I suggest to do both - I can make Pull Request with changed ObjectPage and you implement new Dynamic Page component, and we will switch to it when it is ready

**Comment by MarcusNotheis** [comment]
@adeptb then I would suggest a slightly different approach: You can hide the anchor bar by yourself by creating a CSS class to the object page with the following content:
```css
.objectPageWithoutNavigationBar section[role="navigation"] ui5-tabcontainer {
  display: none;
}
``` 
and add `objectPageWithoutNavigationBar` to the ObjectPage `className` prop.

Then we don't need to modify the ObjectPage and you'll get the expected result immediately :) 
Would that work for you?

The thing is that I'm not eager to add a prop to a component which is just an intermediate solution and results in a breaking change when removing it again.

**Comment by adeptb** [comment]
@MarcusNotheis Yes, className with display none style worked for me.

Thank you!

**Comment by MarcusNotheis** [comment]
Released new component `DynamicPage` in `@ui5/webcomponents-react@0.11.4`
