### ISSUE TITLE
[Analytical Table]: ActionSheet Click highlights Cell

### ISSUE THREAD

**Issue by gitgdako** [SAP/ui5-webcomponents-react#5441]
### Describe the bug

We are using a
@ui5\webcomponents-react\dist\components\AnalyticalTable
with a Column that has a
@ui5\webcomponents-react\dist\components\ActionSheet

When talking about "highlighting" we mean the blue border you get when clicking on a cell

Clicking on the Actionsheet highlights a cell. Irrelevant of which row is clicked, the same cell is highlighted. The highlighted cell seems to always be the first column in the 5-15th row dependent on how many rows have data, if there are less rows it does not happen

We have no idea how to reproduce the issue. We will provide a code sample once we have one, until then we are happy to provide pieces of our code if you can give us a hint which ones might indicate the problems cause

### Reproduction steps

1. Given Code Setup
2. Click Actionsheet

### Expected Behaviour

No cell is highlighted

### Screenshots or Videos

![image](https://github.com/SAP/ui5-webcomponents-react/assets/129291791/31cf46ed-ba0b-4be0-8f5f-3d3d34376012)

### UI5 Web Components for React Version

1.24.0

### UI5 Web Components Version

1.21.0

### Browser

Chrome, Edge

### Operating System

Windows 10/11

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @gitgdako 

this issue is probably similar or even the same as #5394. Could you please check if the [solution](https://github.com/SAP/ui5-webcomponents-react/issues/5394#issuecomment-1880543923) of the linked issue works for you as well?

**Comment by gitgdako** [comment]
Adding
          onFocus={(e) => {
            e.stopPropagation();
          }}
to the ActionSheet fixed the behaviour.
Thanks for the fast response.
I am not sure wether you would want to propagate the focus like that per default though
