### ISSUE TITLE
[AnalyticalTable]: [Config reset on new data]

### ISSUE THREAD

**Issue by florianschmidtsap** [SAP/ui5-webcomponents-react#5453]
### Describe the bug

I am working with AnalyticalTable and get realtime data. I want to offer functionalities like grouping, filtering, ordering and so on. But everytime I am getting new data, all the filters/groups/etc. go back to default. I often get new data so this is really annoying. 

### Reproduction steps

1. Define AnalyticalTable with Data and give a "groupBy" Parameter
2. Use the UI to open a group
3. Update the data in the react app
4. The opened group is closed now

### Expected Behaviour

How can I use realtime data with AnalyticalTables? Give me a config object for all of this, which I can apply as soon as my data got updated and all groups/filters/etc got reconstructed.

### UI5 Web Components for React Version

1.9.3

### UI5 Web Components Version

1.9.3

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @florianschmidtsap 

please take a look at this [recipe](https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable-recipes--docs#how-to-stop-the-table-state-from-automatically-resetting-when-the-data-changes).

If applying `autoResetXYZ: false` doesn't fix your issue, please let us know.
