### ISSUE TITLE
Urgent: Need Deployment Assistance for React App on BTP with Vite and CAPM NodeJS Backend

### ISSUE THREAD

**Issue by shaancse08** [SAP/ui5-webcomponents-react#5454]
### Describe the documentation issue

Documentation is missing

### Description

Hello Team,

I trust this message finds you well. I am currently facing challenges deploying a React app generated with Vite onto BTP. Despite my attempts, the deployment is not functioning as expected.

Our backend service is built on CAPM NodeJS.

I kindly request your urgent assistance in resolving this matter. Could you please provide relevant documentation or share a repository that can guide me through the deployment process?

Your prompt support is highly appreciated as we have already built our app and are eager to make it live.

Thank you in advance for your help.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MarcusNotheis** [comment]
Hi @shaancse08,

I've created a small example repository which contains all the required parts on how to deploy our Vite Template to a Cloud Foundry space: https://github.com/MarcusNotheis/vite-ui5wcr-cf

The most important part is the [@sap/approuter](https://www.npmjs.com/package/@sap/approuter) package which will take care of serving the application.

In my example I've set the `authenticationMethod` property in the `xs-app.json` to `none` - in a real world example you will most likely remove that one and bind an xsuaa service instance instead.

**Comment by shaancse08** [comment]
Hello @MarcusNotheis,
Thank you very much for your help :) . Now I can deploy the app successfully.
