### ISSUE TITLE
[FilterGroupItem]: [Required Fields are not being read aloud in Voice over Software]

### ISSUE THREAD

**Issue by dhruvojha** [SAP/ui5-webcomponents-react#5460]
### Describe the bug

When we use a Voice Over software, such as JAWS on Windows or Voice Over in Mac and navigate to a Filter Bar with a Filter Group Item for which required is set to true, we do not here "Required" or anything to that effect read aloud.

CodeSandboxLink for the same:  
https://codesandbox.io/p/sandbox/flexible-column-layout-sort-table-forked-4ddyfr?file=%2Fsrc%2FApp.js

### Reproduction steps

1. Open the link.
2. Activate a voice over software
3. Navigate to the FilterGroup item with an asterisk
...

### Expected Behaviour

Should give some audio response in the voice over software to stating required or mandatory, etc.

### Screenshots or Videos

<img width="1512" alt="Screenshot 2024-02-02 at 10 58 10 AM" src="https://github.com/SAP/ui5-webcomponents-react/assets/55664966/55880560-2490-4bb9-9b12-dc2601d9ff0d">

### UI5 Web Components for React Version

1.8.1

### UI5 Web Components Version

1.10.3

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @dhruvojha 

I will close this issue as there is already [another one](https://github.com/SAP/ui5-webcomponents-react/issues/3573) covering this topic. If you have any questions or more information, please address them in the original issue.

Duplicate #3573
