### ISSUE TITLE
AnalyticalTable | a11y : For AnalyticalTable Focus is coming for non-interactive Empty Text

### ISSUE THREAD

**Issue by yoganjan** [SAP/ui5-webcomponents-react#5467]
### Bug Description

For AnalyticalTable , When we are tabbing using keyboard, we see that focus is coming for non interactive empty box . 

![image](https://github.com/SAP/ui5-webcomponents/assets/16238780/24df7b03-b03c-428c-8ce0-c286613708a4)

### Affected Component

AnalyticalTable

### Expected Behaviour

Focus should not be coming for empty box 

### Steps to Reproduce

1. Login https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-analyticaltable--docs
2. Using Tab key of the keyboard, try to focus the Header column
3. Observe that the focus is coming for empty box 
4.
...

### Priority

Medium

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @yoganjan 

the linked PR will fix the issue, that when you initially tab into the table, the first cell regardless of the content is selected. After the PR has been merged and released, it is now always the first cell with content, i.e. the "Name" cell in your screenshot, that is focused.

Although, the empty select-all cell will still be focusable. The cell is still inside a table and omitting it would create discrepancies between other SAP/OpenUI5 table, where the behavior is the same. (E.g. see [here](https://openui5.hana.ondemand.com/entity/sap.ui.table.Table/sample/sap.ui.table.sample.Selection))
Also, I would find it strange if a cell is skipped, especially when using screen readers.
