### ISSUE TITLE
Add vertical-align=middle to table cell

### ISSUE THREAD

**Issue by rkl1994** [SAP/ui5-webcomponents-react#547]
**Is your feature request related to a problem? Please describe.**
When using the component 'table', find that content for each cell is not 'vertical-align=middle', and the display doesn't tidy while there is a button in the row.

If I do it by setting a css class, I have to add this classname to every <tablecell>

**Describe the solution you'd like**
Add 'vertical-align=middle' to table rows

**Additional context**
After 'adding vertical-align=middle', button and label are in the same line
<img width="1129" alt="Screen Shot 2020-05-29 at 2 32 47 PM" src="https://user-images.githubusercontent.com/5527455/83228809-7a3c1100-a1b9-11ea-858e-d358fb6b7b40.png">

Otherwise, they are not in the same line.
<img width="1116" alt="Screen Shot 2020-05-29 at 2 35 33 PM" src="https://user-images.githubusercontent.com/5527455/83228948-a9eb1900-a1b9-11ea-8d82-b06a193a6581.png">

**Comment by MarcusNotheis** [comment]
Hey @rkl1994, as the `ui5-table` component is developed by our web component colleagues I've forwarded this issue to their repo: https://github.com/SAP/ui5-webcomponents/issues/1701

**Comment by MarcusNotheis** [comment]
Closing this issue in favour of SAP/ui5-webcomponents#1701
