### ISSUE TITLE
[Theme] Is there a way to disable the theme?

### ISSUE THREAD

**Issue by SunnyWind** [SAP/ui5-webcomponents-react#548]
**Is your feature request related to a problem? Please describe.**
Our website uses a theming service to control the theme of the whole site. The style tag inserted by ui5-webcomponent-react will override our CSS variables.

**Describe the solution you'd like**
Is there a way to disable the theme of ui5-webcomponent-react? The former version of this library (0.6.x) didn't insert the style tag.
![image](https://user-images.githubusercontent.com/4338219/83235972-5383d780-a1c5-11ea-9cb1-f045c210d225.png)

**Comment by MarcusNotheis** [comment]
hey @SunnyWind,
this your Theme coming from the SAP Theme Designer Service? Then this guide might help you: https://github.com/SAP/ui5-webcomponents/blob/master/docs/CustomTheming.md

**Comment by SunnyWind** [comment]
Hi @MarcusNotheis ,

Thanks for your comments.

We do use the SAP Theme Designer Service. We have our own logic to load the theme variables from the theming service. We have to ensure our style tag is loaded after ui5-webcomponents-react's. 

We used to adding a `<style data-ui5-webcomponents-react-theme-properties></style>` tag at the front of <head>. However, the newer version of ui5-webcomponents-react changed the attributes of the style tag to
```
 <style data-ui5-theme-properties="@ui5/webcomponents-theme-base"></style>
  <style data-ui5-theme-properties="@ui5/webcomponents"></style>
```

Is there a better way to locate your style tag?

On the other hand, we are considering using the setTheme method you suggested. BTW, your migration guide does not mention that @ui5/webcomponents-base is also a required peer dependency.
![image](https://user-images.githubusercontent.com/4338219/83246999-79b17380-a1d5-11ea-96f7-adf7338c83e8.png)


Thanks
Ryan

**Comment by MarcusNotheis** [comment]
I think for the styling question I have to include @vladitasev as the Web Components React are basically coming without any Theming Parameters and everything is provided by the UI5 Web Components.

Regarding the migration guide: `@ui5/webcomponents-base` is a dependency of `@ui5/webcomponents`, we just needed to add the peer dependency to make our build work. As soon as #540 is merged, the warning will be gone.

**Comment by MarcusNotheis** [comment]
Hey @SunnyWind,
did the approach with `setTheme` help? Is there anything more to do here or can we close this issue?
