### ISSUE TITLE
[ObjectPage]: [HeaderTitle - disable hover visual effects when not expandable]

### ISSUE THREAD

**Issue by TinaAngeloski** [SAP/ui5-webcomponents-react#5492]
### Describe the bug

In the ObjectPage, when the user hovers over the header that is not expandable, the color and the mouse pointer are changing but there is no action possible, which confuses the users. 
This happens only when the content of the header comes from a sub-component, and doesn't happen when the content is directly embedded within the ObjectPage. Ideally both ways should provide the same result.
Attached is a code sandbox.

### Isolated Example
[CodeSandbox](https://codesandbox.io/p/devbox/sweet-tereshkova-n69mc7?workspaceId=82e20b3a-5a0e-4ceb-8d77-ef6fe77e7db3&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsljgo4c00053b6ieiokcllk%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsljgo4b00023b6iya41z18n%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsljgo4b00033b6ip9lznurr%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsljgo4b00043b6ioiy5ubm4%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B40%252C60%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsljgo4b00023b6iya41z18n%2522%253A%257B%2522id%2522%253A%2522clsljgo4b00023b6iya41z18n%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clsljgo4b00043b6ioiy5ubm4%2522%253A%257B%2522id%2522%253A%2522clsljgo4b00043b6ioiy5ubm4%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clsljhpis005t3b6i976bdf0w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clsljhpis005t3b6i976bdf0w%2522%257D%252C%2522clsljgo4b00033b6ip9lznurr%2522%253A%257B%2522id%2522%253A%2522clsljgo4b00033b6ip9lznurr%2522%252C%2522activeTabId%2522%253A%2522clsljhpfl004t3b6ip37bb37w%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clsljhpfl004t3b6ip37bb37w%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A19.464285714285708%257D)

### Reproduction steps

1. Create an ObjectPage
2. Create a Header component
3. Reference the Header component as HeaderTitle of the ObjectPage
...

### UI5 Web Components for React Version

1.24.0

### UI5 Web Components Version

1.21.2

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @TinaAngeloski 

we moved to [StackBlitz](https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx) as our preferred web IDE/sandbox as it's not possible anymore to edit codeSandboxes with a free plan.
___

You have to make sure to pass through all props to the `DynamicPageHeader` or `DynamicPageTitle` when used inside a custom component. ([example](https://stackblitz.com/edit/github-uweaas?file=src%2FHeader.tsx))
We didn't outline this particularity in our documentation very well, so I've created a PR that will add a note to each component and prop.
