### ISSUE TITLE
[AnalyticalTable]: Support hex colors and other color options for row Highlights

### ISSUE THREAD

**Issue by kmanisha29** [SAP/ui5-webcomponents-react#5500]
### Is your feature request related to a problem?

Need colors as part of row level data to be shown in row highlight instead of states. 
Currently only 5 ValueStates are supported for highlightField prop, hence only 4 colors available.
Few usecase requires colors mapped to data to be shown in highlight and colors will be hex colors [ as part of data]

### Describe the solution you'd like

Provide option to use hex color as string value for highlightField prop.
Update useRowHighlights hook to support any color option if not part of valueState.

### Describe alternatives you've considered

Alternatively, Provide any other prop to add hex color in border left or as row highlight instead of states.

### Additional Context

![image](https://github.com/SAP/ui5-webcomponents-react/assets/149479176/f2664943-8a4f-4612-b3e5-9a7203cfd852)

### Declaration

- [ ] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @kmanisha29 

the linked PR will make it possible to also define `Indication` colors. Adding custom colors is not supported by our UX guidelines (see [here](https://experience.sap.com/fiori-design-web/analytical-table-alv/#highlight-items)) and would therefore lead to discrepancies between other table implementations. If you still need to change it to a custom value, I would recommend overwriting the css var for the specific cell, or for the table in general. Keep in mind though, that you will need to handle theme changes yourself and also mappings to `ObjectStatus` values could differ then.
