### ISSUE TITLE
MessageBox: Empty Action Button for Custom Action

### ISSUE THREAD

**Issue by mathlizee** [SAP/ui5-webcomponents-react#551]
Hello,

I'm using the `MessageBox` control with a custom action. On previous versions of the library, it worked fine. However, the button for the custom action is now empty and does not seem to have any label. [Here](https://codesandbox.io/s/message-box-action-1z87i?file=/src/App.js) is an example of the issue.

I'm currently using version `0.10.0-rc.1` of the library and using Chrome as my browser.

Thanks!
Mathieu

**Comment by MarcusNotheis** [comment]
Released in `@ui5/webcomponents-react@0.10.0-rc.2`
