### ISSUE TITLE
AnalyticalTable: expand will need click twice in some random case

### ISSUE THREAD

**Issue by JackieWei** [SAP/ui5-webcomponents-react#5515]
### Describe the bug

AnalyticalTable: expand will need click twice in some random case
It's not stable reproduce-able. The expand click function is an async function with api request.
And when we use toggleRowExpanded to toggle a new added nodes, it may need to be click twice.
And in the two times clicking, e.detail.isExpanded all show true.

### Reproduction steps

1. Render a tree table of AnalyticalTable
2. Add some nodes from search results and auto expand them by toggleRowExpanded
3. Add some nodes from search results and auto expand them by toggleRowExpanded again
4. The newly added nodes will need click twice
5. Looks that this is caused by reuse of react nodes
...

### Expected Behaviour

If a node is already expanded, only click once to collapse it. And toggleRowExpanded should also count.

### UI5 Web Components for React Version

1.23.2

### UI5 Web Components Version

1.20.0

### Browser

Chrome

### Operating System

MAC

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @JackieWei 

even though the behavior is fuzzy, could you please try to give us an isolated example preferably by leveraging this [stackBlitz template](https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx)?
Without a reproducible example it's unfortunately not possible for us to assist you with this issue.
