### ISSUE TITLE
[SelectDialog]: Ability to rename the 'Cancel' button.

### ISSUE THREAD

**Issue by alehharnizonau** [SAP/ui5-webcomponents-react#5516]
### Is your feature request related to a problem?

When using SelectDialog in one of our features, a problem was identified: we cannot rename the cancel button. We need this in order to add a translation of the text of this button 'Cancel' into another language.

<img width="325" alt="Screenshot 2024-02-21 at 13 05 44" src="https://github.com/SAP/ui5-webcomponents-react/assets/101468748/32c62d94-888f-4df4-a5de-78fa3cbe882a">

### Describe the solution you'd like

Add ability to overwrite the default text for the cancel button.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @alehharnizonau 

to be consistent with other implementations of the `SelectDialog` (e.g. the [SAPUI5 implementation](https://sapui5.hana.ondemand.com/#/api/sap.m.SelectDialog%23overview)), the text of the "Cancel" button should not be changed and you shouldn't need to change it, as it's already translated in all supported languages. You can try out different translations in our [storybook](https://sap.github.io/ui5-webcomponents-react/?path=/docs/modals-popovers-selectdialog--docs) by clicking on the globe icon in the header bar.

**Comment by alehharnizonau** [comment]
Hello @Lukas742 

yes, I see. But in our project we use i18next library to make all the text translated. We use it like t('text') where text is the key for translating in json file. So and when we change the language nothing happens with 'Cancel' button.
