### ISSUE TITLE
Acc: Enable screen readers to read a cell as blank if there is no content inside for AnalyticalTable

### ISSUE THREAD

**Issue by arnabutilities** [SAP/ui5-webcomponents-react#5523]
### Is your feature request related to a problem?

On accessing empty cells, i.e. cells which do not have any data rendered, only column header is announced via the jaws screen reader. The announcement should also highlight that the cell is blank/empty.
Please refer attached screenshot and stackblitz link provided below. here for an empty cell, aria-label is appearing as column name and followed by some instruction for select/deselect the cell. here this cell should read out as blank/empty.
stackblitz link: https://stackblitz.com/edit/github-27exue-9rzaiv?file=src%2FApp.tsx

<img width="1728" alt="Screenshot 2024-02-22 at 11 43 03 AM" src="https://github.com/SAP/ui5-webcomponents-react/assets/6679011/5e17ddc5-e5e2-46ce-99ce-79fbcf33e244">

### Describe the solution you'd like

On accessing empty cells, i.e. cells which do not have any data rendered, only column header is announced via the jaws screen reader. The announcement should also highlight that the cell is blank/empty.
Please refer attached screenshot and stackblitz link provided below. here for an empty cell, aria-label is appearing as column name and followed by some instruction for select/deselect the cell. here this cell should read out as blank/empty.
stackblitz link: https://stackblitz.com/edit/github-27exue-9rzaiv?file=src%2FApp.tsx

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @arnabutilities 

the linked PR will add a new plugin hook enabling the empty cell announcement. We decided not to implement this behavior directly in the table as some screen readers (like "Voice Over") automatically detect empty cells which then leads to duplicate announcements.
