### ISSUE TITLE
AnalyticalTable: Scrollbar is appearing and immediately disappearing when expanding the rows (visibleRowCountMode="Auto")

### ISSUE THREAD

**Issue by adrianui5** [SAP/ui5-webcomponents-react#5525]
### Describe the bug

Hi everyone,

I am using the `AnalyticalTable `within a dialog (element: `Dialog`) with a fixed height (`style={{ height: "35rem", width: "65rem" }}`). I want to avoid having two scrollbars, and that's why I am using `visibleRowCountMode={AnalyticalTableVisibleRowCountMode.Auto}` on the `AnalyticalTable`. Now the issue is that when I am expanding rows, the scrollbar is appearing and immediately disappearing, which looks like a UI glitch. However, at the end of the day, the scrollbar is gone, and that's my intention. Could you please check this UI glitch?

Sometimes you have double scrollbars, sometimes it is glitching: https://codesandbox.io/p/sandbox/reverent-keller-rxpms6

Thanks

### Reproduction steps

1.
2.
3.
...

### UI5 Web Components for React Version

1.23.1

### UI5 Web Components Version

1.20.1

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @adrianui5 

we moved to [StackBlitz](https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx) as our preferred web IDE/sandbox as it's not possible anymore to edit codeSandboxes with a free plan. 

Please create a stackblitz example as I cannot access your codeSandbox.
<img width="542" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/9749730/04b367b2-3a52-43d9-be7f-9bf166de0cd8">
