### ISSUE TITLE
Form: FormItems does not have a consistent width

### ISSUE THREAD

**Issue by mathlizee** [SAP/ui5-webcomponents-react#553]
Hello,

I'm currently using a form that is similar to [this one](https://codesandbox.io/s/keen-keldysh-yem4f?file=/src/App.js). As you can see, the `FormItem` inside my `Form` do not have a consistent width. Would it be possible for all `FormItem` to have the maximum width available or, at least, to have a consistent overall width? It would be even nicer if there was a property to set the `FormItem`'s width according to the screen size (`S`, `M`, ...)

I'm using version `0.10.0-rc.1` of the library with Chrome.

Thanks!
Mathieu

**Comment by MarcusNotheis** [comment]
Hi @mathlizee,

I'm not sure if I understand the issue to 100%. As far as I can see in your code-sandbox, all FormItems using the maximum available width. The inner elements like Input, ComboBox, TextArea etc. all don't have a default width.
I think the easiest solution would we creating a style class like `fullWidth` (with `width: 100%`) and assign them to the individual elements. 

Does that work for you?

**Comment by mathlizee** [comment]
Hi @MarcusNotheis,

I feel a bit dumb not thinking about this before creating the issue! I modified my code sample to use `width: 100%` in the controls. It seems to work fine except for the `TimePicker` control, which doesn't seem to have the full width.

Could it be fixed?

Thanks again!
Mathieu

**Comment by MarcusNotheis** [comment]
Hi @mathlizee,
no worries :) Yes, the TimePicker should definitely be fixed - therefore I'll close this issue here and I've created a new issue on the UI5 Web Components repo for fixing this: https://github.com/SAP/ui5-webcomponents/issues/1738

Best regards,
Marcus
