### ISSUE TITLE
i18n related information

### ISSUE THREAD

**Issue by rkl1994** [SAP/ui5-webcomponents-react#554]
**Describe the documentation issue**

- [x] Documentation is unclear

**Description of the issue**
For ui5-webcomponents-react, to implement i18n functionality, is there any built-in i18n package to use or we can use any other popular i18n framework such as 'react-i18next'. Thanks

**Comment by MarcusNotheis** [comment]
Hi @rkl1994,

there is an internal API available for defining and using i18n texts, but the Web Component team hasn't made a final decision yet whether this API should be public or private. As soon as there is a final decision (hopefully until end of this week) we will either create a documentation page how our i18n setup can be reused/extended or share a receipt using e.g. `react-i18next`.

Related Web Components Issue: https://github.com/SAP/ui5-webcomponents/issues/1713

**Comment by rkl1994** [comment]
Hi @MarcusNotheis,

Is there any update for the final decision about i18n APIs. Thank you.

**Comment by MarcusNotheis** [comment]
Hey @rkl1994, the official API doc from UI5 Web Components should be available mid of this week.
While we are waiting for the offical doc, here is how to handle i18n files with WebComponents for React:

1. You need to have your translation in json files.
   Example:
   ```json
   {
     "CANCEL":"Cancel"
   }
   ```
2. You need something like a "default" language, in our case english and bundle those assets in another file:
   ```js
   export const CANCEL = { key: 'CANCEL', defaultText: 'Cancel' };
   ```
3. Register your assets in your custom namespace:
    Now you have to register your i18n translations in your custom namespace. Example:
   ```js
   import { registerI18nBundle } from "@ui5/webcomponents-base/dist/asset-registries/i18n";
   import ar from "../assets/i18n/messagebundle_ar.json";
   import bg from "../assets/i18n/messagebundle_bg.json";
  
   registerI18nBundle("your-namespace", { ar, bg });
   ```
   This namespace will be reused for the custom hook in step 4.

4. Now you can consume our i18n hook:
   ```js
   import { useI18nText } from '@ui5/webcomponents-react-base/lib/hooks';
   import { CANCEL, SOME_OTHER_TEXT } from '../path/to/your/i18n/defaults';

   const myComponent = () => {
    ...
    const [cancelText, someOtherText] = useI18nText('your-namespace', CANCEL, SOME_OTHER_TEXT);
    ...
   }
   ```
   The API of this hook is:
   1st parameter: Namespace of the translations
   2nd to nth parameter: the keys from step 2 to translate.
   The hook will return an array of translated texts, ordered the same as the translation parameters.

**Comment by rkl1994** [comment]
Cool! Thanks a lot!
