### ISSUE TITLE
Analytical Table: column header checkbox misaligned

### ISSUE THREAD

**Issue by rchrdchn** [SAP/ui5-webcomponents-react#556]
**Describe the bug**
Analytical Table's column header checkbox is misaligned when compared to table's body cells checkboxes.

**To Reproduce**
1. Go to [Analytical Table documentation](https://sap.github.io/ui5-webcomponents-react/?path=/story/components-analytical-table--tree-table)
2. See Analytical Table column header checkbox design

**Expected behavior**
Analytical Table's column header checkbox should be misaligned to table's body cells checkboxes.

**Screenshots**
![analytical-table-misaligned](https://user-images.githubusercontent.com/11576789/83465653-744c6700-a429-11ea-900f-35d0fb0e7b27.png)

**UI5 Web Components for React Information**
Current version.

Operating System: MacOS

Browser:

- Firefox 76.0.1 (64-bit)
- Safari Version 13.1 (15609.1.20.111.8)
- Chrome Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by Lukas742** [comment]
Hi @rchrdchn 

this was fixed in `@ui5/webcomponents-react@0.9.10` (https://github.com/SAP/ui5-webcomponents-react/issues/532)

I will close this issue now, but feel free to re-open if something is unclear :)
