### ISSUE TITLE
AnalyticalTable: groupBy resets after table data is changed

### ISSUE THREAD

**Issue by adeptb** [SAP/ui5-webcomponents-react#557]
**Describe the bug**
Group reset after data prop is changed in AnalyticalTable

**Isolated Example**
https://codesandbox.io/s/throbbing-cookies-20jyg?file=/src/App.js

**To Reproduce**
1. Set group
2. Change table data
3. Table resets group 

**Expected behavior**
Group didnt reset

**UI5 Web Components for React Information**
`@ui5/webcomponents` 1.0.0-rc.7
`@ui5/webcomponents-react` 0.9.11
Operating System: OSX
Browser: Chrome 81.0.4044.129

![Jun-02-2020 14-01-06](https://user-images.githubusercontent.com/9465033/83512882-8dacec00-a4d9-11ea-95f5-c388ea06040a.gif)

**Comment by MarcusNotheis** [comment]
Hi @adeptb,

I think you are looking for a recipe `like [this one](https://github.com/tannerlinsley/react-table/blob/master/docs/faq.md#how-do-i-stop-my-table-state-from-automatically-resetting-when-my-data-changes) right?
By setting `<AnalyticalTable columns={X} data={Y} reactTableOptions={{autoResetGroupBy: false}} ` you can turn off automatic group by resets.

I think we should add this to our documentation as well.

**Comment by MarcusNotheis** [comment]
Documentation is now available at: https://sap.github.io/ui5-webcomponents-react/master/?path=/docs/components-analytical-table--default-table#how-do-i-stop-my-table-state-from-automatically-resetting-when-my-data-changes
