### ISSUE TITLE
MultiComboBox: Parent jumping height

### ISSUE THREAD

**Issue by adeptb** [SAP/ui5-webcomponents-react#558]
**Describe the bug**
After selecting first item/deselecting last item in MultiComboBox - parent div with display: block changes it height

**Isolated Example**
[example](https://codesandbox.io/s/spring-microservice-97xbc?file=/src/App.js)

**To Reproduce**
1. Select item in MultiComboBox
2. Check parent div height

**Expected behavior**
Height of parent div didnt change

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.7
`@ui5/webcomponents-react` version: 0.9.11
Operating System: OSX
Browser: Chrome 81.0.4044.129

**Additional context**
![Jun-02-2020 13-51-33](https://user-images.githubusercontent.com/9465033/83512347-c13b4680-a4d8-11ea-9593-051271480aef.gif)

**Comment by MarcusNotheis** [comment]
This component is developed by our UI5 Web Components colleagues, so I've created an issue on their repo: https://github.com/SAP/ui5-webcomponents/issues/1719

**Comment by MarcusNotheis** [comment]
Hey @adeptb,
I'm going to close this issue as I have created a new issue in the ui5-webcomponents repository that will cover the issue described here. (SAP/ui5-webcomponents#1719)

Best regards,
Marcus
