### ISSUE TITLE
Cant run application anymore 

### ISSUE THREAD

**Issue by monishchintala** [SAP/ui5-webcomponents-react#5585]
### Describe the bug

devDependencies": {
    "@babel/plugin-proposal-private-property-in-object": "^7.21.11",
    "@ui5/webcomponents": "^1.22.0",
    "@ui5/webcomponents-fiori": "^1.22.0",
    "@ui5/webcomponents-react": "^1.25.1",
    "gulp": "^4.0.2",
    "gulp-concat": "^2.6.1",
    "gulp-inline-source": "^4.0.0",
    "gulp-replace": "^1.1.3",
    "react": "18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "sass": "^1.69.5",
    "web-vitals": "^3.5.2"
  }

and getting these error on yarn run start
![Screenshot (1)](https://github.com/SAP/ui5-webcomponents-react/assets/88500256/f884e6fd-861f-4240-8519-0f5067a9f042)

ERROR in ./node_modules/@ui5/webcomponents-react-base/dist/hooks/useIsRTL.js 3:0-68
Module not found: Error: Can't resolve '@ui5/webcomponents-base/dist/config/RTL.js' in 'C:\Users\Monish.Chintala\Documents\stmnt_dsgnr\node_modules\@ui5\webcomponents-react-base\dist\hooks'

### Reproduction steps

1.
2.
3.
...

### UI5 Web Components for React Version

1.25.1

### UI5 Web Components Version

1.22.0

### Browser

Chrome

### Operating System

windows 10

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by monishchintala** [comment]
seems like the rtl.js file is missing in this path "@ui5/webcomponents-base/dist/config" ,
<img width="182" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/88500256/8ed83ad4-a049-4515-8987-2c9ecfd6e1a5">

**Comment by sai-kola** [comment]
we also facing the same issue, i tried downgrading the version still issue is showing

**Comment by Lukas742** [comment]
Hi @monishchintala 

please add a reproducible example, preferably by using this [StackBlitz](https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx) template.

**Comment by monishchintala** [comment]
Hi **@Lukas742** ,

I can't able to replicate the issue in the [StackBlitz](https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx) template.

but when I am trying Npm instead of yarn , application is running fine. but due to some complications, i need to use the yarn workspace.

**Comment by MarcusNotheis** [comment]
I would assume you have already updated `@ui5/webcomponents` and `@ui5/webcomponents-fiori` to `1.23.0` due to the `^1.22.0` dependency. We haven't released our wrapper yet to support the new version, and this should also be logged as peer dependency warning.
I would suggest to change your dependency to:
```
"@ui5/webcomponents": "~1.22.0",
"@ui5/webcomponents-fiori": "~1.22.0",
"@ui5/webcomponents-react": "~1.25.1",
```
Then your application should start without any issues again

**Comment by monishchintala** [comment]
Thanks **@MarcusNotheis**  ,
     we have changed the  @ui5/webcomponents and @ui5/webcomponents-fiori  as suggested ,Now the application is working fine.
