### ISSUE TITLE
Analytical Table: Set Visible Columns for Different Screen Sizes

### ISSUE THREAD

**Issue by mathlizee** [SAP/ui5-webcomponents-react#562]
Hi,

When using an Analytical Table, is it possible to hide different columns depending on the screen size used by the user? Currently, all columns are shown regardless of the screen size.

Dekstop:

![AnalyticalTableDesktop](https://user-images.githubusercontent.com/15334138/83980986-f33d1600-a8e7-11ea-9673-ade6f88b551a.png)

Mobile:

![AnalyticalTableMobile](https://user-images.githubusercontent.com/15334138/83980989-f6d09d00-a8e7-11ea-822c-92564ff73b06.png)

It would be nice if we could display the first 2 columns on mobile devices, the first 4 on tablets and all columns on desktop, for example. 

I assume this is not currently possible since I looked at the documentation and didn't see any property in the column definition that could provide such a functionality. If it is possible, it should be added to the Analytical Table documentation and if not, could it be implemented?

Thanks!
Math

**Comment by MarcusNotheis** [comment]
Hey @mathlizee,

I think what you try to achieve is already possible using the `useViewportRange` hook in combination with a localState:

```jsx
import React, { useState, useEffect } from 'react';
import { AnalyticalTable } from '@ui5/webcomponents-react/lib/AnalyticalTable';
import { useViewportRange } from '@ui5/webcomponents-react-base/lib/hooks';

const columns = [{}, {}, {}, {}, ...]; /* your full set of columns*/
const data = []; /* your data array */

export const ResponsiveTable = () => {
  const [responsiveColumns, setResponsiveColumns] = useState(columns);
  const currentRange = useViewportRange('StdExt');
  useEffect(() => {
    if (currentRange === 'Phone') {
      setResponsiveColumns(columns.slice(0, 2));
    } else if (currentRange === 'Tablet') {
      setResponsiveColumns(columns.slice(0, 3));
    } else {
      setResponsiveColumns(columns);
    }
  }, [currentRange]);
  return <AnalyticalTable columns={responsiveColumns} data={data} title="ResponsiveTable" />;
};

Let me know if this works for you, then I can add it to our docs as recipe.

Best regards,
Marcus

**Comment by mathlizee** [comment]
Hi @MarcusNotheis,

Thank you for your response. It worked like a charm!

Math

**Comment by MarcusNotheis** [comment]
Documentation of that recipe is now available at https://sap.github.io/ui5-webcomponents-react/master/?path=/docs/components-analytical-table--default-table#how-can-i-show-a-subset-of-all-columns-on-mobile-devices
