### ISSUE TITLE
[SF][FileUploader]: onChange cannot be triggered

### ISSUE THREAD

**Issue by summer2200** [SAP/ui5-webcomponents-react#5631]
### Describe the bug

After upgrading to 1.26.1, FileUploader's onChange event cannot be triggered, nothing happens by clicking the component. Example provided in https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-fileuploader--docs also not working.

### Isolated Example

https://codesandbox.io/p/sandbox/file-uploader-wjgqz6?file=%2Fsrc%2FApp.js%3A7%2C26

### Reproduction steps

Click on FileUploader, nothing happens.

### Expected Behaviour

File selecting window should be opened after clicking FileUpload if onChange event is provided.

### UI5 Web Components for React Version

1.26.1

### UI5 Web Components Version

1.23.1

### Browser

Chrome

### Operating System

macOS Sonoma 14.3.1

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @summer2200 

we moved to [StackBlitz](https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx) as our preferred web IDE/sandbox as it's not possible anymore to edit codeSandboxes with a free plan.

I tried to reproduce the issue in our Storybook and via [StackBlitz](https://stackblitz.com/edit/github-8egkpe?file=src%2FApp.tsx) but for me the behavior seems to work as intended. Please add a reproducible example via StackBlitz as I don't have access to your codeSandbox.

**Comment by summer2200** [comment]
Hi @Lukas742 , same sample has been added here https://stackblitz.com/edit/github-hhuuw5?file=src%2Fmain.tsx, also I have changed the access to public of provided sandbox.

Also tried official website example, still not working https://sap.github.io/ui5-webcomponents-react/?path=/docs/inputs-fileuploader--docs

**Comment by Lukas742** [comment]
Please add steps to reproduce the issue, because for me it's still working, both in your example and in our Storybook:

https://github.com/SAP/ui5-webcomponents-react/assets/9749730/1877bd99-d37c-418d-9a1d-653880155b2f

Also, it seems that making the codeSandbox public did not work:

<img width="626" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/9749730/b649e09c-eaf3-4f5c-aa68-e302861eadaa">

**Comment by summer2200** [comment]
@Lukas742  Just tried the same with another browser then it's working...there must be some settings in my Chrome blocking the selecting file window.

Thank you so much for your time!

**Comment by summer2200** [comment]
Upgrading Chrome to the latest resolves this problem.

**Comment by Lukas742** [comment]
Glad to hear :) 

I found, that there is also a Chromium bug report for this behavior: https://issues.chromium.org/issues/330663542: https://issues.chromium.org/issues/330663542
