### ISSUE TITLE
Analytical Table: IE11 shows error on row selection

### ISSUE THREAD

**Issue by gurkirpalgill** [SAP/ui5-webcomponents-react#565]
**Remove Analytical table dependency on proxy**
Using IE11, when clicking on the first column checkbox an error is generated.
e.g.
![Screen Shot 2020-06-09 at 11 08 15 PM](https://user-images.githubusercontent.com/65705637/84233849-03035880-aaa8-11ea-880c-aedb061aebdd.png)

**Expected behavior**
If possible please remove the dependency on proxy.

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 0.21.1
`@ui5/webcomponents-react` version: 0.100.0
Operating System: Windows 10
Browser: IE 11

**Comment by MarcusNotheis** [comment]
Just released `0.100.1` without the proxy API
