### ISSUE TITLE
Sticky header for Analytical table

### ISSUE THREAD

**Issue by gurkirpalgill** [SAP/ui5-webcomponents-react#567]
**Analytical table header row is always visible when user scrolls vertically**
Is it possible to always show the header row when user is scrolling vertically. e.g.

![Screen Shot 2020-06-09 at 11 51 36 PM](https://user-images.githubusercontent.com/65705637/84236365-5e374a00-aaac-11ea-8a35-a421380e6a13.png)

**Comment by MarcusNotheis** [comment]
Hi @gurkirpalgill,

the header should be sticky by default in this component.
You can set the `visibleRow` props to a fixed number (e.g. 10) and this will then act as a window on all your rows. Live Demo: https://sap.github.io/ui5-webcomponents-react/master/iframe.html?id=components-analytical-table--default-table

**Comment by MarcusNotheis** [comment]
Resolved via chat. Setting `minRows` and `visibleRows` to a fixed number solved this issue.
