### ISSUE TITLE
[Analytical Table > Subcomponents]: Dropdown Placeholder is rendered in all cells

### ISSUE THREAD

**Issue by gitgdako** [SAP/ui5-webcomponents-react#5681]
### Describe the bug

In the Analytical Table when using subcomponents an empty placeholder is rendered in all cells, but that has a width which indents the content
<span class="ExpandableIndicatorStyles-nonExpandableCellSpacer-0-2-160 ExpandableIndicatorStyles-withExpandableButton-0-2-161" style="padding-inline-start: 0px;"></span>
.ExpandableIndicatorStyles-nonExpandableCellSpacer-0-1-146 {
  width: var(--_ui5wcr-AnalyticalTableExpandIndicatorWidth);
}

Our fix:
[class*='AnalyticalTable-tableCell']:not([data-column-index='0']) [class*='ExpandableIndicatorStyles-nonExpandableCellSpacer'] {
    display: none !important
}

Interestingly in our project the values in the first column without a dropdown button are porperly indented but in your storybook it is not

webcomponents 1.22.0 with webcomponents-react 1.25.1 did not have this issue

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/story/data-display-analyticaltable--subcomponents

### Reproduction steps

Analytical Table with subcomponent and multiple columns

### Expected Behaviour

No placeholder is rendered in all but the first columns
In the first column values without the dropdown still are indented the same distance

### UI5 Web Components for React Version

1.26.1

### UI5 Web Components Version

1.23.1

### Browser

Chrome

### Operating System

Windows 11

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @gitgdako 

the issue was fixed with this [PR](https://github.com/SAP/ui5-webcomponents-react/pull/5634) ([next release docs](https://sap.github.io/ui5-webcomponents-react/main/?path=/story/data-display-analyticaltable--subcomponents)). We will publish it with our next release.
