### ISSUE TITLE
Charts: Request for BubbleChart new feature

### ISSUE THREAD

**Issue by mishsamb** [SAP/ui5-webcomponents-react#570]
I really like UI5 WebComponents for React. I wanted to use the UI5 BubbleChart in my project, but it is not currently available. Initially the chart was developed using recharts, but since we are moving to UI5 react, I need this Bubble Chart feature to be implemented immediately.
It would be great if you could make it available along with the other scatter charts.

**Comment by MarcusNotheis** [comment]
Released in `@ui5/webcomponents-react-charts@0.10.0-rc.5`, documentation is available [here](https://sap.github.io/ui5-webcomponents-react/master/?path=/docs/charts-scatterchart--render-story).

**Comment by mishsamb** [comment]
Thanks a ton for implementing this feature! 
Now I can implement my recharts scatter plot using UI5 react.
