### ISSUE TITLE
Internet Explorer: After applying polyfill app still have issues

### ISSUE THREAD

**Issue by lpohren** [SAP/ui5-webcomponents-react#571]
**Describe the bug**
This is probably more a question then a bug.
We understand you don't support IE, but also noticed that implementing polyfill it should make the experience better.
What we noticed is that even after implementing it, the application still keeps a lot a bugs.
Is this expected?

**Isolated Example**
*Please provide an isolated example if possible by forking [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34).*

**To Reproduce**
1. Implement IE
2. Explore the app

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/16123699/84382784-8b295100-abc1-11ea-8465-3691be3bfccf.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.7
`@ui5/webcomponents-react` version: 0.9.4
Operating System: Windows
Browser: Internet Explorer

**Additional context**

**Comment by MarcusNotheis** [comment]
Hey @lpohren,

I remember we chatted about that issue. Do you need any further action from our side or can we close this issue?

Best regards,
Marcus

**Comment by lpohren** [comment]
We can close it.
Thanks Marcus!
