### ISSUE TITLE
AnalyticalTable: scroll bar disappear when exceed table visible row

### ISSUE THREAD

**Issue by ggfer** [SAP/ui5-webcomponents-react#572]
**Describe the bug**
as title

**Isolated Example**
set-prop visibleRows={15}, data={tableData}
`if tableData.length > 15, scroll bar disappear.`

**Screenshots**
![image](https://user-images.githubusercontent.com/19473701/84487846-f2362b00-acd1-11ea-9c34-bc916fd14c5c.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: "^1.0.0-rc.7",
`@ui5/webcomponents-react` version: "0.9.11" or 0.10.0-rc2
Operating System:
Browser: chrome

**Comment by MarcusNotheis** [comment]
Hey @ggfer,
could you please share a reproducible sample using [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34)?
We just tried to reproduce it and in our case the scrollbar was always visible when we had more rows than visibleRows.

Thanks!

**Comment by ggfer** [comment]
> Hey @ggfer,
> could you please share a reproducible sample using [this codesandbox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34)?
> We just tried to reproduce it and in our case the scrollbar was always visible when we had more rows than visibleRows.
> 
> Thanks!

https://codesandbox.io/s/suspicious-chebyshev-cwdl1?fontsize=14&hidenavigation=1&theme=dark

**Comment by MarcusNotheis** [comment]
Hey @ggfer,
I think you missed to wrap your app (or at least the codesandbox example) into the ThemeProvider component. That's why the scrollbar is missing.

If you wrap the App into the `ThemeProvider`, the scrollbar behaves correctly: https://codesandbox.io/s/thirsty-violet-76uo4?file=/src/App.js

Does that work for you?

**Comment by MarcusNotheis** [comment]
Closing this issue. In case you are still having issues with the scrollbar, please feel free to reopen it.
