### ISSUE TITLE
MessageBox: Title and actions button text is not translated

### ISSUE THREAD

**Issue by lateefsofi** [SAP/ui5-webcomponents-react#5745]
### Describe the bug

We have an incident where MessageBox Title and action buttons text is not translated in other languages like "Finnish"

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

MessageBox Title and action buttons text should be translated in other languages

### Screenshots or Videos

![image](https://github.com/SAP/ui5-webcomponents-react/assets/18447407/4e482579-c214-403a-b73e-cd769969fe8a)

### UI5 Web Components for React Version

1.23.3

### UI5 Web Components Version

1.20.0

### Browser

Chrome

### Organization
Successfactors

_No response_

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @lateefsofi 

I couldn't reproduce the issue. Please add a reproducible example, preferably by using this [StackBlitz](https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx) template.

**Comment by lateefsofi** [comment]
Looks this is an issue from Application side. We have a missing import `import "@ui5/webcomponents-react/dist/Assets";`. Now translation is working
