### ISSUE TITLE
Analytical Table: Hovering and Resizing columns border color

### ISSUE THREAD

**Issue by rchrdchn** [SAP/ui5-webcomponents-react#580]
**Describe the solution you'd like**
Whole column cell border should have active color when hovering over and/or resizing column - similar to [SAP UI5 Smart Table](https://sapui5.hana.ondemand.com/#/entity/sap.ui.comp.smarttable.SmartTable/sample/sap.ui.comp.sample.smarttable).

**Additional context**
![Screen Shot 2020-06-18 at 15 39 00](https://user-images.githubusercontent.com/11576789/85183609-2913c000-b241-11ea-9dfb-4d2de7870a12.png)

**Comment by MarcusNotheis** [comment]
Released in `@ui5/webcomponents-react@0.10.0-rc.9`.
