### ISSUE TITLE
[Dynamic Page]: Floating footer does not always scroll

### ISSUE THREAD

**Issue by skowrons** [SAP/ui5-webcomponents-react#5801]
### Describe the bug

The floating footer will sometimes stop scrollen when a normal `DynamicPage` with a form is to large for the screen. This happens mostly on mobile and really consistent on mobile but it currently also happens on larger screens.

The provided example does not really showcase my error but also shows another problem with the height (scroll down and see the bar jumping).

### Isolated Example

https://stackblitz.com/edit/github-xww5ig?file=src%2FApp.tsx

### Reproduction steps

The error can not be reproduced all the time but only happens if the form is larger than the current screen and the user is scrolling.

### Expected Behaviour

The floating footer should scroll to the of the page.

### Screenshots or Videos

<img width="769" alt="Bildschirmfoto 2024-05-14 um 11 00 51" src="https://github.com/SAP/ui5-webcomponents-react/assets/61137799/9677efb5-60db-4f52-b8f0-a64275bf5f45">

### UI5 Web Components for React Version

1.28.1

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @skowrons 

the DynamicPage is a [page layout](https://experience.sap.com/fiori-design-web/dynamic-page-layout/) and should include the whole viewport. Therefore, it's generally recommended to use a non-content-based height, but when utilizing a footer, it's mandatory. This requirement is also outlined in our documentation:

> React element which defines the footer content.
>
>Note: To preserve the intended design, please use only non-content based height values (px, rem, vh, etc.) as height of the DynamicPage.




Here you can find an example including a fixed height: https://stackblitz.com/edit/github-xww5ig-7tabyh?file=src%2FApp.tsx
