### ISSUE TITLE
[FormItem]: [Type "FormItemContent" is not exported]

### ISSUE THREAD

**Issue by gregor-vag** [SAP/ui5-webcomponents-react#5802]
### Describe the bug

"@ui5/webcomponents-react" does not export "FormItemContent"

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

"FormItemContent" is exported by "@ui5/webcomponents-react" for customized components

### Screenshots or Videos

![image](https://github.com/SAP/ui5-webcomponents-react/assets/157693975/0ff406cb-6ce2-41f3-9e69-48531a1f0d56)

### UI5 Web Components for React Version

1.28.1

### UI5 Web Components Version

1.24.3

### Browser

Chrome

### Operating System

Windows 11

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @gregor-vag 

We only publicly export types intended for reuse. In this case, `FormItemContent` is a prop type that is typically reused by accessing the type via index. ([See Indexed Access Types](https://www.typescriptlang.org/docs/handbook/2/indexed-access-types.html)) The main advantage of this approach is that the type reflects the actual type of the prop. Therefore, if we'd decide to extend the prop or type (e.g., `children: FormItemContent | number;`), this extension would also be reflected in your app. However, if you directly use `FormItemContent`, `number` wouldn't be supported.
