### ISSUE TITLE
[ObjectStatus]: Even after having the stateAnnouncementText defined the Screen reader reads the default message

### ISSUE THREAD

**Issue by achuth2912** [SAP/ui5-webcomponents-react#5806]
### Describe the bug

When we use the stateAnnouncementText defined on the objectStatus component the default message is still announced read by screen readers.
Ideally the string defined on the stateAnnouncementText must be read, instead it reads the whole default message coming from the ObjectStatus Component.

Refer the link below:
Modify Control to Error
active to true
enter some string for stateAnnouncementText

Current Behaviour: 
The screen reader reads out the default message followed by the string defined on the stateAnnouncementText

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-objectstatus--docs

### Reproduction steps

1. Hit the url https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-objectstatus--docs
2. Modify Control to Error
3. active to true
4. enter some string for stateAnnouncementText

### Expected Behaviour

Ideally the screen reader must announce only the string defined on the stateAnnouncementText for ObjectStatus Component.

### Screenshots or Videos

![MicrosoftTeams-image (61)](https://github.com/SAP/ui5-webcomponents-react/assets/71249041/c81ac395-2c5a-4d02-b081-622467b22c46)

![MicrosoftTeams-image (62)](https://github.com/SAP/ui5-webcomponents-react/assets/71249041/c4fed36d-c28e-4481-8d84-167118df3030)

### UI5 Web Components for React Version

1.23.0

### UI5 Web Components Version

1.20.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @achuth2912 

the `ObjectStatus` should always announce that i's an ObjectStatus, including its content and state (except when the state is "None"). The linked PR will remove the announcements for default icons (such as "Error") because this information is already included in the state announcement. Other aspects will remain unchanged, as they are implemented according to our central a11y guidelines.
