### ISSUE TITLE
AnalyticalTable: Accessibility: Column settings popover does not close on focus out.

### ISSUE THREAD

**Issue by abhijeet181088** [SAP/ui5-webcomponents-react#5821]
### Describe the bug

Settings popover of a column does not close on focus out from the popover. 
Settings header of multiple popovers can be open simultaneously. 

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/story/data-display-analyticaltable--tree-table

### Reproduction steps

1. Bring focus on the first column header of the table by clicking or using tab key
2. Press ENTER, settings popover opens up (where user can sort, search, etc.)
3. Press "TAB", focus goes to "Actions" column button of some random row.
4. Use Up arrow key to navigate to header of some other column, press "ENTER"
5. Settings popover is shown for this column
6. Settings popover for first column's header does not close automatically

### Expected Behaviour

Settings popover of column's header should close on focus out. 
Settings popover of multiple columns should not remain open simultaneously.

### Screenshots or Videos

![Screenshot 2024-05-21 at 9 26 28 AM](https://github.com/SAP/ui5-webcomponents-react/assets/26282517/e884a10b-119f-4ab3-b6b7-75f019f2ff54)

### UI5 Web Components for React Version

1.28.1

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Operating System

macOS

### Additional Context

This is reproducible in https://sap.github.io/ui5-webcomponents-react/?path=/story/data-display-analyticaltable--tree-table example page and in our SAP application as well.
But not reproducible in stackblitz.

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @abhijeet181088 

the focus should not escape the popover while it's opened. The linked PR will fix this issue. Thanks for bringing it to our attention!
After the PR is merged and released, a user cannot focus out the popover via tabbing and only when the popover is closed (by selecting an option, clicking outside or pressing ESC) the keyboard navigation of the table takes over again.
