### ISSUE TITLE
[RadioButton - RadioButton Groups ]: [its not grouping the radiobutton and their label and their mail title]

### ISSUE THREAD

**Issue by vaitheeswari21** [SAP/ui5-webcomponents-react#5823]
### Describe the bug

I have attached a screenshot below in screenshots

In radiobutton groups, its not grouping the radiobutton and their label and their mail title

Link: https://sap.github.io/ui5-webcomponents-react/?path=/story/inputs-radiobutton--radio-button-groups

### Reproduction steps

1. 
2.
3.
...

### Screenshots or Videos

<img width="733" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/42770037/e542c559-e920-4512-9806-9074cb609baf">

### UI5 Web Components for React Version

1.28.1

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Operating System

windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @vaitheeswari21 

unfortunately I don't understand where you see a problem, in the screenshot you posted there's both a vertical and horizontal group of `RadioButton`s which are grouped by the `name` prop. Please provide more details or clarify what specific issue you are encountering so that we can assist you.

**Comment by vaitheeswari21** [comment]
@Lukas742 You can take a horizontal group ,

In that its not reading like option a of horizontal groups  like that.

Currently just announcing like options a alone.

I hope you understood my concern

Thanks

**Comment by Lukas742** [comment]
So, I take it that it's an accessibility issue you're concerned about?
I checked and in my opinion the screen reader announcement for `RadioButton`s inside a group are correct. Only our example needed some improvement. The linked PR will add the `radiogroup` role and a label to the container of each group. Please note, that these attributes should be added by app developers, as we don't offer any group/container component for radio button groups.

**Comment by vaitheeswari21** [comment]
@Lukas742  yes this is an accessibility issue.

Could you please send me that Pr where you changed your opinion?

**Comment by Lukas742** [comment]
It's shown directly above my previous comment and also linked to this issue 😉 

https://github.com/SAP/ui5-webcomponents-react/pull/5825
