### ISSUE TITLE
[DatePicker]: [not respect language change in application]

### ISSUE THREAD

**Issue by piotrmarkiewicz1** [SAP/ui5-webcomponents-react#5830]
### Describe the bug

DatePicker only takes language from browser, but when I change application language by using i18n.changeLanguage it's not changing language

### Reproduction steps

In react app, change language by setting i18n.changeLanguage to something different that default language in browser

### Expected Behaviour

use selected language

### UI5 Web Components for React Version

"@ui5/webcomponents-react": "^1.28.1",

### UI5 Web Components Version

"@ui5/webcomponents": "^1.24.3",

### Browser

Chrome

### Operating System

mac os

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @piotrmarkiewicz1 

please add a reproducible example, preferably by using this [StackBlitz](https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx) template.

**Comment by piotrmarkiewicz1** [comment]
example added

**Comment by Lukas742** [comment]
> example added

Did you perhaps forget to add the link?

**Comment by pmarkiewicz** [comment]
here is sample repo
https://github.com/pmarkiewicz/ui5-datapicker-issue
