### ISSUE TITLE
[DynamicPageTitle]: No Gap Between Buttons in Custom Actions Component in DynamicPageTitle

### ISSUE THREAD

**Issue by bomasap** [SAP/ui5-webcomponents-react#5873]
### Describe the bug

There is an issue with the `DynamicPageTitle` component's `actions` property when using a custom actions component. The custom actions component, which includes two buttons, does not display a gap between the buttons when placed in the `actions` property. However, placing the two buttons directly in the actions property does result in the correct gap between them.

According to another related bug (https://github.com/SAP/ui5-webcomponents-react/issues/5863), this issue is mentioned in the context of a `slot`. However, the custom actions component does not have a slot in its props.

### Isolated Example

https://stackblitz.com/edit/github-zwueh7-t5uuzk?file=src%2FApp.tsx,src%2FCustomActions.tsx

### Reproduction steps

1.Place the custom actions component in the actions property of the DynamicPageTitle component. Observe the lack of gap between the two buttons. https://stackblitz.com/edit/github-zwueh7-t5uuzk?file=src%2FApp.tsx,src%2FCustomActions.tsx
2. Place the two buttons directly in the actions property of the DynamicPageTitle component. Observe the presence of a gap between the buttons. https://stackblitz.com/edit/github-zwueh7-weexue?file=src%2FApp.tsx

### Expected Behaviour

When the custom actions component is placed in the `actions` property of the `DynamicPageTitle`, there should be a gap between the buttons, similar to when the buttons are placed directly in the actions property.

### Screenshots or Videos

<img width="737" alt="Screenshot 2024-05-30 at 3 08 10 PM" src="https://github.com/SAP/ui5-webcomponents-react/assets/169193249/7f1943ec-48d1-42cd-b7a1-cb6f743d3d3f">
<img width="685" alt="Screenshot 2024-05-30 at 3 08 05 PM" src="https://github.com/SAP/ui5-webcomponents-react/assets/169193249/47eb991d-79bb-4716-b3e6-1bee4b8fe0a6">

### UI5 Web Components for React Version

1.28.0

### UI5 Web Components Version

1.24.0

### Browser

Chrome, Edge, Firefox, Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @bomasap 

custom components that render multiple elements are currently not supported as `actions` of the `DynamicPageTitle`. You can find out more about this [here](https://github.com/SAP/ui5-webcomponents-react/issues/4780#issuecomment-1604105567). 

The linked PR will outline this in our docs. For updates please subscribe to the corresponding [feature request](https://github.com/SAP/ui5-webcomponents-react/issues/4780).
