### ISSUE TITLE
[FlexBox]: FlexBox will unexpectedly remove stylesheet.

### ISSUE THREAD

**Issue by allen138** [SAP/ui5-webcomponents-react#5882]
### Describe the bug

Similar to, https://github.com/SAP/ui5-webcomponents-react/issues/5730, The flexbox component relies on CSS styles generated via `useStylesheet`, [FlexBox/index.tsx#L71](https://github.com/SAP/ui5-webcomponents-react/blob/main/packages/main/src/components/FlexBox/index.tsx#L71). But when one or more instances are on the page, when the component unmounts, the flexbox remaining will lose all styles. I presume the solution in #5730 will be the same here. But consider doing this for all components that use the constructed stylesheets.

Thanks!

### Reproduction steps

Its a little hard to reproduce this in a single core template like a stackblitz. If you need to replicate it, please reach out in our private slack channel for the environment details.

### UI5 Web Components for React Version

main

### UI5 Web Components Version

main

### Browser

Chrome

### Organization

SF

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MarcusNotheis** [comment]
As discussed via Slack, please try to update to 1.28.4 which should solve the issue.

**Comment by MarcusNotheis** [comment]
Closing the issue, resolved via Slack.
