### ISSUE TITLE
[AnalyticalTable]: [In entire application for ‘XX’ column header within ‘XX’ table, 4 sided borders are not properly visible, it is visible in dotted border for the users and when we selecting any header row only 3 sided border are visible.]

### ISSUE THREAD

**Issue by jadhavarjun** [SAP/ui5-webcomponents-react#5898]
### Describe the bug

In entire application for ‘XX’ column header within ‘XX’ table, 4 sided borders are not properly visible, it is visible in dotted border for the users and when we selecting any header row only 3 sided border are visible.

Link: https://sap.github.io/ui5-webcomponents-react/?path=/story/data-display-analyticaltable--default&args=sortable:!false;filterable:!false;groupable:!false&globals=theme:sap_horizon_hcb

Reproduction steps:
1. After clicking on link choose Horizon High Contrast Black/Horizon High Contrast White Theme 
2. Click on any table row data you will able to see the selected that selected text 4 sided borders are not properly visible, it is visible in dotted border.

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

User should be able to see 4-sided borders for the UIs and the focus should be strong for all the corners.

### Screenshots or Videos

<img width="509" alt="image" src="https://github.com/SAP/ui5-webcomponents-react/assets/66779051/256dee9b-0cc9-4d1a-ab1f-c5b4eec36dea">

### UI5 Web Components for React Version

^1.16.3

### UI5 Web Components Version

^1.14.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by jadhavarjun** [comment]
Hi @Lukas742, 

As you merged the PR (#5944 ) but the issue is still not resolved, Still 4 sided borders are not properly visible, it is visible in dotted border.

**Expected behavior**:  User should be able to see 4-sided borders for the UIs and the focus should be strong for all the corners.

<img width="491" alt="border issue 1" src="https://github.com/SAP/ui5-webcomponents-react/assets/66779051/e569dd64-adde-43f8-8b9f-b60dd4846c05">

**Comment by Lukas742** [comment]
Hi @jadhavarjun 

merging a PR only means that the commit made it's way to our codebase, not that it has been published. So, the fix will only be available with our next release.

**Comment by sanjayC5373903** [comment]
Hi @Lukas742 Could you please let me know when it will next release. and after release what should necessary changes we need to do from our site.

**Comment by Lukas742** [comment]
Hi @sanjayC5373903 

we will most likely release a new version tomorrow or early next week.
Since this is only bug fix, all you need to do is update your dependencies. :)

**Comment by Lukas742** [comment]
Hi @sanjayC5373903 

the fix is available in both version [1.29.3](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v1.29.3) and our pre release version [2.0.0-rc.0](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v2.0.0-rc.0), so to test it you have to update your dependencies.

**Comment by Lukas742** [comment]
Yes, the changes are there. The focus border now uses the correct offset in every theme and is not overlapping the cell border (e.g. when focused) anymore.
Could you elaborate on what fix you expected?
