### ISSUE TITLE
AnalyticalTable: TreeTable minRows, visibleRows

### ISSUE THREAD

**Issue by Sepper007** [SAP/ui5-webcomponents-react#593]
Describe the bug
When the AnalyticalTable is used with isTreeTable, minRows={10}, visibleRows={10} and the root level of data Array is < 10, there will always be empty rows, even if the tree table is collapsed

Expected behavior
Empty rows disappear, as soon as the number of rows is bigger or equals than the minRows value

Screenshots
![TreeTable_1](https://user-images.githubusercontent.com/22964016/87344720-c3df8180-c503-11ea-8686-073ba0b84dc4.jpeg)
![TreeTable_2](https://user-images.githubusercontent.com/22964016/87344724-c641db80-c503-11ea-83bd-a9f86ee3887b.jpeg)

UI5 Web Components for React Information
@ui5/webcomponents ^1.0.0-rc.7:
@ui5/webcomponents-react "0.9.11:
Operating System:MacOS Catalina
Browser:Chrome

**Comment by MarcusNotheis** [comment]
Hey @Sepper007,

I think this works as designed because it will always render ten rows as defined in the props.
You could also set `minRows` to `1`, then you would have the desired behaviour. (but this will cause your tree table to jump when you expand/collapse the nodes).

**Comment by Sepper007** [comment]
Hey Marcus, thanks for your quick response. I now set the minRows to 1 and wrapped this div around the AnalyticalTable
<div style={{ width: '900px', height: 'calc(11 * var(--sapWcrAnalyticalTableRowHeight))' }}>
to make sure, that there's no jumping when the table is expanded and collapsed
