### ISSUE TITLE
AnalyticalTable: TreeTable Selection in SingleRow Selection Mode

### ISSUE THREAD

**Issue by Sepper007** [SAP/ui5-webcomponents-react#594]
Describe the bug
When the AnalyticalTable is used with isTreeTable and SelectionMode.SINGLE we sometimes experience, that multiple rows are marked as selected (see screenshot attached)

Expected behavior
Only one row is selected

Screenshots
![Profit_Center_screenshot](https://user-images.githubusercontent.com/22964016/87345178-89c2af80-c504-11ea-8964-b64b9fe10cb5.jpeg)

UI5 Web Components for React Information
@ui5/webcomponents ^1.0.0-rc.7:
@ui5/webcomponents-react "0.9.11:
Operating System:MacOS Catalina
Browser:Chrome

**Comment by MarcusNotheis** [comment]
hey @Sepper007,
could you create a reproducible sample for that issue using [this template](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34)? I tried with 0.9.11 as well as our latest version and was not able to reproduce the issue.

**Comment by MarcusNotheis** [comment]
Fixed and released in `@ui5/webcomponents-react@0.10.0-rc.9`.
