### ISSUE TITLE
Input: ValueStateMsg will be hidden if the message is very long

### ISSUE THREAD

**Issue by rkl1994** [SAP/ui5-webcomponents-react#595]
**Describe the bug**
When using the value state message, if the message is very long, it will be hidden.

**Isolated Example**
*Please provide an isolated example if possible.
https://codesandbox.io/s/bold-feather-kcc1g?file=/src/App.js

**Expected behavior**
Can it be like this in ui5-webcomponent?
https://sap.github.io/ui5-webcomponents/playground/components/Input/
<img width="218" alt="Screen Shot 2020-07-14 at 2 43 26 PM" src="https://user-images.githubusercontent.com/5527455/87393308-8e5c9600-c5e0-11ea-9a9d-7dca97963db2.png">

**Screenshots**
Now it is like this:
<img width="370" alt="Screen Shot 2020-07-14 at 2 41 55 PM" src="https://user-images.githubusercontent.com/5527455/87393348-a03e3900-c5e0-11ea-9cf8-115422d5aa84.png">

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:  1.0.0-rc.7
`@ui5/webcomponents-react` version: 0.10.0-rc.2
Operating System:
Browser:

**Additional context**

**Comment by MarcusNotheis** [comment]
Hi @rkl1994,

the issue in this case is that you have prevented the label wrap.
You can solve this issue by either allow the label to wrap:
```jsx
<Label wrap>This is a very very long long value state message</Label>
```
or by using a `div` as wrapper:
```jsx
<div>This is a very very long long value state message</div>
```

Is it now working as intented?

Best regards,
Marcus

**Comment by rkl1994** [comment]
Thanks, it works for me!
