### ISSUE TITLE
ui5-list warning "Provided item is not managed by ItemNavigation"

### ISSUE THREAD

**Issue by jamesPodo** [SAP/ui5-webcomponents-react#5951]
### Describe the bug

Currently, we use ui5 button inside of the CustomListItem to open popover menu. After we upgrade ui5wc = 1.23.3 and ui5wc-react = 1.26.2, opening the button inside of the list item occasionally throws console warning says "Provided item is not managed by ItemNavigation". Moreover, In our production build, we see TypeError: Cannot create property '__reactProps$lzhp7ra1b1' on string '[Circular ~]' and ui component get destroyed

Since the issue is only reproducible on the production build and is hard to trace down, I am not sure if this warning is the culprit of the issue. However, I only see the type error after seeing the itemNavigation warning. 

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

No error or warning is thrown upon interaction with button inside of custom list item

### Screenshots or Videos

![image](https://github.com/SAP/ui5-webcomponents-react/assets/144419170/b26f7847-52f7-49dd-a4de-471e90c577d3)

### UI5 Web Components for React Version

1.26.2

### UI5 Web Components Version

1.23.3

### Browser

Chrome

### Operating System

Mac OS

### Organization

SAP SE

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @jamesPodo 

 If I understand correctly, then you can only not reproduce the TypeError, right? So, could you please add an example for the `ItemNavigation` warning by leveraging this [StackBlitz](https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx) template?
