### ISSUE TITLE
Filter-bar : Screen reader should convey ‘Checked’ information for the checked checkbox and ‘Unchecked’ information for the unchecked checkbox both the information.

### ISSUE THREAD

**Issue by sanjayC5373903** [SAP/ui5-webcomponents-react#5979]
### Describe the bug

We are checked with latest version. Screen reader with filter dialog box open. and that dialog box inside for move on next we press Tab Key move arrow Key Up & Down key. but its not working its not moved. and when I am using spacebar for tryed to unchecked checkbox. its not working. It just read text label of checkbox. 

Without screen reader with arrow key selection is also working. with screen reader its not working.

We are checked Filterbar on https://sap.github.io/ui5-webcomponents-react

![Screenshot 2024-06-26 151340](https://github.com/SAP/ui5-webcomponents-react/assets/170628934/12ea73dd-85fa-4998-be37-0f085a654b41)
![Screenshot 2024-06-26 152349](https://github.com/SAP/ui5-webcomponents-react/assets/170628934/c819e195-66db-4daf-978e-a2aa0b41a56e)

### Reproduction steps

1. Open Jaws Screen reader. 
2. click on filter button. Open filter Dialog box.
3. Press Tab and move on First Row of Checkbox. 
4. Then press arrow key up and down. & check screen Reader history.

### Expected Behaviour

Screen Reader is read checkbox is checked information. selection of row should move up and down with arrow key.

### UI5 Web Components for React Version

~1.29.0

### UI5 Web Components Version

~1.24.0

### Browser

Chrome

### Operating System

Windows11

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by sanjayC5373903** [comment]
Hi @Lukas742  Could you please check this issue. Please provide help for this.

**Comment by jadhavarjun** [comment]
Hello @ui5-webcomponents-react-bot, I am also facing same issue.

**Comment by sanjayC5373903** [comment]
Hi @MarcusNotheis 
Could you please check this issue. Please provide necessary solution for this. 
When should i expect resolution ?

Thanks

**Comment by Lukas742** [comment]
Hi @sanjayC5373903 

Have you tried switching off Virtual Cursor mode (Ins + Z) of JAWS?

If so, please provide the following information, we will then check with our accessibility experts if this is the intended behavior or not:

- What cursor mode are you using?
- What is your JAWS version?
- Isolated example by leveraging this [StackBlitz template](https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx).
- Can you observe the same behavior with the `Table` component in MultiSelect mode? ([Storybook](https://sap.github.io/ui5-webcomponents-react/?path=/story/data-display-table--default&args=mode:MultiSelect))
