### ISSUE TITLE
AnalyticalTable: Loading color bar does not display

### ISSUE THREAD

**Issue by ggfer** [SAP/ui5-webcomponents-react#598]
**Describe the bug**
The loading color bar does not display from beginning logic to ending logic.

**Isolated Example**
**https://codesandbox.io/s/elastic-lake-8kpwj?file=/src/App.js**

**To Reproduce**
1. Go to codesandbox
2. Click on the search button
3. Load data in analyticaltable component
4. See loading error

**Expected behavior**
loading display

**Screenshots**
![image](https://user-images.githubusercontent.com/19473701/87500373-d89c5080-c68e-11ea-9755-fb1c2024efc9.png)

**Comment by MarcusNotheis** [comment]
Hey @ggfer,

I think there is a small error in the `onSearch` function. You currently have the following:
```js
  const onSearch = () => {
    setAnalyticalTableLoading(true);
    setTimeout(() => {
      setData(tableData);
    }, 1500);
    setAnalyticalTableLoading(false);
  };
```
-> You set the loading state to `true` and then directly to `false`.

If you put the `setAnalyticalTableLoading(false)` inside of the timeout, everything works fine:
```js
  const onSearch = () => {
    setAnalyticalTableLoading(true);
    setTimeout(() => {
      setData(tableData);
      setAnalyticalTableLoading(false);
    }, 1500);
  };
```
Does this solve your issue?

**Comment by ggfer** [comment]
> Hey @ggfer,
> 
> I think there is a small error in the `onSearch` function. You currently have the following:
> 
> ```js
>   const onSearch = () => {
>     setAnalyticalTableLoading(true);
>     setTimeout(() => {
>       setData(tableData);
>     }, 1500);
>     setAnalyticalTableLoading(false);
>   };
> ```
> 
> -> You set the loading state to `true` and then directly to `false`.
> 
> If you put the `setAnalyticalTableLoading(false)` inside of the timeout, everything works fine:
> 
> ```js
>   const onSearch = () => {
>     setAnalyticalTableLoading(true);
>     setTimeout(() => {
>       setData(tableData);
>       setAnalyticalTableLoading(false);
>     }, 1500);
>   };
> ```
> 
> Does this solve your issue?

Thank you. It is solved. You changed the spending time from 1000ms to 1500ms, opening my mind. If spending time <=1000ms, the loading color bar won't appear. Is there some notice when spending time <=1000ms?

**Comment by MarcusNotheis** [comment]
Our loading spinner is debounced by 500ms to prevent flickering when the data is loading really fast.
If you want to, you can change that by providing our own `LoadingComponent` like this:
```jsx
const styles = {
  position: 'absolute',
  top: 'var(--sapWcrAnalyticalTableRowHeight)',
  left: 0,
  right: 0,
  zIndex: 1
};

const MyCustomLoader = ({ style }) => {
  return <Loader delay={0} style={{ ...styles, ...style }} />;
};

<AnalyticalTable 
   ...
   LoadingComponent={MyCustomLoader}
/>
```

Please note that is is important to apply the style which is coming in a prop, otherwise your loader component might have the wrong width.

**Comment by ggfer** [comment]
> Our loading spinner is debounced by 500ms to prevent flickering when the data is loading really fast.
> If you want to, you can change that by providing our own `LoadingComponent` like this:
> 
> ```js-jsx
> const styles = {
>   position: 'absolute',
>   top: 'var(--sapWcrAnalyticalTableRowHeight)',
>   left: 0,
>   right: 0,
>   zIndex: 1
> };
> 
> const MyCustomLoader = ({ style }) => {
>   return <Loader delay={0} style={{ ...styles, ...style }} />;
> };
> 
> <AnalyticalTable 
>    ...
>    LoadingComponent={MyCustomLoader}
> />
> ```
> 
> Please note that is is important to apply the style which is coming in a prop, otherwise your loader component might have the wrong width.

Best Practice in our project. Thank you.

**Comment by MarcusNotheis** [comment]
You're welcome.
I'm closing this issue for now, please feel free to reopen in case there is more to do.

Best regards,
Marcus
