### ISSUE TITLE
[Filter Bar] : cannot tab to the next filter field in filters personalization setting dialogue.

### ISSUE THREAD

**Issue by Nakul-Narwal** [SAP/ui5-webcomponents-react#5987]
### Describe the bug

when I click on "Filters" and dialogue opens, when I try to TAB from one filter entry to another instead of going to the next entry it goes to the "OK" Button.  

### Isolated Example

https://sap.github.io/ui5-webcomponents-react/?path=/story/layouts-floorplans-filterbar--default

### Reproduction steps

1.Go to the Filter Bar example 
2.click on filters
3.press TAB once to get into the filter Field [StepInput]
4. press TAB again.
5. Istead of going to the next filter field it goes to the OK button
...

### Expected Behaviour

should have gone to the next filter field [RatingIndicator]

### Screenshots or Videos

![Screenshot 2024-06-27 151239](https://github.com/SAP/ui5-webcomponents-react/assets/168707576/263a969b-f512-473b-87f0-f6d94cb5f92b)

### UI5 Web Components for React Version

v1.29.2

### UI5 Web Components Version

v1.24.5

### Browser

Edge

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @Nakul-Narwal 

this behavior is by design. The `Table` web component that is used here implements its own keyboard navigation and you can move between the rows by using the arrow keys. This is the standard behavior for most complex components (e.g. tables and lists).
