### ISSUE TITLE
[Filter Bar]: [Show Filter Bar button not available on mobile devices]

### ISSUE THREAD

**Issue by DrMalchev** [SAP/ui5-webcomponents-react#5991]
### Describe the bug

The button Show Filter Bar is not visible on mobile devices. tested on IOS and Android, both landscape and portrait mode.

### Reproduction steps

1.
2.
3.
...

### UI5 Web Components for React Version

^1.28.1

### UI5 Web Components Version

^1.22.0

### Browser

Safari

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @DrMalchev 

this behavior is by design. You can find out more about it here: https://experience.sap.com/fiori-design-web/filter-bar/#responsiveness

The linked PR will also add this information to our documentation.

**Comment by DrMalchev** [comment]
Thanks for your prompt reply!
The documentation says that it is closed and accessible through Filter dialog, but I still can't get to my filters. Filters dialog gives me only control which to display. How can I expand it to see my FilterGroupItem-s.
Thanks!

**Comment by Lukas742** [comment]
To edit filters you can press on the "Show Values" button inside the filters dialog:

https://github.com/SAP/ui5-webcomponents-react/assets/9749730/16f1efbe-ca22-4479-aec7-2b9ffe165904

**Comment by DrMalchev** [comment]
@Lukas742 
I thought Show Values is a Label for the display types. Would have never realized this is a button.
It's all clear now, but I consider this a really bad UX.
Thanks again for your help!
