### ISSUE TITLE
[AnalyticalTable & FilterBar]: [A mechanism is unavailable to bypass blocks of content that are repeated. There is no group skipping option (shortcut key) available . Here user needs to navigate through all the UIs within the group to navigate further to next group.]

### ISSUE THREAD

**Issue by sanjayC5373903** [SAP/ui5-webcomponents-react#6026]
### Describe the bug

A mechanism is unavailable to bypass blocks of content(Raw Data in table) that are repeated on the Web page.
There is no group skipping option (shortcut key) available for the group of UIs. Here user needs to navigate through all the UIs within the group to navigate further to next group.
![image](https://github.com/SAP/ui5-webcomponents-react/assets/170628934/1a354991-6e8e-4a26-835f-dbe274fce3a0)

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

It should be possible to skip every group and should be possible to jump between the groups.

### UI5 Web Components for React Version

0.27.5

### UI5 Web Components Version

1.6.0

### Browser

Chrome

### Operating System

Windows11

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by sanjayC5373903** [comment]
Hi @Lukas742 Can you Please help me or any suggestion regarding this ticket. Thanks!

**Comment by Lukas742** [comment]
Hi @sanjayC5373903 

we need more information to process this issue. Please give a detailed example of what you want to implement and explain what is missing to achieve this.

Also, if it's about the F6 Navigation feature, you can find more information about this here: https://sap.github.io/ui5-webcomponents/docs/advanced/using-features/#f6-navigation-fast-navigation

**Comment by sanjayC5373903** [comment]
Hi @Lukas742 
Currently. the UI of our applications has filters at the top and a table below them. The issue we are facing is the lack of a mechanism to bypass these filters which are repeated on the webpage using keyboard. We need a skip option or a shortcut key that allows users to skip these repeated sections (e.g. filters) and move directly to the next group, which in this case is the table. 
For example, as shown in the previous screenshot, users need a way to quickly navigate from the filter section to the table without having to tab through each filter element. 

You mentioned using the F6 navigation feature. However, I have tried that and it is not working as expected. Instead of skipping to the next section, F6 opens the address bar of the browser, as it is also a shortcut for that function in Chrome.
Thank you for your assistance.

**Comment by Lukas742** [comment]
Hi @sanjayC5373903 

I tried the F6 Navigation feature and it was working for me. Could you please add a reproducible example of your implementation, so we can assist you further?

**Comment by sanjayC5373903** [comment]
https://stackblitz.com/edit/github-zmyar5?file=src%2FApp.tsx,src%2FTableData.tsx,src%2FFilterFile.tsx

Here is the reproducible example. We need a way to quickly navigate from the filter section to the table without having to tab through each filter element. If we press F6, it opens the address bar of the browser. 
It should be possible to skip every group and should be possible to jump between the groups.

**Comment by Lukas742** [comment]
As described in the linked documentation, you have to first import the feature:

```ts
import "@ui5/webcomponents-base/dist/features/F6Navigation.js";
```

And then set `data-sap-ui-fastnavgroup="true"` to the element which should be focused via F6 (or Shift + F6).

[Here](https://stackblitz.com/edit/github-zmyar5-zmrhkz?file=src%2FTableData.tsx,src%2Fmain.tsx,src%2FFilterFile.tsx) you can find a working example.
