### ISSUE TITLE
AnalyticalTable: How to set i18n in sort selection

### ISSUE THREAD

**Issue by ggfer** [SAP/ui5-webcomponents-react#603]
**Describe the bug**
as title

**To Reproduce**
1. Go to Analytical Table
2. Click on one of the headers

**Expected behavior**
we can set i18n for the text of text `Sort Ascending`, `Sort Descending` and `Clear Sorting`

**Screenshots**
![image](https://user-images.githubusercontent.com/19473701/87624740-077ff880-c75b-11ea-971f-b6c354520ada.png)
![image](https://user-images.githubusercontent.com/19473701/87625021-b7edfc80-c75b-11ea-8628-1465a489fdd4.png)

**Comment by MarcusNotheis** [comment]
Hey @ggfer,
which version of UI5 Web Components do you have in your project?
Unfortunately the i18n translations in `0.9.x` are broken, but they are fixed in the `0.10.0-rc.x` versions. We expect to finalize `0.10.0` until next week.

Best regards,
Marcus

**Comment by ggfer** [comment]
Hi **@MarcusNotheis**,
version：` "@ui5/webcomponents-react": "^0.10.0-rc.2"`
we got this problem at this version, maybe it will be fixed at `0.10.0`? 
Looking forward to your reply.

**Comment by MarcusNotheis** [comment]
Hey @ggfer,

can you try with `rc.8`?
And did you import the language assets as well by using `import "@ui5/webcomponents-react/dist/Assets";`?

I've prepared a litte codesandbox:
- [Sandbox](https://codesandbox.io/s/adoring-river-tjv4g?file=/src/App.js)
- [English](https://tjv4g.csb.app/?sap-ui-language=en)
- [German](https://tjv4g.csb.app/?sap-ui-language=de)
- [Spanish](https://tjv4g.csb.app/?sap-ui-language=es)

Best regards,
Marcus

**Comment by ggfer** [comment]
Hi **@MarcusNotheis**,
I got the problem. It turns out that i18n does not support my area...Chinese area...Maybe you can try some?
If the i18n can support China in the future, please let me know:)

**Comment by MarcusNotheis** [comment]
Hey @ggfer,
I think this issue might be a prerequisite: https://github.com/SAP/ui5-webcomponents/issues/1976

**Comment by MarcusNotheis** [comment]
Pull Request on the UI5 Web Components side is now open, will then be part of our final `0.10.0`:
https://github.com/SAP/ui5-webcomponents/pull/1985
