### ISSUE TITLE
[Table onLoadMore event]: [onLoadMore event, is getting called abruptly when table growing is set to "Scroll"]

### ISSUE THREAD

**Issue by Smriti-Roy** [SAP/ui5-webcomponents-react#6048]
### Describe the bug

I have created a dialog that has table data inside it. The growing is set to Scroll for the table. 
When dialog is opened for the first time, the loadMoreEvent is triggered when user scrolls the data. But when dialog is closed and opened again, the load-more event is also getting triggered. This is happening only in this particular scenario when dialog is closed and open again.

 <Table
          id="table"
          mode="SingleSelect"
          growing={TableGrowingMode.Scroll}
          onLoadMore={loadMoreMaterials}
/>

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

When the dialog is reopened again, load-more event should not be triggered until user scrolls through the table data.

### Screenshots or Videos

https://github.com/SAP/ui5-webcomponents-react/assets/66247219/5b1ee87d-4894-456d-aec8-960a2e06c32f

### UI5 Web Components for React Version

1.29.2

### UI5 Web Components Version

1.24.5

### Browser

Chrome

### Operating System

macOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @Smriti-Roy 

please add a reproducible example, preferably by using this [StackBlitz](https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx) template.
