### ISSUE TITLE
Datepicker: Translation not working in Chinese

### ISSUE THREAD

**Issue by abhitatachar2000** [SAP/ui5-webcomponents-react#6099]
### Describe the bug

Dear colleagues, greetings.

During one of our feature implementations, we noticed that the date-picker was not being translated into Chinese. When the locale language is set to Chinese, the date-picker still opens up in English. However, the translations seem to work flawlessly for other languages. 

Is this the expected behavior, or is it a bug, or is it possible that I am missing something here?

Please feel free to reach out if more information is needed.

Best regards,
Abhishek.

### UI5 Web Components for React Version

1.29.3

### UI5 Web Components Version

1.24.5

### Browser

Chrome

### Operating System

Mac

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @abhitatachar2000 

I tested it in our Storybook example and the translations seems to be working fine there for me:

`zh_TW`:
<img width="280" alt="image" src="https://github.com/user-attachments/assets/e82ed86f-9546-4eaf-b9b1-31678f466448">

`zh_CN`:
<img width="299" alt="image" src="https://github.com/user-attachments/assets/be1f0184-c2a9-4a85-8378-ddd87db6398d">

Could you please check which language code is applied for you, or if you set it programmatically, provide a reproducible example by leveraging this [StackBlitz](https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx) template?
