### ISSUE TITLE
[Input]: [While navigating around input fields within ‘Create’ dialog, remaining character count information such as ‘3/20, 4/50’ is not being read.

### ISSUE THREAD

**Issue by balakrishnamanash** [SAP/ui5-webcomponents-react#6108]
### Describe the bug

While navigating around input fields within ‘Create’ dialog, remaining character count information such as ‘3/20, 4/50’ is not being read.

### Reproduction steps

const [charCountName, setCharCountName] = useState(formValues?.profileName?.length);
<DialogFormField
            label={t('NAME')}
            accessibleName={t('NAME')}
            name="profileName"
            as={InputField}
            maxlength={20}
            direction={'Column'}
            icon={
              <Text style={{ fontSize: '0.8rem' }}>
                {charCountName}
                {'/20'}
              </Text>
            }
>

### Expected Behaviour

Along with the name and UI place holder text should also be read by the screen reader.

### UI5 Web Components for React Version

^1.16.3

### UI5 Web Components Version

^1.14.0

### Browser

Chrome

### Operating System

windows 11

### Additional Context

jaws July version. 

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MarcusNotheis** [comment]
Hi @balakrishnamanash,

please add a reproducible example, preferably by using our [Stackblitz Template](https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx).
Your current sample contains custom components and libraries from your project, hence we can't use it for testing purposes.

**Comment by Lukas742** [comment]
Hi @balakrishnamanash 

although [this issue](https://github.com/SAP/ui5-webcomponents-react/issues/6191) was created after yours, I'm going to close this one as duplicate as the linked issue has more context. In case of questions or additional feedback, please comment them in the linked issue.

Duplicate of https://github.com/SAP/ui5-webcomponents-react/issues/6191
