### ISSUE TITLE
[Switch]: [I want to test Switch component in High Contrast Black Theme when focus on Switch border is overlaps]

### ISSUE THREAD

**Issue by jadhavarjun** [SAP/ui5-webcomponents-react#6109]
### Describe the bug

I want to test Switch component in @ui5/webcomponents@1.14.0 and @ui5/webcomponents-react@1.16.3  version but when I tried to install these versions, I'll get errors. Can you please help me with that can you please create demo reproducible code with given version and share with me so I will test my components.
![image](https://github.com/user-attachments/assets/a981b6db-40fa-4bcd-be5a-e9ff58f429b7)

### Isolated Example

https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx

### Reproduction steps

1. Open StackBlitz link 
2. Install @ui5/webcomponents@1.14.0 and @ui5/webcomponents-react@1.16.3  version
3. Add demo code that run successfully with given older version.
4. Share with me back so I will test my components.
...

### UI5 Web Components for React Version

1.16.3

### UI5 Web Components Version

1.14.3

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by jadhavarjun** [comment]
Hi @Lukas742,

Please shared stackblitz link with me with required version.

**Comment by MarcusNotheis** [comment]
Hi @jadhavarjun,

here's a stackblitz using the old versions: https://stackblitz.com/edit/github-hqrsgy?file=package.json,src%2FApp.tsx
Is there anything else open in this issue or can we close the issue?

**Comment by jadhavarjun** [comment]
Hi @MarcusNotheis , 

Can I know how we should install any particular versions, what is the process. Because when I tried using npm I got the errors.

**Comment by MarcusNotheis** [comment]
Basically you started the right way by setting the versions in the package.json. The error which came up was most likely related to downgrade of dependencies, so deleting the `node_modules` and `package-lock.json` and then run `npm i` again did the trick in that case.

**Comment by jadhavarjun** [comment]
ok got it thank you i am closing this issue
