### ISSUE TITLE
[Tag]: [No type definitions to be found]

### ISSUE THREAD

**Issue by biscimus** [SAP/ui5-webcomponents-react#6126]
### Describe the bug

I wanted to use the `Tag` component as writted in the documentation, but the component couldn't be found. I looked into the source code & documentation of UI5 web components for a bit, and it seems like the `Badge` component has been renamed to `Tag` component some time ago, but I suppose the type definitions were not correctly set. There's no problem with using it as a `Badge` component, but it took me some time to find it and it's mentioned nowhere in the documentation.

### Reproduction steps

1. use `"import {Tag} from @ui5/webcomponents-react";` 

### Expected Behaviour

No errors

### UI5 Web Components for React Version

1.29.5

### UI5 Web Components Version

1.24.7

### Browser

Chrome

### Operating System

MacOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MarcusNotheis** [comment]
Hi @biscimus,

thanks for reaching out! You're totally right, the `Badge` component has been renamed to `Tag` with the release of UI5 Web Components 2.0. We are currently working on releasing the UI5 Web Components for React wrapper in v2 as well, and here we're going to use and export the new `Tag` as well. 

--> As long as you're running on UI5 Web Components (for React) v1, please keep using the `Badge` component is the `Tag` will be released with v2. You can try out our v2 release candidates (currently [v2.0.0-rc.1](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v2.0.0-rc.1)) if you are interested in the new components.

Documentation for v1 (Badge):
https://sap.github.io/ui5-webcomponents-react/?path=/docs/data-display-badge--docs

Documentation for v2 (Tag):
https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/data-display-tag--docs
