### ISSUE TITLE
[Custom Filter]:[When we click ‘XX’ column header, we get the filter Header Popover List name is not provided.]

### ISSUE THREAD

**Issue by jadhavarjun** [SAP/ui5-webcomponents-react#6132]
### Bug Description

When we click ‘XX’ column header, we get the custom filter Header Popover List in that list when you navigate using up down arrow key and when you focus on acceding and descending filter icon you get the proper meaningful but when your focus come to last  filter name is not provided.

For your better understanding I have attached some screenshots here:
![image](https://github.com/user-attachments/assets/c630b1d3-c374-4932-97f8-412b819d12d9)

I have also mentioned story book link where you can check this issue:
**Story Book Link:** https://sap.github.io/ui5-webcomponents-react/?path=/story/data-display-analyticaltable--custom-filter

Steps:
1. Open Story Book Link and Speech Reader (JAWS)
2. After Opening Story Book Link you able to see table click on Age header you able to see Header Popover List
![image](https://github.com/user-attachments/assets/aba82b45-a634-40e3-8650-1b73a9e37f79)

4. Navigate Header Popover List using arrow keys 
5. When your focus come to 
![image](https://github.com/user-attachments/assets/2b74aad3-01c0-4203-b7e4-51fac9abaaa7)
you can see no meaningful name provided.

### Expected Behaviour

Every UI should have meaningful name here for button name should be provided and same should be conveyed by the screen reader.

### Steps to Reproduce

1.
2.
3.
...

### Priority

High

### UI5 Web Components Version

^1.14.0

### Browser

Chrome

### Operating System

Windows

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by jadhavarjun** [comment]
Hi @kgogov , @MarcusNotheis ,

When can I expect a resolution for this issue? please.

**Comment by MarcusNotheis** [comment]
I'm currently looking into the specs of how the Filter within column header should look like.
When looking at the implementation of SAPUI5, it looks like there is a static text `Filter` included before the input, so I would assume if we switch to that approach it will resolve the screen reader issue.

**Comment by jadhavarjun** [comment]
Hi @Lukas742 ,
I can see that you have fixed and closed the issue from your side. I want to know when will you release this version and what changes do I have to make in my code so that the issue gets resolved from my side, do I have to use any attribute or it will get solved automatically by version update.

**Comment by Lukas742** [comment]
Hi @jadhavarjun 

please see the comment above your last one :wink:

So, the release is available with [v1.29.6](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v1.29.6)

**Comment by jadhavarjun** [comment]
Hi @Lukas742, 

Now if we focus on the filter column, will all the element or filters within the filter column it be read, actually what happening when we fucus on that filter column the input filed is their within filter column is not being read, I have tried with everything i have added accessibleName, Placeholder attributes accissibleName attribute read only when our focus is directly on that particular input field.
**Expected behavior **: When we focus on the filter column within that filter column should read.

I have attached screenshot you can see here input field is not read.
![image](https://github.com/user-attachments/assets/14a49c87-3fea-43c4-be9b-e8e1e4de0a4a)

**Comment by Lukas742** [comment]
Hi @jadhavarjun 

You're using a custom implementation of the Filter, which we cannot reproduce without an isolated example. For the default implementation it's working as intended. 
Also, it doesn't seem like you've updated to at least v`1.29.6` as the "Filter" text is missing. ([v1 Storybook](https://sap.github.io/ui5-webcomponents-react/v1/?path=/story/data-display-analyticaltable--default))

To assist you further please add an isolated example by leveraging this [StackBlitz template](https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/vite-ts?file=src%2FApp.tsx).

**Comment by jadhavarjun** [comment]
Hi @Lukas742,

that above stackblitz link you provided that version is 1.29.0 in that I am not able to check issue can you please provide me latest version stackblitz link

**Comment by Lukas742** [comment]
Hi @jadhavarjun 

the linked StackBlitz uses the latest version (v1.29.8). Here you can find the same template just with a `console.log` that is showing the version number: https://stackblitz.com/edit/github-vpi3cr?file=src%2FApp.tsx

Also, you can update the dependencies yourself, by changing it in the package.json. Sometimes, you may have to refresh the page so StackBlitz reinstalls the dependencies, but apart from that you can use it in the same way as your app.
