### ISSUE TITLE
[DynamicPage]: the width style of header content div is not correct

### ISSUE THREAD

**Issue by GongRichard** [SAP/ui5-webcomponents-react#6135]
### Describe the bug

please don't set width 100% to the head content div of DynamicPage

### Reproduction steps

1. open page https://sap.github.io/ui5-webcomponents-react/?path=/docs/layouts-floorplans-dynamicpage--docs
2. open dev tool to check the width of head content div
3. you will find the div width of head content div is not correct

### Expected Behaviour

remove width 100% setting

### Screenshots or Videos

<img width="1792" alt="image" src="https://github.com/user-attachments/assets/97c51722-f6f7-48ae-a5c7-f844f5f7e0b2">

### UI5 Web Components for React Version

1.29.5

### UI5 Web Components Version

1.24.x

### Browser

Chrome, Edge, Firefox, Safari

### Organization

SAP SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by sebastian-kraemer** [comment]
@Lukas742 
Isn't this breaking the fix for the other issue: https://github.com/SAP/ui5-webcomponents-react/issues/6087

**Comment by Lukas742** [comment]
Hi @sebastian-kraemer 

you're totally right, for some reason I didn't see that when looking at the GitHub annotation for this line. Thanks a lot for noticing!
I will investigate how this can be fixed for both scenarios and publish another version then.

**Comment by Lukas742** [comment]
Hi @sebastian-kraemer 

now the scrolling should [work as intended](https://stackblitz.com/edit/github-nryuqg-2cv8c5?file=package.json) again and also the header shouldn't overflow anymore. Sorry for the inconvenience.
