### ISSUE TITLE
[Switch]: [Property 'checked' does not exist on type 'EventTarget']

### ISSUE THREAD

**Issue by 22shubham22** [SAP/ui5-webcomponents-react#6136]
### Describe the bug

onChange | Fired when the component checked state changes.

Note: Call event.preventDefault() inside the handler of this event to prevent its default action/s.

(event: Ui5CustomEvent<SwitchDomRef, never>) => void

When we assign this type to the event Ui5CustomEvent<SwitchDomRef, never> , we see an error in typescript when we try to access -> event.currentTarget?.checked that says -> Property 'checked' does not exist on type 'EventTarget' 

Although , when we console log it , we get the desired value . 

### Isolated Example

https://stackblitz.com/edit/github-ekiatg?file=src%2FApp.tsx

### Reproduction steps

1. Create a switch component with onChange Event of type Ui5CustomEvent<SwitchDomRef, never> in typescript
2. Try console.log(event.currentTarget?.checked)
3. the error you get is : Property 'checked' does not exist on type 'EventTarget'
...

### Screenshots or Videos

<img width="1728" alt="Screenshot 2024-07-30 at 3 53 09 PM" src="https://github.com/user-attachments/assets/87e0d141-2dea-4236-8926-67ac60d6ad83">

### UI5 Web Components for React Version

1.29.0

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Operating System

Mac

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MarcusNotheis** [comment]
Hi @22shubham22,
thanks for reaching out! Is there any specific reason why you need to use `currentTarget` instead of `target`? Our type definition adds the types of the UI5 Web Component to the `target` property of the custom event, but not to the `currentTarget` as the event might bubble up from somewhere else.
