### ISSUE TITLE
DynamicPageTitle: Query regarding sequence of action buttons

### ISSUE THREAD

**Issue by abhijeet181088** [SAP/ui5-webcomponents-react#6139]
### Describe the bug

We have few(5) action buttons in the DynamicPageTitle. On smaller screens, few buttons shift to overflow menu as expected.
One of the buttons is "Complete" button which is the primary action on our page.

**Queries:**
1. Is it possible to always keep this button visible, irrespective of screen size, it should never go to the overflow menu.
2. And also, is it possible to always keep it at the end (right most) of the visible buttons.
3. Is this possible to achieve with the current components?

![image](https://github.com/user-attachments/assets/f444d63f-3c86-4086-91ac-e924d714af02)

### Isolated Example

https://stackblitz.com/edit/github-lg4jzd-vlpu57?file=src%2FApp.tsx

### Reproduction steps

Query mentioned in description

### Expected Behaviour

Query mentioned in description

### UI5 Web Components for React Version

1.29.0

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Operating System

macOS

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MarcusNotheis** [comment]
Hi @abhijeet181088,

unfortunately this is not possible with the current implementation of the `DynamicPage` and the `Toolbar`. The only workaround which is coming to my mind right now is to move the `Completed` button to the `navigationActions` prop of the `DynamicPageTitle`: On smaller screens the button will be in the top row above the other actions, and for large screens it will be rendered on the right (or left in RTL) hand side of the other actions: https://stackblitz.com/edit/github-lg4jzd-k2qjth?file=src%2FApp.tsx

With the release of UI5 Web Components v2 (our React wrapper is currently in the release candidate state) there is a new Toolbar component available which is also supporting the `overflowPriority` prop: https://sap.github.io/ui5-webcomponents/components/Toolbar/#never-overflowing-items
I think with the new Toolbar component in the DynamicPage, we'll be able to serve your needs 🙂

**Comment by abhijeet181088** [comment]
Thank you Marcus for the clarification and suggestions.
