### ISSUE TITLE
[Input, Table]: Many compile errors

### ISSUE THREAD

**Issue by vrathodsap** [SAP/ui5-webcomponents-react#6186]
### Describe the bug

<img width="1642" alt="image" src="https://github.com/user-attachments/assets/6dbaa1d5-e6be-4e4b-a5f3-1c83eb27a451">

ERROR in ./node_modules/@ui5/webcomponents-react/dist/webComponents/TableGroupRow/index.js 3:0-50
Module not found: Error: Can't resolve '@ui5/webcomponents/dist/TableGroupRow.js' in '/Users/D070484/SAPDevelop/recommerce/recommerce-workbench/node_modules/@ui5/webcomponents-react/dist/webComponents/TableGroupRow'

ERROR in ./node_modules/@ui5/webcomponents-react/dist/webComponents/TableColumn/index.js 3:0-48
Module not found: Error: Can't resolve '@ui5/webcomponents/dist/TableColumn.js' in '/Users/D070484/SAPDevelop/recommerce/recommerce-workbench/node_modules/@ui5/webcomponents-react/dist/webComponents/TableColumn'

### Reproduction steps

upgrade to latest package

"@ui5/webcomponents": "^2.1.1",
    "@ui5/webcomponents-fiori": "^2.1.1",
    "@ui5/webcomponents-icons": "^2.1.1",
    "@ui5/webcomponents-icons-business-suite": "^2.1.1",
    "@ui5/webcomponents-icons-tnt": "^2.1.1",
    "@ui5/webcomponents-react": "^1.29.7",
    "@ui5/webcomponents-react-base": "^1.29.3",
    "@ui5/webcomponents-react-charts": "^1.29.5",

### UI5 Web Components for React Version

1.29.7

### UI5 Web Components Version

2.1.1

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @vrathodsap 

v2 of `@ui5/webcomponents` is not compatible with v1 of `@ui5/webcomponents-react`. You should see peer dependency errors regarding this. We're currently in the process of preparing our 2.0 release and to try out our current progress, you can use the release candidate versions. As of writing this, the latest rc is [v2.0.0-rc.2](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v2.0.0-rc.2)
