### ISSUE TITLE
'PopoverPlacementType' is not exported error when launching app

### ISSUE THREAD

**Issue by brampurnot** [SAP/ui5-webcomponents-react#6205]
### Describe the bug

I started with a fresh NextJS project and followed the nextJS app router template. When booting up the server, it fails to compile with the following stacktrace:
` ⨯ ../../node_modules/@ui5/webcomponents-react/dist/components/AnalyticalTable/ColumnHeader/ColumnHeaderModal.js
Attempted import error: 'PopoverPlacementType' is not exported from '../../../enums/index.js' (imported as 'PopoverPlacementType').

Import trace for requested module:
../../node_modules/@ui5/webcomponents-react/dist/components/AnalyticalTable/ColumnHeader/ColumnHeaderModal.js
../../node_modules/@ui5/webcomponents-react/dist/components/AnalyticalTable/ColumnHeader/index.js
../../node_modules/@ui5/webcomponents-react/dist/components/AnalyticalTable/ColumnHeader/ColumnHeaderContainer.js
../../node_modules/@ui5/webcomponents-react/dist/components/AnalyticalTable/index.js
../../node_modules/@ui5/webcomponents-react/dist/index.js
./app/layout.tsx
 ⨯ ../../node_modules/@ui5/webcomponents-react/dist/components/AnalyticalTable/ColumnHeader/ColumnHeaderModal.js
Attempted import error: 'PopoverPlacementType' is not exported from '../../../enums/index.js' (imported as 'PopoverPlacementType').

Import trace for requested module:
../../node_modules/@ui5/webcomponents-react/dist/components/AnalyticalTable/ColumnHeader/ColumnHeaderModal.js
../../node_modules/@ui5/webcomponents-react/dist/components/AnalyticalTable/ColumnHeader/index.js
../../node_modules/@ui5/webcomponents-react/dist/components/AnalyticalTable/ColumnHeader/ColumnHeaderContainer.js
../../node_modules/@ui5/webcomponents-react/dist/components/AnalyticalTable/index.js
../../node_modules/@ui5/webcomponents-react/dist/index.js
./app/layout.tsx
 GET /_next/static/webpack/fcdb9ccada75a863.webpack.hot-update.json 500 in 10941ms
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.`

### Reproduction steps

1.
2.
3.
...

### UI5 Web Components for React Version

1.29.8

### UI5 Web Components Version

2.1.1

### Browser

Chrome

### Operating System

macOS 

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @brampurnot 

v2 of @ui5/webcomponents is not compatible with v1 of @ui5/webcomponents-react. You should see peer dependency errors regarding this. We're currently in the process of preparing our 2.0 release. To try out our current progress, you can use the release candidate versions. As of writing this, the latest rc is [v2.0.0-rc.2](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v2.0.0-rc.2)
