### ISSUE TITLE
[SF][Table][Drag and Drop]: Looking for ui5-wc and ui5-wc-react to support drag and drop in table component

### ISSUE THREAD

**Issue by Natesan** [SAP/ui5-webcomponents-react#6251]
### Is your feature request related to a problem?

We have a use case where the UX is contemplating having drag and drop functionality built into the table component. When we did the initial round of analysis it came to our notice that the table component doesn't yet support drag and drop. This understanding is based on the release notes available at https://github.com/SAP/ui5-webcomponents/releases?q=2.0&expanded=true where we see the drag and drop available for tabcontainer, list and tree.

<img width="659" alt="image" src="https://github.com/user-attachments/assets/1cfa8405-0d5d-497e-a16a-bc0640d03850">

### Describe the solution you'd like

We would like to have the drag and drop functionality on the table as well just like how the SAPUI5 table.

### Describe alternatives you've considered

We have an existing application that makes use of a table (where a lot of complex functionality is already built and in production). So it would work best for us if the component support is provided to enable drag and drop. 

Alternates like list and tree is something we could consider but this would mean a lot of effort to have the current behaviour re-written. 

### Organization

SF

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @Natesan 

I will close this issue as there is already another [one](https://github.com/SAP/ui5-webcomponents/issues/7240) covering this topic. If you have any questions or more information, please address them in the original issue.

Duplicate https://github.com/SAP/ui5-webcomponents/issues/7240
