### ISSUE TITLE
[ComboBox]: Change event is fired at the wrong time

### ISSUE THREAD

**Issue by lormanlau1** [SAP/ui5-webcomponents-react#6275]
### Describe the bug

The change event is fired while scrolling through the dropdown list using the arrowkeys

### Isolated Example

https://stackblitz.com/edit/github-52u2mk-sz2baq?file=src%2FApp.tsx

### Reproduction steps

1. Focus on the input
2. Use arrow keys to navigate through the list
3. Observe that the change event is fired every time.

### Expected Behaviour

Change event is only fired when entered is press or when focus is lost.

### UI5 Web Components for React Version

1.29.0

### UI5 Web Components Version

1.24.0

### Browser

Chrome

### Organization

SAP SuccessFactors

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @lormanlau1 

this behavior seems to be intended (see [docs](https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/inputs-combobox--docs#properties)):

> Fired when the input operation has finished by pressing Enter, focusout or an item is selected.

Please let us know if you believe the behavior is still incorrect. If so, we will forward this issue to the UI5 Web Components repository, where the component is developed.

**Comment by lormanlau1** [comment]
The behavior that is not intended is that when user is scrolling through the list using arrow keys the change event is fired. This should not count as "item is selected" since there is no way for screen reader users to scroll through the list without the items being selected. This behavior on the UI5 Webcomponent is working as expected as well as the OpenUI5 but the react component is functioning differently.

**Comment by Lukas742** [comment]
> This behavior on the UI5 Webcomponent is working as expected as well as the OpenUI5 but the react component is functioning differently.

Since we only wrap ui5 web components, meaning we're not changing any implementation details, this shouldn't be the case. I've refactored your example to use only HTML with JS and the behavior is the same: https://stackblitz.com/edit/github-mxofyy?file=main.js,index.html,package.json

If that's not the case for you, please provide the following informations:

- Browser + version
- OS + version
- Do you have any Browser plugins/extensions installed?

**Comment by lormanlau1** [comment]
@Lukas742 
I am sure why this is different with UI5 web component on stackblitz but please take a look at this [link](https://sap.github.io/ui5-webcomponents/play/#eyJpbmRleC5odG1sIjp7Im5hbWUiOiJpbmRleC5odG1sIiwiY29udGVudCI6IjwhLS0gcGxheWdyb3VuZC1mb2xkIC0tPlxuPCFET0NUWVBFIGh0bWw-XG48aHRtbCBsYW5nPVwiZW5cIj5cblxuXG5cblxuPGhlYWQ-XG4gICAgXG4gICAgPHN0eWxlPlxuICAgICAgKjpub3QoOmRlZmluZWQpIHtcbiAgICAgICAgZGlzcGxheTogbm9uZTtcbiAgICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gICAgXG4gICAgPHN0eWxlPlxuICAgICAgKjpub3QoOmRlZmluZWQpIHtcbiAgICAgICAgZGlzcGxheTogbm9uZTtcbiAgICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gICAgXG4gICAgPHN0eWxlPlxuICAgICAgKjpub3QoOmRlZmluZWQpIHtcbiAgICAgICAgZGlzcGxheTogbm9uZTtcbiAgICAgIH1cbiAgICA8L3N0eWxlPlxuXG4gIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICA8bWV0YSBuYW1lPVwidmlld3BvcnRcIiBjb250ZW50PVwid2lkdGg9ZGV2aWNlLXdpZHRoLCBpbml0aWFsLXNjYWxlPTEuMFwiPlxuICA8dGl0bGU-U2FtcGxlPC90aXRsZT5cbjwvaGVhZD5cblxuPGJvZHkgc3R5bGU9XCJiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1zYXBCYWNrZ3JvdW5kQ29sb3IpO2hlaWdodDogMzAwcHhcIj5cbiAgPCEtLSBwbGF5Z3JvdW5kLWZvbGQtZW5kIC0tPlxuXG5cbiAgPHVpNS1jb21ib2JveCBpZD1cImNvbWJvYm94XCIgcGxhY2Vob2xkZXI9XCJUd28tY29sdW1uXCI-XG4gICAgPHVpNS1jYi1pdGVtIHRleHQ9XCJBdXN0cmlhXCIgYWRkaXRpb25hbC10ZXh0PVwiQVRcIj48L3VpNS1jYi1pdGVtPlxuICAgIDx1aTUtY2ItaXRlbSB0ZXh0PVwiQmVsZ2l1bVwiIGFkZGl0aW9uYWwtdGV4dD1cIkJFXCI-PC91aTUtY2ItaXRlbT5cbiAgICA8dWk1LWNiLWl0ZW0gdGV4dD1cIkJyYXppbFwiIGFkZGl0aW9uYWwtdGV4dD1cIkJSXCI-PC91aTUtY2ItaXRlbT5cbiAgICA8dWk1LWNiLWl0ZW0gdGV4dD1cIkJ1bGdhcmlhXCIgYWRkaXRpb25hbC10ZXh0PVwiQkdcIj48L3VpNS1jYi1pdGVtPlxuICAgIDx1aTUtY2ItaXRlbSB0ZXh0PVwiQ2FuYWRhXCIgYWRkaXRpb25hbC10ZXh0PVwiQ0FcIj48L3VpNS1jYi1pdGVtPlxuICAgIDx1aTUtY2ItaXRlbSB0ZXh0PVwiVGhlIFVuaXRlZCBLaW5nZG9tIG9mIEdyZWF0IEJyaXRhaW4gYW5kIE5vcnRoZXJuIElyZWxhbmRcIiBhZGRpdGlvbmFsLXRleHQ9XCJVS1wiPjwvdWk1LWNiLWl0ZW0-XG4gIDwvdWk1LWNvbWJvYm94PlxuICA8IS0tIHBsYXlncm91bmQtZm9sZCAtLT5cbiAgPHNjcmlwdCB0eXBlPVwibW9kdWxlXCIgc3JjPVwibWFpbi5qc1wiPjwvc2NyaXB0PlxuPC9ib2R5PlxuXG48L2h0bWw-XG48IS0tIHBsYXlncm91bmQtZm9sZC1lbmQgLS0-XG4ifSwibWFpbi5qcyI6eyJuYW1lIjoibWFpbi5qcyIsImNvbnRlbnQiOiIvKiBwbGF5Z3JvdW5kLWhpZGUgKi9cbmltcG9ydCBcIi4vcGxheWdyb3VuZC1zdXBwb3J0LmpzXCI7XG4vKiBwbGF5Z3JvdW5kLWhpZGUtZW5kICovXG5pbXBvcnQgXCJAdWk1L3dlYmNvbXBvbmVudHMvZGlzdC9Db21ib0JveC5qc1wiO1xuaW1wb3J0IFwiQHVpNS93ZWJjb21wb25lbnRzL2Rpc3QvQ29tYm9Cb3hJdGVtLmpzXCI7XG5cbmNvbnN0IGNvbWJvYm94ID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvcihcIiNjb21ib2JveFwiKTtcbmNvbWJvYm94LmFkZEV2ZW50TGlzdGVuZXIoXCJjaGFuZ2VcIiwgKGUpID0-IHtjb25zb2xlLmxvZyhcImNoYW5nZTpcIiwgZSl9KTtcbmNvbWJvYm94LmFkZEV2ZW50TGlzdGVuZXIoXCJpbnB1dFwiLCAoZSkgPT4ge2NvbnNvbGUubG9nKFwiaW5wdXQ6XCIsIGUpfSk7XG5jb21ib2JveC5hZGRFdmVudExpc3RlbmVyKFwic2VsZWN0aW9uLWNoYW5nZVwiLCAoZSkgPT4ge1wic2VsZWN0aW9uLWNoYW5nZTpcIiwgY29uc29sZS5sb2coZSl9KTsifX0) in the UI5 Web Components playground.

**Comment by lormanlau1** [comment]
I have opened a ticket in the UI5 Web Component repo for patching into version. https://github.com/SAP/ui5-webcomponents/issues/9776. We would also need an update in the ui5 webcomponent react

**Comment by Lukas742** [comment]
I didn't know that they changed this behavior, but good to know.

Patch releases are always compatible with the respective minor version (see [here](https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/getting-started--docs#add-ui5webcomponents-react-to-an-existing-app)), so if the fix is available for example in v 1.24.10 of `@ui5/webcomponents` you can just update the respective dependency if you're using v1.29.x of `@ui5/webcomponents-react`.

Please note that v1 will only be supported until the [end of the year](https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/getting-started--docs#ongoing-support-for-version-1x).
