### ISSUE TITLE
[ProgressIndicator]: Provide a way to disable the "filling" animation

### ISSUE THREAD

**Issue by ThiagoSzz** [SAP/ui5-webcomponents-react#6284]
### Is your feature request related to a problem?

Currently it's not possible to disable the "filling" animation of the `ProgressIndicator` component.

According to the [guidelines](https://experience.sap.com/fiori-design-web/progress-indicator/#animation), it is recommended to not use the animation, since it does not provide any additional value and could even be distracting for users in some use cases.

https://github.com/user-attachments/assets/382d0609-b176-4d58-b4e0-5d7445e13ae8

### Describe the solution you'd like

A new `displayAnimation` (boolean) prop is provided and it defaults to false.
- When set to true, the "filling" animation is displayed when the `value` prop is modified.
- When set to false, the "filling" animation is disabled.

### Additional Context

https://sapui5.hana.ondemand.com/sdk/#/api/sap.m.ProgressIndicator%23controlProperties

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @ThiagoSzz 

you can deactivate or reduce animations by setting the corresponding [animationMode](https://sap.github.io/ui5-webcomponents/docs/advanced/configuration/#animationMode). This can be achieved either via the configuration object (see below), or [programmatically](https://sap.github.io/ui5-webcomponents/docs/advanced/configuration/#configuration-module-imports) by calling the corresponding method.

Here you can find an example using the configuration object: https://stackblitz.com/edit/github-qwm86m?file=index.html
