### ISSUE TITLE
Icon import is not working

### ISSUE THREAD

**Issue by vinniimiranda** [SAP/ui5-webcomponents-react#629]
Hi, i am having an issue with icons for my application.

In the console:
![image](https://user-images.githubusercontent.com/33462844/88968853-5e6eed00-d286-11ea-821a-5b47ffe5f321.png)

In the page: 
![image](https://user-images.githubusercontent.com/33462844/88969111-b6a5ef00-d286-11ea-83aa-968732087ead.png)

My index.tsx file 
![image](https://user-images.githubusercontent.com/33462844/88968908-7181bd00-d286-11ea-94c6-ec64028fc18d.png)

My package.json file:
![image](https://user-images.githubusercontent.com/33462844/88969351-18feef80-d287-11ea-8cee-90fc6e59b1a2.png)

I've already tried to remove node_modules, reinstall the icons package, but nothing worked for me.

This erros starts when i deleted yarn.lock file and run yarn install for eslint.

**Comment by MarcusNotheis** [comment]
Hey @vinniimiranda,
thanks for reporting. I just tried to build a reproducible sample on codesandbox based on the information I found in your description. For me, it's working fine. Do you experience this issue in a certain browser (console looks like Chrome)? Or am I missing something in my sample? If yes, please feel free to adjust it and send it back to me.

Thanks!

**Comment by vinniimiranda** [comment]
I figure it out that was npm problem, when i use yarn it work's,
