### ISSUE TITLE
[DynamicPageTitle]: Background color inconsistency on actions buttons in DynamicPageTitle when buttons are loaded asynchronously.

### ISSUE THREAD

**Issue by mrmabo** [SAP/ui5-webcomponents-react#6298]
### Describe the bug

When the actions buttons within a **DynamicPageTitle** are loaded asynchronously and update the DOM, hovering over these buttons sometimes causes a gray background to appear. However, this behavior does not occur when the actions buttons are not updated asynchronously.

This issue persists regardless of whether the buttons are wrapped in a fragment (<>...</>) or a <Toolbar>.

### Isolated Example

https://stackblitz.com/edit/github-t5j5mn-zrzbe6?file=src%2FApp.tsx

### Reproduction steps

1. Access the stackblitz.
2. Select [data-component-name="DynamicPageTitleActions"] dom in the dev-tool
3. Check the _:hover_ in the Stytles. 
4. Observe that a gray background appears.

### Expected Behaviour

The buttons should not show a gray background on hover, whether they are loaded asynchronously or synchronously.

Is there any known workaround to prevent the gray background from appearing on hover when the buttons are loaded asynchronously?

### Screenshots or Videos

<img width="1861" alt="Screenshot 2024-08-30 at 2 43 38 PM" src="https://github.com/user-attachments/assets/e1aa3f44-da95-489b-b5fd-0630d5f3b97f">

### UI5 Web Components for React Version

1.28.4

### UI5 Web Components Version

1.24.0

### Browser

Chrome, Edge, Firefox, Safari

### Organization

SAP-SF

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @mrmabo 

The v1 `DynamicPageTitle` only supports actions being passed to the `actions` and `navigationActions` props and does not accept a `Toolbar`. Additionally, both props only accept a single `ReactElement` or an array of `ReactElements` as types, so no `null`, hence the TypeScript error.

I've updated your example to use the supported syntax, and now actions are shown without different "active" styles: https://stackblitz.com/edit/github-t5j5mn-5uwesz?file=src%2FApp.tsx.
