### ISSUE TITLE
[version update]: [I have raised multiple issue with ui5 team and get solutions in different versions now while upgrading versions I am getting errors]

### ISSUE THREAD

**Issue by jadhavarjun** [SAP/ui5-webcomponents-react#6326]
### Describe the bug

I have raised multiple issue with ui5 team and get solutions in different versions now while upgrading versions I am getting errors.
I want to upgrade latest **version 2.2.0** but I am getting error below I have attached error link.
how should I resolve this issue and upgrade libraries.
![image](https://github.com/user-attachments/assets/d6901449-98e2-4365-a505-e666b87c00d6)

and also I have another questions when I am upgrading version 2.2.0 that version i need to upgrade "@ui5/webcomponents-react": "2.2.0", "@ui5/webcomponents-react-base": "2.2.0",  like that correct and should I need to upgrade other ui5 libraries also for e.g:-
   "@ui5/webcomponents": "#",
    "@ui5/webcomponents-base": "#",
    "@ui5/webcomponents-fiori": "#",
    "@ui5/webcomponents-icons": "#",

If yes then that other ui5 libraries which version i need to upgrade with "@ui5/webcomponents-react": "2.2.0", so that will be compatible with each other and i never get any erros

please help me with all the above issue that I have mentioned.

### Reproduction steps

1.
2.
3.
...

### UI5 Web Components for React Version

#

### UI5 Web Components Version

#

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by jadhavarjun** [comment]
Hi @Lukas742,

Can I get your help in this above matter.

**Comment by MarcusNotheis** [comment]
You can always lookup the version compatibility table in [our documentation](https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/getting-started--docs).

There is no version of 2.2.0 of `@ui5/webcomponents-react` available, this is why you get the installation error.
You can always lookup our latest version in our [release log](https://github.com/SAP/ui5-webcomponents-react/releases) and in our template package.json: https://github.com/SAP/ui5-webcomponents-react/blob/main/templates/vite-ts/package.json

At the time of writing, these are the current versions:
```json
{
    "@ui5/webcomponents": "2.2.0",
    "@ui5/webcomponents-fiori": "2.2.0",
    "@ui5/webcomponents-icons": "2.2.0",
    "@ui5/webcomponents-react": "2.1.0"
  }

**Comment by Lukas742** [comment]
Closed since a solution was provided.
