### ISSUE TITLE
LineChart: Y-axis Scaling problem

### ISSUE THREAD

**Issue by AFK-Python** [SAP/ui5-webcomponents-react#6334]
### Describe the bug

When dynamically generating graphs, the chart component struggles with y-axis scaling every so often. Data that probably should render ends up being cut off.

Here are some examples:
![image](https://github.com/user-attachments/assets/348517c9-6054-45ec-8624-f1651f6c63e1)
<br/>
![image](https://github.com/user-attachments/assets/52450649-576a-462b-8066-bdc713208956)

I am not sure if this is can happen to other chart components, I've just noticed it frequently occurring with the LineChart component.

### Reproduction steps

I have provided an example dataset ([example_data.csv](https://github.com/user-attachments/files/16935600/example_data.csv)) that seems to trigger the bug. Otherwise, I am not sure what would be causing it, as our component in react looks like the following:
```
  const chartStyling = {
    margin: 0,
    padding: 0
  }
  
<LineChart
          dataset={dataset}
          dimensions={dimensions}
          measures={measures}
          style={chartStyling}
        />
```

The dataset, dimensions, and measures props are what we generate dynamically.

### Expected Behaviour

The expected behavior would be to have all of the data points render on the graph.

### UI5 Web Components for React Version

"^1.24.0"

### UI5 Web Components Version

"^1.21.0"

### Browser

Chrome

### Operating System

macos

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @AFK-Python 

I wasn't able to reproduce this issue. Please add an isolated example that shows the issue; you can use this [StackBlitz example](https://stackblitz.com/edit/ui5wcr-line-chart-q1tqle?file=package.json,src%2Fdata.json,src%2FApp.tsx) I've created while trying to follow your bug description. In the example, I've converted the CSV to JSON.

**Comment by AFK-Python** [comment]
Hi @Lukas742 

We were able to solve it on our side. It occurs when strings are used instead of numerical types in the props above. So you were able to avoid the behavior in the stack blitz by setting the total gross overdue to float.

It's a bit nasty because this doesn't fail and the graphs render on, seemingly, random scaling with string types for the data. I don't know if you can add a warning or error for this behavior, but that would be much appreciated since it took our team a while to discover what was going on.

I'll admit this probably isn't a common use case, since most people are not dynamically generating their graphs, but it would be nice to alert the user about this behavior somehow, if it cannot be fixed.

**Comment by Lukas742** [comment]
Hi @AFK-Python 

we'll outline this more prominently in the linked PR.
