### ISSUE TITLE
tooltipConfig Example for LineChart

### ISSUE THREAD

**Issue by AFK-Python** [SAP/ui5-webcomponents-react#6335]
### Describe the documentation issue

Documentation is missing

### Description

I am trying to find an example of how to use the tooltipConfig for the LineChart component, but am struggling to get a working example. I do not see a working example of this on the [documentation site](https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/getting-started--docs), or for any reference on the tooltipConfig. 

Adding this to the documentation and providing an example would be much appreciated. 

### Link to Documentation Page

https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/getting-started--docs

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by MarcusNotheis** [comment]
Hey @AFK-Python,
I've created a small Stackblitz example of how to configure the tooltip formatter function via the `tooltipConfig` prop:
https://stackblitz.com/edit/github-onzrax?file=package.json,src%2FApp.tsx

In general, you can use all properties which are listed [here](https://recharts.org/en-US/api/Tooltip).

I'll keep this issue open until we have enhanced our documentation :)

**Comment by AFK-Python** [comment]
Thanks @MarcusNotheis!
