### ISSUE TITLE
[Analytical tab;e]: TextAlign issue in Tree table columns due to extra spacer element

### ISSUE THREAD

**Issue by kmanisha29** [SAP/ui5-webcomponents-react#6368]
### Describe the bug

An extra space is getting added to all columns in tree table and it is an element due to which text is not getting aligned from beigining ( TextAlign.Begin). It looks like centrally aligned even horizontally.
This extra space is due to extra element being added to each column of tree table:
<span class="ExpandableIndicatorStyles-nonExpandableCellSpacer-0-2-104 ExpandableIndicatorStyles-withExpandableButton-0-2-105" style="padding-inline-start: 0px;"></span>

This makes the column text look central aligned for normal cells also like 2nd or 3rd coumneven if we try to use TextAlign.Begin . Any textAlign value does not align it from left.

### Isolated Example

https://stackblitz.com/edit/github-3wiuce-kjl4sq?file=src%2FApp.tsx,src%2FTreeCell.tsx,src%2FuseData.ts

### Reproduction steps

1. Create a tree table with hierarchy
2. Have 2nd and 3rd column as normal text cells
3.  Try to align then from start or left
...

### UI5 Web Components for React Version

1.26.0

### UI5 Web Components Version

1.23.0

### Browser

Chrome

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @kmanisha29 

this was fixed in a later version (probably in [v1.28.1](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v1.28.1). 

https://stackblitz.com/edit/github-3wiuce-aymyg7?file=src%2FApp.tsx,src%2FTreeCell.tsx,package.json (latest version)
