### ISSUE TITLE
[Menu, MenuItem]: Menu: Sub-menu not re-rendered despite state change

### ISSUE THREAD

**Issue by stephanemassalia** [SAP/ui5-webcomponents-react#6373]
### Describe the bug

Hi there!

We have a Menu with a nested sub-Menu of standard Menu items. Each menu item toggles a feature when clicked, i.e. clicking once turns it on, clicking on it again turns it off. We represent this with a checkmark icon (accept icon) on the menu item.
 
We use useState to keep track of whether the feature corresponding to a given menu item is enabled or not.
 
When we click on one of the options of the sub-menu, the checkmark doesn't show-up right away. It shows up only if we move the mouse out of the sub-menu, closing it, and then open it again. It seems as if the sub-menu is not re-rendered, even though there's a state change.

![memuWithoutCheckmark](https://github.com/user-attachments/assets/e25913d7-2273-4335-ba39-5d16169fa86a)

![memuWithCheckmark](https://github.com/user-attachments/assets/adcfc6ad-12ff-45b4-9dc4-50c2573e00df)
 
Please note that we're still stuck on v1. The problem doesn't occur with v2.

Thanks a lot in advance!

Best regards

### Isolated Example

https://stackblitz.com/edit/github-d5xtiv-vfny5y?file=src%2FApp.tsx

### Reproduction steps

1.
2.
3.
...

### UI5 Web Components for React Version

1.26.2

### UI5 Web Components Version

1.23.3

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @stephanemassalia 

this bug seems to be fixed in the latest v1 version: https://stackblitz.com/edit/github-d5xtiv-mrajut?file=package.json,src%2FApp.tsx

Can you confirm or am I missing something here?

**Comment by stephanemassalia** [comment]
Hi there!
I confirm fixed by UI5WC4React 1.29.x
Thanks
Stephane
