### ISSUE TITLE
[AnalyticalTable]: [In AnalyticalTable manualSorting getting removed the Sorting Icons from Table Header]

### ISSUE THREAD

**Issue by rahish13** [SAP/ui5-webcomponents-react#6384]
### Describe the bug

In AnalyticalTable manualSorting getting removed the Sorting Icons from Table Header

### Reproduction steps

1.
2.
3.
...

### Expected Behaviour

When Click on sorting Icons should be there

### Screenshots or Videos

https://github.com/user-attachments/assets/b186c2d5-e344-4132-8fe9-9f421c485712

### UI5 Web Components for React Version

1.19.0

### UI5 Web Components Version

1.17.0

### Browser

Chrome, Edge

### Operating System

Windows

### Additional Context

I have provided  
reactTableOptions={{
            
              manualSorting: true,
           
            }}  because i am doing server side sorting.

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @rahish13 

please add a reproducible example, preferably by using this [StackBlitz](https://stackblitz.com/edit/ui5wcr-v1?file=src%2FApp.tsx&file=package.json) template.

**Comment by rahish13** [comment]
https://stackblitz.com/edit/ui5wcr-v1-yhepgq?file=src%2FApp.tsx

**Comment by Lukas742** [comment]
@rahish13 The example you provided also works as intended for me. Also, the `selectionMode` of the v1 `AnalyticalTable` doesn't accept "Single" as value. Did you mean "SingleSelect", or are you using v2 of `@ui5/webcomponents-react`?

To assist you further, please follow our issue template by providing an isolated example that demonstrates the issue and include steps to reproduce it.

**Comment by rahish13** [comment]
Hi @Lukas742 I have update some code, its reproduceable. 
Please apply sorting then scroll down , when new data appended in list then sorting icon disappear from column.

**Comment by Lukas742** [comment]
@rahish13 you can use the `reactTableOption.autoResetSortBy` to achieve this. Per default the table resets its internal state if the `data` changes. You can find out more about this here: https://sap.github.io/ui5-webcomponents-react/v1/?path=/docs/data-display-analyticaltable-recipes--docs#how-to-stop-the-table-state-from-automatically-resetting-when-the-data-changes
