### ISSUE TITLE
Select Component not clear the state

### ISSUE THREAD

**Issue by vinniimiranda** [SAP/ui5-webcomponents-react#639]
Hi, i am having an issue with the Select component,  the case is that i am using the component inside an Drawer which activates when state changes (open / close), the problem is that if i change the Select Option, he persist the state even when i close and re-open the Drawer

The expected behavior would be:
Restart the component in the empty state

Here's a gif with the problem:
![Gravar_2020_08_03_16_33_39_679](https://user-images.githubusercontent.com/33462844/89220542-275f4b00-d5a8-11ea-9a0b-abc5d7411e65.gif)

As you can see above, the text inputs obey the state change, but not the Select Input.

Maybe i am missing something, any help would be appreciated

Currently using React and React Redux Form

**Comment by MarcusNotheis** [comment]
Hey @vinniimiranda,
which version of `@ui5/webcomponents` and `@ui5/webcomponents-react` are you using?
Do you unmount and remount this slider component or do you just push it off the screen?
Can you share any code that would help me to reproduce this issue?

**Comment by MarcusNotheis** [comment]
I'm not sure whether this is really related or not, but I think that this PR might help you once it is merged: https://github.com/SAP/ui5-webcomponents/pull/2040

**Comment by vinniimiranda** [comment]
It's been unmount and remount every time the state changes (open) from the parent.

What am using it's: 
"@ui5/webcomponents": "1.0.0-rc.7",
"@ui5/webcomponents-fiori": "1.0.0-rc.7",
"@ui5/webcomponents-icons": "^1.0.0-rc.7",
"@ui5/webcomponents-react": "^0.9.4",


Here's the code: 

const [isOpen, setIsOpen] = useState(false)
const [user, setUser] = useState<User | null>()

function handleClose () {
    setIsOpen(false)
  }

function handleEditUser (user: User) {
    setUser(user)
    setIsOpen(true)
  }

  function handleAddUser () {
    setIsOpen(true)
    setUser(null)
  }

return (....<FormUser user={user} isOpen={isOpen} handleClose={handleClose} />...)
![image](https://user-images.githubusercontent.com/33462844/89566631-d98c5200-d7f6-11ea-9b71-cc8caf5d8f7c.png)

**Comment by MarcusNotheis** [comment]
I think you could try to fully unmount the FormUser component by using 
`isOpen && <FormUser...> ` instead of the boolean prop you are currently using. This should force the select box to rerender.
In case that doesn't help as well, could you try to create a reproducible example in our [CodeSandBox](https://codesandbox.io/s/ui5-webcomponents-react-template-29l34?file=/src/App.js)?

**Comment by vinniimiranda** [comment]
I assume that rerender should be inside the component (FormUser in this case), but it works with your suggestion.

Thanks!
