### ISSUE TITLE
Form: properties columns and labelSpan have no effect

### ISSUE THREAD

**Issue by kumser0** [SAP/ui5-webcomponents-react#642]
**Describe the bug**
According to the doc [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/components-form--default-story), forms have 2 properties: columns, labelSpan (for S, M, L and XL resolutions).
Regardless what value is set, neither columns nor labelSpan has any effect on the rendered form - it always takes over the default settings.

**Isolated Example**
https://codesandbox.io/s/nostalgic-panini-fud3n

**To Reproduce**
1. Define a component containing Form
2. Define a "main" component using the form component.
3. "Play around" with Form properties for columns and labelSpan and see they have no effect on the result.

**Expected behavior**
Form adjusts depending on the number of columns or label span. 
For example, columns set to 2 arranges FormGroups in 2 columns, and higher label span make more space for labels.

**Screenshots**
Launch the example app and see the result.

**UI5 Web Components for React Information**
See the example
`@ui5/webcomponents` version: "^1.0.0-rc.7"
`@ui5/webcomponents-react` version: "^0.9.11"
Operating System: MacOS
Browser: Google Chrome

**Additional context**
None

**Comment by MarcusNotheis** [comment]
Hey @kumser0,
can you try to upgrade to our latest version `0.10.2`? This requires also `@ui5/webcomponents` to be at version `1.0.0-rc.8`.
The properties you mention have been added with the 0.10.0 release, so they won't work with 0.9.11

**Comment by kumser0** [comment]
@MarcusNotheis thanks for explanation! The latest version resolves the issue.
