### ISSUE TITLE
Text:  Text component ignores the remaining width and truncates earlier than expected, if it encounters a long word, which it can't fit in that line

### ISSUE THREAD

**Issue by arijitpatra-sap** [SAP/ui5-webcomponents-react#6427]
### Describe the bug

I observed a case, where the Text component ignores the remaining width and truncates earlier than expected, if it encounters a long word, which it can't fit in that line. This can look confusing and seems like sub-optimal usage of the real-estate.

I tried locally, this seems to be solvable using CSS `word-break: break-all`. I was thinking if this can be changed in the component level (if there aren't any issue) then it will be nice for everyone and for consistency.

![Component 1](https://github.com/user-attachments/assets/863a3e43-8f3a-4ba3-8302-2acd29df52cc)

### Reproduction steps

Try with a very very long word, make up something... and make sure maxLines is 1.

### Expected Behaviour

The ellipses should be shown at the end of the line

### Screenshots or Videos

![Component 1](https://github.com/user-attachments/assets/19f13b1b-a810-4027-bf7d-a8626fdc3df2)
![Screenshot 2024-09-30 at 5 40 43 PM](https://github.com/user-attachments/assets/9be1fda3-f17e-44d9-a089-4402ee075cd0)
![Screenshot 2024-09-30 at 5 46 57 PM](https://github.com/user-attachments/assets/cfd423fb-334a-49a7-a298-e433c1799587)

### UI5 Web Components for React Version

both v1 and v2

### UI5 Web Components Version

not sure... whatever is used with @ui5/webcomponents-react v1 and v2

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @arijitpatra-sap 

as discussed internally, `wrapping` needs to be set to `true` for `maxLines` to work properly. The linked PR outlines this better and also fixes the behavior with `maxLines <= 1`:

- `maxLines <=1`: the same behavior as `wrapping: false` is applied.
- `maxLines > 1`: i.a. `word-wrap: break-word;` is applied
