### ISSUE TITLE
[Charts]: The react charts are not accessible.

### ISSUE THREAD

**Issue by amdev138** [SAP/ui5-webcomponents-react#6446]
### Describe the bug

Hi team,

Internally we are using recharts. Recharts has recently added an `accessibilityLayer` prop that you can pass to the component to make it keyboard accessible. Please see: [recharts-api-accessibility--docs](https://release--63da8268a0da9970db6992aa.chromatic.com/?path=/docs/api-accessibility--docs)

However, the ui5-wc react wrapper does not currently have a way to pass this prop to the internal rechart component. From what I can tell, ui5-wc-react current version of recharts is 2.12.7 - which this version has the support for `accessibilityLayer`.  We just need a way to allow the consumer to pass this prop.

Thanks,
Allen

### Expected Behaviour

Charts should be accessible.

### UI5 Web Components for React Version

main

### UI5 Web Components Version

main

### Browser

Chrome, Edge, Firefox, Safari

### Organization

SF

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @amdev138, the linked PR will allow setting the `accessibilityLayer` prop on all charts via the `chartConfig` prop. Please note, that we flagged it as "experimental" as it's not supported for all charts and configurations.
