### ISSUE TITLE
Layout: Does not set load theme

### ISSUE THREAD

**Issue by pwasemsap** [SAP/ui5-webcomponents-react#6458]
### Describe the bug

Theme is not set loaded from ui5 config

### Isolated Example

https://stackblitz.com/github/SAP/ui5-webcomponents-react/tree/main/templates/nextjs-app?file=README.md

### Reproduction steps

```jsx
import '@ui5/webcomponents-react/styles.css'
import './globals.css'
import { ThemeProvider } from '@ui5/webcomponents-react'

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <script
          data-ui5-config
          type="application/json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              theme: 'sap_horizon_dark',
            }),
          }}
        />
      </head>
      <body>
        <div className="appShell">
          <ThemeProvider staticCssInjected>{children}</ThemeProvider>
        </div>
      </body>
    </html>
  )
}
```

### Expected Behaviour

Theme should be loaded / set

### UI5 Web Components for React Version

2.3.0

### UI5 Web Components Version

2.3.0

### Browser

Edge, Safari

### Operating System

MacOS

### Additional Context

https://github.com/SAP/ui5-webcomponents-react/blob/main/templates/nextjs-app/app/layout.tsx

### Relevant log output

```shell
You have requested a non-registered theme sap_horizon_dark - falling back to sap_horizon. Registered themes are: sap_horizon
```

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @pwasemsap, the linked PR will allow setting the `accessibilityLayer` prop on all charts via the `chartConfig` prop. Please note, that we flagged it as "experimental" as it's not supported for all charts and configurations.

**Comment by Lukas742** [comment]
Hi @pwasemsap to be able to use theming, the assets must be imported. You can find out more about this [here](https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/getting-started--docs#theming).

We'll also update our template to include the import (see the linked PR).

Example: https://stackblitz.com/edit/github-d95zso-whbyzf?file=app%2Flayout.tsx,app%2Fpage.tsx,app%2FclientAssetsImport.ts

**Comment by pwasem** [comment]
@Lukas742 thanks for the quick reply. 

Updating the documentation would be desirable. 

Having a more complex example app would also be helpful. E.g. an actual implementation of a ListReport / ObjectPage floorplan using an OData V4 service.

Thanks
