### ISSUE TITLE
[Popup/Dialog]: Popups/Dialogs always showing in firefox

### ISSUE THREAD

**Issue by skowrons** [SAP/ui5-webcomponents-react#6522]
### Describe the bug

All popups and dialogs will always be in the shown state. The user can no longer close the dialog with interactions or by pressing the ESC key.

### Isolated Example

https://stackblitz.com/edit/github-yspzgp?file=src%2FApp.tsx

### Screenshots or Videos

![Bildschirmfoto 2024-10-20 um 15 18 53](https://github.com/user-attachments/assets/27705128-cdaa-461c-ad3b-30ffe96d8200)

### UI5 Web Components for React Version

2.2.0

### UI5 Web Components Version

2.3.0

### Browser

Firefox

### Operating System

MacOS

### Additional Context

Firefox Version: Firefox Developer Edition Version 123.0b1 (64-bit)

Will also happen with the newer 2.3.1 webcomponents-react version, the stackblitz was not updated yet ^^

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @skowrons,

I wasn't able to reproduce the behavior using the standard Firefox browser on Mac (131.0.3 (aarch64)) and Windows (127.0 (64-bit)). Could you please check if this issue only occurs with Firefox Developer Edition (which is [not supported](https://github.com/SAP/ui5-webcomponents?tab=readme-ov-file#browser-support) by our library), or does it also happen with the standard Firefox browser?

**Comment by skowrons** [comment]
Hi @Lukas742,

Thank you for your test. You are absolutely right. The regular version of Firefox works perfectly. I initially thought that the only difference between the two editions was the extended developer tools, but it seems there’s more to it.

I'll go ahead and close the issue.
