### ISSUE TITLE
Analytical Table: DatePicker within Table

### ISSUE THREAD

**Issue by Sepper007** [SAP/ui5-webcomponents-react#653]
**Describe the bug**
When the DatePicker component is used within an AnalyticalTable, a click on the DatePicker component triggers the onRowSelected callback of its parent AnalyticalTable component.

**Isolated Example** || **To Reproduce**
https://codesandbox.io/s/elastic-cannon-y21jc?file=/src/App.js
-> Click on the Value Help icon of the DatePicker.
-> The onChange callback of the DatePicker will be called, but also the onRowSelected callback

**Expected behavior**
The event is not bubbled up to the parent component. 

**UI5 Web Components for React Information**
`@ui5/webcomponents` "^1.0.0-rc.8":
`@ui5/webcomponents-react` "0.10.3":
Operating System:MacOS
Browser:Chrome

**Additional context**
We have a quick-fix in place in our app to prevent this:

<DatePicker
            onClick={(evt) => evt.stopPropagation()}

**Comment by Lukas742** [comment]
Released in `@ui5/webcomponents-react@0.10.5`
