### ISSUE TITLE
Charts: warning coming from recharts pre 2.13

### ISSUE THREAD

**Issue by perryd01** [SAP/ui5-webcomponents-react#6551]
### Describe the bug

Having a chart component rendered will throw a warning/error in the console, but everything works fine. Updating recharts 2.13 might be a solution.

The warning:
```
XAxis: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
```

https://github.com/recharts/recharts/issues/3615#issuecomment-2407597181

### UI5 Web Components for React Version

2.3.1

### UI5 Web Components Version

2.3.0

### Browser

Chrome

### Operating System

macOS

### Organization

SAP GCID

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @perryd01 

the linked PR fixes the error, but the types aren't compatible with our current implementation. We didn't find the time yet to check why.
