### ISSUE TITLE
[AnalyticalTable/TreeTable]: edit/ delete action is not working as expected

### ISSUE THREAD

**Issue by roshnijalan97new** [SAP/ui5-webcomponents-react#6563]
### Bug Description

Link - https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/data-display-analyticaltable--docs
<img width="1124" alt="Screenshot 2024-10-28 at 5 34 10 PM" src="https://github.com/user-attachments/assets/10868e79-cb4c-4037-b8b2-cff6488335fb">
edit/ delete button in the action button is not working

### Affected Component

AnalyticalTable

### Expected Behaviour

It should help edit the data in the row or delete it

### Priority

High

### UI5 Web Components Version

1.9.3

### Browser

Chrome

### Operating System

Mac Os

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @roshnijalan97new 

the buttons are only there to show how custom elements can be added to a Cell in the AnalyticalTable. Delete or edit logic has to be implemented on app side.

**Comment by roshnijalan97new** [comment]
Hi @Lukas742, where can we find a example for this operation?

**Comment by Lukas742** [comment]
@roshnijalan97new since there are many ways to implement this behavior and it’s also very specific to each use case (especially for the edit mode) we haven’t provided an example. If you're having trouble implementing this behavior, please describe your use case and what isn’t working.

**Comment by roshnijalan97new** [comment]
I am trying to create a TreeTable which have more than one column such that each row value is editable and the data sent to the tree table is updated once it is focused out. So I am unable to modify the data in the rows .
