### ISSUE TITLE
webcomponents-react-charts: unmet peer dependency from webcomponents-react-base

### ISSUE THREAD

**Issue by OliwiaGowor** [SAP/ui5-webcomponents-react#6577]
### Describe the bug

webcomponents-react-charts@"^2.3.1" has a peer dependency of webcomponents-react-base@"~2.3.0", that is currently not available. Because of that, we cannot upgrade to webcomponents-react@2.3.x. 
<img width="702" alt="Screenshot 2024-10-31 at 12 31 56" src="https://github.com/user-attachments/assets/5e0189f8-9e6a-4d60-b2f2-31279c305de9">

### Reproduction steps

1. Creat a project with webcomponents-react-charts@"^2.3.1" and webcomponents-react@"^2.3.2"
2. Build the project wit package manager (e.g. with npm)

### Expected Behaviour

Project should build without any dependency errors.

### UI5 Web Components for React Version

2.3.2

### UI5 Web Components Version

2.3.0

### Browser

Chrome

### Organization

Kyma

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @OliwiaGowor 

the base package is now updated to meet the defined peer dependency range. Sorry for the inconvenience!
