### ISSUE TITLE
[SF][Button]: SR announcing Search button as search emphasized

### ISSUE THREAD

**Issue by indrakantm23** [SAP/ui5-webcomponents-react#6591]
### Describe the bug

When using button from ui5 and using a screen reader, it's announcing button + button label + design [ie. 
"Default" | "Positive" | "Negative" | "Transparent" | "Emphasized" | "Attention"]

### Reproduction steps

1.
2.
3.
...

### UI5 Web Components for React Version

18

### UI5 Web Components Version

2.4.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @indrakantm23 

please follow our issue template and provide the necessary information. Your description doesn’t clearly explain the issue you’re reporting or the expected behavior.
