### ISSUE TITLE
Input component: Incorrect values after discarding a draft

### ISSUE THREAD

**Issue by yoannaBor** [SAP/ui5-webcomponents-react#6626]
### Describe the bug

When editing an input field, and then discarding it. After clicking on "Edit" again, it shows the changed value, although it wasn't saved anywhere. Cache is also with the original value. 

Unfortunately at the moment I could not reproduce the bug in a CodeSandBox. 

Please accept this screen recording. (In case you need the screen recording - you can let me know to send it per mail)

I am open for any advice of how should we debug this. The state of the component from our side is all fine after debugging it. 

### Reproduction steps

1.
2.
3.
...

### UI5 Web Components for React Version

1.29.11

### UI5 Web Components Version

1.24.13

### Browser

Chrome

### Operating System

MacOS

### Organization

Enterprise Data Technology BL

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @yoannaBor 
The issue could have a lot of root causes, so please follow our issue template and try to isolate it.

> I am open for any advice of how should we debug this.

- Although, there's not much information regarding the implementation or how you tried debugging it, I would recommend checking at what point of time which `value` is applied, both for the `value` property of the `ui5-input` element and the `value` React state/prop.
- Check exactly which version of ui5-webcomponents packages you're using and adjust them in StackBlitz accordingly. 
- Check if you're mutating the the React state somehow.
