### ISSUE TITLE
Possibility to remove arrow button from Tab Filter for ObjectPage

### ISSUE THREAD

**Issue by yoannaBor** [SAP/ui5-webcomponents-react#6643]
### Is your feature request related to a problem?

Currently it is not possible to remove the arrow button from the TabItems in the Tab Filter for ObjectPage. How can we remove it? 
<img width="467" alt="image" src="https://github.com/user-attachments/assets/a460d671-6c65-481c-8b87-4ff612990452">

### Describe the solution you'd like

The possibility to remove the arrow button of the Tab Filter.

### Describe alternatives you've considered

I tried accessing the Tabs via css selectors, but I see there is a shadow root I cannot access.

### Organization

Enterprise Data Technology BL

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @yoannaBor 

could you provide more details about your use case, why you need this feature, and what makes the current design insufficient?

**Comment by yoannaBor** [comment]
Hello @Lukas742, 

Thank you so much for the quick answer. It turns out we were using additional subsection in those cases, and we actually don't need them, so I managed to get rid of the subsections and use only the section and so the arrow button in gone. 

Thank you once again for the support! Closing the issue ticket!
