### ISSUE TITLE
ObjectPage: Content adds too large empty section when headerArea autocollapse (when scrolled)

### ISSUE THREAD

**Issue by aleksaToljic** [SAP/ui5-webcomponents-react#6648]
### Describe the bug

When the user starts scrolling, `headerArea` collapses, and a large section is added above the content

### Isolated Example

https://stackblitz.com/edit/github-sr4l8x?file=src%2FApp.tsx

### Reproduction steps

1. Start scrolling slowly

### Expected Behaviour

Content to not jumb down

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/128235a9-f3e1-4a48-9928-92b14ad15204)

### UI5 Web Components for React Version

2.4.0

### UI5 Web Components Version

2.4.0

### Browser

Chrome

### Operating System

macOs Sequoia 15.1

### Organization

TronIT

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by aleksaToljic** [comment]
I have a fix for this, it's pretty straightforward.
The problem is that we add `position: absolute` to headerArea, when it's collapsed, and it looses it's width, so it looks like this (when I remove `visibility: hidden`)
![Screenshot 2024-11-22 at 14 54 34](https://github.com/user-attachments/assets/bf05f70f-7c37-4724-89b6-b804db749bfc)

Solution for this would be to add `left: 0, right: 0` or width:
<img width="1092" alt="Screenshot 2024-11-22 at 14 56 03" src="https://github.com/user-attachments/assets/b3f3b80c-a8f5-4b78-a023-895e5b97bc6a">

I can create PR if needed.

**Comment by Lukas742** [comment]
Hi @aleksaToljic 

The linked PR will resolve this issue, so there’s no need to create a PR on your end. Nevertheless, thank you for raising this issue and offering a solution! :)
