### ISSUE TITLE
[MultiComboBox] [Both V1 and V2] : [Addition of custom values in multi combo box has multiple issues]

### ISSUE THREAD

**Issue by roy-1996** [SAP/ui5-webcomponents-react#6662]
### Describe the bug

We are using the multi combo box to implement the following functionality:
1. Use the `onSelectionChange` handler to allow selection of items from the dropdown.
2. Use the `onChange` handler to add custom values. The value added by the user will be added to the dropdown and appear as a selected token. Once the token is created, it should be treated in the same way as a selected token from point 1.

Issues:
1. Once the user inputs a custom string and presses Enter, the value appears as a free text beside the token.
2. On pressing Enter again multiple times, the multi combo box goes into an error state temporarily with an empty error message.
3. On deleting all the tokens and pressing Enter, empty tokens are created.

### Isolated Example

https://stackblitz.com/edit/github-b3bzxd-8szfkd?file=src%2FApp.tsx

### Reproduction steps

1. Add a custom token and press Enter. The entered value is shown as a free text beside the token.
2. Now press Enter multiple times. The combo box temporarily enters into an error state.

### Expected Behaviour

1. Once the user inputs a custom string and presses Enter, the value shouldn't appears as a free text beside the token. Only the token should be selected.
2. On pressing Enter again multiple times, the multi combo box shouldn't show error state.
4. On deleting all the tokens and pressing Enter, empty tokens shouldn't be created.

### Screenshots or Videos

https://github.com/user-attachments/assets/03e9d728-7a9b-4b90-9a35-dd0406eceabf

### UI5 Web Components for React Version

2.4.0 and 1.28.4

### UI5 Web Components Version

2.4.0 and 1.24.3

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @roy-1996 

you have to reset the `value` to achieve this. I've added two ways to achieve this to your example. In my opinion, controlling the value via a React state is the better option, as otherwise updates to the web component happen outside of the scope of React, but it's working in both ways.

https://stackblitz.com/edit/github-b3bzxd-u9vjok?file=src%2FArrayEnum.tsx

Does this solve your issue?

**Comment by roy-1996** [comment]
Hi @Lukas742 - This fixes the issue. Thanks for the quick resolution. I will close the ticket.
