### ISSUE TITLE
Toolbar: [V2] Toolbar does not display with Text component

### ISSUE THREAD

**Issue by fushizen** [SAP/ui5-webcomponents-react#6679]
### Describe the bug

On adding a `<Text>` component inside a `<Toolbar>` component for the `<AnalyticalTable>` header, the header does not display. On commenting the `<Text>` component, the header displays correctly as expected.

### Isolated Example

https://stackblitz.com/edit/ui5wcr-at-mpjbpw?file=src%2FApp.tsx,package.json

### Reproduction steps

1. Enable the `<Text>` component inside the `<Toolbar>` under the `<AnalyticalTable>` `header` in the provided sandbox
2. The header does not display

### Expected Behaviour

`<Text>` components should be able to be rendered inside the `<Toolbar>` for the `<AnalyticalTable>` `header`. This functionality was working with UI5 Web Components for React Version 1.x

### UI5 Web Components for React Version

2.4.0

### UI5 Web Components Version

2.4.0

### Browser

Chrome, Edge, Firefox

### Organization

SAP

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @fushizen,  

The `Text` component is not supported as a child of the `Toolbar`. Please refer to the description of the `children` prop:  

> Note: Currently only ToolbarButton, ToolbarSelect, ToolbarSeparator and ToolbarSpacer are allowed here.

There’s an open [feature request](https://github.com/SAP/ui5-webcomponents/issues/9851) in the `ui5-webcomponents` repo requesting support for additional components. Feel free to add any context or questions there.
