### ISSUE TITLE
[MultiComboBox]: Type issue, it complains for `selected` prop in `ComboBoxItem`

### ISSUE THREAD

**Issue by aleksaToljic** [SAP/ui5-webcomponents-react#6690]
### Describe the bug
I need `selected` prop so that initially my multi-combo-box has value, and functionality works, but typescript is complaining that `selected` prop doesn't exist in `<ComboBoxItem`
<img width="990" alt="Screenshot 2024-12-04 at 18 10 27" src="https://github.com/user-attachments/assets/951fa398-26eb-4ebf-b5d7-ab7250f2ed60">

### UI5 Web Components for React Version

2.4.0

### UI5 Web Components Version

2.4.0

### Browser

Chrome

### Declaration

- [X] I’m not disclosing any internal or sensitive information.

**Comment by Lukas742** [comment]
Hi @aleksaToljic 

you're using a `ComboBoxItem` inside a `MultiComboBox` which is not supported. Please use the `MultiComboBoxItem` instead, which offers the `selected` prop.

**Comment by aleksaToljic** [comment]
damn, thanks @Lukas742, I refactored and forgot that part 😢 , sorry for raising issue.
