### ISSUE TITLE
AnalyticalTable: Can't cancel `onSort` event

### ISSUE THREAD

**Issue by ej612** [SAP/ui5-webcomponents-react#6698]
### Describe the bug

Hi there!

We want to add sorting functionality to our AnalyticalTable, but we'll be doing the sorting in the backend. Meaning we want the UI to look like it normally would, but we don't want the table to actually do any sorting of its own. Instead, we'll swap out the table rows we'll be giving to it.

My first instinct was to set `sortable=true` and to implement `onSort` like this:
```
onSort={(event) => {
  event.preventDefault();
}
```

However, that doesn't seem to have any effect, the table still sorts on its own. Is this a bug or am I doing it wrong?

Thanks a lot in advance!

### Isolated Example

https://stackblitz.com/edit/github-9ssrdb?file=src%2FApp.tsx

### UI5 Web Components for React Version

1.29

### UI5 Web Components Version

1.24

### Browser

Chrome

**Comment by Lukas742** [comment]
Hi @ej612 

you can use the [manualSortBy](https://sap.github.io/ui5-webcomponents-react/v2/?path=/docs/data-display-analyticaltable-recipes--docs#how-to-manually-sort-filter-or-group-the-table) `reactTableOption` to disable the internal sorting logic.

https://stackblitz.com/edit/github-9ssrdb-gkgbzg?file=src%2FApp.tsx
