### ISSUE TITLE
DatePicker: Wrong year show

### ISSUE THREAD

**Issue by stevetsanders** [SAP/ui5-webcomponents-react#674]
**Describe the bug**
When opening a datepicker with Jan 1 as the selected day, the date picker shows the previous year in the header

**Isolated Example**
1) go to the story book page and enter in 20200101 for the value and yyyyMMdd as the format

**To Reproduce**
same as above
**Expected behavior**
I expect the datepicker to show Jan 2020

**Screenshots**
![image](https://user-images.githubusercontent.com/18493125/92525835-656c1200-f1d9-11ea-9d2b-17db28d49577.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.8
`@ui5/webcomponents-react` version: 0.10.6
Operating System:
Browser:

**Additional context**

**Comment by Lukas742** [comment]
Hi @stevetsanders 

when I try to do this, the correct year is displayed for me (I tried with macOS and windows - Chrome and Safari).  I have prepared a [codesandbox](https://codesandbox.io/s/magical-keller-sfbq9?file=/src/App.js) where the Datepicker also seems to behave as intended. Could you please check if the correct year is displayed there for you?

**Comment by jeffersonneves** [comment]
The same happens to me, however when I change the date to 20200102, I get the correct year. Javascript has some problems with timezones and DST (I'm in Brazil, so January first is supposed to be DST)

**Comment by Lukas742** [comment]
Hi @jeffersonneves 
I wasn't aware of this, thanks for clarifying.

This seems to be a bug in the UI5 Web Components library. I forwarded this issue to their repo:
https://github.com/SAP/ui5-webcomponents/issues/2202
