### ISSUE TITLE
ObjectPage: Temporary changes are lost when switching tabs

### ISSUE THREAD

**Issue by stevetsanders** [SAP/ui5-webcomponents-react#675]
**Describe the bug**
When an object page is in icon tab bar mode, any changes to any of the subsections will be removed upon switching tabs.

**Isolated Example**
https://codesandbox.io/s/objective-williams-nfwvm?file=/src/App.js

**To Reproduce**
1. enter in a text for the first input
2. switch to the second tab
3. switch back to the first tab

result => changes in first input are lost

**Expected behavior**
I would expect the component to be in the state before switching

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.8
`@ui5/webcomponents-react` version: 0.10.8
Operating System:
Browser:

**Additional context**

**Comment by Lukas742** [comment]
Hi @stevetsanders 

you can maintain the value of the different Inputs by setting a state for each Input:
https://codesandbox.io/s/staging-river-qcl7e?file=/src/App.js

Will this solve your problem?

**Comment by stevetsanders** [comment]
Hi @Lukas742 ,

Closing this as you discussed with @Sepper007. I guess our use case is a bit different, so we have to take care and persist temporary changes within another area of our redux store.
