### ISSUE TITLE
AnalyticalTable: close filter when user presses enter on input

### ISSUE THREAD

**Issue by stevetsanders** [SAP/ui5-webcomponents-react#678]
**Is your feature request related to a problem? Please describe.**
As a user, I would like the filter popup on a column to close when I enter in a value and press enter on my keyboard

**Describe the solution you'd like**
when enter is pressed and the input box in the column filter is focused, close the popup.

1) go to https://codesandbox.io/s/funny-wood-p0314?file=/src/App.js
2) click on the column
3) enter in "2"
4) press enter on your keyboard
desired result -> filter dialog closes

**Describe alternatives you've considered**

**Additional context**

**Comment by Lukas742** [comment]
Hi @stevetsanders 

You can achieve this behavior by setting a custom `Filter` in your columns config:
https://codesandbox.io/s/tender-river-ofpfe?file=/src/App.js

**Comment by stevetsanders** [comment]
HI @Lukas742 

This looks good! Thanks a lot. i'll close the item now.
