### ISSUE TITLE
FilterBar: visibleInFilterBar property of FilterGroupItem

### ISSUE THREAD

**Issue by Sepper007** [SAP/ui5-webcomponents-react#680]
**Describe the bug**
When the visibleInFilterBar property of a FilterGroupItem is initially set to true, it can be de-selected and selected and it correctly appears on the FilterBar. However, if it is initially set to false, it will never appear on the FilterBar even if you click Show on FilterBar and hit Save inside the Filters Dialog

**To Reproduce**
https://codesandbox.io/s/keen-goldberg-bwo5i?file=/src/App.js:1158-1176
Open the Filters Dialog inside the FilterBar and deselect the initially selected "Show on FilterBar" checkbox for "filter2" and select the corresponding checkbox for "filter1". After hitting save, the filterGroupItem "filter2" is now hidden, but "filter1" is still hidden as well.

**Expected behavior**
Either the visibleInFilterBar prop statically determines the visibility, so it has to be handled from the outside or it is managed internally by the FilterBar in both cases.

**UI5 Web Components for React Information**
"@ui5/webcomponents": "^1.0.0-rc.8",
"@ui5/webcomponents-react": "0.10.8",
Operating System:MacOs
Browser:Chrome

**Additional context**

**Comment by Lukas742** [comment]
Fixed in [v0.10.9](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.10.9)
