### ISSUE TITLE
FilterBar: The onFiltersDialogSave callback event does not contain the properties elements and toggledElements

### ISSUE THREAD

**Issue by Sepper007** [SAP/ui5-webcomponents-react#681]
**Describe the bug**
According to this documentation, https://sap.github.io/ui5-webcomponents-react/?path=/docs/components-filterbar--render-default-story the onFiltersDialogSave should contain the 2 custom properties elements and toggledElement. In my tests they were not present.

**Isolated Example**
https://codesandbox.io/s/affectionate-hooks-ri8u3?file=/src/App.js

**To Reproduce**
Open the FiltersDialog, change the selection of shown FilterGroupItems in the FilterBar. Click save and check the console log.

**UI5 Web Components for React Information**
"@ui5/webcomponents": "1.0.0-rc.8",
 "@ui5/webcomponents-react": "0.10.8",:
Operating System:MacOS
Browser:Chrome

**Additional context**

**Comment by Lukas742** [comment]
Fixed in [v0.10.9](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.10.9)
