### ISSUE TITLE
ObjectPage: ResponsivePopover is not rendering correctly

### ISSUE THREAD

**Issue by mishsamb** [SAP/ui5-webcomponents-react#690]
**Describe the bug**
The ResponsivePopover is not displaying correctly in the ObjectPage. Two white bands are being showed over the popover.

**To Reproduce**
1. Go to 'ObjectPage'
2. Click on 'Add a responsive popover component to a the 'headerContent' or 'title''
3. Load page'

**Expected behavior**
Full display of ResponsivePopover component

**UI5 Web Components for React Information**
`@ui5/webcomponents` version:
`@ui5/webcomponents-react` version:0.10.8
Operating System: Windows 10
Browser: All browsers, Chrome

**Comment by Lukas742** [comment]
Hi @mishsamb 

could you try mounting the `ResponsivePopover` outside of the `ObjectPage`? You can use [`createPortal`](https://reactjs.org/docs/portals.html) to achieve this. 

Take a look at this codesandbox if you are unsure how to do this: https://codesandbox.io/s/practical-kare-hpvjo?file=/src/App.js

In case the problem still persists please add a screenshot and preferably a reproducible example of the behavior.
