### ISSUE TITLE
AnalyticalTable: Vertical Scrollbar position

### ISSUE THREAD

**Issue by stevetsanders** [SAP/ui5-webcomponents-react#698]
**Describe the bug**
When a table has lots of columns with defined widths, the vertical scroll bar only appears if a user horizontally scrolls to the very right.

**Isolated Example**
https://codesandbox.io/s/frosty-mayer-knqne?file=/src/App.js

**To Reproduce**
1. Go to codesanbox
2. vertical scroll only appears if you scroll all the way to the right

**Expected behavior**
I would expect the vertical scroll bar to either always be visible or only while the mouse is hovered over the table

**Screenshots**
initial view
![image](https://user-images.githubusercontent.com/18493125/94848058-49beea80-03d8-11eb-9363-fcf6c4b258ce.png)
scroll to the right
![image](https://user-images.githubusercontent.com/18493125/94848075-504d6200-03d8-11eb-8399-43d5fc51159f.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.8
`@ui5/webcomponents-react` version: 0.10.9
Operating System:
Browser:

**Additional context**

**Comment by Lukas742** [comment]
released in (0.11.0-rc.1)[https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.11.0-rc.1]
