### ISSUE TITLE
AnalyticalTable: interactive and auto visible rows

### ISSUE THREAD

**Issue by stevetsanders** [SAP/ui5-webcomponents-react#699]
**Is your feature request related to a problem? Please describe.**
As a user, I am frustrated that:
1) The AnalyticalTable doesn't allow me to drag the bottom of the table and increase the amount of rows shown like the old UI table
2) The AnalyticalTable doesn't auto adjust the number of rows depending on the available container height

https://openui5.hana.ondemand.com/api/sap.ui.table.VisibleRowCountMode

**Describe the solution you'd like**
I would like to see the two options implemented

**Describe alternatives you've considered**

**Additional context**

**Comment by MarcusNotheis** [comment]
## Hacktoberfest Contributions

**This is an advanced feature**

- [ ] Add a new enum `VisibleRowCountMode` with the properties `Fixed` and `Interactive`
- [ ] Add a new prop to the `AnalyticalTable` `visibleRowCountMode` which accepts the newly created `VisibleRowCountMode` enum. Default value should be `VisibleRowCountMode.Fixed`.
- [ ] In case the `visibleRowCountMode` is `Interactive`, make the container of the table vertically resizable. Increasing or decreasing the container height should update the internal `visibleRowCount`.

**Comment by Lukas742** [comment]
> 2. The AnalyticalTable doesn't auto adjust the number of rows depending on the available container height

Released in [v0.12.2](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.12.2)

**Comment by Lukas742** [comment]
> 1. The AnalyticalTable doesn't allow me to drag the bottom of the table and increase the amount of rows shown like the old UI table

Released in [v0.12.3](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.12.3)
