### ISSUE TITLE
AnalyticalTable: Some columns not shown

### ISSUE THREAD

**Issue by stevetsanders** [SAP/ui5-webcomponents-react#719]
**Describe the bug**
After upgrading to 0.10.10, an AnalyticalTable we have within a dialog has hidden columns now

**Isolated Example**
![image](https://user-images.githubusercontent.com/18493125/95480292-99556700-0940-11eb-801b-5fd0048aa4e2.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.8
`@ui5/webcomponents-react` version: 0.10.10
Operating System:
Browser:

**Additional context**

**Comment by stevetsanders** [comment]
Created this issue just to track progress. Marcus already told me it is being worked on.

**Comment by Lukas742** [comment]
released in [0.11.0-rc.1](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.11.0-rc.1)
