### ISSUE TITLE
Add JSDoc comments to Page component

### ISSUE THREAD

**Issue by Lukas742** [SAP/ui5-webcomponents-react#729]
Add JSDoc comments to:

- [ ] Page

- [ ] PagePropTypes

In essence the `Page` was implemented to behave similar to the UI5 Page, therefore some descriptions can be adopted from the UI5 documentation.

- [Page](https://sapui5.hana.ondemand.com/#/api/sap.m.Page)

**Comment by dulcehc** [comment]
Hi @Lukas742, can I work on this?

**Comment by Lukas742** [comment]
Hi @dulcehc 

sure, thank you. I've assigned this issue to you.

**Comment by MarcusNotheis** [comment]
Merged with #736. Thanks for your contribution! :)
