### ISSUE TITLE
Card: list items not centered and contains vertical scroll

### ISSUE THREAD

**Issue by stevetsanders** [SAP/ui5-webcomponents-react#733]
**Describe the bug**
Card component containing StandardListItems have some weird css after upgrading libraries.

1. text of StandardListItems are not centered
2. List contains a vertical scrollbar

**Isolated Example**
https://codesandbox.io/s/async-snow-6ssuk?file=/src/App.js

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/18493125/96030283-abd41280-0e10-11eb-90c8-5e6ee9c1c233.png)

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.9
`@ui5/webcomponents-react` version: 0.11.0-rc.1
Operating System:
Browser:

**Additional context**

**Comment by MarcusNotheis** [comment]
Hey @stevetsanders,
looks like this issue is caused by the StandardListItems as they only have a description set.
You can use `children` instead of `description` and then it looks good in my opinion:
https://codesandbox.io/s/keen-hopper-ny2dq?file=/src/App.js:458-561
```js
  const renderLink = (link) => {
    return (
      <StandardListItem key={link.id} data-key={link.id}>
        {link.desc}
      </StandardListItem>
    );
  };
```

**Comment by stevetsanders** [comment]
Yup, that works. Thanks.
