### ISSUE TITLE
rewrite AnalyticalCard test using react-testing-library

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents-react#750]
We are currently in the phase of transitioning our tests from `enzyme` to `react-testing-library`.
You can use our custom renderer by importing it from `import { render } from '@shared/tests';`.

Affected File: `packages/main/src/components/AnalyticalCard/AnalyticalCard.test.tsx`

**Comment by sidram05** [comment]
Would like to work on this, thanks!

**Comment by kajal1811** [comment]
Sir, I have attached Pull Request to this issue for my contribution.

**Comment by sidram05** [comment]
Hi Marcus,

Please go ahead and assign this to Kajal

Thanks
Siddarth Ramachandra
