### ISSUE TITLE
rewrite Breadcrumbs test using react-testing-library

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents-react#752]
We are currently in the phase of transitioning our tests from `enzyme` to `react-testing-library`.
You can use our custom renderer by importing it from `import { render } from '@shared/tests';`.

Affected File: `packages/main/src/components/Breadcrumbs/Breadcrumbs.test.tsx`

**Comment by sidram05** [comment]
Would like to work on this, thanks!
