### ISSUE TITLE
rewrite FilterBar test using react-testing-library

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents-react#753]
We are currently in the phase of transitioning our tests from `enzyme` to `react-testing-library`.
You can use our custom renderer by importing it from `import { render } from '@shared/tests';`.

Affected File: `packages/main/src/components/FilterBar/FilterBar.test.tsx`

**Comment by sidram05** [comment]
Would like to work on this, thanks!

**Comment by MarcusNotheis** [comment]
Hey @sidram05,

do you have capacity to work on this soon?
Otherwise I could offer that I would grab this issue.

Best regards,
Marcus

**Comment by sidram05** [comment]
Hi @MarcusNotheis , 

I have created a PR, but was having the following issue

![FilterBarTest](https://user-images.githubusercontent.com/38928563/98413331-0ee74c80-203f-11eb-9d3b-c8cba6bd2114.JPG)

**Comment by MarcusNotheis** [comment]
Hey @sidram05,
thanks for tackling this one, I left some Pull Request comments which hopefully will help you :)
