### ISSUE TITLE
rewrite ObjectPage tests using react-testing-library

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents-react#757]
We are currently in the phase of transitioning our tests from `enzyme` to `react-testing-library`.
You can use our custom renderer by importing it from `import { render } from '@shared/tests';`.

Affected Files: 
- `packages/main/src/components/ObjectPage/ObjectPage.test.tsx`
- `packages/main/src/components/ObjectPageSection/ObjectPageSection.test.tsx`
- `packages/main/src/components/ObjectPageSubSection/ObjectPageSubSection.test.tsx`

**Comment by sidram05** [comment]
Would like to work on this, thanks!

**Comment by kajal1811** [comment]
Can I contribute to this?

**Comment by MarcusNotheis** [comment]
Hey @kajal1811, thanks for reaching out. 
Actually @sidram05 has claimed this issue first, so it is assigned to him as of now. But if @sidram05 says he has currently no capacity to work on this and he is fine with assigning you to the issue then I'm happy to reassign the issue.

**Comment by sidram05** [comment]
Hi Marcus,

Please go ahead and assign this to Kajal, currently little busy with work

Thanks
Siddarth Ramachandra
