### ISSUE TITLE
rewrite Spinner test using react-testing-library

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/ui5-webcomponents-react#760]
We are currently in the phase of transitioning our tests from `enzyme` to `react-testing-library`.
You can use our custom renderer by importing it from `import { render } from '@shared/tests';`.

Affected File: `packages/main/src/components/Spinner/Spinner.test.tsx`

**Comment by sidram05** [comment]
Hi @MarcusNotheis I would like to work on this, since this is one of my first projects might need some guidance..thanks!

**Comment by MarcusNotheis** [comment]
Hey @sidram05,

sure, I've just assigned this issue to you :) 
Basically going through our [Contributing docs](https://github.com/SAP/ui5-webcomponents-react/blob/master/CONTRIBUTING.md#contribute-code) should give you a brief overview how things work in this project. Regarding the test you want to rewrite: Basically it is all about replacing the `mount(XYZ).render()` syntax with the react testing library equivalent. I think the button test should be good example how things should look like in the end: https://github.com/SAP/ui5-webcomponents-react/blob/master/packages/main/src/webComponents/Button/Button.test.tsx

In case you need more information, just write it down here :) 

Thanks for your contribution!

**Comment by sidram05** [comment]
Hi @MarcusNotheis,

If the changes look good, you can assign the rest of the test cases update to me itself I will be able to work on all of them and provide you an update in a day or two..

Thanks

**Comment by MarcusNotheis** [comment]
Hey,

sure, I'll assign them all to you, thanks :)
