### ISSUE TITLE
Stacked Bar/Column Chart: Negative measures don´t lead to negative x-axis min value

### ISSUE THREAD

**Issue by vbersch** [SAP/ui5-webcomponents-react#773]
Although there are negative values for the measure, the Chart does not display a negative x-axis min value:

![image](https://user-images.githubusercontent.com/8361111/96681324-5ac79f80-1377-11eb-85af-a26bf7f67f8e.png)

**Comment by Lukas742** [comment]
This seems to be a bug in the `recharts` version we are using. 
I've created an [issue](https://github.com/recharts/recharts/issues/2306) in their repo.

**Comment by Lukas742** [comment]
Released in [v0.11.4](https://github.com/SAP/ui5-webcomponents-react/releases/tag/v0.11.4)
