### ISSUE TITLE
AnalyticalTable: Column filtering bugs

### ISSUE THREAD

**Issue by stevetsanders** [SAP/ui5-webcomponents-react#800]
**Describe the bug**
Two bugs:

1. filtering on a column does not show filter value within the column popover
2. filtering on a column forces the page to scroll down to the bottom of the viewport

**Isolated Example**
1. 
![image](https://user-images.githubusercontent.com/18493125/96754332-011aa180-1386-11eb-866d-ded1999a1857.png)

**To Reproduce**
bug 1: go to the storybook and try to filter on a column: https://sap.github.io/ui5-webcomponents-react/?path=/story/components-analyticaltable--default-story

bug 2: go to the storybook and zoom in such that the canvas can't fit the table in the viewport. Then filter on a column. Result will be that the page will scroll down to the bottom.
**Expected behavior**
bug 1. I expect to see what I typed into the column filter 
bug 2. I expect the page not to scroll down to the bottom when I filter on a column

**Screenshots**
see above

**UI5 Web Components for React Information**
`@ui5/webcomponents` version: 1.0.0-rc.9
`@ui5/webcomponents-react` version: 0.11.1
Operating System:
Browser:

**Additional context**

**Comment by MarcusNotheis** [comment]
Fixed and released in `@ui5/webcomponents-react@0.11.2`
