### ISSUE TITLE
AnalyticalTable: Each child in a list should have a unique "key" prop error in 'ColumnHeaderContainer'

### ISSUE THREAD

**Issue by rkl1994** [SAP/ui5-webcomponents-react#801]
**Describe the bug**
Using 'AnalyticalTable' component with version "@ui5/webcomponents-react": "0.11.0",, there will be two errors in console like the snapshot.
<img width="645" alt="Screen Shot 2020-10-22 at 2 20 33 PM" src="https://user-images.githubusercontent.com/5527455/96832698-c1c97f00-1471-11eb-9cb0-b05e654cc8b7.png">

**Isolated Example**
https://codesandbox.io/s/busy-framework-miom5

**To Reproduce**
go to the isolated example link, you will find this error

**UI5 Web Components for React Information**
"@ui5/webcomponents": "1.0.0-rc.9",
@ui5/webcomponents-react": "0.11.0"

**Comment by MarcusNotheis** [comment]
Fixed and released in `@ui5/webcomponents-react@0.11.2`
