### ISSUE TITLE
SideNavigation: Expose click or toggle event.

### ISSUE THREAD

**Issue by rkl1994** [SAP/ui5-webcomponents-react#809]
In the latest ui5-webcomponents-react, there is only onSelectionChange method, and if I want to click anywhere on the SideNavigationList instead of just the icon, it is impossible to todo it with only onSelectionChange method. So, could u help to expose the click or toggle event for Side Navigation? Thank you.

**Additional context**
Seems the same request for ui5-webcomponents: https://github.com/SAP/ui5-webcomponents/issues/2293
And there is a fix for this: https://github.com/SAP/ui5-webcomponents/pull/2298

**Comment by MarcusNotheis** [comment]
Hey @rkl1994,
thanks for reporting. As soon as the feature is released from the ui5 web components we will update to the latest version and then expose the click event as well.

**Comment by fifoosid** [comment]
Hi guys, just want to share that  SAP/ui5-webcomponents#2298 is now merged 😊

**Comment by MarcusNotheis** [comment]
Hey @rkl1994,
we've just released this feature in `@ui5/webcomponents-react@v0.13.0` 🎉
