### ISSUE TITLE
AnalyticalTable: There would be style warning in console while scrollbar exists 

### ISSUE THREAD

**Issue by rkl1994** [SAP/ui5-webcomponents-react#811]
**Describe the bug**
While using the Analytical Table, everything goes well while there is no scroll bar. However, while the number of data is larger than the minRows, and the scroll bar exists, there will be a warning in the console: 

**Isolated Example**
https://codesandbox.io/s/busy-framework-miom5

![Screen Shot 2020-10-22 at 4 47 30 PM](https://user-images.githubusercontent.com/5527455/96847885-49b98400-1486-11eb-944a-9037519044d3.png)

**UI5 Web Components for React Information**
    "@ui5/webcomponents": "1.0.0-rc.9",
    "@ui5/webcomponents-fiori": "1.0.0-rc.9",
    "@ui5/webcomponents-react": "0.11.0",

**Comment by MarcusNotheis** [comment]
Fixed and released in `@ui5/webcomponents-react@0.11.2`
