### ISSUE TITLE
language message pack into bundle.js

### ISSUE THREAD

**Issue by jiawang1** [SAP/ui5-webcomponents-react#9]
**Describe the bug**
fiori3.production.min.js cause to import all language message files, so the final bundle js is about 8.2m. 

**To Reproduce**
1. create react application
2  following the example: import { ContentDensity, ThemeProvider, Themes } from '@fiori-for-react/fiori3'; 
3 npm run build

the bundle size will be larger than 8m. when you look into the bundle, lots of language.json file inside.

I know I could import single component from /lib folder. But as a components libs, the size is too huge, suppose language should not go into final bundle.

**Screenshots**
![Screen Shot 2019-05-14 at 2 15 00 PM](https://user-images.githubusercontent.com/8968109/57674814-da195580-7652-11e9-8e92-8b6cff9db06e.png)

**Comment by MarcusNotheis** [comment]
Hi @jiawang1,

first of all thanks for submitting the issue.
I think the only way of avoiding this issue at the moment is to eject the `create-react-app` and customize the webpack-config to exclude the localization files from the bundle by using the `file-loader`.

You could add this loader config to the loaders array:
```js
{
  test: [/cldr\/.*\.json$/, /i18n\/.*\.json$/],
  loader: 'file-loader',
  options: {
    name: 'static/media/[name].[hash:8].[ext]',
  },
  type: 'javascript/auto'
},
// "file" loader makes sure those assets get served by WebpackDevServer.
// When you `import` an asset, you get its (virtual) filename.
// In production, they would get copied to the `build` folder.
// This loader doesn't use a "test" so it will catch all modules
// that fall through the other loaders.
```
(Original from https://github.com/SAP/ui5-webcomponents-sample-react#configure-react-build).

We investigate further if we can avoid the bundling without ejecting the react app.

Next steps:
- [ ] Add a note to the Readme with loader code.
- [ ] React out to the create-react-react them if there is any chance to modify loaders without ejecting

**Comment by MarcusNotheis** [comment]
Issue was fixed the the `ui5-webcomponents` team. Default Texts are now inlined english texts, for i18n there is now a separate file to import.
