### ISSUE TITLE
Configure Compact/Cozy setting

### ISSUE THREAD

**Issue by TinaC** [SAP/ui5-webcomponents-react#91]
In ui5-webcomponents, there is a "Configure Compact/Cozy setting". How to use it in ui5-webcomponents-react?

I have tried this in my header, but not working:
```html
<style data-ui5-webcomponents-theme-properties></style>
<script data-ui5-config type="application/json">
{
    "compactSize": true
}
</script>
```

**Comment by TinaC** [comment]
After reading the source code, we found it is used in this way:
```html
<script data-id="sap-ui-config" type="application/json">
{
  "compactSize": true
}
</script>
```
Why not keep it consistent with `ui5-webcomponents` and add it in the document?

**Comment by MarcusNotheis** [comment]
Hi @TinaC 

thanks for submitting this issue.
When exactly do you experience this issue? In our Storybook or in the your application?
For the application itself, we don't have any extra code in place, so the UI5 Config you wrote should work fine.
In our Storybook I found the outdated coding snippets, we will replace them as soon as possible.

Thanks!

**Comment by TinaC** [comment]
In my application. 
`data-ui5-config` attribute should be changed to `data-id="sap-ui-config"`. 
Maybe this should be added to Readme?

**Comment by MarcusNotheis** [comment]
We are running on `v1.0.0-rc.2` of the `@ui5/webcomponents`.
With this version, the correct config is:
```html
<script data-id="sap-ui-config" type="application/json">
{
  "compactSize": true
}
</script>
```
You can find the Readme for this version here: https://github.com/SAP/ui5-webcomponents/tree/release-1.0.0-rc.2

I would assume that the documentation of the UI5 Web Components is showing instructions for an unreleased version.
@MapTo0 can you confirm?

**Comment by MarcusNotheis** [comment]
A note is now added to our readme

**Comment by MarcusNotheis** [comment]
As a follow up issue was created in the `ui5-webcomponents` repository, I'll close this one.
