### ISSUE TITLE
ObjectPage: hide header when scroll down and section clicked

### ISSUE THREAD

**Issue by TinaC** [SAP/ui5-webcomponents-react#92]
In sap.uxap.ObjectPageLayout,
When the user scrolls down or clicking another ObjectPageSection inside anchor navigation,
the header will be minimized with only smaller profile picture and title.
[Behavior in sap.uxap.ObjectPageLayout](https://sapui5.hana.ondemand.com/#/entity/sap.uxap.ObjectPageLayout/sample/sap.uxap.sample.ObjectPageOnJSON)

But ObjectPage of ui5-webcomponent, only `showHideHeaderButton` function is provided.
[ObjectPage Component, showHideHeaderButton](https://sap.github.io/ui5-webcomponents-react/?path=/story/components-objectpage--default)

Will the hidden header behavior be enhanced?

**Comment by TinaC** [comment]
Hi Team, any update or evaluation on this issue?

**Comment by MarcusNotheis** [comment]
Hi Tina,

yes, we are currently investigating different options to implement this "collapse header on scroll"-feature.
I'll create separate issues for the individual tasks.
