### ISSUE TITLE
ShellBar: Logo Issue with webpack v3

### ISSUE THREAD

**Issue by ivaylo-stoilov-i** [SAP/ui5-webcomponents-react#940]
**Describe the bug**
Shell Bar not show any logo.

I am using ShellBar component as:
```jsx
   <ShellBar 
                        logo={<img  src="https://logos-download.com/wp-content/uploads/2016/08/SAP_logo.png" />}
                        primaryTitle={this.store.shellBarTitle}
                        // secondaryTitle={ this.props.store.currentWorkspace.name }
                        // profile={}
                        onLogoClick={this.logoHandler}
                        onProductSwitchClick={null}
                        searchField={null}
                        startButton={backBtn}
                    >
              
                    </ShellBar> 
```

but get error message in console :

react_devtools_backend.js:2450 Unknown slotName: logo, ignoring <img src="https://logos-download.com/wp-content/uploads/2016/08/SAP_logo.png" slot="logo"> Valid values are: default, profile, menuItems, searchField, startButton
    at div
    at App (eval at ES6ProxyComponentFactory (webpack:///./node_modules/react-hot-loader/dist/react-hot-loader.development.js?), <anonymous>:14:7)
    at inject-App-with-store (eval at ES6ProxyComponentFactory (webpack:///./node_modules/react-hot-loader/dist/react-hot-loader.development.js?),

I am not sure but all comes from webpack version 
this is package.json configuration :

    "@ui5/webcomponents": "1.0.0-rc.9",
    "@ui5/webcomponents-base": "0.24.0",
    "@ui5/webcomponents-fiori": "1.0.0-rc.9",
    "@ui5/webcomponents-icons": "1.0.0-rc.9",
    "@ui5/webcomponents-react": "0.11.3",
    "webpack": "^3.12.0",
    "webpack-dev-server": "2.11.5"

Unfortunately at this moment we cant incrase webpack version.
 

**Isolated Example**
```jsx
   <ShellBar 
                        logo={<img  src="https://logos-download.com/wp-content/uploads/2016/08/SAP_logo.png" />}
                        primaryTitle={this.store.shellBarTitle}
                        // secondaryTitle={ this.props.store.currentWorkspace.name }
                        // profile={}
                        onLogoClick={this.logoHandler}
                        onProductSwitchClick={null}
                        searchField={null}
                        startButton={backBtn}
                    >
              
                    </ShellBar> 

```

**Expected behavior**
I am using ShellBar component as: logo hast to be shown

**UI5 Web Components for React Information**
    "@ui5/webcomponents": "1.0.0-rc.9",
    "@ui5/webcomponents-base": "0.24.0",
    "@ui5/webcomponents-fiori": "1.0.0-rc.9",
    "@ui5/webcomponents-icons": "1.0.0-rc.9",
    "@ui5/webcomponents-react": "0.11.3",
    "webpack": "^3.12.0",
    "webpack-dev-server": "2.11.5"
Operating System: windows 
Browser: google chrome

**Additional context**

**Comment by MarcusNotheis** [comment]
Hey @ivaylo-stoilov-i,

I've created a [codesandbox](https://codesandbox.io/s/agitated-boyd-br97z?file=/src/App.js) based on your issue description and used the dependencies you shared in your issue. For me it is working fine.
Can you compare your coding with my codesandbox and adopt in case I missed something?

Thanks!

**Comment by ivaylo-stoilov-i** [comment]
Hi @MarcusNotheis 

This issue is reproduce with version of webpack  3
"webpack": "^3.12.0"  I pretty sure that version of webpack in sandbox is 4 that's way is working but i don't know how to changed.


Regards Ivaylo

**Comment by MarcusNotheis** [comment]
Hey @ivaylo-stoilov-i,
so you are running with a custom webpack setup and not with create-react-app?
As a general statement, we always recommend using `create-react-app`, but if you can create a reproducible sample with your issue I'm happy to look into it.
