### ISSUE TITLE
Carousel: Blank Footer shows with no page indicator and arrow placement in content

### ISSUE THREAD

**Issue by JWandrocke** [SAP/ui5-webcomponents-react#95]
**Describe the bug**
When trying to use the showPlageIndicator false and move the arrow placement into the content area the footer area is still shown.

**To Reproduce**
<Carousel showPageIndicator={false}>
Also reproducible in the storybook page https://sap.github.io/ui5-webcomponents-react/?path=/story/components-carousel--default

**Expected behavior**
Footer area to be hidden

**Comment by MarcusNotheis** [comment]
Hi @JWandrocke 

the fix is now released with the version `0.5.1-rc.0`.
I think you can update safely to the release candiate, there are no breaking changes included.
