### ISSUE TITLE
Carousel: Accessibility issues

### ISSUE THREAD

**Issue by JWandrocke** [SAP/ui5-webcomponents-react#96]
**Describe the bug**
For accessibility need to be able to access the left and right via keyboard and have some visual indicators on mouse over and focus

**To Reproduce**
<Carousel arrowsPlacement="PageIndicator">
Try tabbing to the icon arrows

**Expected behavior**
The navigations icon arrows should behave like the button component

**Comment by MarcusNotheis** [comment]
Hi @JWandrocke,

thanks for submitting this issue.
I would try to implement a similar concept like the UI5 `sap.m.Carousel`:
https://sapui5.hana.ondemand.com/#/entity/sap.m.Carousel/sample/sap.m.sample.CarouselWithDisplayOptions

As far as I tested it, the Carousel has a tab index and you can change pages with the `arrow-left` and `arrow-right` keys.
Would that work for you?

**Comment by JWandrocke** [comment]
If it behaves the same as the ui5 web version then that will be great.

**Comment by MarcusNotheis** [comment]
Released with `0.5.1-rc.1`
