### ISSUE TITLE
ObjectPage: display header image on the left of header title

### ISSUE THREAD

**Issue by SunnyWind** [SAP/ui5-webcomponents-react#97]
In below UI5 Object Page examples,  the header image can be positioned on the left of the header title.
https://sapui5.hana.ondemand.com/#/entity/sap.uxap.ObjectPageLayout/sample/sap.uxap.sample.ObjectPageOnJSON
https://sapui5.hana.ondemand.com/#/entity/sap.uxap.ObjectPageLayout/sample/sap.uxap.sample.ObjectPageHeaderContentPriorities

However, as far as I knew, ObjectPage component in UI5-webcomponents-react doesn't support this feature. (The header image is always displayed beneath the title.) Could it be added? 

Current:
![image](https://user-images.githubusercontent.com/4338219/63147806-dae6cc80-c031-11e9-81a1-51a85b4a5534.png)

Expected:
![image](https://user-images.githubusercontent.com/4338219/63147889-1bdee100-c032-11e9-91e1-2b89e825c4c8.png)

**Comment by MarcusNotheis** [comment]
Hi @SunnyWind,

thanks for submitting this feature request. As it was already requested by #92, I'll mark this as duplicate. You can track the status by following issue #99.

Best regards,
Marcus

**Comment by SunnyWind** [comment]
OK. Thanks.

**Comment by MarcusNotheis** [comment]
Hi @SunnyWind,

sorry, I misunderstood your issue. We'll add a property `showTitleInHeaderContent` like it is in UI5 which will enable the requested feature.

Best regards,
Marcus

**Comment by MarcusNotheis** [comment]
Fixed by #179, released in `v0.6.0-rc.13`
