### ISSUE TITLE
ObjectPage: accept avatar initials for header image

### ISSUE THREAD

**Issue by SunnyWind** [SAP/ui5-webcomponents-react#98]
**Is your feature request related to a problem? Please describe.**
I want to show a avatar with initials on the object page header, but the object page only accepts image url for header image.

**Describe the solution you'd like**
ObjectPage accepts initials and renders a avatar with initials in the header

**Additional context**
Expected:

![image](https://user-images.githubusercontent.com/4338219/63147679-73c91800-c031-11e9-84b7-2055f3d08fe9.png)

**Comment by MarcusNotheis** [comment]
Hi @SunnyWind,

thanks for submitting this issue.
Our proposal would we that the `image` prop can accept both the a string (and we'll render a image for you) and the `Avatar` Component.
Would that work for you?

Best regards,
Marcus

PS: We are currently working on a major refactoring of the ObjectPage, so this might take a bit until we have solution for this one.

**Comment by SunnyWind** [comment]
Thanks for your prompt reply.
`image` prop accepting `Avatar` component fits my need well :)
