### ISSUE TITLE
How to change the background-color of ShellBar?

### ISSUE THREAD

**Issue by ansujohn** [SAP/ui5-webcomponents-react#998]
**Describe the documentation issue**

- [ ] Documentation is incorrect
- [ ] Documentation is missing

**Description of the issue**
Changing the background-color of ShellBar. 
The documentation says properties className or style can be used. However there doesn't seem to be any effect?
Please help

**Comment by Lukas742** [comment]
Hi @ansujohn 

As described [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/style-web-components--page#change-styles-for-existing-components), Ui5 Web Components for React use CSS Variables to apply styles. You can still apply styles by using `style` or `className` but in some cases, the value will be overwritten or it can cause unwanted side effects. 

I prepared a codesandbox that should explain a bit more on how to change the backgroundColor of the Shellbar:
https://codesandbox.io/s/objective-silence-o5m5o?file=/src/index.js

**Comment by ansujohn** [comment]
It worked. Thank you  @Lukas742 for the quick response and clarification.

**Comment by vishnucta** [comment]
@Lukas742 I am not able to change the sidenavigation color.

`<SideNavigation className="sideNav"
  className=""
  fixedItems={<><SideNavigationItem icon="chain-link" text="Useful Links"/><SideNavigationItem icon="history" text="History"/></>}
  onSelectionChange={function noRefCheck(){}}
  slot=""
  style={{height: '100vh',color:"blue"}}
  tooltip=""
>`


No change in color

**Comment by vishnucta** [comment]
I tried overriding it with custom css class but it didn't work.

**Comment by Lukas742** [comment]
Hi @vishalmour 

it's basically the same answer for you. You can use CSS variables to apply these colors to the `SideNavigation`. Only the linked documentation has changed, you can now find it [here](https://sap.github.io/ui5-webcomponents-react/?path=/docs/knowledge-base--page#styling).

I created another example, which you can checkout [here](https://codesandbox.io/s/solitary-sun-415iz?file=/src/App.js)
