### ISSUE TITLE
How can I style my Web Components? page has a Link which gives 404

### ISSUE THREAD

**Issue by ansujohn** [SAP/ui5-webcomponents-react#999]
**Describe the documentation issue**

- [ ] Documentation is incorrect

**Description of the issue**
https://sap.github.io/ui5-webcomponents-react/?path=/docs/style-web-components--page
The above page has a link which does not work
A full list of all supported CSS Variables can be found **here** 

link points to https://github.com/SAP/ui5-webcomponents-react/blob/master/packages/base/src/styling/sap_fiori_3.ts

**Comment by MarcusNotheis** [comment]
Hey @ansujohn,
thanks for reporting! We just fixed the link and will update our documentation in todays release :)
